### ISSUE TITLE
Update environment's security menu to that is based on CDS 2.0

### ISSUE THREAD

**Issue by kojisaiki** [MicrosoftDocs/power-automate-docs#101]
On CDS 2.0, "User roles" and "Permisson sets" is disappeared.
Please update this document to that is based on CDS 2.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec72d8df-bd1f-6eee-e89c-b029aa14fa67
* Version Independent ID: c1cda151-9cf7-103b-a62c-e0c2fef549f7
* Content: [Environment overview for Administrators - Microsoft Flow](https://docs.microsoft.com/en-us/flow/environments-overview-admin#feedback)
* Content Source: [flow-docs/environments-overview-admin.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/environments-overview-admin.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by KumarVivek** [comment]
@kojisaiki We have updated the article to point to Power Platform admin guide that has latest information on environments. Closing the issue now.
