### ISSUE TITLE
Sharing Flow with Everyone

### ISSUE THREAD

**Issue by zshane15** [MicrosoftDocs/power-automate-docs#102]
I have a custom approval Flow that uses the HTTP request trigger. I've formatted a column in a document library to run the Flow. When a user is ready to send for approval they click the formatted column (Submit Button).

However, if the Flow is not shared directly with the user, or with a team/group that the user is a member of, it won't run. It just does nothing. I really don't want to make everyone an "owner", I'd rather just allow everyone to have "run" permissions of some kind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-team-flows#feedback)
* Content Source: [flow-docs/create-team-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by bowlinbd** [comment]
There are two potential things that need to be done.  First, you can share the flow with the SharePoint doc library itself which will give users of the library access to run the flow.  Second, in order to trigger the flow using a JSON formatted column, the person clicking the button needs to have Edit rights on the doc library.

**Comment by zshane15** [comment]
Thank you for the feedback. I had tried the sharing with the document library, looks like I was just missing the edit permission. Unfortunately the way my document library is setup, I can't grant users the ability to edit the library due to my requirements on this project. Not sure if there's a work-around for that?

**Comment by MSFTMan** [comment]
@zshane15 Thanks for your patience. To run flows, the user must have either Member, Owner permission on the doc library, or edit, if you are not using grop permissions.

**Comment by MSFTMan** [comment]
@zshane15 We've updated the document with a note that explains the permissions requirements to run flows in SharePoint.
