### ISSUE TITLE
Sending notification to a named group chat in Teams - Two minor issues I cannot resolve...

### ISSUE THREAD

**Issue by Lrochefort** [MicrosoftDocs/power-automate-docs#1023]
Hello!

I created a flow to send a notification to a named group chat when a new article/message is posted in a specific channel for our team.

I mainly did what is documented here: 

https://learn.microsoft.com/en-us/power-automate/teams/send-a-message-in-teams#posting-a-message-as-the-flow-bot-in-an-existing-named-group-chat

It was successful, the notification arrived in the group chat, with the message template.

However, I ran into 2 problems, one in the flow's notification template, and one in the group chat.

The notification template allows us to include in the message any dynamic content available, even the custom computed variables we created. But it is not possible to create a link using a **linkText** and a **messageUrl** variables. I tried the button and I tried to edit the source to add an ```<a href="***MY COMPUTED MESSAGE_URL***">***MY COMPUTED LINK_TEXT***</a>```.
![image](https://user-images.githubusercontent.com/5980343/233767904-55a37c76-69ae-42fa-8af7-891c23f43d6e.png)

The second issue I have is that I **cannot delete a notification** sent into a named group chat. The option is just not available.

![image](https://user-images.githubusercontent.com/5980343/233768971-076a306a-cdf2-4d9a-a962-2fb0ec92eb97.png)

Any help would greatly be appreciated.

Thank you in advance,

Luc
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60106692-52d5-4f8b-2220-6e66a483ecba
* Version Independent ID: c15b0ee3-c0a7-7377-219d-b6e811f959dd
* Content: [Send a message in Teams using Power Automate - Power Automate](https://learn.microsoft.com/en-us/power-automate/teams/send-a-message-in-teams)
* Content Source: [articles/teams/send-a-message-in-teams.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/teams/send-a-message-in-teams.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @natalie-pienkowska
* Microsoft Alias: **napienko**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please submit a [support ticket](https://learn.microsoft.com/power-platform/admin/get-help-support) so our support teams can investigate this problem and help with the resolution.

**Comment by Lrochefort** [comment]
Well…I am not an admin on any application in Office…I am not even admin on my machine!So…Thanks for nothing.Oh! And it’s nice of you to just close this ticket. Job well done…LucLe 2 mai 2023 à 17:56, Tapan Maniar ***@***.***> a écrit :﻿
Closed #1023 as completed.

**Comment by tapanm-MSFT** [comment]
Hi @Lrochefort , the GitHub issues for Power Automate documentation are meant for any problems with the information documented in the referenced topic. However, looking at the two issues you describe, they need a problem reproduction, investigation and resolution. We have support teams to help for these scenarios. 

Please feel free to contact your IT administrator to help with creating a support ticket and our support teams will assist you further.
