### ISSUE TITLE
Need to edit the statement with word 'AND' 

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/power-automate-docs#1039]
In the document: https://learn.microsoft.com/en-us/power-automate/triggers-troubleshoot , section : https://learn.microsoft.com/en-us/power-automate/triggers-troubleshoot#my-trigger-is-firing-for-old-events  has below line documented. It should have AND instead of OR. 
Correct statement should be: There are two types of triggers—polling triggers **AND** Webhook triggers.

Incorrect statement is: "There are two types of triggers—polling triggers **or** Webhook triggers."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41be07d3-6596-29e2-f9c6-449db00254dd
* Version Independent ID: 7a282d6d-0b39-ed50-6dbe-2b726662ea39
* Content: [Troubleshoot common issues with triggers - Power Automate](https://learn.microsoft.com/en-us/power-automate/triggers-troubleshoot)
* Content Source: [articles/triggers-troubleshoot.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/triggers-troubleshoot.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by v-aangie** [comment]
@HinaMS - Thanks for your feedback. We will soon look into this issue.
