### ISSUE TITLE
Installation of flow gateway

### ISSUE THREAD

**Issue by desmondkung** [MicrosoftDocs/power-automate-docs#104]
I'm in Southeast Asia. How come the recommended is in East Asia? How do I check my default environment and region? And how do I change them in Azure? If I'd like to switch region of the gateway installation after successfully once, do I have to uninstall and reinstall to switch region?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25f8411c-d9d8-54c8-cfb9-bafe3856d061
* Version Independent ID: 5bd1ee67-4ca2-a0d7-60e8-0ed39835bc4b
* Content: [Understand on-premises data gateways - Microsoft Flow](https://docs.microsoft.com/en-us/flow/gateway-reference)
* Content Source: [flow-docs/gateway-reference.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/gateway-reference.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@desmondkung  Thanks for reporting this issue. Please let us know where you see the recommendation. Thanks!

**Comment by desmondkung** [comment]
@MSFTMan Hi mate, I've uninstalled the gateway long ago and won't be able to follow-up anymore. This issue was opened more than a year back.

**Comment by desmondkung** [comment]
@MSFTMan Based on the comment I left last year, I think the recommendation option might've been in the installer itself.
