### ISSUE TITLE
Any ability to trigger a flow?

### ISSUE THREAD

**Issue by dougscc** [MicrosoftDocs/power-automate-docs#1053]
Can one actually trigger a cloud flow? If so, why is it not included in this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eecc2503-eee7-8779-2445-d6cd6968a0bd
* Version Independent ID: 532be787-8be9-c9b5-37a2-88841c5b8118
* Content: [Manage flows with the Power Automate Web API - Power Automate](https://learn.microsoft.com/en-us/power-automate/web-api)
* Content Source: [articles/web-api.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/web-api.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* Product: ****
* Technology: ****
* GitHub Login: @ChrisGarty
* Microsoft Alias: **cgarty**

**Comment by v-aangie** [comment]
Contacted PM for resolution.

**Comment by ChrisGarty** [comment]
The document is about managing flows with code. A flow can be triggered via HTTP request or by getting code to complete the event the trigger is waiting for such as the update of some data, the creation of a list item, or a call to an endpoint. An example of triggering the simple "When an HTTP request is received" trigger is described in https://learn.microsoft.com/en-us/azure/connectors/connectors-native-reqres?tabs=consumption#test-your-workflow

**Comment by v-aangie** [comment]
@dougscc - Thanks for contacting us. Closing this issue. If you need further help, please reopen the issue or open a new one.
