### ISSUE TITLE
typo at the end

### ISSUE THREAD

**Issue by datadrivenoutcomes** [MicrosoftDocs/power-automate-docs#1056]
[Enter feedback here]
Fix the typo: "If the you select Cancel, the selector isn't repaired"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e21b81c6-17ae-402d-0e81-693403398463
* Version Independent ID: e21b81c6-17ae-402d-0e81-693403398463
* Content: [Repair a selector - Power Automate](https://learn.microsoft.com/en-au/power-automate/desktop-flows/repair-selector)
* Content Source: [articles/desktop-flows/repair-selector.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/repair-selector.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @NikosMoutzourakis
* Microsoft Alias: **nimoutzo**

**Comment by v-aangie** [comment]
@datadrivenoutcomes - Thanks for your feedback. We have updated the docs to remove the extra "the", and the updated content will be live in a few hours. Closing this issue.
