### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by EricaT-SW** [MicrosoftDocs/power-automate-docs#1071]
community misspelled in 'government community' 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c21f8e65-0f40-3ebb-8354-58897b55151d
* Version Independent ID: 99313c27-45bb-6ab4-d78a-6f0499614c4e
* Content: [Use Power Automate flows in Microsoft Teams (contains video) - Power Automate](https://learn.microsoft.com/en-us/power-automate/teams/overview)
* Content Source: [articles/teams/overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/teams/overview.md)
* Service: **power-automate**
* Sub-service: **teams**
* GitHub Login: @MSFTMan
* Microsoft Alias: **hamenon**

**Comment by v-aangie** [comment]
@EricaT-SW - Thanks for your feedback. We have updated the docs to fix the typo, and the updated content will be live in a few hours. Closing this issue.
