### ISSUE TITLE
Please update the steps "Create your own custom Power BI workspace"

### ISSUE THREAD

**Issue by DoherDrizzle** [MicrosoftDocs/power-automate-docs#1180]
Please update the steps "Create your own custom Power BI workspace"
From this

1. On the left panel, select Workspaces > Create a Workspace.
2. In Advanced Options, select a premium Power BI license. (We recommend a premium per capacity license.)
3. Select Save.
4. Select Access.
5. Search for and add Process Insights Prod.
6. Assign it admin access.

To this

1. On the left panel, select Workspaces > Create a Workspace.
2. In Advanced Options, select a premium Power BI license. (We recommend a premium per capacity license.)
3. Select Apply.
4. On the created workspace, Select Manage Access.
5. Click the 'Add people or groups'
6. Search for and add Process Insights Prod.
7. Assign it admin access.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 032379f8-5d74-d161-da18-65a4d3039310
* Version Independent ID: 032379f8-5d74-d161-da18-65a4d3039310
* Content: [Customize a report with your own Power BI workspace - Power Automate](https://learn.microsoft.com/en-us/power-automate/process-mining-pbi-workspace?source=docs)
* Content Source: [articles/process-mining-pbi-workspace.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/process-mining-pbi-workspace.md)
* Service: **power-automate**
* Sub-service: **process-advisor**
* GitHub Login: @donums
* Microsoft Alias: **derahonuorah**

**Comment by v-aangie** [comment]
@DoherDrizzle - Thanks for your feedback. We have updated the docs to fix information about https://learn.microsoft.com/en-us/power-automate/process-mining-pbi-workspace?source=docs, and the updated content will be live in a few hours. Closing this issue.
