### ISSUE TITLE
How to show history tab?

### ISSUE THREAD

**Issue by luoyong0201** [MicrosoftDocs/power-automate-docs#122]
[Enter feedback here]
Please give advises. the following documents indicate can not show history tab?

Default active tab to show in the Flow widget. 
Valid values : 'receivedApprovals', 'sentApprovals'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac3ad92-eb8f-554a-5de3-14c430e594aa
* Version Independent ID: fab1ceb3-5110-4452-0a0d-99346cc31230
* Content: [Integrate Microsoft Flow with websites and apps - Microsoft Flow](https://docs.microsoft.com/en-us/flow/developer/embed-flow-dev)
* Content Source: [flow-docs/developer/embed-flow-dev.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/developer/embed-flow-dev.md)
* Service: **flow**
* GitHub Login: @bbarath
* Microsoft Alias: **barathb**

**Comment by MSFTMan** [comment]
@luoyong0201 Thanks for using Power Automate. Yes, the valid values are: 'receivedApprovals' and 'sentApprovals'. Thank you.
