### ISSUE TITLE
Improper information

### ISSUE THREAD

**Issue by VigneshMSCRM** [MicrosoftDocs/power-automate-docs#125]
In configure a firewall or proxy section its mentioned "If you want to be exhaustive, substitute the ComputerName and Port values with those listed under Configure ports later in this topic". But in the below configure ports section only domain name is give and not the full computer name. cannot use Test-NetConnection -ComputerName *.analysis.windows.net -Port 443
Please provide detailed computer name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25f8411c-d9d8-54c8-cfb9-bafe3856d061
* Version Independent ID: 5bd1ee67-4ca2-a0d7-60e8-0ed39835bc4b
* Content: [Understand on-premises data gateways - Microsoft Flow](https://docs.microsoft.com/en-us/flow/gateway-reference#configure-a-firewall-or-proxy)
* Content Source: [flow-docs/gateway-reference.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/gateway-reference.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by raaourik** [comment]
The section that's being described in this issue is no longer in the Content Source page. I searched all the Power Automate documentation without finding this. Suggest to close the issue @MSFTMan

**Comment by v-aangie** [comment]
This issue is no longer applicable, per Deon.
