### ISSUE TITLE
Removing Creator

### ISSUE THREAD

**Issue by Arcalight** [MicrosoftDocs/power-automate-docs#126]
I'm not sure if there's something I'm doing wrong, but I am not able to remove the account that originally created or imported the Flow, even if I have added other owners and updated the connections. I have to export the Flow, delete the original, and then import the Flow to the new account that I want to be the owner of the Flow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-team-flows)
* Content Source: [flow-docs/create-team-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
@Arcalight Thanks for submitting docs feedback. I apologize that this didn't get a response, as this is where we track documentation issues. I'm tagging a couple of PMs who might be able to help @radioblazer & @ChrisGarty , but I recommend that you post your question on the [Power Automate Community Forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity) if you have not found the answer you were looking for. Thanks!
