### ISSUE TITLE
Updated Experience Available

### ISSUE THREAD

**Issue by syntax922** [MicrosoftDocs/power-automate-docs#128]
The experience for creating recurring flows has changed (There's now a dialog process for selecting the recurring information) the link to advanced options is still relevant but may need to be called out more prominently based on the new experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba2e127-56bc-5910-3af6-30030cf58c1f
* Version Independent ID: c8fea93d-3d8d-bf8e-af7d-ae853a936843
* Content: [Run flows on a schedule - Microsoft Flow](https://docs.microsoft.com/en-us/flow/run-scheduled-tasks)
* Content Source: [flow-docs/run-scheduled-tasks.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/run-scheduled-tasks.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by Dean-Haas** [comment]
@syntax922 thanks for your feedback. I checked and it looks like the doc has been updated, so I will close this issue.
