### ISSUE TITLE
Before and after options for real-time workflows

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/power-automate-docs#129]
This is related to this existing issue: https://github.com/MicrosoftDocs/flow-docs/issues/37

The documentation above about [Initiating real-time workflows before or after status changes](https://docs.microsoft.com/en-us/flow/configure-workflow-steps#initiating-real-time-workflows-before-or-after-status-changes) suggests that the before and after options only apply to status changes. The UI certainly seems to suggest that, but I believe it applies to all of the following options, not just the first one. Each of these represent an update operation.
- Record status changes
- Record is assigned
- Record fields change options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a013bf3e-675d-6188-6115-bef65547c566
* Version Independent ID: a6c6e501-806e-0376-94aa-56b004c5c3c9
* Content: [Configure workflow stages and steps in PowerApps - Microsoft Flow](https://docs.microsoft.com/en-us/flow/configure-workflow-steps#initiating-real-time-workflows-before-or-after-status-changes)
* Content Source: [flow-docs/configure-workflow-steps.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/configure-workflow-steps.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Dean-Haas** [comment]
@JimDaly Thanks for your feedback. I see that this one has been sitting a while. I am evaluating whether there is a documentation issue that needs to be addressed. Can you clarify what you think needs to be updated or added? The same applies to your releated issue. Thanks!

**Comment by JimDaly** [comment]
The issue had to do with real-time workflows.
Now the content has been split and all discussion of realtime (synchronous) workflows is in the CDS documenttation:
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/configure-workflow-steps rather than in the Power Automate content that focuses on background workflows.

The specific link above is no longer in this topic, it is now here:
https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/configure-workflow-steps#initiating-real-time-workflows-before-or-after-status-changes
