### ISSUE TITLE
Missing "process" in new menu

### ISSUE THREAD

**Issue by andifandrich** [MicrosoftDocs/power-automate-docs#131]
There is no "process" in the new menu of the solution, so this whole page is kind of useless. How can I add a custom action?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85bd6d61-8b2c-07bf-d5ff-3994c9cae6fb
* Version Independent ID: 29528b38-1581-aec7-5e15-0244cc307f2d
* Content: [Create a custom action - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-actions#feedback)
* Content Source: [flow-docs/create-actions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-actions.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@jimholtz This looks like it's in Power Apps. Can you take a look please?

**Comment by Dean-Haas** [comment]
@ChrisGarty Can you please validate this so we can resolve the issue? Thanks!

**Comment by v-aangie** [comment]
@andifandrich - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.
