### ISSUE TITLE
Screenshots are from elsewhere

### ISSUE THREAD

**Issue by andifandrich** [MicrosoftDocs/power-automate-docs#132]
The screenshots showing how to create a new solution are completely different from what one sees in the browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 005137dc-f411-ccf5-0c65-714802dda860
* Version Independent ID: 89bfebce-e8c8-15ed-d385-6e5bfe0fdaf0
* Content: [Overview of solution-aware flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/overview-solution-flows)
* Content Source: [flow-docs/overview-solution-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/overview-solution-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Min-Rao** [comment]
Following statement is not longer "True"
 >You cannot move non-solution-aware flows (flows not created in a solution) into a solution.

**Comment by nijemcevic** [comment]
@MSFTMan I have submitted commit to refresh this doc. please assist.

**Comment by MSFTMan** [comment]
@andifandrich This doc is now updated. Thanks for using Power Automate.
