### ISSUE TITLE
Unable to refresh adaptive cards within Microsoft Teams

### ISSUE THREAD

**Issue by KeyboardMonkey221** [MicrosoftDocs/power-automate-docs#138]
Currently, there is no support for updating an adaptive card in Microsoft Teams after an action is triggered. For example, if I trigger an Action.OpenUrl button, the button currently cannot be updated to reflect that I have indeed sent an Action.OpenUrl - not just from my perspective, but the perspective of all members of the chat.

Outlook uses Action.http in its 'Refresh cards' to implement said feature, however, this isn't supported for adaptive cards.

My context, I have a busy office with many guests coming and going:
Guests fill out a e-form on entry, which triggers a Microsoft workflow, which sends an Adaptive card to a Microsoft Teams chat. This adaptive card has a 'Sign Out' button for an employee to click when their guest leaves. This then causes the adaptive card to send an Action.OpenUrl to a webhook that triggers a workflow that does some data handling in the background. I would like the adaptive to update and indicate that the guest as been signed out and has left the building - this is important for other employees to know.

We treated this scenario as not the ultimate use of this technology, but just a sandbox for discovering possibilities - I believe that an Action.http feature would be very useful to increase workflow efficiency.

Github query: https://github.com/MicrosoftDocs/flow-docs/issues/137

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da15c461-b88d-7497-cd59-efcd785d5994
* Version Independent ID: 00dd913a-44c7-b407-02c5-528c3b0e7643
* Content: [Learn to create flows that post adaptive cards to Microsoft Teams - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-adaptive-cards-teams)
* Content Source: [flow-docs/create-adaptive-cards-teams.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-adaptive-cards-teams.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Hi, and thanks for your feedback. Please submit a feature request in [Microsoft Power Automate Community  Give Feedback & Share Ideas  Power Automate Ideas](https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas)
