### ISSUE TITLE
`Create from blank` is (no longer) an option

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/power-automate-docs#143]
please up date this ( and possibly other) sections of the article.

- Automated - from blank
- Instant - from blank
- Scheduled - from blank 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27504e8c-568f-ee52-542c-5ca87c2906db
* Version Independent ID: dc8f9282-90ce-60e0-402c-ea8829b6334e
* Content: [Use expressions with conditions. - Microsoft Flow](https://docs.microsoft.com/en-us/flow/use-expressions-in-conditions#feedback)
* Content Source: [flow-docs/use-expressions-in-conditions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/use-expressions-in-conditions.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@Josverl Thanks for reporting this issue. We'll update the docs with the new steps.
