### ISSUE TITLE
Page is out of date with office365

### ISSUE THREAD

**Issue by keithkirkhope** [MicrosoftDocs/power-automate-docs#144]
There is no longer an edit in advanced mode link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af5f3e7-4734-5813-0e3d-dada381fec0b
* Version Independent ID: 393c8bdd-da49-d6cd-f97a-94283f55c0a2
* Content: [Add a condition to a flow - Microsoft Flow](https://docs.microsoft.com/en-us/flow/add-condition#feedback)
* Content Source: [flow-docs/add-condition.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/add-condition.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by Dean-Haas** [comment]
Advanced mode reference removed from this topic.
