### ISSUE TITLE
Limitation on Approval Emails Missing

### ISSUE THREAD

**Issue by audrieMSFT** [MicrosoftDocs/power-automate-docs#145]
There is 1 more limitation for GCC customers for Flow. I would like to add this point as the last bullet point:

**Approvals**: Although GCC customers may use Flow Approvals, they will not be able to send actionable emails, and will need to direct approvers to the Approval Center. As a workaround, Flow makers can leverage standard email connectors to notify someone that they have an approval pending. In that case, they would also include the hyperlink, within the body of the email, which points to the Approval Center where GCC consumers may act on the approvals.**

Thank you.
Audrie

**Comment by MSFTMan** [comment]
@audrieMSFT Thanks for using Power Automate. This doc has been updated to reflect that GCC customers will need to use the Approval Center.
