### ISSUE TITLE
Similar examples

### ISSUE THREAD

**Issue by thedavegray** [MicrosoftDocs/power-automate-docs#147]
These are all basically the same flow.  How about a flow that inserts into a SharePoint list?  That would probably be a more common scenario than SMS... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38b2975-5eb6-1aa4-c1fd-d0f033ace5ca
* Version Independent ID: 85899731-9939-a779-29c4-4da652667b74
* Content: [Run flows based on email properties - Microsoft Flow](https://docs.microsoft.com/en-us/flow/email-triggers#feedback)
* Content Source: [flow-docs/email-triggers.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/email-triggers.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Hi @thedavegray . Thanks for submitting docs feedback. We'll keep this in mind as we build out and update content.
