### ISSUE TITLE
10-minute timeout when testing Flows?

### ISSUE THREAD

**Issue by platinumazure** [MicrosoftDocs/power-automate-docs#148]
I've run into some sort of 10-minute timeout while testing a Flow. I visited this page for more information and didn't see any timeouts of 10 minutes. Furthermore, when I went back to the Run History, the run was shown as still executing. Is there an actual timeout? If this behavior is intended, could it be documented here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Microsoft Flow](https://docs.microsoft.com/en-us/flow/limits-and-config#feedback)
* Content Source: [flow-docs/limits-and-config.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by ChrisBenJohnson** [comment]
There is also a post on the Flow Community forums about this - necroed recently.

**Comment by Dean-Haas** [comment]
This is covered in the doc  https://github.com/MicrosoftDocs/ai-builder-pr/pull/311

**Comment by Dean-Haas** [comment]
Solution is in this community post: https://powerusers.microsoft.com/t5/General-Power-Automate/Do-Until-Need-help-understanding-limits/m-p/371382#M36381

**Comment by platinumazure** [comment]
In my original post, I was asking about if documentation could be made more clear on this. Do we really believe no documentation changes are needed here?

**Comment by ChrisBenJohnson** [comment]
The post linked by @Dean-Haas is a different issue. This is a bug where a Flow seems to have timed out if it is 'watched' in a window while executing. However it has not timed out and is still running, which can be confirmed by navigating away and then selecting the Flow run again.

The post I linked to has multiple users confirming this behaviour. I would imagine a bug fix would be more appropriate than a documentation change, depending on timescales.

**Comment by Dean-Haas** [comment]
Thanks for the clarifications. I'll add a note to the topic.
