### ISSUE TITLE
Check for Condition within Message Headers

### ISSUE THREAD

**Issue by macWyo** [MicrosoftDocs/power-automate-docs#149]
Can you please tell me how to check for a string within the message headers?  Specifically, I need to see if the original message originated from a particular IP address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38b2975-5eb6-1aa4-c1fd-d0f033ace5ca
* Version Independent ID: 85899731-9939-a779-29c4-4da652667b74
* Content: [Run flows based on email properties - Microsoft Flow](https://docs.microsoft.com/en-us/flow/email-triggers#feedback)
* Content Source: [flow-docs/email-triggers.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/email-triggers.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
@macWyo Thanks for submitting docs feedback. Sorry for the delay in responding. If you haven't found the answers you were looking for, please submit your question on the [Power Automate Community forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity). As I don't see a documentation issue here I am going to close this one. Thank you.
