### ISSUE TITLE
Application Insights Connector showing incorrect png when sending it as email

### ISSUE THREAD

**Issue by backendjavadeveloper** [MicrosoftDocs/power-automate-docs#152]
Hi,

I am trying to use the Microsoft flows for reporting purpose. We use application insights to monitor our services and we would like to have hourly reports (i.e. run application insights query via Flows and send it as emails).

The problem that we are facing is, the data is sporadically shown incorrect. I.e. the results are mixed up quite a bit of times.

Example: 
There are 2 query results that i want to embed in my email report. 
1. The first is the number of successful requests in last 1 hour and 
2. The number of failed requests in last 1 hour. 

The application insights queries are correct as we already have application dashboards with the same queries and the result is shown correctly in application insights. 

However, when the timechart is embedded into the email report generated by Flows, the results are duplicated i.e. we see successful requests png being displayed for failed requests and vice versa as well.

Can you please help on the suggested solution for the same?

Thanks,
Deepak

**Comment by Dean-Haas** [comment]
Hi @backendjavadeveloper. You've submitted this as feedback on the documentation. I apologize for the delay in responding. If you have not found a resolution to this issue, please post your question on the [Power Automate Community forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity).
