### ISSUE TITLE
Anchor links not working properly in approval markdown

### ISSUE THREAD

**Issue by dylanwauters** [MicrosoftDocs/power-automate-docs#153]
Hey

I just noticed that the markdown for anchor links does not work properly in approvals. When clicking on the anchor link in the approval email, it opens a new **Office 65 Outlook** tab in the browser instead of navigating to the right header in the approval email. 

Thanks for helping!

**Comment by PzKfWg** [comment]
Same here. Markdown links are not working at all on Outlook Online or Outlook 365 thick client.

**Comment by Dean-Haas** [comment]
@hamenon-ms Is this a known issue? Do we need to note it [here](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support)? Thanks.

**Comment by dblyth-msft** [comment]
@Dean-Haas yes we should add it as a known issue. This would an Outlook issue. We can relay it to them, but we should add it as a known issue. Let me know if you need me to do that or if you will.

**Comment by Dean-Haas** [comment]
Could you please file the product bug?  You’re better able to explain it.

Thanks!

Dean Haas
Murphy & Associates
TECHNICAL WRITER | MICROSOFT CLOUD + AI | CLOUD DESIGN STUDIO
v-dehaas@microsoft.com<mailto:v-dehaas@microsoft.com> | 360-440-6333

**Comment by v-aangie** [comment]
@dylanwauters - Anchor links support is a known issue. We've documented it here - https://docs.microsoft.com/en-us/power-automate/approvals-known-issues and will go live later Tuesday. Closing this issue.
