### ISSUE TITLE
Actions are changed - Please update document

### ISSUE THREAD

**Issue by lovethakker02** [MicrosoftDocs/power-automate-docs#154]
"start an approval" is now "create an approval". Please update document. Also include details for "start and wait for approval" action if possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78d8ec21-2a2d-e06d-9379-b30b3595cfe7
* Version Independent ID: 978afb49-2fa2-9e95-76e4-446e689f19a0
* Content: [Create an approval flow that requires everyone to approve - Microsoft Flow](https://docs.microsoft.com/en-us/flow/all-assigned-must-approve#feedback)
* Content Source: [flow-docs/all-assigned-must-approve.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/all-assigned-must-approve.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@lovethakker02 Thanks for using Power Automate. We'll update the document. Thanks!
