### ISSUE TITLE
Limits and config - Looping typo

### ISSUE THREAD

**Issue by akaskela** [MicrosoftDocs/power-automate-docs#155]
In Limits and Config, Looping and debatching limits section, he column name "Actions concurrent outgoing calls - Free and Plan 1 license" is listed twice. The second one should (probably) be for Plan 2.

![image](https://user-images.githubusercontent.com/37714318/64288580-77fd9c80-cf30-11e9-9b01-fb7dfb4f5d9f.png)

**Comment by MSFTMan** [comment]
@akaskela Thanks for reporting this issue. It has been fixed.
