### ISSUE TITLE
Filter array unclear - needs clarification

### ISSUE THREAD

**Issue by pconnell99** [MicrosoftDocs/power-automate-docs#157]
I am trying to implement a filter like this, but the screenshot is unclear and there is no depth in the example.  HOW do you get 'first' into the first box?  I have an equivalent setup in one of my flows and I cannot get a named field of my array into that box!

A step by step or even a screenshot of the advanced edit would be useful in this case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bddf7e-aad7-5b99-0b73-a893d25615f5
* Version Independent ID: f2f0c4d6-b613-d269-4756-bcd7548f76ec
* Content: [Understand data operations - Microsoft Flow](https://docs.microsoft.com/en-us/flow/data-operations#use-the-filter-array-action)
* Content Source: [flow-docs/data-operations.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/data-operations.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by pconnell99** [comment]
For anyone wondering put item()['first'] in the first box.  Icon is different in my Flow though. Blue/white finger icon.

**Comment by Beck0Fish** [comment]
Thanks pconnell99! What I wanted was even simpler than what they partially demo'd here: I had a Variable of type Array of whole numbers (1s, 2s, or 3s) and wanted to display how many of  these were number 3.  In the Filter Array action my 'From' was the Array (available under Variables in Dynamic Content) and my operator 'is equal to' and value 3.  Your mention of 'item' helped me figure out the first part of the equation -  item()  on its own ended up working as a pasted expression (note NO parameters).  The advanced mode looked like this:  @equals(item(), 3)
Posting in case this helps someone else!

**Comment by Beck0Fish** [comment]
Oh, I could then use length(body('Filter_array')) to get a count of how many that filter caught!

**Comment by MSFTMan** [comment]
@pconnell99 Thanks for the heads up. We'll overhaul this doc soon.
