### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by lmvdz** [MicrosoftDocs/power-automate-docs#158]
Hello I am trying to embed widgets into my SPA.

I am able to get the accessToken no problem (via MSAL), but when trying to render the (approvalCenter) widget i get the following error:

Time:
Server/Client Correlation ID: a5b725a8-2485-4cf5-9f0c-5c7de917abad
Error: Authentication failed.

When using a different widget type (flows), I do not get this error rather an endless loading animation.
I am using `msflowsdk-1.1.js`
If you'd like to see the code please let me know and I will give access to my gitlab repository.

```javascript
this.msflowsdk = new MsFlowSdk({
        hostName: "https://flow.microsoft.com",
        locale: "en-US"
      });
      this.approvalCenterWidget = this.msflowsdk.renderWidget(
        "approvalCenter",
        {
          container: "flow-div",
          enableOnBehalfOfTokens: true,
          flowsSettings: {},
          templatesSettings: {},
          approvalSettings: {},
          widgetStyleSettings: {}
        }
      );
      var that = this;
      this.approvalCenterWidget.listen("GET_ACCESS_TOKEN", function(
        requestParam,
        widgetDoneCallback
      ) {
        widgetDoneCallback(null, {
          token: that.$store.state.accessToken
        });
      });
      this.approvalCenterWidget.listen("WIDGET_READY", function() {
        console.log("The flow widget is now ready.");
      });
      this.approvalCenterWidget.listen("WIDGET_RENDERED", function() {
        console.log("The flow widget is now rendered.");
        document.getElementById("flow-div").className = "flow-container";
      });
      this.approvalCenterWidget.listen(
        "RECEIVED_APPROVAL_STATUS_CHANGED",
        function(param) {
          console.log(
            "The received approval has changed status. The current count of approvalRequests is " +
              param.data.approvalRequestsCount
          );
        }
      );
```

Thank you,

Lars

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac3ad92-eb8f-554a-5de3-14c430e594aa
* Version Independent ID: fab1ceb3-5110-4452-0a0d-99346cc31230
* Content: [Integrate Microsoft Flow with websites and apps - Microsoft Flow](https://docs.microsoft.com/en-us/flow/developer/embed-flow-dev#feedback)
* Content Source: [flow-docs/developer/embed-flow-dev.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/developer/embed-flow-dev.md)
* Service: **flow**
* GitHub Login: @bbarath
* Microsoft Alias: **barathb**

**Comment by XeonPowder** [comment]
Hello... any response?

**Comment by Dean-Haas** [comment]
Hi @lmvdz . Sorry for the long delay here. This came through as documentation feedback where customers submit feedback regarding what's in our documentation, and update our docs based on that feedback. I think you are looking for product support. Have you tried submitting this on the [Power Automate Community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity)?

**Comment by lmvdz** [comment]
Hi @Dean-Haas,

Sorry, I have just given up on using the library now... Perhaps I'll try again and see if I can get it working this time around. I'll make sure to post in the correct place if I run into an issue.

Thanks,

Lars

**Comment by Akuma-U1** [comment]
Hi @lmvdz 
Did you ever get this integration working?
