### ISSUE TITLE
Lack of Advanced Edit Mode

### ISSUE THREAD

**Issue by jpheeter** [MicrosoftDocs/power-automate-docs#159]
Could you please update the examples to show the new mode of input, I'm primarily looking to check if a [value] is empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27504e8c-568f-ee52-542c-5ca87c2906db
* Version Independent ID: dc8f9282-90ce-60e0-402c-ea8829b6334e
* Content: [Use expressions with conditions. - Microsoft Flow](https://docs.microsoft.com/en-us/flow/use-expressions-in-conditions#feedback)
* Content Source: [flow-docs/use-expressions-in-conditions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/use-expressions-in-conditions.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@jpheeter - Thanks for your feedback. We have updated the docs to fix information here - https://docs.microsoft.com/en-us/power-automate/use-expressions-in-conditions#use-the-empty-expression. The updated content is live. Closing this issue.
