### ISSUE TITLE
Edit a Flow edit in All Solutions

### ISSUE THREAD

**Issue by mowafakgabal** [MicrosoftDocs/power-automate-docs#160]
If you import a Flow from an existing solution into another solution in the same environment, every time you chance the flow, it is changed in all solutions.
This cannot be right, what is the reason even to create different solutions if you cannot edit each flow separate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d865166-93b6-e99e-9b76-13144fe77a10
* Version Independent ID: 2c16aac3-0db9-9b47-75b5-a4015eb6da7f
* Content: [Learn how to import a solution - Microsoft Flow](https://docs.microsoft.com/en-us/flow/import-flow-solution#feedback)
* Content Source: [flow-docs/import-flow-solution.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/import-flow-solution.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@mowafakgabal Thanks for reporting this issue. Are you still seeing this behavior?

**Comment by MSFTMan** [comment]
@mowafakgabal We are closing this issue since we haven't gotten a response from you. Do let us know if you still see this issue.
