### ISSUE TITLE
Edit change all Flow in All Solutions

### ISSUE THREAD

**Issue by mowafakgabal** [MicrosoftDocs/power-automate-docs#161]
If you edit a flow in one solution, it edit all flows in all other solutions, this cannot be right. Else, why create different solutions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 405a5cc9-f91f-4230-8140-4446324914b0
* Version Independent ID: 8196e230-463d-5b1e-0e07-11aca8bb886b
* Content: [Overview of solution-aware flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/edit-solution-aware-flow)
* Content Source: [flow-docs/edit-solution-aware-flow.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/edit-solution-aware-flow.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@mowafakgabal Thanks for your feedback. The behavior you've identified is the expected behavior. We'll update the docs to reflect this behavior. Closing this issue.
