### ISSUE TITLE
Confusing Language

### ISSUE THREAD

**Issue by Pseudo-Register** [MicrosoftDocs/power-automate-docs#162]
The tip says "The bot lists and runs flows that are triggered by a schedule, or manually triggered without user input." If a flow isn't triggered automatically, isn't the only other way it can be triggered by 'user input' of some kind? Like pressing a button or using the bot? Where is the 'manual' part if it's not 'user input'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3429a9-84f0-0c7a-158b-6fb6ced457ab
* Version Independent ID: 8232b831-10f7-d59d-3dd9-a1e288b2c2ed
* Content: [Learn to create and manage flows in Microsoft Teams - Microsoft Flow](https://docs.microsoft.com/en-us/flow/flows-teams#feedback)
* Content Source: [flow-docs/flows-teams.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/flows-teams.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@Pseudo-Register Thanks for your question. Instant flows are considered manual, because someone must initiate the flow.
