### ISSUE TITLE
Out of date content?

### ISSUE THREAD

**Issue by Texterity** [MicrosoftDocs/power-automate-docs#165]
I suspect this tutorial is out of sync with the product, some of the actions and selections don't appear in the version of Flow that I have been assigned. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f51e26d-e8cd-2152-45a2-bd23d13fb3b2
* Version Independent ID: 30768baf-8dd7-d64c-aec2-f500fbbe1e78
* Content: [Easily Automate approval workflows. - Microsoft Flow](https://docs.microsoft.com/en-us/flow/modern-approvals#feedback)
* Content Source: [flow-docs/modern-approvals.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by rosskyl** [comment]
A big one is the Response token is renamed to Outcome.

**Comment by darrenr19** [comment]
Yes - that was problematic.  Outcome fixed my Flow
