### ISSUE TITLE
There is an issue

### ISSUE THREAD

**Issue by nwoodcl** [MicrosoftDocs/power-automate-docs#169]
I cant change values such as timezone, hour, minute in the advance settings section. it just closes the section and then puts the recurrence trigger into error. tried all browsers (including edge?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba2e127-56bc-5910-3af6-30030cf58c1f
* Version Independent ID: c8fea93d-3d8d-bf8e-af7d-ae853a936843
* Content: [Run flows on a schedule - Microsoft Flow](https://docs.microsoft.com/en-us/flow/run-scheduled-tasks#feedback)
* Content Source: [flow-docs/run-scheduled-tasks.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/run-scheduled-tasks.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@nwoodcl Thanks for using Power Automate. We've created a flow with the Schedule connector and we are able to modify the time zon and other properties. If you continue to see a problem, consider contacting support so that you can receive assistance.
