### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by awgraf** [MicrosoftDocs/power-automate-docs#170]
Appears to be a typo on this section:

GCC Customers:
.microsoft.us
.azure-apihub.us
.azure.us
.usgovcloudapi.net
.microsoftonline.com
. microsoft.com
.windows.net
. azureedge.net
. azure.net
.crm9.dynamics.com

Recommended fix:

GCC Customers:
.microsoft.us
.azure-apihub.us
.azure.us
.usgovcloudapi.net
.microsoftonline.com
.microsoft.com
.windows.net
.azureedge.net
.azure.net
.crm9.dynamics.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d0a9ce-bdc6-9f60-fecb-eb5cabfe21ee
* Version Independent ID: d2267099-da75-d3d7-77cf-af41fcc1cf1e
* Content: [Microsoft Flow US Government - Microsoft Flow](https://docs.microsoft.com/en-us/flow/us-govt)
* Content Source: [flow-docs/us-govt.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/us-govt.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@awgraf Thannks for reporting this issue. We've fixed it and the fix will be available soon.
