### ISSUE TITLE
IP used to send messages through Office 365

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/power-automate-docs#171]
Hi! Can you add information what IPs are being used by the Office 365 Send an email action? It's necessary to detect if message was sent by Flow in transport rules. I can see that from my European environment it is using 20.190.129.100 address so it's out of range for IPs for Europe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Microsoft Flow](https://docs.microsoft.com/en-us/flow/limits-and-config#feedback)
* Content Source: [flow-docs/limits-and-config.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@Larryngolog  Thanks for using Power Automate. This IP address is documented in the linked "office 365 and urls page here: https://docs.microsoft.com/office365/enterprise/urls-and-ip-address-ranges#microsoft-365-common-and-office-online

**Comment by Larryngolog** [comment]
@MSFTMan can you please point exactly where is it documented? In the article you have pointed to there is no reference to "Flow" or "Power Automate" or anything that points to sending emails by flow
