### ISSUE TITLE
How to mark a flow as Noncustomizable and CannotBedeleted ? 

### ISSUE THREAD

**Issue by Kaviarasi** [MicrosoftDocs/power-automate-docs#172]
Is there any way to set the microsoft flow as non customizable / can not be deleted once created. 
I can set a workflow in dynamics as non customizable and cannot be deleted. 
Is there any similar settings in flow 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f78faa65-bb08-e6bb-4b0e-6b1f3862b975
* Version Independent ID: 4efbfdaa-b753-1aae-7f09-ef97fe2f544d
* Content: [Create a flow with Dynamics 365 (online) - Microsoft Flow](https://docs.microsoft.com/en-us/flow/connection-dynamics365)
* Content Source: [flow-docs/connection-dynamics365.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/connection-dynamics365.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by MSFTMan** [comment]
@Kaviarasi Thanks for using Power Automate. No, you can always modify and delete flows that you create.
