### ISSUE TITLE
update page with new per user and per flow plans?

### ISSUE THREAD

**Issue by robdawsoncranhillinsight** [MicrosoftDocs/power-automate-docs#173]
P1 and P2 are retiring; what about the new Flow plans please? Could this page please be updated to revise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Microsoft Flow](https://docs.microsoft.com/en-us/flow/limits-and-config#looping-and-debatching-limits)
* Content Source: [flow-docs/limits-and-config.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@robdawsoncranhillinsight Thanks for using Power Automate. This issue has been addressed.
