### ISSUE TITLE
Doc is unclear

### ISSUE THREAD

**Issue by ianceicys** [MicrosoftDocs/power-automate-docs#175]
So I'm trying to follow along with this document and I'm not sure how to read in the associated json <indicies>. 

I am not able to figure out where/how I can define inputs for a web-ui flow. Is there any documentation on how to call input variables in UI Flows?

[https://i.imgur.com/ERFroyl.png](https://i.imgur.com/ERFroyl.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9ffaec1-7e0d-fedb-a300-7492e91f26a0
* Version Independent ID: d900cdf8-4e0e-2211-c694-271de641e7b3
* Content: [Use inputs and outputs in Web UI flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/ui-flows/inputs-outputs-web)
* Content Source: [flow-docs/ui-flows/inputs-outputs-web.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/ui-flows/inputs-outputs-web.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@gachasta Hi Gautier, any thoughts on this item?

**Comment by MSFTMan** [comment]
@ianceicys Thanks for your feedback. Please consider using Power Automate Desktop for your automation needs. Closing this issue.
