### ISSUE TITLE
Workflow on BPF

### ISSUE THREAD

**Issue by rajyraman** [MicrosoftDocs/power-automate-docs#180]
In the last part, the workflow is a background workflow. I don't think real-time workflow works in this scenario. Can this be made more explicit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9be36ba-123a-840b-48c2-c040a065097a
* Version Independent ID: 24e7d362-b0bb-1e75-802b-c8e00196c1b0
* Content: [Best practices for using business process flow entity attributes - Power Automate](https://docs.microsoft.com/en-in/flow/best-practices-entity-attributes#feedback)
* Content Source: [flow-docs/best-practices-entity-attributes.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/best-practices-entity-attributes.md)
* Service: **crm-online**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@rajyraman - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.
