### ISSUE TITLE
Typo in information box

### ISSUE THREAD

**Issue by nonodename** [MicrosoftDocs/power-automate-docs#183]
If you don't see the feature in your environement... should be  If you don't see the feature in your environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1328965-3272-9380-7215-87b87b9169a1
* Version Independent ID: db6b4071-a4ee-c9fb-1142-f38d6d6e0a47
* Content: [Set up UI flows on your device - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/setup#feedback)
* Content Source: [flow-docs/ui-flows/setup.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/ui-flows/setup.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@nonodename thanks for reporting this issue. It has been fixed and will be available publicly soon.
