### ISSUE TITLE
Organisation ID

### ISSUE THREAD

**Issue by petebryan** [MicrosoftDocs/power-automate-docs#184]
I don't see the Organisation ID in Power Automate in the way this document suggests, can you please expand on this section and how to get my Org ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eecc2503-eee7-8779-2445-d6cd6968a0bd
* Version Independent ID: 532be787-8be9-c9b5-37a2-88841c5b8118
* Content: [Flows are now stored in Common Data Service and use the rich Web API - Power Automate](https://docs.microsoft.com/en-us/power-automate/web-api#feedback)
* Content Source: [articles/web-api.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/articles/web-api.md)
* Service: **business-applications**
* Product: ****
* Technology: ****
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@petebryan Thanks for using Microsoft Power Automate. We'll investigate this issue.
