### ISSUE TITLE
32 bit version cant register keys hkey_local_machine

### ISSUE THREAD

**Issue by macsilber** [MicrosoftDocs/power-automate-docs#188]
Getting the following error when trying to install the first time it tries to download on y machine which is Windows 10 64 bit

<img width="696" alt="Screen Shot 2019-11-21 at 9 57 22 AM" src="https://user-images.githubusercontent.com/5730979/69349607-09ce9900-0c46-11ea-8a0d-2438938c87ce.png">

**Comment by Dean-Haas** [comment]
@macsilber  thanks for submitting this feedback. As this would be a product issue, not a docs issue, we'll submit it for evaluation and tracking as a product bug, and close out this docs bug.
