### ISSUE TITLE
Admin URL missing

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/power-automate-docs#189]
The power platform admin center is not in the list of gov URLs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d0a9ce-bdc6-9f60-fecb-eb5cabfe21ee
* Version Independent ID: d2267099-da75-d3d7-77cf-af41fcc1cf1e
* Content: [Power Automate US Government - Power Automate](https://docs.microsoft.com/en-us/power-automate/us-govt)
* Content Source: [articles/us-govt.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/us-govt.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@jordanmills Thanks for using Power Automate. As noted in the limitations section of this doc, the power platform admin center isn't available for gov. See this:
_Power Platform admin center – You can use the admin center to open support tickets, but other functionality is currently not available in US Government tenants._
