### ISSUE TITLE
Approval timeouts and escalations

### ISSUE THREAD

**Issue by ChrisGarty** [MicrosoftDocs/power-automate-docs#190]
It would be useful to have documentation about how to manage timeouts on approval requests and how to set up an escalation if the approval times out. This is a common scenario in large organizations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f51e26d-e8cd-2152-45a2-bd23d13fb3b2
* Version Independent ID: 30768baf-8dd7-d64c-aec2-f500fbbe1e78
* Content: [Easily Automate approval workflows. - Power Automate](https://docs.microsoft.com/en-us/power-automate/modern-approvals)
* Content Source: [articles/modern-approvals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by ChrisGarty** [comment]
Basically an official documentation version of this: https://flow.microsoft.com/en-us/blog/approval-escalation-tutorial/

**Comment by MSFTMan** [comment]
@ChrisGarty Thanks for your questions. We will update the documentation with this information: https://flow.microsoft.com/en-us/blog/approval-escalation-tutorial/. Thanks!
