### ISSUE TITLE
parallel processing in ms flow

### ISSUE THREAD

**Issue by vidhya9687** [MicrosoftDocs/power-automate-docs#191]
Please help me understand this scenario: 

I have a customer who wants to upload multiple documents to a Document library. 
Every time a document is uploaded, It triggers a MS Flow(Power Automate). I want to know if suppose he uploads 100 documents at a time, What happens to the MS flow? 
Does it run a 100 Parellel flow or keeps the flow in Queue and process it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config#feedback)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by ThreeTen22** [comment]
Depends on how you set up the flow.  If you use the @splitOn setting, (which can be found on the settings property of the trigger) then yes, it will run 100 parallel flows.  

However if you turn it off,  it will instead batch up triggered processes into arrays, and run the flow one batch at a time until all triggered actions have been processed.
