### ISSUE TITLE
Parse JSON

### ISSUE THREAD

**Issue by Hjaf** [MicrosoftDocs/power-automate-docs#192]
There should be more information / examples on parse JSON. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bddf7e-aad7-5b99-0b73-a893d25615f5
* Version Independent ID: f2f0c4d6-b613-d269-4756-bcd7548f76ec
* Content: [Understand data operations - Power Automate](https://docs.microsoft.com/en-us/power-automate/data-operations#feedback)
* Content Source: [articles/data-operations.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/data-operations.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by johnmsaxton** [comment]
Agree... there are so many JSON examples that should be documented. If MSFT wants this to be low-code / no-code we need much, much better and more explicit documentation. Otherwise I might as well just write the C / C++ or C# code and be done with it.

**Comment by MSFTMan** [comment]
@Hjaf Thanks for reporting this issue. We're adding this request for more json examples to our backlog.
