### ISSUE TITLE
There is an error in the description of the Gateways

### ISSUE THREAD

**Issue by github129** [MicrosoftDocs/power-automate-docs#195]
[Enter feedback here]
This description is incorrect.
Supported in the default environment only, not in custom environments.
![image](https://user-images.githubusercontent.com/25972825/70402815-03c71d80-1a78-11ea-8314-56795c2cf202.png)

The gateway supports custom environments in the same region as the default environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2ea76cf-af8d-12a6-1d73-23cee3a0667d
* Version Independent ID: 0fdd1b60-d353-cf90-40d1-2610c11e314a
* Content: [Regions overview for Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/regions-overview#feedback)
* Content Source: [articles/regions-overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/regions-overview.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by github129** [comment]
The problem page is here
https://docs.microsoft.com/en-us/power-automate/regions-overview

**Comment by MSFTMan** [comment]
@github129  Thanks for reporting this issue. It is now fixed.
