### ISSUE TITLE
is this supposed to read "the speed that you type during recording"??

### ISSUE THREAD

**Issue by Scheevel** [MicrosoftDocs/power-automate-docs#196]
https://docs.microsoft.com/en-us/power-automate/ui-flows/create-desktop#known-issues-and-solutions
 - 3rd bullet
...Duplicate actions may be created depending on *the type and the speed of you are recording.*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d024a2c8-e958-e643-93f5-95cf8637fb2c
* Version Independent ID: 9f9028ac-88ef-bf06-0dd8-77729edd84e8
* Content: [Learn to create desktop UI flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/create-desktop#feedback)
* Content Source: [articles/ui-flows/create-desktop.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/create-desktop.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@Scheevel Thanks for reporting this issue. It's now resolved.
