### ISSUE TITLE
Flow / PA Connections and My Connections instructions outdated

### ISSUE THREAD

**Issue by semopz** [MicrosoftDocs/power-automate-docs#197]
Since the Power Automate rebrand, the Connections and My Connections links have been (re?)moved.

There is no longer a Connections menu item when the gear icon is clicked on. I've tried clicking on the gear icon when in the "My Flows" or "Shared Flows" views and even when editing a Flow but there's no Connections menu item.

![screenshot of Power Automate gear icon where Connections menu item is missing](https://i.imgur.com/tJ1yBoT.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bf9b6c-5628-f18c-7027-45b21eb3b6bc
* Version Independent ID: a4394ad5-9d46-2a6d-16d9-48b0c88fb401
* Content: [Learn to connect to your data using connections and on-premises data gateways - Power Automate](https://docs.microsoft.com/en-us/power-automate/add-manage-connections)
* Content Source: [articles/add-manage-connections.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/add-manage-connections.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by Quartermaster-007** [comment]
I faced the same issue, the settings menu on (at least) emea.flow.microsoft.com does not contain a section to manage existing data connections.
A quick workaround that I found, is to go to Power Apps (make.powerapps.com) (make sure you are in the same environment). On the left side, click on 'Data', and then click on 'Connections'. That page will allow you to add and delete connections.

**Comment by semopz** [comment]
Another workaround is to click on "My Flows" in the navigation pane and then change the end of the URL from `/flows` to `/connections`

**Comment by IsmaelInRedlands** [comment]
Thanks @semopz! More than 4 months have elapsed since this issue was reported to Microsoft. It is about time the documentation is updated.

**Comment by Dean-Haas** [comment]
Updates made - changes pending publish.
