### ISSUE TITLE
Edit in advanced mode

### ISSUE THREAD

**Issue by jeannineshiu** [MicrosoftDocs/power-automate-docs#198]
I couldn't find "Edit in advanced mode" anywhere in the condition block, is this featured already be deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af5f3e7-4734-5813-0e3d-dada381fec0b
* Version Independent ID: 393c8bdd-da49-d6cd-f97a-94283f55c0a2
* Content: [Add a condition to a flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/add-condition#add-a-condition)
* Content Source: [articles/add-condition.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/add-condition.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by axtain** [comment]
As per the below post, "Edit in Advanced mode" feature has been removed. Alternative approach is explained in the same post.

[https://flow.microsoft.com/en-us/blog/build-more-powerful-conditions-in-flows-and-more/](url)

**Comment by goravseth** [comment]
the link above goes to https://docs.microsoft.com/en-us/power-automate/url and does not work, here is correct link
https://flow.microsoft.com/en-us/blog/build-more-powerful-conditions-in-flows-and-more/

**Comment by Dean-Haas** [comment]
@jeannineshiu thanks for submitting this feedback. As this appears to have been resolved in the doc, I'll go ahead and close this issue.
