### ISSUE TITLE
SharePoint limits section wrong link

### ISSUE THREAD

**Issue by pealmasa** [MicrosoftDocs/power-automate-docs#199]
This section of this article: https://docs.microsoft.com/en-us/power-automate/limits-and-config?source=docs#sharepoint-limits

contains a link to supposedly SharePoint with Power Automate limitations but it points to a completely wrong content.

Is there any available information about this limitation to point to the correct article?

**Comment by GiantCrocodile** [comment]
I think this is what you are looking for: https://docs.microsoft.com/en-us/connectors/sharepointonline/#limits

**Comment by MSFTMan** [comment]
@GiantCrocodile Thanks for reporting this issue. It has been fixed.
