### ISSUE TITLE
"Where can I find out what my plan is?" - not answered

### ISSUE THREAD

**Issue by murchu27** [MicrosoftDocs/power-automate-docs#200]
The supplied answer points to the pricing page, which does not answer the question. How can I check what plan is currently active on my account? 

https://docs.microsoft.com/en-us/power-automate/billing-questions#where-can-i-find-out-what-my-plan-is

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1947fd4e-170f-6392-e309-5fd05082ffb8
* Version Independent ID: 79ccd9e1-0998-bc4e-004c-ffbe57291196
* Content: [Billing and metering questions - Power Automate](https://docs.microsoft.com/en-us/power-automate/billing-questions#where-can-i-find-out-what-my-plan-is)
* Content Source: [articles/billing-questions.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/billing-questions.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by GiantCrocodile** [comment]
You can see it here @murchu27: https://portal.office.com/account/#subscriptions
