### ISSUE TITLE
Outdated info for Power Automate Capabilities

### ISSUE THREAD

**Issue by LinnZawWin** [MicrosoftDocs/power-automate-docs#202]
Run child workflows (flows) is available now in Power Automate.
https://flow.microsoft.com/en-us/blog/october-updates-for-microsoft-flow/

Run Common Data Service actions (including custom)	is possible with "Perform a bound/unbound action" using Common Data Service (current environment) connector
https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/#perform-a-bound-action

Trigger on multiple Common Data Service entity events is possible with Common Data Service (current environment) connector
https://docs.microsoft.com/en-us/connectors/commondataserviceforapps/#when-a-record-is-created,-updated-or-deleted

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c08ddd-c290-34f4-5e82-ae9369012efd
* Version Independent ID: 98652aac-b377-c9fe-bb32-47d873f7237a
* Content: [Replace classic Common Data Service workflows with Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/replace-workflows-with-flows)
* Content Source: [articles/replace-workflows-with-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/replace-workflows-with-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@LinnZawWin Thanks for reporting this issue. We are fixing it and it will be released within 1 day.
