### ISSUE TITLE
Broken link on https://flow.microsoft.com/en-us/ that might be endemic of a bad URL rewrite rule

### ISSUE THREAD

**Issue by dreftymac** [MicrosoftDocs/power-automate-docs#203]
On one of the top-level MSFT marketing/brochure pages, there is a broken link that looks like a result of a bad URL-rewrite rule.

Here is a screenshot:

![Capture](https://user-images.githubusercontent.com/4074354/71533119-e5508700-28ab-11ea-9b3e-cd73d8ca694c.PNG)

**Comment by ryotokuro** [comment]
Can't seem to locate what you've attached in our screenshot.
Maybe the format of the page has changed since?

**Comment by dreftymac** [comment]
Yes that page is now substantially different. This is no longer an issue.
