### ISSUE TITLE
F.A.Q. needs update

### ISSUE THREAD

**Issue by bartjablonski** [MicrosoftDocs/power-automate-docs#205]
I'm confussed - You're reffering to the Plan 2 and Plan 1 which no longer exists? At the same time you're using "Power Automate" instead of "Microsoft Flow", so it looks like naming has been updated, but not plans?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec72d8df-bd1f-6eee-e89c-b029aa14fa67
* Version Independent ID: c1cda151-9cf7-103b-a62c-e0c2fef549f7
* Content: [Environment overview for Administrators - Power Automate](https://docs.microsoft.com/en-us/power-automate/environments-overview-admin#feedback)
* Content Source: [articles/environments-overview-admin.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/environments-overview-admin.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by MSFTMan** [comment]
@bartekgraczyk This issue is now fixed. It will be live on Monday. Thanks for using Power Automate.
