### ISSUE TITLE
Failed at the first step

### ISSUE THREAD

**Issue by jfgoodhew1** [MicrosoftDocs/power-automate-docs#207]
"Select showing drop down list" - from where? I don't see it anywhere... I'm pretty sure I have full access to Flow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ced33bf5-ecdb-4aa9-fc67-0fac06659369
* Version Independent ID: dcd3c2f4-6a2e-f9ce-d573-0a9d6e530de5
* Content: [Learn how to automate and run repetitive tasks with button flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/introduction-to-button-flows#feedback)
* Content Source: [articles/introduction-to-button-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/introduction-to-button-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@jfgoodhew1 Thanks for reporting this issue. We are updating this content all up, and will publish it as soon as it's ready.
