### ISSUE TITLE
Any new releases??

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/power-automate-docs#208]
It's been awhile since this page has been updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53c02fee-38c5-649a-0faa-23bf5edbcd7f
* Version Independent ID: 65ee90be-a0f2-15c0-b487-7210eddda17a
* Content: [Release notes - Power Automate](https://docs.microsoft.com/en-us/power-automate/release-notes#feedback)
* Content Source: [articles/release-notes.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/release-notes.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by DeanGross** [comment]
I agree, where is the new content?

**Comment by MSFTMan** [comment]
@cconrado Thanks for reporting this issue. It's now fixed. Find release plans here: https://docs.microsoft.com/dynamics365/release-plans/)

**Comment by DeanGross** [comment]
Thanks, but that does not fix the problem on the referenced Release Notes page, it would be helpful if there was a cross reference link added to this page.

**Comment by cconrado** [comment]
@MSFTMan agree with @DeanGross
