### ISSUE TITLE
Instant flow only working when made in default environment?

### ISSUE THREAD

**Issue by svanmoerkerke** [MicrosoftDocs/power-automate-docs#209]
I'm trying to create an "instant" flow in another environment than the default environment and this seem not to be working?

Is there any reference to what works and what doesn't on other environments than the default one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec72d8df-bd1f-6eee-e89c-b029aa14fa67
* Version Independent ID: c1cda151-9cf7-103b-a62c-e0c2fef549f7
* Content: [Environment overview for Administrators - Power Automate](https://docs.microsoft.com/en-us/power-automate/environments-overview-admin#feedback)
* Content Source: [articles/environments-overview-admin.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/environments-overview-admin.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by Dean-Haas** [comment]
Hi @svanmoerkerke. Thanks for providing docs feedback. It's hard to know what issue you might be seeing here. I recommend you refer to the more in-depth environments documentation that we link to in the [power platform docs](https://docs.microsoft.com/en-us/power-platform/admin/environments-overview). If you still have questions, try posting a question on the [Power Automate Community forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity)
