### ISSUE TITLE
Need to cover scenario when a boolean field is set as required in BPF stage.

### ISSUE THREAD

**Issue by pganapmsft** [MicrosoftDocs/power-automate-docs#210]
We need to cover this scenario in the documentation - https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/201364/two-options-in-business-process-flow-error-you-have-to-complete-the-required-steps-before-you-can-advance?pifragment-97030=1#responses

Ie: What happens when a boolean field is set as required for a BPF stage? This is a special case and should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7759368-a61e-08ce-e24f-b43a200521dd
* Version Independent ID: 80c1d8d8-a995-1023-91f9-0a1fd687c5b6
* Content: [Create a business process flow in Power Apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-business-process-flow#feedback)
* Content Source: [articles/create-business-process-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/create-business-process-flow.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Dean-Haas** [comment]
Hi @prsi-msft . Can you please evaluate this, and let me know if you think a documentation update is needed? If so, I can work with you to get it done. Thanks!

**Comment by prsi-msft** [comment]
Adding @Mark Spilde<mailto:mspilde@microsoft.com> who owns BPFs

@Kumar Vivek<mailto:kvivek@microsoft.com> please set Mark as the owner so he gets these notifications.

Thanks,
Praveen

**Comment by Dean-Haas** [comment]
@pganapmsft  Thanks for this great feedback. We've update the docs, and the change should be live shortly.
