### ISSUE TITLE
Flow vs Power Automate 

### ISSUE THREAD

**Issue by sth2258** [MicrosoftDocs/power-automate-docs#211]
Notes still listed about the name change however I believe documentation has been updated already

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d12f42-d17f-647e-b25c-ef6e56167983
* Version Independent ID: de5ec638-fffb-bd32-ee7c-66928026aa1c
* Content: [Find and fix errors with the Power Automate checker - Power Automate](https://docs.microsoft.com/en-us/power-automate/error-checker#feedback)
* Content Source: [articles/error-checker.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/error-checker.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by KumarVivek** [comment]
@sth2258 Thanks for the comment. Yes, we are aware of this but persisting with the message a little longer. We'll soon remove the note.

Closing the issue.
