### ISSUE TITLE
Submitted template not listed in Approvals

### ISSUE THREAD

**Issue by MartinM85** [MicrosoftDocs/power-automate-docs#213]
I submitted my flow as a template but the submitted template is not listed in Action items -> Approvals, so I cannot check the status of approval request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8d0d2-3a6f-c3f1-494d-b0ea73c22f9b
* Version Independent ID: 41bc35b2-5a4d-7406-1ae7-27b292033fcd
* Content: [Submit a flow template - Power Automate](https://docs.microsoft.com/en-us/power-automate/publish-a-template)
* Content Source: [articles/publish-a-template.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/publish-a-template.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by MSFTMan** [comment]
@MartinM85 Thanks for using Power Automate. Your flow template must be approved by Microsoft. Once your template is approved, it will be displayed in the template gallery.
