### ISSUE TITLE
Revoke Users Access if Malicious/Non permissible Web site open using Microsoft Flow Please Suggest

### ISSUE THREAD

**Issue by techgeekashishkumar** [MicrosoftDocs/power-automate-docs#214]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf98fbf-59fc-825d-e8bc-b4b5b42719a2
* Version Independent ID: 22977ae9-2f4b-c98e-d19d-1d8ebf43fbd2
* Content: [Get started - Power Automate](https://docs.microsoft.com/en-us/power-automate/getting-started)
* Content Source: [articles/getting-started.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/getting-started.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by techgeekashishkumar** [comment]
Hi,

Please suggest can we Revoke Users Access if Malicious/non-permissible Web site open using Microsoft Flow. 

KR 
Ashish Kumar

**Comment by KumarVivek** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, visit <https://flow.microsoft.com/support/>.
 
Closing this issue.
