### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by goyaweb** [MicrosoftDocs/power-automate-docs#218]
here is the new way to add loops:
https://powerusers.microsoft.com/t5/General-Power-Automate/Add-a-Condition-has-moved-in-Flow/td-p/165401

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39d79925-8b72-d4b0-e3fb-1b9164ecaaf3
* Version Independent ID: 06c8759f-1adf-470f-bdba-1f3af6f0a523
* Content: [Use the apply to each action to loop through an array of items. - Power Automate](https://docs.microsoft.com/en-us/power-automate/apply-to-each#feedback)
* Content Source: [articles/apply-to-each.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/apply-to-each.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@goyaweb Thanks for reporting this issue. We are updating this document and the updates will be live soon.
