### ISSUE TITLE
Can you actually provide inputs for Web UI Flows?

### ISSUE THREAD

**Issue by dougbell-ms** [MicrosoftDocs/power-automate-docs#219]
It's clear how inputs work for Desktop flows but what about Web UI flows?  The experience shown in this videa (https://www.youtube.com/watch?v=2UgZaSM2tq8) doesn't exist for Web UI flows.  Is it possible to provide inputs to Web UI flows?  Is this a feature that will come in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9ffaec1-7e0d-fedb-a300-7492e91f26a0
* Version Independent ID: d900cdf8-4e0e-2211-c694-271de641e7b3
* Content: [Use inputs and outputs in Web UI flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/inputs-outputs-web#feedback)
* Content Source: [articles/ui-flows/inputs-outputs-web.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/inputs-outputs-web.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by wbsmolen** [comment]
@dougbell-ms I just just a few days to this but I figured it out. The documentation is accurate, just poorly worded.

Create a web UI flow as you would expect. Wherever you want your variables input, type "${VARIABLE NAME}". Save the flow and return to the power automate portal. You will see the UI Flow action card in Flow has new fields that correspond to your variable names.

Eg: I am using a ui flow to automate some forefront identity manager (\\idweb) actions. I have two variables: ${groups} and ${alias}. After I saved my flow with those variables, this is how the card appears in flow:
![image](https://user-images.githubusercontent.com/3998040/75412279-9c3aa480-58e7-11ea-9783-d5a69eed5fac.png)

**Comment by andrewbarrot** [comment]
@wbsmolen I'm initializing a variable from an instant trigger (string) and then passing it to my UI flow (not stored) and it still fails.  I'm using the following:  command - click          target - id=txt...         value - ${MC}

**Comment by wbsmolen** [comment]
@andrewbarrot what's the error message say? this sounds different than @dougbell-ms 's issue of surfacing variable inputs in the flow card ui

**Comment by andrewbarrot** [comment]
Bad gateway 502.  I can get the variable to surface in the flow ui card, but it seems to fail when trying to actually pass it to ui web flow from power automate.  As I understand it, there’s no store command needed before calling the variable in ui flow, so I just added it to a “type” command in the value field with the syntax ${MC}.  However, it isn’t evaluating that as dynamic content, instead it just types “${MC}”

**Comment by dougbell-ms** [comment]
Thank you, @wbsmolen, works like a charm.  I probably should have been able to figure that one out.  Not sure how I missed it before...

**Comment by michael7-tech** [comment]
I was hoping to use selenium to call values from google sheets when uploaded through power apps I have selenium working just can't figure how if it is possible to link to google sheets for row/column data any help would be appreciated?

**Comment by dougbell-ms** [comment]
@michael7-tech, if you're using a traditional Flow to trigger your selenium UI flow then you should be able to use the "trigger Flow" to grab rows/fields out of the sheet and then pass to the selenium UI flow as an input variable

**Comment by wbsmolen** [comment]
@andrewbarrot 502 sounds like your gateway is inaccessible to Flow (network issue). Check firewall settings and rerun the gateway setup to ensure it reports healthy status.

**Comment by michael7-tech** [comment]
Thanks @dougbell-ms obvious need to get my head around it. Another quick question is there a way I can cycle through multiple rows on google sheets for data entry without having to automate each row?

**Comment by dougbell-ms** [comment]
@michael7-tech, you should be able to use the Get Rows command followed by an Apply to each control.  That'll allow you to take an action for every row in the table.

**Comment by Dean-Haas** [comment]
Glad you all found the solution. I'm going to close this issue out. Thanks for your input!
