### ISSUE TITLE
Someone should expand the create CSV/HTML table sections

### ISSUE THREAD

**Issue by ChrisGarty** [MicrosoftDocs/power-automate-docs#220]
Have a look at http://johnliu.net/blog/2018/4/how-to-use-select-to-simplify-create-html-table-and-create-csv-in-microsoftflow and evaluate the need to expand the create CSV/HTML table sections. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bddf7e-aad7-5b99-0b73-a893d25615f5
* Version Independent ID: f2f0c4d6-b613-d269-4756-bcd7548f76ec
* Content: [Understand data operations - Power Automate](https://docs.microsoft.com/en-us/power-automate/data-operations#use-the-create-csv-table-action)
* Content Source: [articles/data-operations.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/data-operations.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@ChrisGarty Thanks for the heads up. We'll overhaul this doc soon.
