### ISSUE TITLE
Desktop UI Flow - Java Applications

### ISSUE THREAD

**Issue by kgopi1** [MicrosoftDocs/power-automate-docs#221]
As Java Applications are  unsupported  preview UI Flow for Desktops in  Power Automate , does this applies only to preview state or even in GA also ?

As we currently looking  PowerAutomate with Desktop UI as RPA solution ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d024a2c8-e958-e643-93f5-95cf8637fb2c
* Version Independent ID: 9f9028ac-88ef-bf06-0dd8-77729edd84e8
* Content: [Learn to create desktop UI flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/create-desktop#feedback)
* Content Source: [articles/ui-flows/create-desktop.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/create-desktop.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by KumarVivek** [comment]
“Thanks for your feedback. For product-related feedback/questions, visit https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas. 

Closing this issue.
