### ISSUE TITLE
link to internal guide is broken

### ISSUE THREAD

**Issue by tonglingchen** [MicrosoftDocs/power-automate-docs#223]
On [https://github.com/MicrosoftDocs/power-automate-docs/blob/live/README.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/README.md), the "please visit the internal version of this guide" link points to https://aka.ms/docsguidescontribute which will redirect you to Microsoft.com home page.

**Comment by KumarVivek** [comment]
@tonglingchen We have removed the link to the internal guide; changes will be published soon.

Closing the issue.
