### ISSUE TITLE
Leaving organization

### ISSUE THREAD

**Issue by BlackMercy** [MicrosoftDocs/power-automate-docs#224]
If I create a flow and add my colleagues as co-owners, then one day I leave my organization and my Office 365 account is terminated. Will the flow still work and be accessible by the co-owners?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-team-flows)
* Content Source: [articles/create-team-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by KumarVivek** [comment]
@BlackMercy This a is a great question. Have you tried asking this question in the Power Automate community: https://powerusers.microsoft.com/t5/Get-Help-with-Power-Automate/ct-p/FL_GeneralDiscussions

Many Power Automate experts are part of the community, and will surely be able to answer your question.

**Comment by MSFTMan** [comment]
@BlackMercy 
Hi, we recommend that co-owners export and save the flow as one of the persons who remain in the organization. The new owner may also need to update credentials that are used for connections and also update his/her license, if a different license is needed for the connections that are used in the flow.
