### ISSUE TITLE
Creating numbered lists

### ISSUE THREAD

**Issue by gable44** [MicrosoftDocs/power-automate-docs#226]
Numbered list example: 
0. First item.
0. Second item.
0. Third item.

and in the nested list example:

1. First item.
   - Item 1
   - Item 2
   - Item 3
1. Second item.
   - Nested item 1
   - Nested item 2
   - Nested item 3

This shouldn't be 0 too?

And also is I would like to nest bullet list how can I do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support#feedback)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by MSFTMan** [comment]
@gable44 Thanks for reporting this issue. The doc was updated and no longer shows the example you gave. Additionally, here is how you do nested bullets:
1. First item.
   - Item 1
   - Item 2
   - Item 3
2. Second item.
   - Nested item 1
   - Nested item 2
      - dffdfdf
      - dfdfd
   - Nested item 3

**Comment by gable44** [comment]
@MSFTMan you misunderstood my previous question (And also is I would like to nest bullet list how can I do that?)

To clarify please tell me how to do nested lists with only bullet type.
• Item 1
   ⚬ Item 1.1
   ⚬ Item 1.2
• Item 2
