### ISSUE TITLE
How to see aware flow in flow maker portal?

### ISSUE THREAD

**Issue by Prashant4787** [MicrosoftDocs/power-automate-docs#229]
When aware flow is remove from solution , it is not visible in flow makers portal to edit or delete. How to check that this flow exist in the systema and can be editable and deletable. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6c87a4-f50f-3d70-0db5-067b4dcaf7ea
* Version Independent ID: 636efbd0-e145-46bd-35b1-070847432c07
* Content: [Learn how to remove or delete solution-aware flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/remove-solution-aware-flow?source=docs)
* Content Source: [articles/remove-solution-aware-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/remove-solution-aware-flow.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@Prashant4787 Thanks for reporting your questions. Go my My flows, select the flow you want to work with, then select edit.
