### ISSUE TITLE
Incorrect reference to license requirement

### ISSUE THREAD

**Issue by AnupmaSharma** [MicrosoftDocs/power-automate-docs#230]
Can we please remove the requirement around - A Power Automate P2 license. This is not needed for DLP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b153bd2d-0c9a-2982-5cee-c271bd814388
* Version Independent ID: c58d38f5-5a7b-dabb-c75b-c38108139bbe
* Content: [Introduction to data loss prevention (DLP) policies. - Power Automate](https://docs.microsoft.com/en-us/power-automate/prevent-data-loss)
* Content Source: [articles/prevent-data-loss.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/prevent-data-loss.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@AnupmaSharma Thanks for reportign this issue. We've fixed it. The updated document will be live shortly.
