### ISSUE TITLE
Flow 30-day Limination - Approval Items is not deleted

### ISSUE THREAD

**Issue by Faker110** [MicrosoftDocs/power-automate-docs#231]
I would like to seek your advice regarding the Flow 30-day limitation. As per the document stated in this link https://docs.microsoft.com/en-us/power-automate/limits-and-config, approval items will be deleted after 30days. However, we have a situation where the approval items exceeded 30 days and can still be accessed. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-gb/power-automate/limits-and-config#feedback)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@Faker110 Thanks for using Power Automate. This limit has been removed. We will update the doc: https://docs.microsoft.com/en-us/business-applications-release-notes/april19/microsoft-flow/increased-run-duration
