### ISSUE TITLE
Get BadGateway Error

### ISSUE THREAD

**Issue by michael-kubala** [MicrosoftDocs/power-automate-docs#232]
I keep getting BadGateway on the step to create the adaptive card. I've copied and pasted the body from this page. I'm the owner of the Team and connecting under my account. Not sure where to go from here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da15c461-b88d-7497-cd59-efcd785d5994
* Version Independent ID: 00dd913a-44c7-b407-02c5-528c3b0e7643
* Content: [Learn to create flows that post adaptive cards to Microsoft Teams - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-adaptive-cards-teams#feedback)
* Content Source: [articles/create-adaptive-cards-teams.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/create-adaptive-cards-teams.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@michael-kubala Thanks for using Power Automate. Kindly use the support options for this issue: https://flow.microsoft.com/support/
