### ISSUE TITLE
Managed solutions

### ISSUE THREAD

**Issue by jordaniza** [MicrosoftDocs/power-automate-docs#233]
Please clarify if managed solutions are supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0535b1a-e189-75c9-d5f0-c200a65150ec
* Version Independent ID: 7120c4d7-3223-6c65-f70f-03ca718775f1
* Content: [Learn how to export solution-aware flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/export-flow-solution)
* Content Source: [articles/export-flow-solution.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/export-flow-solution.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@jordaniza Thanks for your question. Yes, managed solutions are supported if you mark the flow as customizable.
