### ISSUE TITLE
Number of flows that can be owned by a user

### ISSUE THREAD

**Issue by Laskewitz** [MicrosoftDocs/power-automate-docs#234]
I would love to see the number of flows that can be owned by a user here as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config#feedback)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@Laskewitz Thanks for reporting this issue. We'll update the docs and publish shortly.
