### ISSUE TITLE
Incorrect limit at the bottom of the page.

### ISSUE THREAD

**Issue by Laskewitz** [MicrosoftDocs/power-automate-docs#235]
"You can install a gateway only in the default environment."

This statement is not correct. It's possible to install gateways on other environments as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1947fd4e-170f-6392-e309-5fd05082ffb8
* Version Independent ID: 79ccd9e1-0998-bc4e-004c-ffbe57291196
* Content: [Billing and metering questions - Power Automate](https://docs.microsoft.com/en-us/power-automate/billing-questions#other-limits-and-caveats)
* Content Source: [articles/billing-questions.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/billing-questions.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
Thanks for reporting this issue @Laskewitz,  This is is fixed.
