### ISSUE TITLE
Create CSV Table doesn't have option "No" Automatic and Custom only

### ISSUE THREAD

**Issue by JerryMWeeks** [MicrosoftDocs/power-automate-docs#237]
Might be an instance difference?
We have Enterprise access.
perhaps needs updating?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bddf7e-aad7-5b99-0b73-a893d25615f5
* Version Independent ID: f2f0c4d6-b613-d269-4756-bcd7548f76ec
* Content: [Understand data operations - Power Automate](https://docs.microsoft.com/en-us/power-automate/data-operations#feedback)
* Content Source: [articles/data-operations.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/data-operations.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@JerryMWeeks Thanks for the heads up. We'll overhaul this doc soon.
