### ISSUE TITLE
Common data service (Current) enviornment trigger was not documented

### ISSUE THREAD

**Issue by pavansarma93** [MicrosoftDocs/power-automate-docs#240]
The trigger which can be created only using solutions is not mentioned.

https://powerusers.microsoft.com/t5/Connecting-To-Data/Missing-trigger-for-Common-Data-Service-connector/m-p/317815#M5876 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c3bde-6083-7a7c-3469-48137843198f
* Version Independent ID: d1466842-8d49-67ad-1ca1-326511b2560e
* Content: [Create an automated flow with Common Data Service - Power Automate](https://docs.microsoft.com/en-us/power-automate/connection-cds?utm_source=dynamics_crm&utm_content=wf_editor)
* Content Source: [articles/connection-cds.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/connection-cds.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@pavansarma93 If you search for "When a record is created, updated or deleted"  you will find the trigger.
