### ISSUE TITLE
Outputs Selenium - Flow

### ISSUE THREAD

**Issue by declankelly170** [MicrosoftDocs/power-automate-docs#241]
The input parameters seem to work ok, but how do I get an output parameter back to my flow?
I've tried "execute script" with "return ...", but the flow fails with message "Action '' failed"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9ffaec1-7e0d-fedb-a300-7492e91f26a0
* Version Independent ID: d900cdf8-4e0e-2211-c694-271de641e7b3
* Content: [Use inputs and outputs in Web UI flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/inputs-outputs-web#feedback)
* Content Source: [articles/ui-flows/inputs-outputs-web.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/inputs-outputs-web.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@declankelly170 Thanks for reporting this issue. We will investigate and get back to you.

**Comment by charlesanands** [comment]
Any further updates? I also have the same question on how to use the output from the UI flow back into the data entity?

**Comment by rakrish84** [comment]
Any output you created while making a UI flow recording will be available as Dynamic content in the API flow. For eg: if you have used selenium actions to extract value from a webpage to create an output variable, you will be able to access those values in the subsequent flow steps within 'Dynamic Content' under the 'Run a UI flow for Web' action

**Comment by Dean-Haas** [comment]
Thanks Rakesh. I'll close this out.
