### ISSUE TITLE
Doesn't cover Approve/Reject - First to respond

### ISSUE THREAD

**Issue by cv042020** [MicrosoftDocs/power-automate-docs#243]
This page is good for the Everyone Must Approve, but you have no instructions on the Approve/Reject - First to respond option.  That option is not working in a straightforward manner and needs to have a page like this specifically for that option.  Users are having to resort to non-Microsoft Q&A sites to figure out how to make that work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78d8ec21-2a2d-e06d-9379-b30b3595cfe7
* Version Independent ID: 978afb49-2fa2-9e95-76e4-446e689f19a0
* Content: [Create an approval flow that requires everyone to approve - Power Automate](https://docs.microsoft.com/en-us/power-automate/all-assigned-must-approve#feedback)
* Content Source: [articles/all-assigned-must-approve.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/all-assigned-must-approve.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
@cv042020 Thanks for submitting this feedback. We will evaluate and consider this for a future update to docs. @hamenon-ms Can you please have a look?

**Comment by Dean-Haas** [comment]
Hi @cv042020. After looking into your feedback, this particular topic is intended to be specific to the 'everyone must approve' scenario, but there are other approvals documented that use 'first to approve'. for example: [Single approvals](https://docs.microsoft.com/power-automate/modern-approvals)

Thanks.
