### ISSUE TITLE
To fetch the responses when flow is running

### ISSUE THREAD

**Issue by lovyjain** [MicrosoftDocs/power-automate-docs#245]
I wanted to fetch the response of approvers when the flow is running and all the responses are yet to complete. 
So that i can track the people who have not submitted their responses.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78d8ec21-2a2d-e06d-9379-b30b3595cfe7
* Version Independent ID: 978afb49-2fa2-9e95-76e4-446e689f19a0
* Content: [Create an approval flow that requires everyone to approve - Power Automate](https://docs.microsoft.com/en-us/power-automate/all-assigned-must-approve#feedback)
* Content Source: [articles/all-assigned-must-approve.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/all-assigned-must-approve.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by lovyjain** [comment]
I am using the create an approval + wait for approval instead of the start and wait for approval as i wanted an approval link also to be sent

**Comment by MSFTMan** [comment]
@lovyjain There are multiple ways you can do this. One way is to send a notification when each person approves. You can also update an Excel spreadsheet when each person approves, and then run a flow on the spreadsheet to determine who has approved and who has not.
