### ISSUE TITLE
How we can access assigned flow to me on SharePoint online ?

### ISSUE THREAD

**Issue by spo365** [MicrosoftDocs/power-automate-docs#246]
How we can access assigned flow to me on SharePoint online ?

![image](https://user-images.githubusercontent.com/5062256/79706616-265a2480-82fd-11ea-816b-7e8415edfc3f.png)

**Comment by MSFTMan** [comment]
@spo365 Thanks for reaching out. Can you clarify what you mean? There is no way to access approvals in SharePoint Online. You can access approvals in email and in the Approval center only.
