### ISSUE TITLE
Power Automate checker vs Flow Checker

### ISSUE THREAD

**Issue by DennisGaida** [MicrosoftDocs/power-automate-docs#247]
I am aware of the Power Automate name change. We do still create flows within Power Automate though and I would want to check a flow, not "a Power Automate", correct?

The error checker is still called "Flow Checker" in all UI as well as in the screenshots in this documentation. The article was renamed to "Power Automate checker". Right now users would be confused in finding this article as "Power Automate checker" but this not being represented anywhere in the UI. Please rename article back to Flow checker, change all UI or keep the note that was removed with ticket #211. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d12f42-d17f-647e-b25c-ef6e56167983
* Version Independent ID: de5ec638-fffb-bd32-ee7c-66928026aa1c
* Content: [Find and fix errors with the Power Automate checker - Power Automate](https://docs.microsoft.com/en-us/power-automate/error-checker?source=docs#feedback)
* Content Source: [articles/error-checker.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/error-checker.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by KumarVivek** [comment]
@DennisGaida Your feedback is valid. We have renamed this back to Flow Checker to be consistent with the feature/UI. The changes will be live for public in docs after 6:30 AM Pacific Time on April 28.

Closing the issue. Thanks for your feedback.
