### ISSUE TITLE
Number of Send an Email blocks per user in a single flow 

### ISSUE THREAD

**Issue by mohitnpm** [MicrosoftDocs/power-automate-docs#248]
"You have exceeded the Number of Send an Email " Error  is coming. We have added around 100 or email in a single flow for our possibility but still wanted to know how many can we add for a single flow.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@mohitnpm Connectors can have their own limits, which may be the cause of this issue. Check out the details for the email connector you are using here: https://docs.microsoft.com/connectors/connector-reference/.
