### ISSUE TITLE
Please indicate that individual connectors may have their own limitations

### ISSUE THREAD

**Issue by RichWK** [MicrosoftDocs/power-automate-docs#249]
Spent far too long today trying to work out why the Common Data Service and Dynamics 365 connectors were only returning 512 results when the same filter in the Web API was returning more. Even a single line at the top of this document indicating that connectors may have their own limitations would be helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config#feedback)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@RichWK Thanks for reporting this issue. We've fixed it.

**Comment by RichWK** [comment]
Thanks! Appreciate the change. 🙂
