### ISSUE TITLE
Run frequency not clear

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/power-automate-docs#250]
it says free tier runs every 15 minutes.
I see https://github.com/MicrosoftDocs/power-automate-docs/issues/85 references this question a bit but all the answer given is depends. I have an application where I have a need to run immediately. What plans works for this? Consider a chart perhaps for showcasing these differences.

**Comment by MSFTMan** [comment]
@JohnGGeo Thanks for using Power Automate. Consider using any of the plans described here: https://flow.microsoft.com/pricing/. For your flow to run immediately, use a trigger that runs when the specific condition that your flow needs to run is met.
