### ISSUE TITLE
Add Step is not working in 'Check if Due Date has value' condition selection. Why I could't able to see enable option 'Add Step' after added 'Check if Due Date has value'.

### ISSUE THREAD

**Issue by Prashanth396** [MicrosoftDocs/power-automate-docs#251]
Details: 
Exercise - Creating a custom workflow extension (WorkflowActivities)
using below link: 
(https://docs.microsoft.com/en-us/learn/modules/plug-ins-extend-power-platform/6-exercise-2/)
in Exercise 2 --> Task 3 --> Step 7.
We had tried to add created custom workflow activity to convert datetime format. But we are not getting enable option to add 'Add Step' at Step7.
your help is required to us ASAP.
Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a013bf3e-675d-6188-6115-bef65547c566
* Version Independent ID: a6c6e501-806e-0376-94aa-56b004c5c3c9
* Content: [Configure workflow stages and steps in Power Apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/configure-workflow-steps#feedback)
* Content Source: [articles/configure-workflow-steps.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/configure-workflow-steps.md)
* Service: **flow**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by MSFTMan** [comment]
@Mattp123

**Comment by KumarVivek** [comment]
@Prashanth396 Can you please provide feedback on the relevant MS Learn topic (https://docs.microsoft.com/en-us/learn/modules/plug-ins-extend-power-platform/6-exercise-2/).

Closing the issue.

**Comment by Prashanth396** [comment]
> @Prashanth396 Can you please provide feedback on the relevant MS Learn topic (https://docs.microsoft.com/en-us/learn/modules/plug-ins-extend-power-platform/6-exercise-2/).
> 
> Closing the issue.

@KumarVivek The explained way is good idea, but when learners gone through it those steps are not working. I did not get any solution for my question I was asked. Can you please understand me what should be done at that step7 from my question?

Thanks.
