### ISSUE TITLE
This page is redundant and doesnt have latest information on DLP

### ISSUE THREAD

**Issue by AnupmaSharma** [MicrosoftDocs/power-automate-docs#252]
Need to point to the Power Platform admin DLP page ideally instead of a separate topic.
https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention
https://docs.microsoft.com/en-us/power-platform/admin/create-dlp-policy
https://docs.microsoft.com/en-us/power-platform/admin/prevent-data-loss

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b153bd2d-0c9a-2982-5cee-c271bd814388
* Version Independent ID: c58d38f5-5a7b-dabb-c75b-c38108139bbe
* Content: [Introduction to data loss prevention (DLP) policies. - Power Automate](https://docs.microsoft.com/en-us/power-automate/prevent-data-loss#feedback)
* Content Source: [articles/prevent-data-loss.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/prevent-data-loss.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by KumarVivek** [comment]
@AnupmaSharma Addressing this issue internally as communicated on email. Closing the issue here.
