### ISSUE TITLE
This page is redundant and doesn't have latest information

### ISSUE THREAD

**Issue by AnupmaSharma** [MicrosoftDocs/power-automate-docs#253]
Need to point to the Power Platform admin DLP page ideally instead of a separate topic.
https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention
https://docs.microsoft.com/en-us/power-platform/admin/create-dlp-policy
https://docs.microsoft.com/en-us/power-platform/admin/prevent-data-loss

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb93f0ce-44a2-770c-c499-9c08d8c7ad2f
* Version Independent ID: 987fd295-7fb2-d559-396b-b3a6099825fc
* Content: [Data groups for Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/introduction-to-data-groups)
* Content Source: [articles/introduction-to-data-groups.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/introduction-to-data-groups.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by KumarVivek** [comment]
@AnupmaSharma Addressing this issue internally as communicated on email. Closing the issue here.
