### ISSUE TITLE
Page needs to be updated

### ISSUE THREAD

**Issue by jlandgrave** [MicrosoftDocs/power-automate-docs#254]
This feature no longer requires a premium license so the screen shots should be updated to reflect this!
![image](https://user-images.githubusercontent.com/4333469/80394509-f58b6980-887f-11ea-9196-1acfd7a2db68.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b2c12c-7262-de3d-eb95-410fb6a33df6
* Version Independent ID: b316d8da-19ac-6b00-7675-2b9d03d33377
* Content: [Create approval flows with custom responses - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-approval-response-options)
* Content Source: [articles/create-approval-response-options.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/create-approval-response-options.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@jlandgrave Thanks for pointing this out. We're fixing this issue.

**Comment by MSFTMan** [comment]
@jlandgrave This issue is fixed. You'll see the update publicly within 24 hours. Thanks!
