### ISSUE TITLE
How do you select environment?

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/power-automate-docs#255]
When in https://us.flow.microsoft.com/en-us/ you can seemingly select an environment from the top right corner, but nothing indicates which is selected or that a change has been made.  These instructions best explain how to switch between environments when building flows.

**Comment by dialedin2014** [comment]
My problem may be due to a longer environment name not being entirely displayed.  Also, the checkmark doesn't always appear.  It appears this is a bug and would not need to be documented if fixed.

![image](https://user-images.githubusercontent.com/7587722/80722079-35d72b80-8abc-11ea-8efb-ca8a72fdda78.png)

**Comment by MSFTMan** [comment]
@dialedin2014 Thanks for reporting this issue. I'll pass it on to the dev team.
