### ISSUE TITLE
Should update the gateway information 

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/power-automate-docs#256]
Kindly update the **Create flows in the right environment** content as:

Gateway installation is now enabled for also non-default environments.

https://docs.microsoft.com/en-us/power-platform-release-plan/2019wave2/power-automate/support-gateways-all-environments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ddd5e3-db39-4f50-4be4-71ae16dd19d2
* Version Independent ID: 61cafb41-19d2-24cc-a17f-85a36b22b4fa
* Content: [Learn about Power Automate environments - Power Automate](https://docs.microsoft.com/en-us/power-automate/environments-overview-maker)
* Content Source: [articles/environments-overview-maker.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/environments-overview-maker.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by MSFTMan** [comment]
@DavidPaf  Thanks for reporting this issue. This is fixed, and will be available later today.
