### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jordaniza** [MicrosoftDocs/power-automate-docs#257]
https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/create-solution#add-solution-components

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7632694a-e3b9-7f71-5e19-765d4d203155
* Version Independent ID: c961c989-bc01-5088-6993-b5ee9485d4f4
* Content: [Business process flows overview - Power Automate](https://docs.microsoft.com/en-us/power-automate/business-process-flows-overview)
* Content Source: [articles/business-process-flows-overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/business-process-flows-overview.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DEONHE**

**Comment by MSFTMan** [comment]
@jordaniza Thanks for reporting this issue. We'll fix this issue and update the docs.
