### ISSUE TITLE
Creating new environments info is incorrect. 

### ISSUE THREAD

**Issue by AaronAdmin** [MicrosoftDocs/power-automate-docs#259]
The [Learn about Power Automate environments](https://docs.microsoft.com/en-us/power-automate/environments-overview-maker) article incorrectly states "To create environments, you must be a Power Automate administrator". This is not accurate. Any appropriately licensed user can create a production environment in the Power Platform Admin Center unless the default "Who can create production environments" setting has been changed from "Everyone" to "Only specific admins". There are settings for control of trial environment creation as well.

**Comment by MSFTMan** [comment]
@AaronAdmin Thanks for letting us know about this issue. We are updating the document and the updates will be live later today.
