### ISSUE TITLE
Maximum number of flows that one user can create

### ISSUE THREAD

**Issue by albegut** [MicrosoftDocs/power-automate-docs#260]
The documentation indicates that a user can only own 50 flows. The following link indicates that a user can own up to 250. What is the correct limit? If the limit is reached, the documentation indicates that more can be requested, how do you make that request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee8a6fc-8a07-bcf7-412f-21344c46f4c6
* Version Independent ID: 3289c7dd-3a4a-0d96-0e4c-e08689ab2c2d
* Content: [Frequently asked questions - Power Automate](https://docs.microsoft.com/en-us/power-automate/frequently-asked-questions#feedback)
* Content Source: [articles/frequently-asked-questions.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/frequently-asked-questions.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@albegut Thanks for reporting this issue. With the new licensing plans, you can have an unlimited number of flows. The updated docs will be available soon. See https://flow.microsoft.com/pricing for more details.
