### ISSUE TITLE
non-printable character in the example JSON

### ISSUE THREAD

**Issue by grayson-hilliard** [MicrosoftDocs/power-automate-docs#261]
there's a "box" character in the example JSON:

```
 "weight": "Bolder",      "id": "Title",
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 506ffdd7-7ba6-f59b-d35c-9bbd2dc3b49a
* Version Independent ID: 35de2f4f-8d89-af2f-8d65-8e9911c89493
* Content: [Candidate feedback sample - Power Automate](https://docs.microsoft.com/en-us/power-automate/candidate-feedback-sample#feedback)
* Content Source: [articles/candidate-feedback-sample.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/candidate-feedback-sample.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@grayson-hilliard  Thanks for reporting this issue. We've fixed it. You'll see the update soon.
