### ISSUE TITLE
Power Automate - Approval process

### ISSUE THREAD

**Issue by rajesharra1** [MicrosoftDocs/power-automate-docs#266]
Hi ,

I am admin for one of the SharePoint site in my Org. I just created Approval process flow. Its working fine.

I want that flow to be added to all the document library ,by changing the approver according to the library .  

Currently that flow is in my account, I want to implement the same for all the users who access the site.

I need your guidance to implement this.

thanks!
Raj

**Comment by rajesharra1** [comment]
I got the solution to publish every one in my Org, using the share option . but only concern with this that any one can edit as everyone or the owners.

Is there any possibility that I can share with read only mode?

**Comment by Dean-Haas** [comment]
Thanks for your feedback. For help with questions like this, ask your question on our forums: https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity
