### ISSUE TITLE
Why would you want this to check only the last 10 emails?

### ISSUE THREAD

**Issue by Orcuthe** [MicrosoftDocs/power-automate-docs#267]
This offers no certainty that the process is picking up all the emails that have come in - it's obviously because Microsoft don't want to broadcast that this flow is restricted to a max number of 25 operations.

Which is ludicrous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39d79925-8b72-d4b0-e3fb-1b9164ecaaf3
* Version Independent ID: 06c8759f-1adf-470f-bdba-1f3af6f0a523
* Content: [Use the apply to each action to loop through an array of items. - Power Automate](https://docs.microsoft.com/en-us/power-automate/apply-to-each#feedback)
* Content Source: [articles/apply-to-each.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/apply-to-each.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@Orcuthe Thanks for your feedback. There is no special reason that this flow uses the last 10 emails. The purpose of this article is to demonstrate how to use apply to each, and how it can be applied to email. All limits are outlined in the limits and config document: https://docs.microsoft.com/power-automate/limits-and-config. Thanks!
