### ISSUE TITLE
Should have more information about languages on faq

### ISSUE THREAD

**Issue by haavfr17** [MicrosoftDocs/power-automate-docs#270]
What regions and languages does Power Automate support?
There seems to be no easy way to find the list of languages that Power Automate supports. (I cannot find any list, only know there are 42 languages supported)
Followed hyperlink in the answer but cannot find anything about languages only information about the regions supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee8a6fc-8a07-bcf7-412f-21344c46f4c6
* Version Independent ID: 3289c7dd-3a4a-0d96-0e4c-e08689ab2c2d
* Content: [Frequently asked questions - Power Automate](https://docs.microsoft.com/en-us/power-automate/frequently-asked-questions#feedback)
* Content Source: [articles/frequently-asked-questions.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/frequently-asked-questions.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by Dean-Haas** [comment]
@haavfr17 Thanks for your feedback. I've submitted an update to this topic, which should be published shortly.
