### ISSUE TITLE
Is there a newer version of this documentation?

### ISSUE THREAD

**Issue by citykidz** [MicrosoftDocs/power-automate-docs#273]
I'm hoping to use Microsoft Forms as the front end and have approvers interact with the workflow from within Microsoft Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f86061a-70b6-f9d0-4450-158876f2cd4d
* Version Independent ID: ee2fde39-1f02-6a2b-ca91-5caba0d1694a
* Content: [Create a modern approval workflow with multiple approvers - Power Automate](https://docs.microsoft.com/en-us/power-automate/sequential-modern-approvals#feedback)
* Content Source: [articles/sequential-modern-approvals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/sequential-modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
This doc has been updated.

**Comment by Dean-Haas** [comment]
Updating this topic

**Comment by Dean-Haas** [comment]
Topic updated
