### ISSUE TITLE
Not able to import the solution in same tenant.

### ISSUE THREAD

**Issue by lovyjain** [MicrosoftDocs/power-automate-docs#277]
i wanted to make a copy of solution to be able to use for my different site collection but could not figure out a way to do so. I just exported and iimported the solution in same tenant but it just update the version even if i change the name of solution.

I have also tried something like clone a solution/Patch but i think they are also just updating the version of it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0535b1a-e189-75c9-d5f0-c200a65150ec
* Version Independent ID: 7120c4d7-3223-6c65-f70f-03ca718775f1
* Content: [Learn how to export solution-aware flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/export-flow-solution)
* Content Source: [articles/export-flow-solution.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/export-flow-solution.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Hi @lovyjain. Thanks for submitting docs feedback. I don't see a documentation issue here. Were you able to resolve your issue? Did you try posting on the Power Automate Community forums?  https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity
