### ISSUE TITLE
Missing support or not for outlook mobile

### ISSUE THREAD

**Issue by tcardos0** [MicrosoftDocs/power-automate-docs#278]
Hi team, please add on session client support related the outlook mobile. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support?source=docs)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by Dean-Haas** [comment]
Thanks for your feedback. Please submit your feature request here:  https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas

**Comment by Dean-Haas** [comment]
For Outlook Mobile, the above parameters can vary depending on the Outlook client app and version that you are using. I've added this note to the doc
