### ISSUE TITLE
Common Data Service (Current Environment) – When a record is selected

### ISSUE THREAD

**Issue by ConsoleMAD** [MicrosoftDocs/power-automate-docs#279]
The documentation has this text "From the list of triggers, select Common Data Service (Current Environment) – When a record is selected" but I thought this trigger was only available for the older CDS connector? Is it just a mistake or is the 'When a record is selected' trigger coming to the Current Environment connector?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c08ddd-c290-34f4-5e82-ae9369012efd
* Version Independent ID: 98652aac-b377-c9fe-bb32-47d873f7237a
* Content: [Replace classic Common Data Service workflows with Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/replace-workflows-with-flows)
* Content Source: [articles/replace-workflows-with-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/replace-workflows-with-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by coolsama** [comment]
"From the list of triggers, select Common Data Service (Current Environment) – **When a record is selected** and select Quotes as the entity. This trigger allows a flow to be run on-demand on a record or list of records."
Can't find this trigger! please shed some light on this!

**Comment by Sina1984** [comment]
It would be great to have this trigger on CDS (current environment) for running flows on selected records on-demand inside Dynamics 365. Still, it is not available. It is only available from old CDS!

**Comment by Dean-Haas** [comment]
Hi @prsi-msft . Can you please evaluate this and let me know if a docs update is needed? thanks!

**Comment by prsi-msft** [comment]
This trigger is not available for current environment connector, but instead available for the Common Data Service connector. So we should just drop (current environment).

Thanks,
Praveen

**Comment by Dean-Haas** [comment]
@ConsoleMAD  Thanks for submitting this. We've updated the topic -  should be published live shortly.
