### ISSUE TITLE
Specify region Europe

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/power-automate-docs#280]
Hello,

the region 'Europe' is too vague to be helpful for documentations and legal documents. Please provide a list of countries being used if the region is 'Europe'. Is it the same as the following list?

European Union | Austria, Finland, France, Ireland, Netherlands
-- | --

(https://docs.microsoft.com/en-us/office365/enterprise/o365-data-locations#countryregion-specific-data-center-city-locations)

Furthermore to clarify: Do you mean Europe or European Union?

Thank you.

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2ea76cf-af8d-12a6-1d73-23cee3a0667d
* Version Independent ID: 0fdd1b60-d353-cf90-40d1-2610c11e314a
* Content: [Regions overview for Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/regions-overview)
* Content Source: [articles/regions-overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/regions-overview.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
We've updated this topic, simplifying and linking to the broader Power Platform documentation which this largely duplicated. Added links to Azure geography  info for more detailed info about datacenter locations.
