### ISSUE TITLE
What about access control

### ISSUE THREAD

**Issue by GitOffMyGrass** [MicrosoftDocs/power-automate-docs#282]
This example is useful and I was able to follow it to get a working flow.   However, it is missing information about securing the list.  I am pretty new to SharePoint, but from what I have read  someone would have to have at least "Contribute" access to submit an item to a list.  This means that after the submitter saves the item and the approval flow ends, that same user could then access the list again and edit their submission to change the approved field to an arbitrary value.  There is nothing in the tutorial about how to prevent this.  This tutorial should at least mention this is a problem if there is no solution.

**Comment by Dean-Haas** [comment]
Hi @GitOffMyGrass. Thanks for submitting your comments. This issue doesn't reference a specific docs page that I can see. Can you please point me to the doc that this feedback is in reference to?  Thanks!

**Comment by GitOffMyGrass** [comment]
It was here:  https://docs.microsoft.com/en-us/power-automate/modern-approvals#:~:text=With%20Power%20Automate%2C%20you%20can,approval%20action%20to%20any%20flow.

**Comment by Dean-Haas** [comment]
@hamenon-ms Please have a look at this. Can the requestor simply approve his own request or make other arbitrary changes in the given example? Should SharePoint security be in-scope for this topic? Perhaps there's a sharepoint doc we can link to?

**Comment by MSFTMan** [comment]
@GitOffMyGrass Thanks for using Power Automate. SharePoint security is a complex topic, which is outside the scope of this article. However, we've added a link in the doc to get folks started on best practices for managing SharePoint. This update will  be public soon. Thanks!
