### ISSUE TITLE
Page needs update

### ISSUE THREAD

**Issue by ram008** [MicrosoftDocs/power-automate-docs#283]
Page needs update - condition UI does  not exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af5f3e7-4734-5813-0e3d-dada381fec0b
* Version Independent ID: 393c8bdd-da49-d6cd-f97a-94283f55c0a2
* Content: [Add a condition to a flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/add-condition)
* Content Source: [articles/add-condition.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/add-condition.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@ram008 Thanks for reporting this issue. I've updated the document.
