### ISSUE TITLE
Power Automate Flow Approval Walk-Throughs Need Refreshed

### ISSUE THREAD

**Issue by ToddBleeker** [MicrosoftDocs/power-automate-docs#285]
These Power Automate Flow approval examples are very dated. Most of the user interface elements have changed making the walk-throughs very difficult to follow:
https://docs.microsoft.com/en-us/power-automate/modern-approvals

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f51e26d-e8cd-2152-45a2-bd23d13fb3b2
* Version Independent ID: 30768baf-8dd7-d64c-aec2-f500fbbe1e78
* Content: [Easily Automate approval workflows. - Power Automate](https://docs.microsoft.com/en-us/power-automate/modern-approvals)
* Content Source: [articles/modern-approvals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Working on these

**Comment by Dean-Haas** [comment]
Modern approvals updated
