### ISSUE TITLE
Wrong information on page

### ISSUE THREAD

**Issue by EricKlippas** [MicrosoftDocs/power-automate-docs#287]
taken to this page because when I tried to activate the flow I created, it gave me the error message below, Clicked the learn more and was taken to a page which is only about DLP and does not mention what the billing restrictions are. Probably because I'm using a free account, but it would be nice to know that!


Your flow was saved, but could not be enabled because of billing restrictions. Learn more

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b153bd2d-0c9a-2982-5cee-c271bd814388
* Version Independent ID: c58d38f5-5a7b-dabb-c75b-c38108139bbe
* Content: [Introduction to data loss prevention (DLP) policies. - Power Automate](https://docs.microsoft.com/en-us/power-automate/prevent-data-loss)
* Content Source: [articles/prevent-data-loss.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/prevent-data-loss.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@EricKlippas Thanks for reporting this issue. I've forwarded to the product team to update where this Learn more link points.
