### ISSUE TITLE
Topic is very stale

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/power-automate-docs#288]
This topic is very old and incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f7b3337-c547-4960-fa13-ca16a559b083
* Version Independent ID: 9b02414f-872e-14da-71c6-bd68fbb0e23e
* Content: [Common Data Service - Power Automate](https://docs.microsoft.com/en-us/power-automate/common-data-model-intro)
* Content Source: [articles/common-data-model-intro.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/common-data-model-intro.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by MSFTMan** [comment]
@JimDaly Thanks for reporting this issue. The doc has been updated.
