### ISSUE TITLE
Seeing a login from different set of IPs

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/power-automate-docs#289]
40.83.187.134 and 40.83.189.163  are ips I'm seeing that are trying to login to a salesforce instance. I am not seeing these IPs listed in the documentation above. Are these IPs supposed to be logging in?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config#connectors)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by JohnGGeo** [comment]
Adding context, I'm seeing this login from PowerAutomate on a salesforce connector.

**Comment by Dean-Haas** [comment]
@PriyaKodukula can you please verify connector IP list?

**Comment by IvanBil** [comment]
Similar problem. 104.41.132.180 is not listed.

**Comment by JohnGGeo** [comment]
@hamenon-ms  any updates on this? I'm still seeing a couple weird IPs occasionally try and access my Salesforce enviroment.

**Comment by hamenon-ms** [comment]
Not sure I can help on this one @Dean-Haas @MSFTMan . Would be good to include someone from the connectors team to verify the IP ranges

**Comment by MSFTMan** [comment]
@IvanBil 104.41.132.18 is not listed in the docs. Thanks!

**Comment by MSFTMan** [comment]
@JohnGGeo Can you let us know what region are you using when you get requests from: 40.83.187.134 and 40.83.189.163?

**Comment by JohnGGeo** [comment]
South Central US

**Comment by MSFTMan** [comment]
@natalie-pienkowska Kindly look at this issue about un-documented IPs connecting to the Salesforce connector.

**Comment by MSFTMan** [comment]
@JohnGGeo We've looked into these IP addresses. These IP addresses belong to Azure services but not to connectors. So, the requests are not coming from the connector you set up. Kindly check your network configuration to see why Azure may be calling into your network for some other reasons. We're closing this issue.
