### ISSUE TITLE
Include example in documentation

### ISSUE THREAD

**Issue by thomassandsor** [MicrosoftDocs/power-automate-docs#292]
https://msolenacrm.blog/2020/05/20/cds-current-environment-connector-the-following-filtering-attributes-are-not-valid/

This blog saved med a lot of time. The example here should be included in docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b1b1bbc-51ba-e114-62c0-a663b25c36b1
* Version Independent ID: 31711a31-db0f-3916-7597-e04dda4696fa
* Content: [Create an automated flow with Common Data Service (current environment) connector - Power Automate](https://docs.microsoft.com/en-us/power-automate/connection-cds-native)
* Content Source: [articles/connection-cds-native.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/connection-cds-native.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by Dean-Haas** [comment]
@thomassandsor Thanks for submitting this feedback. We will take a look at adding your suggestion. 

@prsi-msft Can you please evaluate this feedback & work with me to get the update made if necessary. If you're not the correct PM, please help me redirect.  Thanks!

**Comment by v-aangie** [comment]
@thomassandsor - Thanks for your feedback. We have updated the docs to fix information about https://docs.microsoft.com/en-us/power-automate/connection-cds-native, and the updated content is live. Closing this issue.
