### ISSUE TITLE
Licensing information is incorrect

### ISSUE THREAD

**Issue by martinlaukkanen** [MicrosoftDocs/power-automate-docs#294]
The licensing section of this incorrectly states that customer users with Office365 or Dynamics365 subscriptions will not require additional licenses. However in the case of O365 (E3 or E5) the included Power Automate license does not include premium connectors, which unfortunately all custom connectors are.

I hope I'm wrong as this little fact means most of us need to consider alternatives. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e534fb-0608-62e2-e257-77ca64397af6
* Version Independent ID: 0f9e11dc-455d-e1cf-fbc1-89a07cb53ef6
* Content: [Power Automate for enterprise developers, ISVs, and partners - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/dev-enterprise-intro)
* Content Source: [articles/developer/dev-enterprise-intro.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/developer/dev-enterprise-intro.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@martinlaukkanen Thanks for letting us know about this. We've updated the docs to clarify  that one of the Power Automate licenses are required to use premium or custom connectors.
