### ISSUE TITLE
What work would go into updating a flow template?

### ISSUE THREAD

**Issue by kodster28** [MicrosoftDocs/power-automate-docs#297]
Say I publish a template and it gets published. Then, I have changes that I wanted to make.

What does that process look like? Can I easily update my templates? Or would I have to delete and re-create a template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8d0d2-3a6f-c3f1-494d-b0ea73c22f9b
* Version Independent ID: 41bc35b2-5a4d-7406-1ae7-27b292033fcd
* Content: [Submit a flow template - Power Automate](https://docs.microsoft.com/en-us/power-automate/publish-a-template)
* Content Source: [articles/publish-a-template.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/publish-a-template.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by MSFTMan** [comment]
@kodster28 Thanks for your question. We will look into this and update the document.

**Comment by MSFTMan** [comment]
The information for those items are detailed in the article. We recommend that the partner follows these instructions - they describe how to do what the customer wants for #1-#3. However, #4 is not possible - the user will have to have an account with Microsoft, as that's how authentication works.

**Comment by kodster28** [comment]
Howdy @MSFTMan , I don't believe those PRs are addressing my question.

If I submit a template, am I allowed to modify the template itself (not any implementations)? Or would I need to delete the old template + create a new one?

We're wondering because--as a partner--we're evaluating whether we want to create internal templates for our customers to consume.
