### ISSUE TITLE
Update request for the latest UI

### ISSUE THREAD

**Issue by sasaito** [MicrosoftDocs/power-automate-docs#299]
Could you update the screenshot to the latest UI?

SharePoint 2010 workflows will be retired starting August 1, 2020 and we recommend migrating to Power Automate. This article is useful for SharePoint 2010 workflow users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f51e26d-e8cd-2152-45a2-bd23d13fb3b2
* Version Independent ID: 30768baf-8dd7-d64c-aec2-f500fbbe1e78
* Content: [Easily Automate approval workflows. - Power Automate](https://docs.microsoft.com/en-us/power-automate/modern-approvals?source=docs)
* Content Source: [articles/modern-approvals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Updated this topic for current UI in text and screens
