### ISSUE TITLE
"Flow" is still frequently used as the product name

### ISSUE THREAD

**Issue by AlexJerabek** [MicrosoftDocs/power-automate-docs#300]
This page contains multiple references to "Flow" instead of "Power Automate". There are headers like "Administration of Flow" and "Can I block another person from using the paid features of Flow?" This seems outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c23aa79-64e4-9488-b528-af781d7b456e
* Version Independent ID: aacc4f60-044f-d587-9dde-8a48168c59e7
* Content: [Power Automate sign-up Q&A in your organization - Power Automate](https://docs.microsoft.com/en-us/power-automate/organization-q-and-a)
* Content Source: [articles/organization-q-and-a.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/organization-q-and-a.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by Dean-Haas** [comment]
I have updated this article & swept the repo for references to Flow as a product name. Flow is still valid within power automate, as you still create a 'flow' in PA.
