### ISSUE TITLE
shall I use this within SharePoint site without using the clientid

### ISSUE THREAD

**Issue by vbalaji27** [MicrosoftDocs/power-automate-docs#301]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac3ad92-eb8f-554a-5de3-14c430e594aa
* Version Independent ID: fab1ceb3-5110-4452-0a0d-99346cc31230
* Content: [Integrate Power Automate with websites and apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/embed-flow-dev)
* Content Source: [articles/developer/embed-flow-dev.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/developer/embed-flow-dev.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@vbalaji27 Yes, the steps in the document should work. Please let us know if you have a specific issue when you follow the document.
