### ISSUE TITLE
How to create a SharePoint list of co-owners

### ISSUE THREAD

**Issue by blachawk** [MicrosoftDocs/power-automate-docs#302]
The docs clearly states that this is an option to do when we want to share flows.  But there is no link provided on page that shows us how to actually set this up. What steps do we take to create & use a SharePoint list (of co-owners), as a sharable resource for Power automate flows?

**Comment by MSFTMan** [comment]
@blachawk Thanks for reporting this issue. We will look into it and update the docs.

**Comment by Dean-Haas** [comment]
I've added a link to how to create a sharepoint list to https://docs.microsoft.com/en-us/power-automate/create-team-flows#add-a-list-as-a-co-owner. This change won't be public immediately.
