### ISSUE TITLE
Is ti possible to schedule "every 4th Monday of each month" ?

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/power-automate-docs#303]
I am unclear if it is possible to set a specific day of each month.
I want my scheduled task to start, as an example, on the 4th of each month.

What is the custom format, where is that documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba2e127-56bc-5910-3af6-30030cf58c1f
* Version Independent ID: c8fea93d-3d8d-bf8e-af7d-ae853a936843
* Content: [Run flows on a schedule - Power Automate](https://docs.microsoft.com/en-us/power-automate/run-scheduled-tasks)
* Content Source: [articles/run-scheduled-tasks.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/run-scheduled-tasks.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by Dean-Haas** [comment]
Hi @scyto . Thanks for your feedback . This would be a great idea to suggest via our ideas forum: https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas
