### ISSUE TITLE
UI Flow Recorder doesn't recognize installed and activated extensions

### ISSUE THREAD

**Issue by philippschaefer4** [MicrosoftDocs/power-automate-docs#304]
Hi,

I followed the instruction to set up a UI Flows from RPA in a day. I installed "UI Flow", "On Premise Gateway",  "WinAutomation" and "Selenium"  

![image](https://user-images.githubusercontent.com/16938379/88528675-3752ba00-cfff-11ea-86e5-1db7ed48b747.png)

and activated all of them

![image](https://user-images.githubusercontent.com/16938379/88528743-4df91100-cfff-11ea-9d0a-009539cdc422.png)

but I still get the message that I didn't:

![image](https://user-images.githubusercontent.com/16938379/88528562-14280a80-cfff-11ea-80bb-a6c0a06702e2.png)

Is there still something that I am missing? Thanks for any help.

Philipp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1328965-3272-9380-7215-87b87b9169a1
* Version Independent ID: db6b4071-a4ee-c9fb-1142-f38d6d6e0a47
* Content: [Set up UI flows on your device - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/setup)
* Content Source: [articles/ui-flows/setup.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/setup.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by lanlanlee2008** [comment]
Could you restart the browser and try again? Thanks.

**Comment by Dean-Haas** [comment]
@philippschaefer4  please let us know if this issue persists. Thanks for submitting Docs feedback

**Comment by Dean-Haas** [comment]
As this does not appear to be a documentation issue, I'll go ahead and close this. For more help with issues like this, try posting your question on the [community forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity). Thanks
