### ISSUE TITLE
Forced line break

### ISSUE THREAD

**Issue by mikeg-roebbelen** [MicrosoftDocs/power-automate-docs#305]
Under Forced line break example 1, shouldn't the example only include a single (space) at the end?  Example 2 shows two (spaces) which results in two new lines, but example 1 appears to intend to only show one line break.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by Dean-Haas** [comment]
@mikeg-roebbelen  Thanks for submitting this feedback. The correction should be published shortly. Thanks for submitting it.
