### ISSUE TITLE
Power Automate don't have premium plan that is mentioned in documentation

### ISSUE THREAD

**Issue by baludharmarajan** [MicrosoftDocs/power-automate-docs#306]
Microsoft phased out premium 1,2 plans and have Office 365 as well as user plans. The documentation is still not updated. Please update with differences.

**Comment by Dean-Haas** [comment]
@baludharmarajan thanks for this feedback. We're working on getting this updated.

**Comment by MSFTMan** [comment]
@baludharmarajan This issue has been fixed. Thank you for reporting it.
