### ISSUE TITLE
No example of multiple ORs nor ANDs. added ORs: Fields are greyed out and cant be updated

### ISSUE THREAD

**Issue by devbenjamin** [MicrosoftDocs/power-automate-docs#307]
![image](https://user-images.githubusercontent.com/42345459/89319705-7bbd0600-d64e-11ea-94cd-f5566c4a3a53.png)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6af5f3e7-4734-5813-0e3d-dada381fec0b
* Version Independent ID: 393c8bdd-da49-d6cd-f97a-94283f55c0a2
* Content: [Add a condition to a flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/add-condition)
* Content Source: [articles/add-condition.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/add-condition.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by Dean-Haas** [comment]
Hi @devbenjamin. Thanks for submitting docs feedback. Were you able to resolve this? I'm looking at your issue and reviewing the doc to see if there's a fix or improvement we can make to the topic, but it's hard to know what's going on in your case based only on this screenshot. If you feel the docs need to be updated, please provide some context as to what you are seeing. If you are looking for help troubleshooting your implementation, the best place to post a question is probably on the [Power Automate forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity)
