### ISSUE TITLE
FLOW BOT name change

### ISSUE THREAD

**Issue by scjohnmsft** [MicrosoftDocs/power-automate-docs#311]
When we use FLOW to send an adaptive card to TEAMS, the message in TEAMS says, "**_FLOW Bot sends a message_**" we like to know if we can change that to the Application name
![flow bot name](https://user-images.githubusercontent.com/64435811/90049596-0632e480-dca3-11ea-90ea-263706603265.png)

**Comment by MSFTMan** [comment]
@scjohnmsft Thanks for your question. There isn't a way to change this. Thanks!
