### ISSUE TITLE
select action documentation doesnt match json example

### ISSUE THREAD

**Issue by goravseth** [MicrosoftDocs/power-automate-docs#312]
doc says:

> and you’d like to reshape the incoming data by renaming "first" to "FirstName", "last" to "LastName" and adding a new member named "FamilyName" that combines "first" and "last" (separated with a space):

json shows
> [ { "FirstName": "Deon", "FamilyName": "Herb", "FullName": "Deon Herb" }, { "FirstName": "K", "FamilyName": "Herb", "FullName": "K Herb" } ].

doc should say
and you’d like to reshape the incoming data by renaming "first" to "FirstName", "last" to "FamilyName" and adding a new member named "FullName" that combines "first" and "last" (separated with a space):

last name --> FamilyName (not LastName)
new member is named FullName, not FamilyName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bddf7e-aad7-5b99-0b73-a893d25615f5
* Version Independent ID: f2f0c4d6-b613-d269-4756-bcd7548f76ec
* Content: [Understand data operations - Power Automate](https://docs.microsoft.com/en-us/power-automate/data-operations)
* Content Source: [articles/data-operations.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/data-operations.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
@goravseth thank you for this feedback. We'll investigate this.  @msftman Can you please evaluate?

**Comment by Dean-Haas** [comment]
Doc updated by Deon
