### ISSUE TITLE
Examples do not include Links in Mobile Notifications

### ISSUE THREAD

**Issue by tweing** [MicrosoftDocs/power-automate-docs#313]
I realized that when sending a Mobile Notification with the "Subject" of the e-Mail message triggering the flow, the link will not open on the mobile App (iPhone).

Did you leave the link fields empty in all the examples by intend?
What do I need to do to see the e-Mail subject in the notification on the mobile App?

Some examples on this page or a hint about limitations would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38b2975-5eb6-1aa4-c1fd-d0f033ace5ca
* Version Independent ID: 85899731-9939-a779-29c4-4da652667b74
* Content: [Run flows based on email properties - Power Automate](https://docs.microsoft.com/en-us/power-automate/email-triggers)
* Content Source: [articles/email-triggers.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/email-triggers.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
@hamenon-ms Can you please look at whether an update to the docs page is warranted here? If you aren't the correct PM, and you please redirect?  Thanks.

**Comment by hamenon-ms** [comment]
@Dean-Haas I think this might be better solved through a dedicated mobile app section with details on what you can do with it. Can you check with Kartik on who can help from the PM side.

On a side note on this specific example to get the notification to show the subject of the email you just need to replace the text field with the dynamic token for Subject. I'm not sure if our current app allows opening the client email app directly though

**Comment by tweing** [comment]
@Dean-Haas , @hamenon-ms : This is not about what you can do on the mobile app, but rather how the Text of the e-Mail subject can be included in the Mobile Notification sent by flow to the mobile app.

**Comment by hamenon-ms** [comment]
@tweing that is fairly straightforward. You just need to include the token for Subject in the text field. For example:
![image](https://user-images.githubusercontent.com/39499084/93924486-a7ad4d00-fcc9-11ea-8e5f-54077dcf3759.png)

You can check out the template for Receiving a notification when your managers sends you an email for an example of how this is done

https://flow.microsoft.com/en-us/galleries/public/templates/135019e1cdc6457b8bc6f6051607e778/get-a-push-notification-when-you-receive-an-email-from-your-boss/
