### ISSUE TITLE
Include DLP Needed to run UI flows

### ISSUE THREAD

**Issue by RaisinBread42** [MicrosoftDocs/power-automate-docs#314]
I have tried googling but to no luck.  One thing that all tutorials, and surprisingly this one, seem to ignore is the DLP that will prevent Web UI (selenium) in flows from running. Why is this ?  I too am stuck because because this has not been configured correctly?!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38b1ee-9441-f41e-4e4c-6e0783803662
* Version Independent ID: de38cf18-2895-27f9-bc91-3f72eb3fa0d1
* Content: [Learn to create UI flows for Websites - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/create-web)
* Content Source: [articles/ui-flows/create-web.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/create-web.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by RaisinBread42** [comment]
@MSFTMan

**Comment by MSFTMan** [comment]
@RaisinBread42  Thanks for your feedback. Your Admin can configure the DLP settings to allow/block services. Thanks!

**Comment by RaisinBread42** [comment]
@MSFTMan at least mentioning that and linking to how to configure would be nice. Pretty sure other devs would end up in a similar situation as I have.  We should know this stuff before diving deep into this tutorial just to hit that DLP issue.
