### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/power-automate-docs#316]
This link "Long running approvals" is directing to a different article. I believe you want to refer to this article https://docs.microsoft.com/en-us/business-applications-release-notes/april19/microsoft-flow/increased-run-duration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f51e26d-e8cd-2152-45a2-bd23d13fb3b2
* Version Independent ID: 30768baf-8dd7-d64c-aec2-f500fbbe1e78
* Content: [Easily Automate approval workflows. - Power Automate](https://docs.microsoft.com/en-us/power-automate/modern-approvals)
* Content Source: [articles/modern-approvals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
Thanks for reporting this issue @ahamin01 . It's not fixed.
