### ISSUE TITLE
Unable to select user's response {acPollChoices}

### ISSUE THREAD

**Issue by RaisinBread42** [MicrosoftDocs/power-automate-docs#319]
Not able to select user's response {acPollChoices} from adaptive card via dynamic content or expressions within flow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf788f3b-9ad6-3c79-689d-5f36c1ab292f
* Version Independent ID: d8a78d1d-7f90-7fb1-b0f6-8ae6518031f1
* Content: [Create flows that post adaptive cards to Microsoft Teams - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-adaptive-cards)
* Content Source: [articles/create-adaptive-cards.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/create-adaptive-cards.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by RaisinBread42** [comment]
@MSFTMan

**Comment by Dean-Haas** [comment]
Hi @RaisinBread42 . Thanks for submitting docs feedback. This doesn't look to be a documentation issue, so I will close this, but I suggest you post your question on the [Power Automate Community forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity) I hope this helps.
