### ISSUE TITLE
Request for more illustration on the usage of Power Automate Web API to Create Flows using code

### ISSUE THREAD

**Issue by vidyasagaralti** [MicrosoftDocs/power-automate-docs#322]
Only minimal information is available in configuring clientData property in the article [https://docs.microsoft.com/en-us/power-automate/web-api](url). It would be helpful if you can illustrate in details of how to create a flow and add different type of actions with examples and demos. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eecc2503-eee7-8779-2445-d6cd6968a0bd
* Version Independent ID: 532be787-8be9-c9b5-37a2-88841c5b8118
* Content: [Flows are now stored in Common Data Service and use the rich Web API - Power Automate](https://docs.microsoft.com/en-us/power-automate/web-api)
* Content Source: [articles/web-api.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/web-api.md)
* Service: **business-applications**
* Product: ****
* Technology: ****
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by Dean-Haas** [comment]
@radioblazer Could you please evaluate this feedback & work with me or @MSFTMan if doc updates are needed? Thanks.

**Comment by MSFTMan** [comment]
@radioblazer  The details of the client data field are documented here https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-workflow-definition-language

Thank you.
