### ISSUE TITLE
Flow Always Gets Created in 'Default Solution'

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/power-automate-docs#323]
Is it possible to indicate a solution other than 'Default Solution' when creating a flow via the Power Management API's?  Or is it possible to update an existing flow to 'move' it to another solution?  I've tried using the 'solutionid' parameter to do both, but neither worked.  

![image](https://user-images.githubusercontent.com/38665906/93245926-ddd65400-f740-11ea-9aa9-efc3e423ee92.png)

**Comment by Dean-Haas** [comment]
Hi @TracyGH . I'm not sure. Unfortunately, this isn't the best place for questions like this. This is where you can submit issues related to documentation. The best place for you to submit a question like this is on the Power Automate community forums: https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity. I hope this helps!

**Comment by TracyGH** [comment]
Hi @Dean-Haas,
Thank you for the prompt response.  I'm familiar with that community, but I don't think that's the appropriate place for this question either.  Those are typically 'power users' who ask questions pertaining to the Power Platform tool set (Power Automate, Power Apps Studio, etc.).  I'm asking a question about the Power Management APIs themselves, which is a different technology than the tools.  
This piece of documentation is showing an example pertaining to my question.  In the past, I've seen users post technical questions regarding specific examples associated with the documentation it was in.  I can point out several examples.  
I guess I will post something in StackOverflow, because I'm not really sure where else this belongs...?
