### ISSUE TITLE
approvalCenterSettings initialization

### ISSUE THREAD

**Issue by IsolatedStorage** [MicrosoftDocs/power-automate-docs#324]
In the [Widget Architecture](https://docs.microsoft.com/en-us/power-automate/developer/embed-flow-dev#widget-architecture) section, the JavaScript for initialization is listed as follows

var widget = sdk.renderWidget('<widgettype>', {
        container: 'flowDiv',
        flowsSettings: {},
        templatesSettings: {},
        approvalSettings: {},
        widgetStyleSettings: {}
});

However, I think the **approvalSettings** value is incorrect as this should be **approvalCenterSettings** ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac3ad92-eb8f-554a-5de3-14c430e594aa
* Version Independent ID: fab1ceb3-5110-4452-0a0d-99346cc31230
* Content: [Integrate Power Automate with websites and apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/embed-flow-dev#configuring-your-client-application)
* Content Source: [articles/developer/embed-flow-dev.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/developer/embed-flow-dev.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by Dean-Haas** [comment]
@IsolatedStorage  Thanks for submitting this. we'll look into it. 

@msftman can you please evaluate?

**Comment by Dean-Haas** [comment]
@hamenon-ms & @dblyth-msft can you confirm that the approvalSettings value should be approvalCenterSettings in the Widget Architecture section? LMK, and I can get this updated and close it out. Thanks!

**Comment by dblyth-msft** [comment]
Yes it should be approvalCenterSettings

**Comment by MSFTMan** [comment]
@IsolatedStorage Thanks for reportign this issue. We've updated the docs. It will be available publicly later today.
