### ISSUE TITLE
Outdated images.

### ISSUE THREAD

**Issue by quinlanharsch** [MicrosoftDocs/power-automate-docs#325]
Outdated images. Connections is now on left sidebar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bf9b6c-5628-f18c-7027-45b21eb3b6bc
* Version Independent ID: a4394ad5-9d46-2a6d-16d9-48b0c88fb401
* Content: [Learn to connect to your data using connections and on-premises data gateways - Power Automate](https://docs.microsoft.com/en-us/power-automate/add-manage-connections#update-a-connection)
* Content Source: [articles/add-manage-connections.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/add-manage-connections.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **stepsic**

**Comment by Dean-Haas** [comment]
Hi @quinlanharsch . Thanks for pointing this out. We're currently updating these docs to match the current UI.  I went ahead and fixed this one now, so it should be live shortly. I do appreciate the heads up.
