### ISSUE TITLE
Suggestion to abandon real-time workflows is unhelpful

### ISSUE THREAD

**Issue by RobertAndersonHunt-PeterMac** [MicrosoftDocs/power-automate-docs#327]
The FAQ response for Real-Time Workflows is patronising at best, insulting at worst.

Dedicate an article to useful examples of replacements. There is no documentation available for this.

The Dynamics/Powerapps platform has a *massive* failure in its ability to check data from lookups & related records in real-time. This is important business functionality for complicated apps and this response feels like a huge middle finger.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c08ddd-c290-34f4-5e82-ae9369012efd
* Version Independent ID: 98652aac-b377-c9fe-bb32-47d873f7237a
* Content: [Replace classic Common Data Service workflows with Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/replace-workflows-with-flows)
* Content Source: [articles/replace-workflows-with-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/replace-workflows-with-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by Dean-Haas** [comment]
@RobertAndersonHunt-PeterMac  Thanks for your feedback. I see your point in how the answer is worded and how it might be perceived. I've updated it to address that (should be live soon). We'll add your suggestion to add examples as a suggestion for future update project. Thanks!
