### ISSUE TITLE
pls be more specific what happens if not-mandatory fields are not used

### ISSUE THREAD

**Issue by csjn** [MicrosoftDocs/power-automate-docs#328]
e.g. "Start Time" is not mandatory. What happens, if you do not use that field: Does the flow never run, run on next occurence, ... ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba2e127-56bc-5910-3af6-30030cf58c1f
* Version Independent ID: c8fea93d-3d8d-bf8e-af7d-ae853a936843
* Content: [Run flows on a schedule - Power Automate](https://docs.microsoft.com/en-us/power-automate/run-scheduled-tasks)
* Content Source: [articles/run-scheduled-tasks.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/run-scheduled-tasks.md)
* Service: **flow**
* GitHub Login: @stepsic-microsoft-com
* Microsoft Alias: **nijemcevic**

**Comment by Dean-Haas** [comment]
Hi @csjn Thanks for submitting docs feedback. The default start time is populated in that field if you don't set a custom value, and the recurrence occurs at the selected interval from that point if you don't make any changes to the additional options in advanced settings. You'll see the default start time in the UI:

![image](https://user-images.githubusercontent.com/50121982/94321655-1ba75980-ff45-11ea-9751-78a61065229d.png)

I hope this helps.
