### ISSUE TITLE
Inconsistency in DataTable reference instructions

### ISSUE THREAD

**Issue by pdennis33** [MicrosoftDocs/power-automate-docs#329]
Hey there, thanks a lot for the docs on Power Automate Desktop, I'm trying to use it and the docs are helping a lot.  This issue is that you state **To retrieve a specific item of a datatable, use the following notation: %VariableName[RowNumber][ColumnNumber]%**.   However, you also state **to access the A2 cell of an Excel file, use the expression displayed below: %ExcelData[0][1]%**.  This [0][1] reference implies cell B1 if it is indeed [RowNumber][ColumnNumber].

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6b6266-07ea-2d22-6da9-fe109877b89c
* Version Independent ID: a9a4c8f2-8e41-746c-ada7-e6f97fe8abf7
* Content: [Datatables - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/desktop/datatables)
* Content Source: [articles/ui-flows/desktop/datatables.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/desktop/datatables.md)
* Service: **flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **getrantz**

**Comment by Dean-Haas** [comment]
Hi @radioblazer Can you please evaluate this? lmk if we need to redirect to a different PM. Thanks!

**Comment by mariosleon** [comment]
@pdennis33  Thank you for pointing this out. Please note that in this case %ExcelData% is a datatable with all the excel contents, not the excel file itself. We made the required changes to avoid future confusion.
