### ISSUE TITLE
Sending special keys

### ISSUE THREAD

**Issue by pdennis33** [MicrosoftDocs/power-automate-docs#331]
Hello,

I don't see anywhere in the docs that illustrate how to send special keys such as the Up, Down, Left, and Right arrows for navigation, and things like Tab, Backspace, and Enter.  Really any special key would apply here.

Thank you!

**Comment by Dean-Haas** [comment]
Hi @pdennis33 . Thanks for submitting docs feedback. It looks like the metadata in the submission form got over written when you wrote your comments, so I can't see which page this refers to. Can you point me to the docs topic (and section if applicable) that this pertains to?
