### ISSUE TITLE
Managed now supported

### ISSUE THREAD

**Issue by ChristopherMank** [MicrosoftDocs/power-automate-docs#332]
This doc looks to need updates as now Managed is a possible, selectable option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0535b1a-e189-75c9-d5f0-c200a65150ec
* Version Independent ID: 7120c4d7-3223-6c65-f70f-03ca718775f1
* Content: [Learn how to export solution-aware flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/export-flow-solution)
* Content Source: [articles/export-flow-solution.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/export-flow-solution.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by KumarVivek** [comment]
@ChristopherMank Thanks for reporting this; the topic is now updated with the latest information. Closing the issue now.
