### ISSUE TITLE
Embedding templates like described in this article is broken

### ISSUE THREAD

**Issue by antonkhrit** [MicrosoftDocs/power-automate-docs#333]
Embedding templates like described in this article is broken. It worked before. 

Example:
https://flow.microsoft.com/en-us/widgets/templates/?q=SharePoint

Gives:
We couldn't find any templates that matched your search.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac3ad92-eb8f-554a-5de3-14c430e594aa
* Version Independent ID: fab1ceb3-5110-4452-0a0d-99346cc31230
* Content: [Integrate Power Automate with websites and apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/embed-flow-dev)
* Content Source: [articles/developer/embed-flow-dev.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/developer/embed-flow-dev.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by Dean-Haas** [comment]
@antonkhrit Thanks for this feedback. We'll look into it. 

@hamenon-ms Can you please confirm that this should work?  https://docs.microsoft.com/en-us/power-automate/developer/embed-flow-dev#show-templates-for-your-scenarios  It looks to me like a bug in the template search function. If so, can you file a product bug so I can close this doc bug? Thanks!

**Comment by hamenon-ms** [comment]
Yup that should work. @dblyth-msft can you help on this?

**Comment by nickdurak** [comment]
Fix in progress thank you for identifying

**Comment by Dean-Haas** [comment]
@antonkhrit thanks for pointing this out. As the product bug has been filed, I'll go ahead and close out this docs issue. We appreciate your feedback!
