### ISSUE TITLE
Retrieve email messages from Outlook with smtp addresses of TO & CC fields

### ISSUE THREAD

**Issue by malayvir** [MicrosoftDocs/power-automate-docs#336]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34835c44-604e-9820-db62-c7fe2abdf1bf
* Version Independent ID: 8734bb69-fa2b-4d92-d595-b1d763108caf
* Content: [Outlook - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/desktop/actions-reference/outlook)
* Content Source: [articles/ui-flows/desktop/actions-reference/outlook.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/desktop/actions-reference/outlook.md)
* Service: **flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by malayvir** [comment]
%CurrentEmail['To']% fetches email address in X500 format, need an option to either convert it to smtp format.

**Comment by mariosleon** [comment]
@malayvir Thank you for your feedback. This appears to be a feature request, please go ahead and share this with the product team in the following link: https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas
