### ISSUE TITLE
Can well call out what templating language features aren't available for the Teams Adaptive Cards connector?

### ISSUE THREAD

**Issue by chryw** [MicrosoftDocs/power-automate-docs#337]
I used array `$data` binding to [repeat some sections](https://docs.microsoft.com/en-us/adaptive-cards/templating/language#repeating-items-in-an-array) which worked great in mockup on https://adaptivecards.io/designer. 

However, I didn't know that this is not supported in the Power Automate connector. I ended up spending a lot of time digging through docs and asking around as I thought my code is wrong.

@tposzytek generously jumped in and helped me. That's how I learned that some templating language features aren't supported in the PA connector. Can we call out what's not available in the [Known issues](https://docs.microsoft.com/en-us/power-automate/overview-adaptive-cards#known-issues) section (or in the Teams connector [Known issues](https://docs.microsoft.com/en-us/connectors/teams/#known-issues-and-limitations)? This would save people time and may also impact their decision on whether Adaptive Cards + Power Automate is the appropriate tool for their projects.

PS: I ended up using "Apply to each" action to compose repeated sections separately then insert the composed result into the "Post an Adaptive Card" action later. Just sharing my workaround in case it can help people land on the same question :-)

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f9dedee-52fa-d9ff-ef0e-d4fab19146c2
* Version Independent ID: bf2de98c-09c9-d8f1-0867-dbdf8efcddcf
* Content: [Overview of Adaptive Cards for Teams - Power Automate](https://docs.microsoft.com/en-us/power-automate/overview-adaptive-cards)
* Content Source: [articles/overview-adaptive-cards.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/overview-adaptive-cards.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
@chryw thanks for submitting docs feedback. We'll evaluate your suggestion

@hamenon-ms does it make sense to build out the [known issues](https://docs.microsoft.com/en-us/power-automate/overview-adaptive-cards#known-issues) section to call out what's not supported, as suggested above? Thanks!

**Comment by v-aangie** [comment]
@hamenon-ms — In addition to the question above, "does it make sense to build out the known issues section to call out what's not supported, as suggested above?", please let me know if the suggested workaround, "apply to each" in the original request above, belongs in the doc. Thank you!

**Comment by v-aangie** [comment]
@chryw - Thanks for your feedback. We have updated thttps://docs.microsoft.com/en-us/power-automate/approvals-known-issues, and the updated content will be live later today. Closing this issue.
