### ISSUE TITLE
Start an approval action no longer used

### ISSUE THREAD

**Issue by airdouglas** [MicrosoftDocs/power-automate-docs#338]
The section for **Add a condition** confuses two different Approval actions.  The old way, **Start an approval**, had a **Response** property.  The new way, **Start and wait for approval** (used in the article), has an **Outcome** property.  The method for adding the **Responses Approver Response** is not correct when using the current **Start and wait for approval** (which used to be referred to as V2) action.  The instructions conflate methods from both actions.

The correct sequence would be:

1.  Add the **Start and wait for approval** action (as is mentioned in the article)
2.  Add a **Condition** action
3.  Use the **Outcome** property and check to see if that value is equal to **Approve** or **Reject** (case sensitive)

If you follow the instructions as written when you add the **Responses Approver Response** you will insert an **Apply to each** action that will assume you want to loop through the **Responses** array.

If using the old action, **Start an approval** such as the one included in some of the **Approval** templates, then using the **Response** property in the **Condition** or **Switch** would be appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f51e26d-e8cd-2152-45a2-bd23d13fb3b2
* Version Independent ID: 30768baf-8dd7-d64c-aec2-f500fbbe1e78
* Content: [Easily Automate approval workflows. - Power Automate](https://docs.microsoft.com/en-us/power-automate/modern-approvals?source=docs#add-a-condition)
* Content Source: [articles/modern-approvals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Hi @airdouglas. Thanks for submitting docs feedback. We'll evaluate this and update the topic if necessary. 

@hamenon-ms can you please evaluate the feedback above & make a recommendation? Thanks!

**Comment by MSFTMan** [comment]
@airdouglas Thanks for your report. We've walked thru the steps and confirm that as written, the document is correct. Kindly let us know if you are still seeing issues. Closing the issue now. Thanks!
