### ISSUE TITLE
Minutes are recommended

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/power-automate-docs#339]
Based on conversations on the flow DL it would be good to state that if you don't specify minutes then the flow can run anytime during the hour(s) specified. For example if you set it for 2:00 it could run anytime from 2;00 to 2:59.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba2e127-56bc-5910-3af6-30030cf58c1f
* Version Independent ID: c8fea93d-3d8d-bf8e-af7d-ae853a936843
* Content: [Run flows on a schedule - Power Automate](https://docs.microsoft.com/en-us/power-automate/run-scheduled-tasks)
* Content Source: [articles/run-scheduled-tasks.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/run-scheduled-tasks.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Hi @JerryCRMI. Thanks for submitting docs feedback. Can you please point me to the discussions you are referencing? In testing this, I am seeing scheduled flows run on the hour. I's like to see more details on what people are seeing so we can validate. Thanks.

**Comment by JerryCRMI** [comment]
Hi Dean,

See the attached response from Prabir to my email on the DL list.

Jerry
