### ISSUE TITLE
GCC Availability

### ISSUE THREAD

**Issue by pagejustin** [MicrosoftDocs/power-automate-docs#340]
Is this available in GCC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4deb6978-b47f-3860-ea17-442759744c0e
* Version Independent ID: 9cabdd98-d0cf-cf2a-ae01-ed3dc3acdfb0
* Content: [Manage SharePoint page approvals with Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/customize-sharepoint-page-approvals)
* Content Source: [articles/customize-sharepoint-page-approvals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/customize-sharepoint-page-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Hi @pagejustin . Thanks for submitting Docs feedback. Looking at the Power Automate GCC section, it looks like approvals are available, but subject to certain limitations described [here](https://docs.microsoft.com/en-us/power-automate/us-govt#power-automate-us-government-feature-limitations). If that doesn't answer it fully, the best place to ask this type of question is on the [Power Automate Community forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity). Thanks!
