### ISSUE TITLE
Create MFA Session for PowerScript

### ISSUE THREAD

**Issue by dodge1350-frp** [MicrosoftDocs/power-automate-docs#343]
What is the best way to create an MFA session for a PowerScript operation in UI workflow?

**Comment by Dean-Haas** [comment]
Hi @dodge1350-frp. Thanks for submitting docs feedback. I am not seeing a docs issue here, but I encourage you to submit this question on the [Power Automate Community forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity). Thanks.
