### ISSUE TITLE
When is the GA ?

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/power-automate-docs#344]
when is the GA for the feature documented : https://docs.microsoft.com/en-us/power-automate/flic-button-flows, i guess this was updated in 2017. Please share information regarding GA of this feature and who is the feature PM of this product ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a87ed26-9876-e7aa-7826-ce7b3ccbea43
* Version Independent ID: c6804cc1-90ff-00f3-59d3-fd7fac90f93e
* Content: [Start flows with Flic buttons - Power Automate](https://docs.microsoft.com/en-us/power-automate/flic-button-flows)
* Content Source: [articles/flic-button-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/flic-button-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@HinaMS Thanks for your interest in Power Automate. We don't have any further information to be released pulicly about this feature at this time. Thanks!
