### ISSUE TITLE
OData parsing error

### ISSUE THREAD

**Issue by mwilsonray** [MicrosoftDocs/power-automate-docs#345]
I'm trying to run through this example in a GCC High environment, but the Get my profile (V2) steps keeps erroring with:

Parsing OData Select and Expand failed: Term 'can I get a break2020-11-06T05:00:00Z2020-12-06T05:00:00Ztesting again3Truexxxxx xxxxxyyyyy@yyyyy.com' is not valid in a $select or $expand expression.

xxxxx xxxxx = Created By Display Name
yyyyy@yyyyy.com = Created By Email

Fields selected:
Title, Start Date, End Date, Comments, ID, Manager Comments, Approved, Created By Display Name, Created By Email

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f51e26d-e8cd-2152-45a2-bd23d13fb3b2
* Version Independent ID: 30768baf-8dd7-d64c-aec2-f500fbbe1e78
* Content: [Easily Automate approval workflows. - Power Automate](https://docs.microsoft.com/en-us/power-automate/modern-approvals)
* Content Source: [articles/modern-approvals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/modern-approvals.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Hi @mwilsonray. Thanks for submitting docs feedback. I would refer you to post your question on the [Power Automate Community Forums](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity). Also see [Power Automate US Government feature limitations](https://docs.microsoft.com/en-us/power-automate/us-govt#power-automate-us-government-feature-limitations)

 I am not seeing a docs issue here, so will close this out. Thanks.
