### ISSUE TITLE
What happens when a limit is reached?

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/power-automate-docs#348]
What happens when a limit is reached?

I've got a flow (O365 licensed) that should be limited to 2000 actions per day, but I'm completing >40,000 actions per day.

MS Support are telling me that once the limit is reached, flows will drop in performance and may stop on some actions.
But if I run the flow, one instance at a time, then there's no slowdown or stopping.
If I run multiple instances, it seems to get into a deadlock and neither will finish (tested up to ~1.5 hours).

So what's the deal here?  What really happens when a limit is reached.

A side note: There's currently no way for an O365 user to find out how many steps/actions there is in their flow, or to see how many actions they've used in a day (to figure out if they're getting near the limits). These are hidden behind a premium license.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Hi @Craig-Humphrey. Thanks for submitting docs feedback. I am reading your question as a licensing question rather than a technical limitations question as discussed in this docs topic. It sounds like you are in contact with MS Support. Have you provided the information about what you're experience is? Another way you might find an answer is by posting your question on the [Power Automate Community forums] (https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity)

**Comment by Craig-Humphrey** [comment]
Hi @Dean-Haas,

thanks for responding.
It's not really a licensing question.  As the licensing just adjusts where the limit is.

I need to know what happens when a limit is reached.

I'd also like to know how a flow builder can measure their flow(s) against these limits - I believe this is somewhat available under a premium license - so that is probably a licensing question - but it's a bit unfair for non-premium licensed users to be subject to limits that they can't track.

MS Support said that the flow "may slowdown or stop" when a limit is reached, which isn't particularly helpful, especially as that's not entirely what I'm experiencing.  They are unable to give me a better answer for both questions and just want to close the call.

So I'm trying the documentation avenue, to try and establish just what is expected to happen if a limit is reached, as the documentation makes no mention of this.

Thanks
Craig
