### ISSUE TITLE
Please provide more info about "Number of users" and "Number of runs"

### ISSUE THREAD

**Issue by redmondChris** [MicrosoftDocs/power-automate-docs#349]
The "Number of users" and "Number of runs" seem ambiguous to me. Does number of users refer to how many users would author using this template, the number of users that would be impacted by using the template, or something else? Is the number of runs over a certain time period or in a certain context?

Depending on the context, the answers to these questions could vary wildly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8d0d2-3a6f-c3f1-494d-b0ea73c22f9b
* Version Independent ID: 41bc35b2-5a4d-7406-1ae7-27b292033fcd
* Content: [Submit a flow template - Power Automate](https://docs.microsoft.com/en-us/power-automate/publish-a-template)
* Content Source: [articles/publish-a-template.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/publish-a-template.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by Dean-Haas** [comment]
Hi @redmondChris . Thanks for submitting docs feedback. I think the point you are raising should be addressed in the UI. Where "number of runs" should probably be "run frequency". The descriptive text in those fields does provide guidance, and it's up to the submitter to describe whether it runs "every x minutes",  "x times daily", or "x times per month". This could vary depending on circumstance, so I don't think we should define this in docs. 

@sunaysv can you please evaluate whether this warrants a UI update? Thanks!
