### ISSUE TITLE
Need to see solutions in the Flow widget

### ISSUE THREAD

**Issue by Naitik-Xpertladr** [MicrosoftDocs/power-automate-docs#354]
Team,

The use case to support embed of power automate in custom apps is very helpful, but the challenge we are facing is that, we cannot see solutions when we embed and hence is a big blocker since we have many child flows which are only visible within solutions. Is there a settings to enable viewing of solutions when we embed power automate or any workarounds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac3ad92-eb8f-554a-5de3-14c430e594aa
* Version Independent ID: fab1ceb3-5110-4452-0a0d-99346cc31230
* Content: [Integrate Power Automate with websites and apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/embed-flow-dev)
* Content Source: [articles/developer/embed-flow-dev.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/developer/embed-flow-dev.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@Naitik-Xpertladr  Thanks for reporting this issue. We are looking into this issue and will updte you asap.

**Comment by Naitik-Xpertladr** [comment]
@MSFTMan - Thanks for the update. Looking to hear from you soon on a resolution/workaround.

**Comment by MSFTMan** [comment]
@Naitik-Xpertladr Thanks for your question. Kindly ask this question in the Power Automate community for assistance: https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity. Closing this issue.
