### ISSUE TITLE
View a Flow Performance Profile

### ISSUE THREAD

**Issue by phillipharding** [MicrosoftDocs/power-automate-docs#355]
The document states that to view the performance profile of a Flow, to open the export page for the flow.

When doing this no performance profile is displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by lgmsmm** [comment]
Same issue here, We have Office 365 Standard licenses, I can't see wich profile is my flow, and even if I knew, I don't see anywhere how many API CALLS I have for having O365 Standard

**Comment by MSFTMan** [comment]
@phillipharding Thanks for reporting this issue. We've updated the performance profile section of this doc to provide more details: https://docs.microsoft.com/en-us/power-automate/limits-and-config#performance-profiles
