### ISSUE TITLE
Detailed Spec for each parameters

### ISSUE THREAD

**Issue by chris-han** [MicrosoftDocs/power-automate-docs#357]
[Enter feedback here]
Can we provide more details such as:
what expression syntax it support, regular expression?
how to express special characters such as a space?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecff9ff1-2172-e57c-cede-7bed05cfede8
* Version Independent ID: b1af9741-0c06-e359-3c4b-27bfd993877d
* Content: [File | Microsoft Docs - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/desktop/actions-reference/file#renamefiles)
* Content Source: [articles/ui-flows/desktop/actions-reference/file.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/desktop/actions-reference/file.md)
* Service: **flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
@chris-han Thank you for the feedback. We have added this information and will be live soon.
