### ISSUE TITLE
This page says Edge is supported.  Does this include the old (pre-Chromium) Edge?  We should specify this.

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/power-automate-docs#358]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8988e5d9-a986-020a-1012-b474a0573250
* Version Independent ID: 43d4cc08-f0b9-fa11-cae9-b7ec1fafbd67
* Content: [Automation in the web - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/desktop/automation-web)
* Content Source: [articles/ui-flows/desktop/automation-web.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/desktop/automation-web.md)
* Service: **flow**
* GitHub Login: @rokontol
* Microsoft Alias: **rokontol**

**Comment by HinaMS** [comment]
For browsers, this page says Edge is supported.  Does this include the old (pre-Chromium) Edge?  We should specify this.

**Comment by MSFTMan** [comment]
@HinaMS We don't call out the versions because it's not version-specific. Thanks for using Power Automate.

**Comment by HinaMS** [comment]
I confirmed with Engineering team and this is the answer that i got "The browser extension for Microsoft Edge only supports the chromium-based browser" , I am not sure if its good to specify it in public doc, please confirm PM etc. and let me know .
