### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/power-automate-docs#359]
For browsers, this page : https://docs.microsoft.com/en-us/power-automate/ui-flows/desktop/automation-web  ,  says Edge is supported.  Does this include the old (pre-Chromium) Edge?  We should specify this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8988e5d9-a986-020a-1012-b474a0573250
* Version Independent ID: 43d4cc08-f0b9-fa11-cae9-b7ec1fafbd67
* Content: [Automation in the web - Power Automate](https://docs.microsoft.com/en-us/power-automate/ui-flows/desktop/automation-web)
* Content Source: [articles/ui-flows/desktop/automation-web.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/ui-flows/desktop/automation-web.md)
* Service: **flow**
* GitHub Login: @rokontol
* Microsoft Alias: **rokontol**

**Comment by rokontol** [comment]
Thanks for the comment, we'll link to this information in the article. Apologies for the delay.

**Comment by MSFTMan** [comment]
@HinaMS Thanks for reporting this issue. The Chromium-based version is required. We'll update document shortly to reflect that.
