### ISSUE TITLE
BotRequestFailed Error

### ISSUE THREAD

**Issue by NightGreyMoon** [MicrosoftDocs/power-automate-docs#360]
[Enter feedback here]

Keep getting this error:
The request failed. Error code: 'BotRequestFailed'. Error Message: 'Request to the Bot framework failed with error: '{"error":{"code":"BotNotInConversationRoster","message":"The bot is not part of the conversation roster."}}'.'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf788f3b-9ad6-3c79-689d-5f36c1ab292f
* Version Independent ID: d8a78d1d-7f90-7fb1-b0f6-8ae6518031f1
* Content: [Create flows that post adaptive cards to Microsoft Teams - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-adaptive-cards)
* Content Source: [articles/create-adaptive-cards.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/create-adaptive-cards.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@NightGreyMoon — Thanks for your feedback.  This sounds like a product issue. For product-related feedback, visit https://ideas.flow.microsoft.com.  

Closing this issue.
