### ISSUE TITLE
Can't find Power Automate - 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/power-automate-docs#361]
When I do a search for Power Automate in 2 different tenants, it is not found. Flow is found. Please add something to the documentation about what to expect and how this can be confusing
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d0e2ad1-d98d-6b2d-0505-9121e1f9ff60
* Version Independent ID: e7dcc8f2-2111-02ce-4254-63e4f007e2ee
* Content: [Install the Power Automate App in Microsoft Teams - Power Automate](https://docs.microsoft.com/en-us/power-automate/teams/install-teams-app)
* Content Source: [articles/teams/install-teams-app.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/teams/install-teams-app.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **hamenon**

**Comment by MSFTMan** [comment]
@DeanGross Thanks for your feedback. The steps in this document are intended to be carried out in Microsoft Teams. I just tried searching in **More added apps** in Microsoft Teams for 'Power Automate', and I found  Power Automate app. Kindly try searching and Microsoft Teams. Do let us know if your experience is different.

**Comment by DeanGross** [comment]
thanks, it is showing up for me now, it must have been fixed in the past 2 months
