### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by ImkeF** [MicrosoftDocs/power-automate-docs#363]
Hi there,
there is a wrong field in the approval flow: https://docs.microsoft.com/en-us/power-automate/modern-approvals

![image](https://user-images.githubusercontent.com/18321412/101238567-6aaa0180-36e1-11eb-8d2e-675152cca7e4.png)

**Comment by MSFTMan** [comment]
@ImkeF Thanks for reporting this issue. It's now fixed.
