### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by PekkaJalonen** [MicrosoftDocs/power-automate-docs#365]
Links are pointing to 404 not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd4366d9-2275-80aa-3ba6-195a234d45f4
* Version Independent ID: 11726543-8d63-c7e4-00b7-c715110b6032
* Content: [Overview of Process Advisor (preview) - Power Automate](https://docs.microsoft.com/en-us/power-automate/process-advisor-overview)
* Content Source: [articles/process-advisor-overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/process-advisor-overview.md)
* Service: **flow**
* GitHub Login: @nijemcevic
* Microsoft Alias: **tatn**

**Comment by MSFTMan** [comment]
@PekkaJalonen Thanks for reporting this issue. The fix will be avilable in the next 3 hours.
