### ISSUE TITLE
How do I track if my Flow Template gets approved?

### ISSUE THREAD

**Issue by avijitghosh77** [MicrosoftDocs/power-automate-docs#366]
I have submitted couple of flow from my EY corporate account. However I do not a way to track the approval.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8d0d2-3a6f-c3f1-494d-b0ea73c22f9b
* Version Independent ID: 41bc35b2-5a4d-7406-1ae7-27b292033fcd
* Content: [Submit a cloud flow template - Power Automate](https://docs.microsoft.com/en-us/power-automate/publish-a-template)
* Content Source: [articles/publish-a-template.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/publish-a-template.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by Dean-Haas** [comment]
@PriyaKodukula  - is it possible to track template status? The topic says: "If the team approves your template, it appears in the gallery of templates for Power Automate.", but is the customer notified? We should clarify in the topic. 

@avijitghosh77 - thanks for submitting docs feedback.

**Comment by PriyaKodukula** [comment]
Adding Customer retention team to track this.

**Comment by MSFTMan** [comment]
@avijitghosh77 Thanks again for your question. Did your templates get approved?

**Comment by v-aangie** [comment]
@sunaysv — I added you as an assignee since you are the author of the doc. The customer is asking if is it possible to track template status. The topic says: "If the team approves your template, it appears in the gallery of templates for Power Automate.", but is the customer notified? We should clarify in the topic. Thank you.

**Comment by sunaysv** [comment]
Please re-assign this issue to the Power Automate team.

Thanks,
Sunay

**Comment by MSFTMan** [comment]
@avijitghosh77 Thanks for your feedback. This question was forwarded to the customer retention team.  You may want to create a feature request on the Power Automate ideas site: https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas Closing this issue.
