### ISSUE TITLE
Flow is now Power Automate

### ISSUE THREAD

**Issue by mikemorrison111** [MicrosoftDocs/power-automate-docs#367]
The pages needs an update. Flows was renamed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3429a9-84f0-0c7a-158b-6fb6ced457ab
* Version Independent ID: 8232b831-10f7-d59d-3dd9-a1e288b2c2ed
* Content: [Learn to create and manage flows in Microsoft Teams - Power Automate](https://docs.microsoft.com/en-us/power-automate/flows-teams)
* Content Source: [articles/flows-teams.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/flows-teams.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
@mikemorrison111 - thanks for submitting this. The topic has been updated, and should be published soon,  once reviewed.
