### ISSUE TITLE
Misleading/Missing information on editing UI Elements

### ISSUE THREAD

**Issue by briangre** [MicrosoftDocs/power-automate-docs#368]
This page talks about editing UI Elements, but neither has a link to docs on how to do it or the instructions to do it. One must click View, then click UI Elements in order to get the window where editing is possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccc9f94e-5baf-8a02-bdf7-480e456032c6
* Version Independent ID: 5fe4e7a9-51cc-9116-faa0-bdab46d0b2c6
* Content: [UI elements and controls - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/ui-elements)
* Content Source: [articles/desktop-flows/ui-elements.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/ui-elements.md)
* Service: **flow**
* GitHub Login: @rokontol
* Microsoft Alias: **rokontol**

**Comment by mariosleon** [comment]
@briangre We have added the content as you suggested. Closing the issue.
