### ISSUE TITLE
Duplicated line on page

### ISSUE THREAD

**Issue by tababcoc** [MicrosoftDocs/power-automate-docs#369]
Hi,

This line, "Terminates the loop and the flow resumes at the next action or statement following the loop," is included twice on this page, once at the very top and once under the heading Exit loop. I think you meant only the second appearance.

Ted Babcock

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2410c8e2-2a31-7fd4-abb4-7e613fd9b66a
* Version Independent ID: eed68fc9-2ee7-97af-ecae-db3372a1794c
* Content: [Loops - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/loops)
* Content Source: [articles/desktop-flows/actions-reference/loops.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/actions-reference/loops.md)
* Service: **flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by MSFTMan** [comment]
@tababcoc Thanks for reporting this issue. It is now fixed.
