### ISSUE TITLE
What are the before and after drop-downs in the Options for Automatic Processes mean

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/power-automate-docs#37]
I see these in the UI, but I didn't find mention of them in this content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee23cfb-7825-0b52-8c94-4070a47b4f49
* Version Independent ID: 4fb1373c-7a28-3b4e-691b-dc778660d65f
* Content: [Classic Common Data Service (CDS) for Apps workflows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/workflow-processes)
* Content Source: [flow-docs/workflow-processes.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/workflow-processes.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by JimDaly** [comment]
Including a screenshot of what I mean.
![image](https://user-images.githubusercontent.com/6353736/48320955-abeb8800-e5d3-11e8-9ba9-08cc56e6aeb1.png)
I think these must be new. 
Also, there doesn't seem to be any option that I can select that will enable any but the middle option.
I suspect that they are similar to the pre-validation, pre-operation, and post-operation steps available for a plug-in. 
Documentation should call out what these are for.

**Comment by MSFTMan** [comment]
@JimDaly Thanks for reporting this issue. I'm following up with the team and will get back to you.

Thanks,
Deon

**Comment by JimDaly** [comment]
@MSFTMan 
Deon I think I've figured most of this out.

The option that corresponds to **Record is created** is not editable and it is always set to **After**. This indicates that the operation is performed in the **PostOperation** stage of the [Event execution pipeline](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/event-framework#event-execution-pipeline). This makes sense because the entity won't have a unique identifier until after the internal **MainOperation** stage.

The **Record status changes**, **Record is assigned**, and **Record fields change** options all correspond to **Update** operations and provide the ability to specify either **After** or **Before**.

- **Before** corresponds to the **PreOperation** stage
- **After** corresponds to the **PostOperation** stage. This is the default value.

The **Record is deleted** option is not editable and is set to **Before** which corresponds to the **PreOperation** stage because after the MainOperation, the entity will be deleted and there is nothing you can do with it after it is deleted.

So the only remaining question is why you would choose **Before** or **After** for an **Update** operation?

Generally, you don't want to make changes to the entity in the **PostOperation** stage because this should trigger a new Update event. Changes to entity values should be done in the **PreOperation** stage.

The **PostOperation** stage would be better for applying any other changes.

**Comment by Dean-Haas** [comment]
@JimDaly Thanks for your feedback here as well. Can you clarify whether you think the documentation needs to be updated or added? The same applies to your related issue. Thanks!
