### ISSUE TITLE
Error in content

### ISSUE THREAD

**Issue by FranklinD10** [MicrosoftDocs/power-automate-docs#370]
[Mistake in the content
![image](https://user-images.githubusercontent.com/54560710/103279477-c8bac380-49c5-11eb-8c4f-7f87e0185ec3.png)
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6870e9fe-dca9-66a8-1cd0-0000b83f385c
* Version Independent ID: ca5edb5e-80c3-05ef-b5aa-7c607f5cc706
* Content: [Overview of the types of flows in Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/flow-types)
* Content Source: [articles/flow-types.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/flow-types.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
@FranklinD10 Thanks for submitting this. We'll get it fixed right away.
