### ISSUE TITLE
The information share on this page, like 'Share' button, its not available to test , when will it be available to test in our tenant

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/power-automate-docs#371]
The information share on this page, like 'Share' button, its not available to test , when will it be available to test in our tenant to test . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae761774-78a1-83be-4f75-18ff7ad9074d
* Version Independent ID: f6f4a32d-f5af-3e07-9178-a65547039c3b
* Content: [Share and manage desktop flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/manage?source=docs)
* Content Source: [articles/desktop-flows/manage.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/manage.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@HinaMS Thank you for reporting this issue. I tried the steps (https://docs.microsoft.com/en-us/power-automate/desktop-flows/manage?source=docs#share-desktop-flows) to share a **Desktop flow** and they worked fine. I see the **Share** button. Please try again. If this doesn't work, let us know exactly which step doesn't work. Feel free to send a screenshot as well so we can help identify the issue.
