### ISSUE TITLE
GCC and DOD Public IP Address including Loopback address (127.0.0.1)

### ISSUE THREAD

**Issue by SteveWinward** [MicrosoftDocs/power-automate-docs#372]
The GCC and DoD public IP Address documentation is including the loopback IP address (127.0.0.1) and should be removed from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config#ip-addresses)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@SteveWinward  Thanks for reporting this issue. It's now fixed.
