### ISSUE TITLE
A couple of suggestions.

### ISSUE THREAD

**Issue by flintuser** [MicrosoftDocs/power-automate-docs#373]
Add actions and conditions Step 5:
**Condition 2** Importance is equal to "High" the 'H' is capitalized in the instructions and it didn't work for me until I used lowercase 'h' in "high".  I'm newer to flows so maybe I did something wrong.

Add actions and conditions Step 8: 
There is a number 2 over "Add an action" implying there should be a second step here.  I assume it was supposed to be to add a **Mark as read or unread** step.

Otherwise, thanks for the help getting started with flows!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39d79925-8b72-d4b0-e3fb-1b9164ecaaf3
* Version Independent ID: 06c8759f-1adf-470f-bdba-1f3af6f0a523
* Content: [Use the apply to each action to loop through an array of items. - Power Automate](https://docs.microsoft.com/en-us/power-automate/apply-to-each)
* Content Source: [articles/apply-to-each.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/apply-to-each.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@flintuser  These issues are fixed. You'll see them in the live docs within a few hours. Welcome to Power Automate!
