### ISSUE TITLE
Misleading Screenshots that show far better information than is actually in Flow

### ISSUE THREAD

**Issue by cameron0208** [MicrosoftDocs/power-automate-docs#374]
You are misleading consumers with the screenshots included in the section titled "Identify the error". I have never received an error message that helpful and I am an above average user that uses flow every single day. Either way, I'd like to know why I get error messages such as this:

![image](https://user-images.githubusercontent.com/55471049/103520372-a8af5800-4e3c-11eb-9b4a-8b5f1badfe3f.png)

The helpful advice from the Flow team to fix the error, just in case you missed it: **"To make this flow work, inspect the inputs"**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d04539c-cf39-3ab2-7ee2-5141e6a5bf89
* Version Independent ID: 81a19210-725f-17a7-238e-1ff3ffe14d23
* Content: [Troubleshooting a cloud flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/fix-flow-failures)
* Content Source: [articles/fix-flow-failures.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/fix-flow-failures.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dean-Haas** [comment]
Hi @cameron0208 . Thanks for submitting docs feedback. The screenshot in the topic is for a common authentication failure scenario. For help figuring out your specific issue, see the sections in the topic [Getting help from support or the community](https://docs.microsoft.com/en-us/power-automate/fix-flow-failures#getting-help-from-support-or-the-community) and [Ask for help from others](https://docs.microsoft.com/en-us/power-automate/fix-flow-failures#ask-for-help-from-others)
