### ISSUE TITLE
How do I find out the Power Automate license that I have?

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/power-automate-docs#375]
Hi, when I follow the instructions: "How does an individual find out what plan they are on?  Anyone can see the plan they have by visiting the Power Automate pricing page at https://flow.microsoft.com/pricing. The plan or trial they are currently on will be shown there." However, the linked pricing page doesn't show the plan I have, it just lists all available licenses and pricing.  Is this a feature that's coming soon or are the instructions incorrect?  How do I find out the Power Automate license that I have?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c23aa79-64e4-9488-b528-af781d7b456e
* Version Independent ID: aacc4f60-044f-d587-9dde-8a48168c59e7
* Content: [Power Automate sign-up Q&A in your organization - Power Automate](https://docs.microsoft.com/en-us/power-automate/organization-q-and-a)
* Content Source: [articles/organization-q-and-a.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/organization-q-and-a.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@HandyAndyOnGitHub Thanks for reporting this issue. This has been fixed. You will see the steps in a few hours. Here are the steps:

1. Sign into https://powerautomate.com.
1. Select your profile picture in the top right corner of the screen.
1. Select **View account**.
1. Select the **Subscriptions** tile.
1. Search for **Power Automate** under the **Licenses** section.
