### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by jamilhaddadin** [MicrosoftDocs/power-automate-docs#376]
Examples would make our life easiery! i spent 10 minutes trying to understand how to get the Datetime.Now() equivalent but could not succeed. I figured it out later but this was not an easy job :-) examples would cut those 10 mins to 10 seconds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6187c3e6-5b3e-4b5c-05eb-6f4c7612570f
* Version Independent ID: 7776f0e2-a633-b29d-0f67-4607aedc5472
* Content: [Datetime - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/datetime)
* Content Source: [articles/desktop-flows/actions-reference/datetime.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/actions-reference/datetime.md)
* Service: **flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
@jamilhaddadin  Thanks for your feedback. We always look for these and find ways to make the docs easier to follow.
