### ISSUE TITLE
Column set example needed

### ISSUE THREAD

**Issue by lfinman** [MicrosoftDocs/power-automate-docs#377]
Can you provide an example of passing array data to be displayed in the Column Set?  The screenshot of 'SharePoint list of change orders' is quite impressive, but the description and provided card JSON do not explain how to provide an array and have it populate the columns.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 948d800d-ba05-4a3d-6dc3-63a06d5786d5
* Version Independent ID: 8189a27b-5fd1-a319-fd79-b56f0d2267ee
* Content: [Adaptive Cards metadata update card sample - Power Automate](https://docs.microsoft.com/en-us/power-automate/metadata-update-sample)
* Content Source: [articles/metadata-update-sample.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/metadata-update-sample.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@lfinman Thanks for your suggestion. We will get this updated.

**Comment by v-aangie** [comment]
@lfinman - Thanks for your feedback. We have placed this issue in our backlog and will address it soon. Closing the issue.
