### ISSUE TITLE
Programmatically moving between Stages

### ISSUE THREAD

**Issue by woodyarray** [MicrosoftDocs/power-automate-docs#378]
If I interpret the documentation correctly, you can set the active stage to the next or previous stage.

But what if I have a condition after a stage? I can't set the stage (programmatically within my external flow) without replicating the condition logic.

How about having an option to set the current stage as complete, then the BPF can process the condition to determine the next stage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a13ad7f-5f83-d1d4-0d33-0a7842aea1de
* Version Independent ID: 792cbd63-a2d0-5793-bb62-55835392b977
* Content: [Work with business process flows using code - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/business-process-flows-code)
* Content Source: [articles/developer/business-process-flows-code.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/developer/business-process-flows-code.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@woodyarray Thanks for your suggestion. The product team uses https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas to track ideas. Kindly consider making your suggestion there. Thanks!
