### ISSUE TITLE
Add details about sharing with external users

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/power-automate-docs#379]
This document (or perhaps a separate document) should highlight that it is possible to share flows with external users (Guest AAD B2B users) & should show the process needed to sharing flows in this manner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to share a cloud flow with other users - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-team-flows)
* Content Source: [articles/create-team-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@kilasuit - Thanks for your feedback. We believe this link to our docs resolves your issue - https://docs.microsoft.com/en-us/power-automate/modern-approvals#request-approvals-from-guest-users. Closing the issue.
