### ISSUE TITLE
admin center link is broken

### ISSUE THREAD

**Issue by aliyoussefi** [MicrosoftDocs/power-automate-docs#380]
The admin center link is broken and resolves to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6f8b36-0101-6ccd-142d-184db1143ddc
* Version Independent ID: eccbac6f-0382-f295-6e0d-48f29c093982
* Content: [View desktop flows analytics in the Power Platform admin center - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/overview-analytics#feedback)
* Content Source: [articles/desktop-flows/overview-analytics.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/overview-analytics.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@aliyoussefi Thanks for reporting this issue. We fixed it a few days ago.
