### ISSUE TITLE
Markdown doesn't work for teams approvals

### ISSUE THREAD

**Issue by stinethebean** [MicrosoftDocs/power-automate-docs#382]
Hi team! I'm using approvals in a PowerAutomate. As part of my approval content, I have MarkDown content. The Markdown is 'translated' properly when the approval comes through via email, but it doesn't work in teams. 

Is there a way I can disable teams notifications while the Markdown support is lacking?

Christine

![Approval in PowerAutomate](https://user-images.githubusercontent.com/5238880/105114562-f43c4580-5a7b-11eb-8676-871ef3ca85e8.png)
![Approval comes through in Outlook](https://user-images.githubusercontent.com/5238880/105114569-f69e9f80-5a7b-11eb-86ec-8baa2530edfa.png)
![Approval comes through in Teams](https://user-images.githubusercontent.com/5238880/105114580-f9999000-5a7b-11eb-9579-69e3bd441fe1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by stinethebean** [comment]
Note, updated my issue - most of it was due to my poor initial reading of the documentation.

**Comment by charlesnorman2** [comment]
Hi, I am having the same issue between Outlook and Teams.  Can you share what you changed to get it working in Teams?

Thanks,
Charles

**Comment by stinethebean** [comment]
It isn't supported in teams :( - no solution.

**Comment by charlesnorman2** [comment]
Well that's a bummer.  Thanks for the quick response :)
