### ISSUE TITLE
Are custom controls in a BPF still in preview?

### ISSUE THREAD

**Issue by jlattimer** [MicrosoftDocs/power-automate-docs#383]
If not, this page probably should not reference a blog post written when it was only in preview. 

Would be less confusing to remove the link and add the content to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 792c0e95-24ac-c787-6549-d778dfd86b12
* Version Independent ID: 8e67638d-5793-2554-2372-168c2e2eb866
* Content: [Use custom controls in business process flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/custom-controls-business-process-flows)
* Content Source: [articles/custom-controls-business-process-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/custom-controls-business-process-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@jlattimer  Thanks for reporting this issue. I'll confirm and update the page as necessary.

**Comment by RedsGT** [comment]
It's now 4 months later and the same confusion is now made worse with the deprecation of the Flip Label in 2021 Wave 1 per [Action required by you](https://docs.microsoft.com/en-us/power-platform/important-changes-coming#action-required-by-you-2).   
Can we get this actioned please? @jhauppams1 @shsasi
