### ISSUE TITLE
Documentation for Power Automate needs to be updated to include the power automate gateway

### ISSUE THREAD

**Issue by jimmylin829** [MicrosoftDocs/power-automate-docs#385]
The current documentation makes no mention of the Power Automate Gateway as a requirement.  Please update the documentation to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482ae90c-6a0a-f8c6-05cb-660ad43ba0e0
* Version Independent ID: 770951a1-ea51-bb85-f6a3-f7d9148510a5
* Content: [Create a Power Automate Desktop flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/create-flow)
* Content Source: [articles/desktop-flows/create-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/create-flow.md)
* Service: **flow**
* GitHub Login: @olegmelnykov
* Microsoft Alias: **olmelnyk**

**Comment by QuentinSele** [comment]
There is a specific section here: 
https://docs.microsoft.com/en-us/power-automate/desktop-flows/setup#install-the-on-premises-data-gateway-to-run-your-desktop-flows-from-the-cloud

**Comment by KumarVivek** [comment]
@jimmylin829 We have added the content as you suggested. Closing the issue.
