### ISSUE TITLE
Unable to change flow status/Turn on

### ISSUE THREAD

**Issue by Seshan-Dixit** [MicrosoftDocs/power-automate-docs#388]
Hi there,

I have been trying to turn on flow from PowerShell script and also from c# but  every time I try to run my code I get this below issue.

I am using Service principal user for this.

![image](https://user-images.githubusercontent.com/77995039/105859025-0be27380-6012-11eb-8ce1-e7007ddb0fc7.png)

Doesn't matter what ever I do, this doesn't seem to be working but strange thing is I am able to turn flow on/off in postman.

Can anyone please help on this, it is big blocker for me.

**Comment by MSFTMan** [comment]
@Seshan-Dixit Thanks for using Power Automate. This issue sounds specific to your scenario. Kindly contact Microsoft Support for help: https://preview.flow.microsoft.com/en-us/support/. This forum is for documentation issues only.
