### ISSUE TITLE
What to fill in Scope field?

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/power-automate-docs#389]
The Dataverse connector needs a Scope filled, but it's unclear where the value for it should come from. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f7b3337-c547-4960-fa13-ca16a559b083
* Version Independent ID: 9b02414f-872e-14da-71c6-bd68fbb0e23e
* Content: [Microsoft Dataverse - Power Automate](https://docs.microsoft.com/en-us/power-automate/common-data-model-intro)
* Content Source: [articles/common-data-model-intro.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/common-data-model-intro.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@algattik - Thanks for your feedback. In https://docs.microsoft.com/en-us/power-automate/common-data-model-intro#customize-your-flow-template, we've added a link to https://docs.microsoft.com/en-us/power-automate/dataverse/create-update-delete-trigger#scope for more information on scope. The doc will be live later today. Closing this issue.
