### ISSUE TITLE
Create business process flow from https://web.powerapps.com/.

### ISSUE THREAD

**Issue by JaKovac87** [MicrosoftDocs/power-automate-docs#39]
Unable select solution, can only create with prefix new_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dad73cd-63b8-b3e3-dc37-c48dbad9205f
* Version Independent ID: 8e8cf5c4-5ec6-8c57-f97c-41841296de8c
* Content: [Add an on-demand workflow to a business process flow - Microsoft Flow](https://docs.microsoft.com/en-us/flow/bpf-add-on-demand-workflow)
* Content Source: [flow-docs/bpf-add-on-demand-workflow.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/bpf-add-on-demand-workflow.md)
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by KumarVivek** [comment]
@MSFTMan Can you please look into this issue.

**Comment by MSFTMan** [comment]
@JaKovac87 Thanks for reporting this issue. We are not able to reproduce this issue. Kindly let us know if you can still reproduce this. Thanks!
