### ISSUE TITLE
Different IP ranges listed in separate pages

### ISSUE THREAD

**Issue by unearthnz** [MicrosoftDocs/power-automate-docs#391]
Hi there - I am after the IP ranges that Power Automate (Australian tenant) uses to make an outbound request (in this case, the SFTP connector). I can see two pages that detail this, but they have differing info - can you please confirm which is correct, and look consolidate the info to one page? Or am i misunderstanding the context and they are used in different scenarios?

https://docs.microsoft.com/en-us/power-automate/ip-address-configuration#connectors
https://docs.microsoft.com/en-us/power-automate/limits-and-config#ip-addresses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@unearthnz - Yes, kindly use the information in both documents. We will consider combining them in the future. Closing this issue.
