### ISSUE TITLE
Missing information as location of the settings button as the reference to the request limits

### ISSUE THREAD

**Issue by BillyCottrell** [MicrosoftDocs/power-automate-docs#392]
Hi there,

I was looking around to see what the limits are for using flow but for as far I have seen in the community people are giving different values, so I don't know what limits there are with all the changes going on lately and such.
So that's why I came to this page and since there was a section explaining this I thought that it would be usefull, but it only says for free plans to click on a settings button as shown on the picture but not which settings button that actually is and where to find it. Also, the picture doesn't explain anything about where or on what page you can find this button.

Because is this the settings button from power automate because it isn't showing anything related, or is it from powerapps homepage or from within a powerapp or is this from dynamics? Honestly I have no clue where I am supposed to look. I would add a caption or something like that to this image so that you can display more information about the location of the settings button.

I would also refer to the following page, so users can easily calculate those limits in case they don't know where to look:
https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#request-limits-based-on-user-licenses

This way it's easier to find the information that the user is looking for.

Thanks in advance!

Kind regards,

Billy Cottrell

PS: If I'm too aggressive or too "pushy" in my speech or so my apologies, I just think that documentation is really crucial for everyone, so when things are missing in my opinion I might get a bit harsh here and there, without me noticing it. So again my apologies!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1947fd4e-170f-6392-e309-5fd05082ffb8
* Version Independent ID: 79ccd9e1-0998-bc4e-004c-ffbe57291196
* Content: [Billing and metering questions - Power Automate](https://docs.microsoft.com/en-us/power-automate/billing-questions#feedback)
* Content Source: [articles/billing-questions.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/billing-questions.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@BillyCottrell Thanks for sharing your thoughts. We will look into this issue and update the docs.

**Comment by MSFTMan** [comment]
@BillyCottrell We've update the document to clarify that you must first sign into Power Automate before you see the settings button.
