### ISSUE TITLE
Do you think you could mention or at least refer to the various time outs that apply here?

### ISSUE THREAD

**Issue by dexblack** [MicrosoftDocs/power-automate-docs#393]
According to various forum comments there are time outs relevant to the configuring of Data Connections in PowerAutomate that are not mentioned AT ALL on this page.
Perhaps you could remedy that oversight. Furthermore, please consider whether such timeouts are of any real use to anybody?
In my professional opinion this should at the very least be part of the connection configuration UI and have a few specific options, one of which is "Only expire token if the account password is changed or the account is disabled."
This will also mean that if the user changes their password the existing access token information, along with links to the relevant PowerAutomate Flows should be immediately emailed to the user who changed their password or the person who disabled the account.

Think about the user here people. THINK.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bf9b6c-5628-f18c-7027-45b21eb3b6bc
* Version Independent ID: a4394ad5-9d46-2a6d-16d9-48b0c88fb401
* Content: [Learn to connect to your data using connections and on-premises data gateways - Power Automate](https://docs.microsoft.com/en-us/power-automate/add-manage-connections)
* Content Source: [articles/add-manage-connections.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/add-manage-connections.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by v-aangie** [comment]
@dexblack - Thanks for the feedback. You can find the limits here - https://docs.microsoft.com/en-us/power-automate/limits-and-config#gateway-limits. We'll update the document with the link to https://docs.microsoft.com/en-us/power-automate/limits-and-config#gateway-limits. 

For your product-related feedback, visit https://ideas.flow.microsoft.com. Closing this issue.
