### ISSUE TITLE
Performance Profile information not showing as documented

### ISSUE THREAD

**Issue by crowcoder** [MicrosoftDocs/power-automate-docs#395]
I can't find the performance profile information for a flow. Is this old information?: "You can see your performance profile by selecting Export on your flow and seeing the performance profile for your flow"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@crowcoder Thanks for reporting this issue. We'll investigate and update this issue with a response.

**Comment by MSFTMan** [comment]
@ChrisGarty Please take a look. I confirmed that I don't see the performance info when I export a flow.

**Comment by MSFTMan** [comment]
@crowcoder Thanks for reporting this issue. It's fixed. You will see the update in 6 hours.

**Comment by lgmsmm** [comment]
Same issue here, We have Office 365 Standard licenses, I can't see wich profile is my flow, and even if I knew, I don't see anywhere how many API CALLS I have for having O365 Standard
