### ISSUE TITLE
Markdown doesn't work at all in Teams

### ISSUE THREAD

**Issue by gerradferrier** [MicrosoftDocs/power-automate-docs#396]
[Enter feedback here]
Hello,

I've tried all possible ways that your markdown documentation says to get approvals in teams looking decent but none of the options actually work. They do work in outlook and outlook online.
I checked the compatibility and it tells me line breaks and lists should work but they dont.

please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support#lists)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by MSFTMan** [comment]
@gerradferrier  Thanks for sharing your feedback. This sounds like an issue with the product. I'll pass this on to the product team for it to be addressed.

**Comment by v-aangie** [comment]
@gcorvera — This sounds like an issue with the product. Can you please address this?

**Comment by MSFTMan** [comment]
@hamenon-ms Kindly take a look at this issue.

**Comment by v-aangie** [comment]
@gerradferrier - Thanks for your feedback. Forced line breaks are not supported in tables. We have updated https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support, and the updated content will be live on Tuesday. Closing this issue.

**Comment by gerradferrier** [comment]
Great, thanks Angie.



Gerrad Ferrier
+44 7468694009
>  Please consider the environment and avoid printing this email



Classification - Public
