### ISSUE TITLE
Can't find the settings that be wrote on this document.

### ISSUE THREAD

**Issue by yan0020** [MicrosoftDocs/power-automate-docs#397]
This document is wrote following sentence under the "Maximum waiting runs". But we can't find the settings on the setting of the trigger.
"You can change the maximum number up to 100 inclusively."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@yan0020 Thanks for reporting this issue. We'll investigate and make a doc update as needed.

**Comment by MSFTMan** [comment]
@yan0020 Thanks for reporting this issue. You set it in the settings for the trigger under the **Concurrency Control** section. It's fixed in the docs as well. You'll see it in the docs in a few hours.
