### ISSUE TITLE
Duplicate sections in document.

### ISSUE THREAD

**Issue by phatmandrake** [MicrosoftDocs/power-automate-docs#400]
The following  sections are duplicated.

"Action Request Limits"
"Runtime endpoint request limits"
"Content throughput limits"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@phatmandrake Thanks for your feedback. We've removed the duplicated sections. You'll see this update publicly after our next release.
