### ISSUE TITLE
Teams Desktop & Web - Markdown Not Honoured

### ISSUE THREAD

**Issue by BH-BP** [MicrosoftDocs/power-automate-docs#401]
The documentation details that Teams should support the following elements of markdown:

- Numbered Lists
- Nested Numbered Lists
- Forced Line Breaks

However, even when copying the example code, the markdown formatting is being ignored in Teams (Desktop & Web). The formatting is rendering correctly on other clients (i.e. Outlook).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by MSFTMan** [comment]
@hamenon-ms Kindly take a look at this issue.

**Comment by MSFTMan** [comment]
@BH-BP Thanks for reporting this issue. We'll track the resolution in this issue: https://github.com/MicrosoftDocs/power-automate-docs/issues/396. Closing this issue.
