### ISSUE TITLE
PDF download link broken

### ISSUE THREAD

**Issue by JerryCRMI** [MicrosoftDocs/power-automate-docs#407]
Hi,

The Download PDF link in the lower left hand corner of the page (in fact for all the learning pages in this series) returns a 404 page not found.

Jerry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06f994bd-101c-7c60-486e-92e0b3e16160
* Version Independent ID: 67ff2c96-622e-0820-2492-eacaddb071a1
* Content: [Planning phase for a Power Automate project - Power Automate](https://docs.microsoft.com/en-us/power-automate/guidance/planning/planning-phase?source=docs)
* Content Source: [articles/guidance/planning/planning-phase.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/guidance/planning/planning-phase.md)
* Service: **flow**
* GitHub Login: @taiki-yoshida
* Microsoft Alias: **tayoshi**

**Comment by MSFTMan** [comment]
@JerryCRMI Thanks for reporting this issue. We'll get this fixed and released ASAP.
