### ISSUE TITLE
Roadmap Insights to US Gov/GCC

### ISSUE THREAD

**Issue by bobbyschang** [MicrosoftDocs/power-automate-docs#408]
Can you please share timeline of this Power Automate app being available to US Government/GCC?  Working with several US Gov customers noting that this is missing on their tenant.  Can you please help clarify?  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3429a9-84f0-0c7a-158b-6fb6ced457ab
* Version Independent ID: 8232b831-10f7-d59d-3dd9-a1e288b2c2ed
* Content: [Learn to create and manage flows in Microsoft Teams - Power Automate](https://docs.microsoft.com/en-us/power-automate/flows-teams#feedback)
* Content Source: [articles/flows-teams.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/flows-teams.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@bobbyschang  Thanks for your feedback. All public information about roadmap are released here: https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/. This document is updated regularly. Thanks!
