### ISSUE TITLE
Duplicated content with other topic

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/power-automate-docs#41]
This topic and https://docs.microsoft.com/en-us/flow/configure-actions have much of the same content.
These should be merged into a single topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85bd6d61-8b2c-07bf-d5ff-3994c9cae6fb
* Version Independent ID: 29528b38-1581-aec7-5e15-0244cc307f2d
* Content: [Create a custom action - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-actions#feedback)
* Content Source: [flow-docs/create-actions.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-actions.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@JimDaly This issue is now resolved.
