### ISSUE TITLE
Add row for Emphasis to Client Support table

### ISSUE THREAD

**Issue by schumatt-msft** [MicrosoftDocs/power-automate-docs#410]
It would be helpful to include a row in the **Client Support** table for **Emphasis** since the support for this Markdown syntax, sadly, varies widely across clients.  For example, Teams does not render even simple emphasis like \*\*bold\*\* at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by MSFTMan** [comment]
@schumatt-msft  Thanks for your feedback. I've updated the docs. You'll see the updates after our next public releae.
