### ISSUE TITLE
Is HTML is not an Advanced option, Send an Email V2

### ISSUE THREAD

**Issue by ChrizK-oldGit** [MicrosoftDocs/power-automate-docs#411]
[Enter feedback here]
The formatting of the HTML table is very poor in the resulting eMail.
The columns are much too close together.

There is no options for Is HTML within the Advanced Options, as shown in the screen shot.

It would be very useful to have a link to page which provides instructions to format a table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33fd0a66-4a31-a543-6b4d-45a6b324b862
* Version Independent ID: d31ecdce-fb50-131e-8f4c-5558c01b1f12
* Content: [Top Office 365 Outlook scenarios - Power Automate](https://docs.microsoft.com/en-us/power-automate/email-top-scenarios)
* Content Source: [articles/email-top-scenarios.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/email-top-scenarios.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@ChrizK-oldGit Thanks for the feedback. We've updated the document to remove references to isHTML since isn't no longer needed. Consider posting your feedback about the HTML table rendering to here: https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas. Thanks!
