### ISSUE TITLE
Plz add requirement for an active internet network connection. Document is incomplete

### ISSUE THREAD

**Issue by MDelagram** [MicrosoftDocs/power-automate-docs#413]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67bfcee8-33a4-a706-5ef1-4d08174b3b32
* Version Independent ID: b1b9a4dd-db58-9f9d-ee65-9a590366d803
* Content: [Set up Power Automate Desktop on your device - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/setup#limitations)
* Content Source: [articles/desktop-flows/setup.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/setup.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@MDelagram Thanks for you feedback. I've updated the document. You see the update after our next public update of the document.
