### ISSUE TITLE
Update Limitations for Power Platform GCC

### ISSUE THREAD

**Issue by rocamp** [MicrosoftDocs/power-automate-docs#415]
Please specify in the **Power Automate US Government feature limitations** section under the Connectors limitation that all 3rd party services are not enabled in GCC High due to a missing feature preventing it.

**Power Automate US Government feature limitations**

Some of the features available in the commercial version of Flow are not available in Flow US Government customers. The Flow team is actively working on making these features available to US Government customers and will update this article when these features become available.

AI Builder is not yet available for GCC and GCC High tenants.

Approvals are available for GCC and GCC High tenants, subject to the following:

There is no actionable approval support. Approval emails will contain links to the Power Automate approvals center for users to respond.
There is no markdown support for approval email.
Submitting Templates

Connectors – The most popular connectors in use in our commercial service (based on usage telemetry) have been published; if there is a Connector available in the commercial offering that you do not see deployed, please contact support and we will review your request.

_All 3rd party services are not enabled in GCC High due to a missing feature preventing it._

Power BI – Power Automate US Government doesn’t support Power BI at this time.

Power Platform admin center – You can use the admin center to open support tickets, but other functionality is currently not available in US Government tenants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d0a9ce-bdc6-9f60-fecb-eb5cabfe21ee
* Version Independent ID: d2267099-da75-d3d7-77cf-af41fcc1cf1e
* Content: [Power Automate US Government - Power Automate](https://docs.microsoft.com/en-us/power-automate/us-govt)
* Content Source: [articles/us-govt.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/us-govt.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@rocamp  thanks for feedback. I'll disucss this with the product team and make updates as needed.
