### ISSUE TITLE
Concurrent edit of share PAD flows

### ISSUE THREAD

**Issue by hitendra72** [MicrosoftDocs/power-automate-docs#419]
Can we update the documentation to provide information on the behaviour if 2 users concurrently edit the same PAD flow which is shared between them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae761774-78a1-83be-4f75-18ff7ad9074d
* Version Independent ID: f6f4a32d-f5af-3e07-9178-a65547039c3b
* Content: [Share and manage desktop flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/manage)
* Content Source: [articles/desktop-flows/manage.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/manage.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by mariosleon** [comment]
@hitendra72  Thank you for the feedback. We have added this information and will be live soon.
