### ISSUE TITLE
Unable to Set Process Logs to Complete as Non-System Administrator

### ISSUE THREAD

**Issue by calechko** [MicrosoftDocs/power-automate-docs#420]
I am following the instructions under "Flow Step considerations" to mark the process complete.  This works perfectly when the flow is executed as a user with System Administrator permissions.  When I use an account with lower permissions, I get the following error:

"Unable to retrieve attribute=ownerid for entityLogicalName=asyncoperation. Entity has Attribute Count=2. AttributeNames= status, workflowlogid"

I have attached a screenshot.  I have reproduced this on multiple workflows and I also tried adding various permissions, but nothing seems to work.
![CRMError](https://user-images.githubusercontent.com/29961021/109514628-3e014e00-7a74-11eb-85bf-157dae837855.PNG)

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7759368-a61e-08ce-e24f-b43a200521dd
* Version Independent ID: 80c1d8d8-a995-1023-91f9-0a1fd687c5b6
* Content: [Create a business process flow in Power Apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-business-process-flow)
* Content Source: [articles/create-business-process-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/create-business-process-flow.md)
* Service: **flow**
* GitHub Login: @vashr
* Microsoft Alias: **vashr**

**Comment by MSFTMan** [comment]
@calechko Thanks for reporting this issue. It appears to be an issue with the product. For faster service, consider using the Support option listed here: https://preview.flow.microsoft.com/en-us/support/. I'll update this document as needed to reflect the permissions required for this action.
