### ISSUE TITLE
Incorrect action request limits based on entitlement for High entitlement 

### ISSUE THREAD

**Issue by NinhGreen123** [MicrosoftDocs/power-automate-docs#421]
The action request limits of high entitlement (Power Automate per flow plan) should be 15,000 actions per flow according to the documents: 
https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations
https://support.microsoft.com/en-us/topic/troubleshooting-slow-running-flows-2a51dcd6-0b21-33da-5ce8-1e908b1540ef

Currently, from this link: https://docs.microsoft.com/en-us/power-automate/limits-and-config#action-request-limits
It indicates 100,000 actions for High

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config#action-request-limits)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/limits-and-config.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@NinhGreen123 - Thanks for your feedback. We have updated the action request limits, and the updated content is live - https://docs.microsoft.com/en-us/power-automate/limits-and-config#action-request-limits. Closing this issue.
