### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by yoshinag** [MicrosoftDocs/power-automate-docs#423]
[フィードバックをこちらに入力してください]

```
- テキストを datetime に変換する
+ datetime をテキストに変換
```
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 263c52c4-e89d-2fa5-c8d5-d791e3a37350
* Version Independent ID: 9afb1a06-c257-07c7-f50a-6697a28a811b
* Content: [テキスト | Microsoft Docs - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/desktop-flows/actions-reference/text)
* Content Source: [articles/desktop-flows/actions-reference/text.md](https://github.com/MicrosoftDocs/power-automate-docs.ja-JP/blob/live/articles/desktop-flows/actions-reference/text.md)
* Service: **flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by MSFTMan** [comment]
@yoshinag Thanks for reporting this issue. 

@mariosleon  here is the translation:

![image](https://user-images.githubusercontent.com/9972157/109859194-8bff8880-7c11-11eb-9689-2b9c03beb7a4.png)

**Comment by jowilco** [comment]
@yoshinag 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
