### ISSUE TITLE
Please update known issues: does not work for flows created outside the solution

### ISSUE THREAD

**Issue by packnology** [MicrosoftDocs/power-automate-docs#424]
Please add a note that this functionality is only useful if you manually create each child and parent flow in a solution. There is no ability to re-use and adapt or extend flows created outside of solutions or in other solutions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f42c36-4ce0-fff2-4cfb-e191c636edf4
* Version Independent ID: 510353c0-7e45-0302-d7d4-80c68bff7eb4
* Content: [Call Child Flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-child-flows)
* Content Source: [articles/create-child-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/create-child-flows.md)
* Service: **business-applications**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@packnology Thanks for reporting this issue. We'll update the docs.

**Comment by MSFTMan** [comment]
@packnology Please clarify what you mean here. The docuement says that you will need to have both the child and parent in a solution. Is there something that we missed?

**Comment by packnology** [comment]
@MSFTMan I was just suggesting to specify that the child and parent must actually be created within the solution (can't be imported), which means there's no ability to "template" a parent-child configuration for re-use in other solutions (which would be really useful for developers).

**Comment by MSFTMan** [comment]
@packnology We've updated the documentation as follows:

You must create the parent flow and all child flows **directly** in the same solution. If you import a flow into a solution, you will get unexpected results.
