### ISSUE TITLE
No way to change the application language

### ISSUE THREAD

**Issue by StoyanStAtanasov** [MicrosoftDocs/power-automate-docs#425]
Even on the picture shown there is no "Application Language" area.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1848df-191d-5f1c-6e39-401ece1decf2
* Version Independent ID: 0883dde8-6774-03b0-9fb0-e97f9051b2a5
* Content: [Power Automate Desktop console - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/console)
* Content Source: [articles/desktop-flows/console.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/console.md)
* Service: **flow**
* GitHub Login: @rokontol
* Microsoft Alias: **rokontol**

**Comment by MSFTMan** [comment]
@mariosleon  Please take a look at this.

**Comment by MSFTMan** [comment]
@StoyanStAtanasov Thanks for reporting this issue. We'll look into it and update the docs as needed.

**Comment by mariosleon** [comment]
@StoyanStAtanasov  Thank you for reporting this issue. It's now fixed and will be live in a few hours.
