### ISSUE TITLE
Unable to find IsHTML on Send Email (V2) Outlook 365 connector

### ISSUE THREAD

**Issue by ThatTechieGirl** [MicrosoftDocs/power-automate-docs#426]
Hi Team

I was working on compose action available for Power Automate, trying to send email.
The current doc says to look for IsHTML if you wish to send the table in email. However, I guess its been removed & updated Outlook 365 connector with action - Send an email (v2) does not have an option for IsHTML. Attaching file for reference.

<img width="399" alt="sendemail" src="https://user-images.githubusercontent.com/79997850/109848446-f38cf680-7c58-11eb-9bb9-543c0e514367.PNG"> 

<img width="370" alt="ishtml" src="https://user-images.githubusercontent.com/79997850/109848442-f25bc980-7c58-11eb-8700-e2a41df512e6.PNG">

Regards
Roma

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bddf7e-aad7-5b99-0b73-a893d25615f5
* Version Independent ID: f2f0c4d6-b613-d269-4756-bcd7548f76ec
* Content: [Understand data operations - Power Automate](https://docs.microsoft.com/en-us/power-automate/data-operations)
* Content Source: [articles/data-operations.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/data-operations.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@ThatTechieGirl Thanks for reporting this issue. You are correct, IsHTML is no longer needed. We've updated the documentation and will release within the next few days.
