### ISSUE TITLE
<br> not availabe in tables

### ISSUE THREAD

**Issue by alex-zwingli** [MicrosoftDocs/power-automate-docs#428]
- The documentation says to put `<br/>` to start a new line in a table cell, but the example has `<br>`.
- When testing either of the above tags, it did not work in Outlook, OWA, or Teams. Please update the documentation accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by MSFTMan** [comment]
@alex-zwingli Thanks for reporting this issue. We'll look into it and update the documentation.

**Comment by MSFTMan** [comment]
@hamenon-ms Are HTML break tags supported in approvals markdown?

**Comment by v-aangie** [comment]
@alex-zwingli - Thanks for your feedback. We have updated the docs to fix information in https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support. The updated content will be live later today. Closing this issue.
