### ISSUE TITLE
Can an ISV create a custom connector for Power Automate Desktop that uses native code instead of web services?

### ISSUE THREAD

**Issue by lebakken** [MicrosoftDocs/power-automate-docs#432]
This page describes the steps for an ISV to create a custom connector for the Power Automate platform using cloud APIs.  Is it possible for an ISV to create a custom connector using native code for the Power Automate Desktop only?  If so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e534fb-0608-62e2-e257-77ca64397af6
* Version Independent ID: 0f9e11dc-455d-e1cf-fbc1-89a07cb53ef6
* Content: [Power Automate for enterprise developers, ISVs, and partners - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/dev-enterprise-intro)
* Content Source: [articles/developer/dev-enterprise-intro.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/developer/dev-enterprise-intro.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@mariosleon Do you know the road map for supporting custom connectors in Power Automate Desktop?

**Comment by mariosleon** [comment]
Hello @lebakken thank you for your interest. Please note that this is part of our future roadmap, however we can't communicate any further details yet.
