### ISSUE TITLE
Web data extraction does not work for Paging

### ISSUE THREAD

**Issue by tatsean** [MicrosoftDocs/power-automate-docs#433]
I tried to crawl the data from https://news.ycombinator.com/newest, and for paging, it does not work if one of the items has the text that starts with "More ...". 
Supposedly, "More" also serves as "Next Page" (first image) in the context of https://news.ycombinator.com/newest, but if one of the items is also having the prefix as "More..." (second image), it will always "treats" that item as "Next Page", and redirects to the item. 

**First Image:**
![image](https://user-images.githubusercontent.com/487243/110227531-4655ff00-7f34-11eb-9393-7362826668b4.png)

**Second Image**
![image](https://user-images.githubusercontent.com/487243/110227555-7bfae800-7f34-11eb-9a92-2fe8d079533e.png)

**Comment by MSFTMan** [comment]
Thanks for your contribution. Closing this issue as it's not relevant to Power Automate.

**Comment by tatsean** [comment]
Why it is not related to Power Automate? was using Power Automate Desktop to perform the Web Extraction. I was using Web Automation -> Web data extraction to perform the action and it fails to work correctly if the above scenario happens.
