### ISSUE TITLE
get user info broken?

### ISSUE THREAD

**Issue by xenoguy** [MicrosoftDocs/power-automate-docs#436]
I think the "get user info" function might be broken.

I cannot get it to work.

I tried putting a user DN in explicitly, as well as a foreach loop with AD group members "%CurrentItem.DistinguishedName%"

the explicit value was similar to this: CN=Luse\, Rick,OU=User Accounts,OU=City,DC=contoso,DC=com

I'm able to successfully connect to the directory and get group info and membership.

the error it gives me when i try this is "directory object not found"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99d94f3-671c-56b9-43aa-ace95c78e85c
* Version Independent ID: 23036a14-c90e-3f34-d6b3-3e3565de6a93
* Content: [Active Directory - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/activedirectory#connecttoserveraction)
* Content Source: [articles/desktop-flows/actions-reference/activedirectory.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/actions-reference/activedirectory.md)
* Service: **flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Thank you @xenoguy for your comment. We will update the docs. In the meantime, try using the following syntax instead:  CN="Doe, John",DC=contoso,DC=com

**Comment by xenoguy** [comment]
thanks, that syntax works for the explicit value.

however when looping with a foreach, i can't use %CurrentItem.DistinguishedName% from a "get group members" operation.  the returned distinguishedname value has an escaped comma and no quotes.

I can probably work around it by manipulating the string value each loop to add quotes, but I think most people would expect this to just work.

**Comment by mariosleon** [comment]
Hello @xenoguy, thank you for the feedback. I have shared this with our product team. For future similar feature requests, you may suggest them in the [Power Automate community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity).
