### ISSUE TITLE
Needs a description of the JSON output

### ISSUE THREAD

**Issue by BobRed0965** [MicrosoftDocs/power-automate-docs#437]
This indicates that the output of the cognitive sentiment analysis is JSON but it doesn't describe the content of the JSON making this pointless. That would be like you asking what my phone number is and me responding "a series of digits".

By running it I can see that it's returning a  "score" as a decimal number, but I have no idea what that number means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d014d362-e48e-f27f-9fdd-19510df04fc8
* Version Independent ID: 5e44a5df-7744-34e0-e268-ebb69bf740d9
* Content: [Cognitive - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/cognitive#sentiment)
* Content Source: [articles/desktop-flows/actions-reference/cognitive.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/actions-reference/cognitive.md)
* Service: **flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @BobRed0965, thank you for using Power Automate Desktop. In regard to what you are asking, I would suggest you further consult the API provider's documentation. For any further technical guidance, you can always pose your questions to the [Power Automate community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity) where technical experts can assist you further.
