### ISSUE TITLE
Information shared is incorrect about creating a cloud flow in the wrong environment

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/power-automate-docs#438]
This statement : "If you create a cloud flow in the wrong environment, you'll have to delete it, and then create it in the correct environment." is NOT correct in Doc:https://docs.microsoft.com/en-us/power-automate/environments-overview-maker#create-flows-in-the-right-environment 

Please correct it.  We don't necessarily have to delete the flow and then recreate it in the correct environment. we can export the flow from the wrong environment and import in the correct one. after importing to the correct environment you would then delete the original flow.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ddd5e3-db39-4f50-4be4-71ae16dd19d2
* Version Independent ID: 61cafb41-19d2-24cc-a17f-85a36b22b4fa
* Content: [Learn about Power Automate environments - Power Automate](https://docs.microsoft.com/en-us/power-automate/environments-overview-maker?source=docs#create-flows-in-the-right-environment)
* Content Source: [articles/environments-overview-maker.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/environments-overview-maker.md)
* Service: **flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by MSFTMan** [comment]
@HinaMS Thanks for reporting this issue. We've fixed it. You'll see the update publicly in the next few days.
