### ISSUE TITLE
You never tell the user to approve their request.

### ISSUE THREAD

**Issue by gdstuart** [MicrosoftDocs/power-automate-docs#439]
I'm sitting here an hour after I posted the Approval Request, killing time waiting for the approval.  You never tell the user to approve it!  Those of us who are not familar with Approvals or why we are approving something for ourselves (why is that even necessary?) are just following your instructions.  Please add a step to Approve the Request.

Thanks,

Geoff Stuart
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ee0d822-e9af-4380-4526-47a848b0dadf
* Version Independent ID: b2517f75-528d-e570-c3f7-32b7f86fc266
* Content: [Create a Microsoft Dataverse database - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/create-database)
* Content Source: [articles/desktop-flows/create-database.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/create-database.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@gdstuart Thanks for reporting this issue. We've added a step to indicate that you must approve the request. This update will be live in the next day.
