### ISSUE TITLE
Can we set a variable to null which was previously set?

### ISSUE THREAD

**Issue by IT-LCEC** [MicrosoftDocs/power-automate-docs#443]
Can we set a variable to null which was previously set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52e0d3b7-5d54-b28b-ed97-8bc0970d0c96
* Version Independent ID: c25847a1-f575-cfd9-73e5-10cdf75bbfa6
* Content: [Variables - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/variables#assign)
* Content Source: [articles/desktop-flows/actions-reference/variables.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/actions-reference/variables.md)
* Service: **power-automate**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @IT-LCEC, thank you for using Power Automate Desktop. 

Please note that Power Automate Desktop doesn't handle the null value in the same way as programming languages. In most cases, you can set the variable to zero or an empty text value.

As this question concerns a technical issue, I would kindly ask you to post a question regarding the context of the case to the [Power Automate community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity).
