### ISSUE TITLE
PowerAutomate Approval action not allowing to attach documents

### ISSUE THREAD

**Issue by jenilChristo** [MicrosoftDocs/power-automate-docs#444]
[Enter feedback here]
As per the documentation below, the powerapp approval action lets user to create an approval with an attachment file, but in the recent flows which we tried to build this action seems to be not supported. This document should be updated with the same and alternative , if any available

![image](https://user-images.githubusercontent.com/28510266/112267397-6824e500-8c9b-11eb-9a11-0f97db832a13.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8733617a-cad0-07ac-23c9-064ed750e3a7
* Version Independent ID: 787cd076-51a5-f198-06de-12046126063e
* Content: [Send attachments with approval requests - Power Automate](https://docs.microsoft.com/en-us/power-automate/approval-attachments)
* Content Source: [articles/approval-attachments.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approval-attachments.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by kotato196** [comment]
I am very troubled by the same problem.
**Must be an attachments, not a shared link.**
I am also concerned about the impact on the flows running now.
We hope that this destructive change will be fixed soon.

**Comment by MSFTMan** [comment]
@jenilChristo Thanks for using Power Automate. We've tried the steps as outlined in this document and they work. We notice that you mention Power Apps, this is a Power Automate document. Perhaps you reported it on the wrong document. This is the doc on which this issue was reported: https://docs.microsoft.com/en-us/power-automate/approval-attachments

Thanks!
