### ISSUE TITLE
UI Element needs to use the Browser variable and not hard coded

### ISSUE THREAD

**Issue by IT-LCEC** [MicrosoftDocs/power-automate-docs#445]
When using the web automation controls, the IP address of the UI Element is hard coded. So if we build a flow for the test environment, we can't migrate to production. We need the UI Elements to honor the browser variable like all the other web controls do.

This is a show stopper for us.

**Comment by georgiostrantzas** [comment]
Hello @IT-LCEC, thank you for using Power Automate Desktop. 

As this question is more of a technical issue than a documentation issue, I would kindly ask you to post your question to the [Power Automate community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity), where technical experts can assist you.
