### ISSUE TITLE
After downloading Power Automate Desktop from the english website, the desktop version is in German - i cannot find any information of how to change the language to English

### ISSUE THREAD

**Issue by bbrumec** [MicrosoftDocs/power-automate-docs#447]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1848df-191d-5f1c-6e39-401ece1decf2
* Version Independent ID: 0883dde8-6774-03b0-9fb0-e97f9051b2a5
* Content: [Power Automate Desktop console - Power Automate](https://docs.microsoft.com/en-gb/power-automate/desktop-flows/console)
* Content Source: [articles/desktop-flows/console.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/console.md)
* Service: **power-automate**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @bbrumec, thank you for using Power Automate Desktop. 

Let us inform you that the language used in Power Automate Desktop is the display language selected on your Windows OS. For more information regarding Power Automate Desktop's display language, please visit the [respective documentation article](https://docs.microsoft.com/power-automate/desktop-flows/setup#set-the-display-language-for-power-automate-desktop).
