### ISSUE TITLE
How to retrieve the value of a UI element

### ISSUE THREAD

**Issue by ben1628** [MicrosoftDocs/power-automate-docs#449]
using UI element, I can get the name of the window, but I cannot get the value underneath it.

for example, I have a field call text1, it has a value of 1200.

I can get detail of the windows which will give me text1, but I cannot figure how I can get the value 1200.

**Comment by georgiostrantzas** [comment]
Hello @ben1628, thank you for using Power Automate Desktop. 

As this question is more of a technical issue than a documentation issue, I would kindly ask you to post your question to the [Power Automate community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity), where technical experts can assist you.
