### ISSUE TITLE
Is there provision for making text underlined? Can I help in anyways as it'll be a common request?

### ISSUE THREAD

**Issue by ravesonly** [MicrosoftDocs/power-automate-docs#450]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approvals-markdown-support.md)
* Service: **power-automate**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by v-aangie** [comment]
@gcorvera — Can you please help with this issue? If there is no provision, I will refer customer to https://ideas.flow.microsoft.com for product feedback. If there is a provision, let me know if there's a doc change needed. Thank you.

**Comment by MSFTMan** [comment]
@hamenon-ms Kindly take a look at this issue.

**Comment by v-aangie** [comment]
@ravesonly - Thanks for your input. No, underline is not supported. Closing the issue.
