### ISSUE TITLE
Cancel a flows template submission

### ISSUE THREAD

**Issue by FEALBA** [MicrosoftDocs/power-automate-docs#451]
Dear colleagues.

I've submitted a Flows template by mistake and I would need to cancel and avoid publishing it.

Can you please help me?

Thanks & regards.

**Comment by MSFTMan** [comment]
@FEALBA Thanks for contacting us. There's no way to cancel a submission. If there are problems with the template, it likely won't be accepted, or the team will fix the issues. Thanks!
