### ISSUE TITLE
Clarify difference between INPUT and OUTPUT variables

### ISSUE THREAD

**Issue by spun69** [MicrosoftDocs/power-automate-docs#452]
[Enter feedback here]
Text does not clearly explain difference between INPUT and OUTPUT variables.  Only INPUT type are somewhat explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73eedb7f-affa-e1e1-270e-369653a038d2
* Version Independent ID: cf6d454b-7b64-968b-8ad4-37878a9baa6d
* Content: [Manage the Variables pane - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/manage-variables)
* Content Source: [articles/desktop-flows/manage-variables.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/desktop-flows/manage-variables.md)
* Service: **power-automate**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **getrantz**

**Comment by georgiostrantzas** [comment]
Hello @spun69, thank you for reporting this issue. We have updated the respective documents and you will see the changes soon.
