### ISSUE TITLE
typing error 

### ISSUE THREAD

**Issue by Anassawalhaa** [MicrosoftDocs/power-automate-docs#455]
in desktop flow section ( two legacy methods of **of** creating flows ) 

have two word of (of )word .. 

thanks :)  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6870e9fe-dca9-66a8-1cd0-0000b83f385c
* Version Independent ID: ca5edb5e-80c3-05ef-b5aa-7c607f5cc706
* Content: [Overview of the types of flows in Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/flow-types)
* Content Source: [articles/flow-types.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/flow-types.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by KumarVivek** [comment]
@Anassawalhaa Thanks for reporting the issue. This issue has been resolved and will be pushed live by end of day today. Closing the issue.
