### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by RobPiovesan** [MicrosoftDocs/power-automate-docs#456]
[Enter feedback here]
There's a spelling mistake, Desktop is spelled as dekstop in one occasion
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea541994-b3d3-7f6a-e3bf-2465dcfb7df2
* Version Independent ID: cd0ebb34-b041-b7f5-633d-afc1995d2f4e
* Content: [Run a Power Automate Desktop flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/run-pad-flow)
* Content Source: [articles/desktop-flows/run-pad-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/run-pad-flow.md)
* Service: **power-automate**
* GitHub Login: @olegmelnykov
* Microsoft Alias: **olmelnyk**

**Comment by olegmelnykov** [comment]
Fixed: https://github.com/MicrosoftDocs/power-automate-docs-pr/pull/1081

**Comment by KumarVivek** [comment]
Closing the issue as this is resolved now.
