### ISSUE TITLE
Is there some deadline for migrate the classic workflows to power automate flows? the classic workflows will be deprecated in nearby future?

### ISSUE THREAD

**Issue by eduardorivas9** [MicrosoftDocs/power-automate-docs#457]
Is there some deadline for migrate the classic workflows to power automate flows? the classic workflows will be deprecated in nearby future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c08ddd-c290-34f4-5e82-ae9369012efd
* Version Independent ID: 98652aac-b377-c9fe-bb32-47d873f7237a
* Content: [Replace classic Common Data Service workflows with Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/replace-workflows-with-flows)
* Content Source: [articles/replace-workflows-with-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/replace-workflows-with-flows.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@eduardorivas9 Thanks for using Power Automate. There isn't any additional info that we can share publicly at this time.
