### ISSUE TITLE
Add glossary entry for "Item"

### ISSUE THREAD

**Issue by T0437247436** [MicrosoftDocs/power-automate-docs#458]
LOCATION:
In Power Automate > Start from Blank > Build an automated cloud flow > Choose you flows trigger.

Many options have "item" as a trigger option and it is unclear what are the possible items.   For example "When an item is deleted"   It could refer to  Cells?  Rows?  Columns?  Entire Files?  

It would be good to cover in the Glossary for the beginning users that are looking at it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42649601-628b-f121-942d-4dcfd60eee18
* Version Independent ID: e867c2cd-876b-695f-ea5c-7f70727d2dd4
* Content: [Power Automate Glossary - Power Automate](https://docs.microsoft.com/en-us/power-automate/glossary#i)
* Content Source: [articles/glossary.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/glossary.md)
* Service: **power-automate**
* GitHub Login: @nijemcevic
* Microsoft Alias: **tatn**

**Comment by nijemcevic** [comment]
Item: As a Power Automate trigger, an item represent a row in a SharePoint list. What it actually is depend on the user's list. For example it can a row in excel, or a table in a Word document.

**Comment by v-aangie** [comment]
The glossary has been updated - https://github.com/MicrosoftDocs/power-automate-docs/pull/472.
