### ISSUE TITLE
Incorrect Expand Query expression

### ISSUE THREAD

**Issue by shlemonz** [MicrosoftDocs/power-automate-docs#463]
[Enter feedback here]
On this page Expand Query expression example is: primarycontactid(contactid,fullname) 

it must be: primarycontactid($select=contactid,fullname) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d2fb7a-7614-bba8-c2da-52bc048812f3
* Version Independent ID: b4ade253-98f4-96f3-548b-7bc5e4b38af8
* Content: [Get a row by ID from Dataverse - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/get-row-id)
* Content Source: [articles/dataverse/get-row-id.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/get-row-id.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@shlemonz Thanks for the feedback. We'll get this fixed.

**Comment by v-aangie** [comment]
@shlemonz — Thanks for your feedback. We have updated the docs to fix information about the expand query example, and the updated content will be live tonight. Closing this issue.
