### ISSUE TITLE
Different product names.

### ISSUE THREAD

**Issue by noriji** [MicrosoftDocs/power-automate-docs#464]
サービス名の誤記載。
誤：Selenium ID。
正：Selenium IDE

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6870e9fe-dca9-66a8-1cd0-0000b83f385c
* Version Independent ID: ca5edb5e-80c3-05ef-b5aa-7c607f5cc706
* Content: [Power Automate フローの種類の概要 - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/flow-types)
* Content Source: [articles/flow-types.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/flow-types.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@mariosleon  Please work with the localization team on this issue.

**Comment by v-aangie** [comment]
@jowilco — As this appears to be a loc issue, I have removed the other assignees and left you as the sole assignee. The issue is being closed.

**Comment by v-aangie** [comment]
@noriji — Thanks for your feedback. We have informed the appropriate team of your issue and will We will soon look into this.

**Comment by jowilco** [comment]
@noriji 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
