### ISSUE TITLE
Forced Line Breaks works on Outlook Desktop version 2008 or later

### ISSUE THREAD

**Issue by mchibams** [MicrosoftDocs/power-automate-docs#465]
In Client Support table, Forced Line Breaks is "No" for Outlook Desktop.
But it works version 2008 (16.0.13127.20000) or later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support#client-support)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/approvals-markdown-support.md)
* Service: **power-automate**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by MSFTMan** [comment]
@mchibams Thanks for your feedback. We'll verify and update the docs.

**Comment by v-aangie** [comment]
@mchibams - Thanks for your contribution.  We've updated the document with the support for line breaks. Line breaks are not supported in tables, but they work outside of tables - This link will be live later today - https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support#client-support. Closing the issue.
