### ISSUE TITLE
Clarification on scope of licencing explanation

### ISSUE THREAD

**Issue by Fandengbo** [MicrosoftDocs/power-automate-docs#466]
Once you assign an approval request to a user, they can respond directly from an Outlook email, a Teams adaptive card, or the Power Automate action center, if they have a Power Automate, an Office 365, or a Dynamics 365 license **with built-in Power Automate capabilities.** You can find a list of these Office 365 and Dynamics 365 licenses in the Microsoft Power Apps and Power Automate licensing guide.

1/ Wording is confusing: does "*with built-in Power Automate capabilities" apply to just Dynamics 365, or all the listed items (incld Office 365 AND Dynamics 365)

2/Microsoft Power Apps and Power Automate licensing guide. Suggestion to add link to :https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/powerapps-flow-licensing-faq.md 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 013c76ec-927e-4fff-77f3-aed163b9ccf1
* Version Independent ID: b463656a-9ea6-1cc8-8efa-fdd6d83f51bc
* Content: [Get started with Power Automate approvals. - Power Automate](https://docs.microsoft.com/en-us/power-automate/get-started-approvals)
* Content Source: [articles/get-started-approvals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/get-started-approvals.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@Fandengbo —  Thanks for your feedback. We will soon look into this issue.

**Comment by MSFTMan** [comment]
@PriyaKodukula Can you help clarify this issue?

**Comment by MSFTMan** [comment]
@Fandengbo Thanks for your feedback. We've updated the document to clarify the licensing requirements. We've also added the link to the liceing FAQs. You'll see these updates publicly within the next 12 hours.
