### ISSUE TITLE
no documentation about access notificaiton

### ISSUE THREAD

**Issue by nphadro** [MicrosoftDocs/power-automate-docs#467]
I would like to be able to share a flow and NOT send all the users a notification stating that have run only access. I want no alert to go out. This page doesn't talk anything about notifications or if it is possible to turn of the notification. Thanks so much for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to share a cloud flow with other users - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-team-flows)
* Content Source: [articles/create-team-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-team-flows.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@nphadro - Thanks for your feedback. The ability to turn off notification is not supported. If you would like to add product feedback, go to visit https://ideas.flow.microsoft.com. Closing this issue.
