### ISSUE TITLE
Incorrect Select Column field names in images

### ISSUE THREAD

**Issue by jlattimer** [MicrosoftDocs/power-automate-docs#470]
[Enter feedback here]

In all the images the Select Columns values are invalid
The fields: firstname, lastname, fullname, annualincome do not belong to the Account table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fae8260-c3b8-4582-884d-72119ab256b7
* Version Independent ID: a12c64c0-9293-d86c-91c3-bce01efd1e1b
* Content: [Use lists of rows in flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/list-rows)
* Content Source: [articles/dataverse/list-rows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/list-rows.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@jlattimer  Thanks for reporting this issue. We'll update the docs.

**Comment by v-aangie** [comment]
@jlattimer - Thanks for your feedback. We have updated the docs to fix https://docs.microsoft.com/en-us/power-automate/dataverse/list-rows, and the updated content will be live later today. Closing this issue.
