### ISSUE TITLE
Table variable

### ISSUE THREAD

**Issue by Geradav** [MicrosoftDocs/power-automate-docs#476]
[Enter feedback here]
Hello

Regarding the action "Write to Excel worksheet" it is mentioned "If the variable contains a table..." but I didn't find any documentation about how to create a variable that would contain a table. How can we create a table variable?
We can create new lists and add new items to lists but what about creating a table?

Thanks

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08dbb236-dbdd-af9e-118a-db2ba29f6733
* Version Independent ID: c9922ccc-6d8b-7f3c-65db-6f3fdc23743e
* Content: [Excel - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/excel#writetoexcel)
* Content Source: [articles/desktop-flows/actions-reference/excel.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/excel.md)
* Service: **power-automate**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by v-aangie** [comment]
@mariosleon - Hi, Marios. Can you please take a look? Thank you.

**Comment by mariosleon** [comment]
Hello @Geradav, thank you for your interest Power Automate Desktop. You can find information on Datatables and how to create them under the ["Advanced data types"](https://docs.microsoft.com/en-us/power-automate/desktop-flows/variable-data-types#advanced-data-types).
