### ISSUE TITLE
Reference named range

### ISSUE THREAD

**Issue by Geradav** [MicrosoftDocs/power-automate-docs#477]
[Enter feedback here]
With the Select action, Copy action, and other similar actions, it would be great if we could reference a named range.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08dbb236-dbdd-af9e-118a-db2ba29f6733
* Version Independent ID: c9922ccc-6d8b-7f3c-65db-6f3fdc23743e
* Content: [Excel - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/excel#copycellsfromexcel)
* Content Source: [articles/desktop-flows/actions-reference/excel.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/excel.md)
* Service: **power-automate**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by v-aangie** [comment]
@mariosleon - Hi, Marios. This sounds like a feature request. Can you please take a look? Thank you.

**Comment by mariosleon** [comment]
Hello @Geradav thank you for your feedback. I shared this feature request with the product team to consider it as a future feature. Please note, that you may suggest features or ask technical questions in the [Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to technical questions and suggest solutions.
