### ISSUE TITLE
type/copy paste error under Unbound Action

### ISSUE THREAD

**Issue by s3696369** [MicrosoftDocs/power-automate-docs#481]
Under the heading "Unbound Action" it says:
To perform a bound action in your flow, you must add Perform an unbound action to your flow.

It should probably read:

To perform an **unbound** action in your flow, you must add Perform an unbound action to your flow.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ca006d-c310-d225-e568-d4da0fe9d291
* Version Independent ID: 43036476-a546-c88a-bbc2-e12324a4ffb5
* Content: [Use a flow to perform bound and unbound actions in Dataverse - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/bound-unbound)
* Content Source: [articles/dataverse/bound-unbound.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/bound-unbound.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by v-aangie** [comment]
@s3696369 — Thanks for your feedback. We have updated the docs to fix the issue you described. The updated content will go live later today. Closing this issue.

**Comment by v-aangie** [comment]
Changed "bound" to "unbound" and closed issue.
