### ISSUE TITLE
Power Automate OCR text has a misspelling 

### ISSUE THREAD

**Issue by cvillegashak** [MicrosoftDocs/power-automate-docs#486]
Preconfigured is misspelled.

<h5 id="input-parameters-2" class="heading-anchor" style="box-sizing: inherit; margin: 36px 0px 6px -1.875rem; padding: 0px 0px 0px 1.875rem; font-size: 1.25rem; font-weight: 600; outline-color: inherit; line-height: 1.3; letter-spacing: 1px; position: relative; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">Input Parameters</h5><div class="table-scroll-wrapper" style="box-sizing: inherit; outline-color: inherit; overflow: auto hidden; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Argument | Optional | Accepts | Default Value | Description
-- | -- | -- | -- | --
OCR engine | No | OCR engine variable, Tesseract engine | OCR engine variable | The OCR engine type to use. Select a **peconfigured** OCR engine or set up a new one.
OCR engine variable | No | OCREngineObject | &nbsp; | The engine to use for the OCR operation
OCR source | N/A | Screen, Foreground window, Image on disk | Screen | The source of the image to perform the OCR operation on

</div>

**Comment by v-aangie** [comment]
@cvillegashak - Thanks for your feedback. We have updated the docs to fix the Power Automate OCR text issue, and the updated content will be live later today. Closing this issue.
