### ISSUE TITLE
Conditional Action, Table of Contents mistranslation　en-ja

### ISSUE THREAD

**Issue by ZeroSysLog** [MicrosoftDocs/power-automate-docs#487]
日本語ページ　条件アクション　目次の誤訳

「Case」が「サポート案件」と記載されています。
正しくは
「Case」または「ケース」です。

"Case"  is listed as"サポート案件".
The correct word is
The correct word is "Case" or "ケース".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 71049db5-07d5-5471-1baf-a4629798be00
* Version Independent ID: 22b27bb7-ad9b-a40d-3780-7e9261c6d319
* Content: [条件 | Microsoft Docs - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/desktop-flows/actions-reference/conditionals)
* Content Source: [articles/desktop-flows/actions-reference/conditionals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/conditionals.md)
* Service: **power-automate**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by jowilco** [comment]
@ZeroSysLog 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@ZeroSysLog 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。
