### ISSUE TITLE
Get value of named field in Data Row

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/power-automate-docs#489]
It would be useful to include that the value in an individual field can be retrieved using `CurrentItem['ColumnName']`, especially when using the For Each action to loop through a Data Table that was retrieved through an SQL statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c072a86-f779-49d4-4992-897c288ee663
* Version Independent ID: 3e2e7687-e85c-8ade-9786-cb2cb7476412
* Content: [Variable data types - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/variable-data-types)
* Content Source: [articles/desktop-flows/variable-data-types.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/variable-data-types.md)
* Service: **power-automate**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **getrantz**

**Comment by georgiostrantzas** [comment]
Hello @HairyDrumroll! We updated the content and you'll be able to see the changes soon.
