### ISSUE TITLE
Cannot send Feedback at ms-docs website, missing action "tesseract OCR" in PowerAutomate

### ISSUE THREAD

**Issue by bauinformatiker** [MicrosoftDocs/power-automate-docs#491]
Cannot enter Feedback at the webspage 
https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/ocr?source=docs
even after login with my Office 365 account. So I'm posting here. 

I wanted to create a little Fow for OCR over PDF files in PowerAutomate which I can start manually for scanned PDF files in OneDrive. I see some tutorials using Tesseract OCR Engine for this task, e.g. 
https://www.flexmind.co/blog/how-to-use-ocr-in-power-automate-desktop/
but TesseractOCR seems to be removed from Powerautomate Actions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81d0345a-3fab-2adc-c7cc-c4d2b03fe0d2
* Version Independent ID: c50b23b6-616c-2962-b87f-7593e7c97f4b
* Content: [OCR | Microsoft Docs - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/ocr?source=docs)
* Content Source: [articles/desktop-flows/actions-reference/ocr.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/ocr.md)
* Service: **power-automate**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @bauinformatiker thank you for using Power Automate Desktop. Please note, that you may find responses to your questions in the [Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to such technical questions.
