### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by onkeljoe** [MicrosoftDocs/power-automate-docs#492]
In automatic translation of this page there is an error, hardly to understand if you don't speak english: In all tables with yes/no cells, the "no" is interpreted by auto-translate as shortcut to "number", so in german it is not translated to "nein" but to "Nr.", what is the german abbreviation to number.  

is there a way to disambiguate the "no" for auto-translate?

[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 67bfcee8-33a4-a706-5ef1-4d08174b3b32
* Version Independent ID: b1b9a4dd-db58-9f9d-ee65-9a590366d803
* Content: [Power Automate Desktop auf Ihrem Gerät einrichten - Power Automate](https://docs.microsoft.com/de-de/power-automate/desktop-flows/setup)
* Content Source: [articles/desktop-flows/setup.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/setup.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by jowilco** [comment]
@onkeljoe Thank you for your feedback. We are looking into this issue.

**Comment by jowilco** [comment]
@onkeljoe We have fixed this page. I believe this is also an issue in other pages, which we will also fix but it will take a little longer. Thank you again for catching this issue and bringing it to our attention!
