### ISSUE TITLE
Please add method to determine whether the trigger event was Create or Update or Delete

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/power-automate-docs#493]
[Enter feedback here]
There are potentially a lot of cases where the user wants to put a switch condition on whether the trigger condition was create, update or delete. 
Therefore it would be extraordinarily helpful if you could add this piece of information to help the user achieve that:

"When the flow was triggered by the Creation, Update or Deletion of a row, the value of `triggerOutputs()['body/SdkMessage']` will respectively be `Create`, `Update` and `Delete`."

Just that much, and it will help a lot of people in a lot of cases, and I'm not even talking niche cases. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c84a31-4f63-6ee1-ad15-096cae44cb41
* Version Independent ID: de8cf5bc-b78b-a88e-696f-7755e3ce22f0
* Content: [Trigger flows when a row is added, modified, or deleted - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/create-update-delete-trigger)
* Content Source: [articles/dataverse/create-update-delete-trigger.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/create-update-delete-trigger.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by v-aangie** [comment]
@user0604 - Thanks for your feedback. We have updated the docs to add information about the trigger condition feature, and the updated content will be live later today. Closing this issue.
