### ISSUE TITLE
Incorrect link for COntoso CRM app

### ISSUE THREAD

**Issue by JonAngove** [MicrosoftDocs/power-automate-docs#494]
Hi, just tried accessing aka.ms/contosocrmapp but it seems to resolve to an SCM Canvas app instead of the CRM app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385ab7e2-6554-02dc-9163-fa566cbc774e
* Version Independent ID: 298ec053-059e-8e74-692b-8075a53c2fe8
* Content: [Use RPA with Dynamics 365 Customer Service - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/dynamics365-cs-rpa)
* Content Source: [articles/desktop-flows/dynamics365-cs-rpa.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/dynamics365-cs-rpa.md)
* Service: **flow**
* GitHub Login: @amina196
* Microsoft Alias: **aminab**

**Comment by lanlanlee2008** [comment]
Thanks Jon. please try again. We just fixed the link.

**Comment by v-aangie** [comment]
@JonAngove — Thanks for contacting us. As we have fixed the link and haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
