### ISSUE TITLE
Don't have option for attachments

### ISSUE THREAD

**Issue by mlenair** [MicrosoftDocs/power-automate-docs#496]
[Enter feedback here]
Option to add attachments is not available in my Get Approve template is not available. I cannot see any other option. It only appears for the approved e-mail but that doesn't work for me. I have to include the attachments to approver email.

---
#### Document Details
![image](https://user-images.githubusercontent.com/65755497/120745759-65166280-c530-11eb-8e37-052d236bf4b7.png)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8733617a-cad0-07ac-23c9-064ed750e3a7
* Version Independent ID: 787cd076-51a5-f198-06de-12046126063e
* Content: [Send attachments with approval requests - Power Automate](https://docs.microsoft.com/en-us/power-automate/approval-attachments)
* Content Source: [articles/approval-attachments.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/approval-attachments.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@mlenair We've updated this document with the steps for adding attachments to approval requests.
