### ISSUE TITLE
Spelling Correction in Text Actions

### ISSUE THREAD

**Issue by sharur7** [MicrosoftDocs/power-automate-docs#497]
Spelling Error in the "delimiter" spelling. Instead of "delimiter", it's written "delimeter" in Split text definition.
Link:
https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/text

Image:
![Untitled](https://user-images.githubusercontent.com/57194200/120812355-88f69a00-c56a-11eb-9fb3-27f139511766.png)

I have corrected the spelling should create a pull request?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263c52c4-e89d-2fa5-c8d5-d791e3a37350
* Version Independent ID: 9afb1a06-c257-07c7-f50a-6697a28a811b
* Content: [Text | Microsoft Docs - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/text)
* Content Source: [articles/desktop-flows/actions-reference/text.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/text.md)
* Service: **power-automate**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
@sharur7 Thank you for reporting this. It will be resolved very soon
