### ISSUE TITLE
Patch request to turn on the flow fails with 400 - Bad Request Error

### ISSUE THREAD

**Issue by bvrit-sravya** [MicrosoftDocs/power-automate-docs#498]
Hi, I followed the below document to create dynamic flows and turn them on - https://docs.microsoft.com/en-us/power-automate/web-api

Here is the code snippet but this fails with 400 Bad Request error. 

`private void PatchNewFlow(string workflowUrl, string accessToken)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Authorization =
                      new AuthenticationHeaderValue("Bearer", accessToken);
                    client.Timeout = new TimeSpan(0, 2, 0);
                    client.DefaultRequestHeaders.Add("OData-MaxVersion", "4.0");
                    client.DefaultRequestHeaders.Add("OData-Version", "4.0");
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json"));                
                    var data = JsonConvert.SerializeObject(new
                    {                       
                        statecode = 1
                    });
                    var content = new StringContent(data, Encoding.UTF8, "application/json");
                    var method = new HttpMethod("PATCH");
                    var flowURI = new Uri(workflowUrl);
                    var request = new HttpRequestMessage(method, flowURI)
                    {
                        Content = content
                    };
                    var response = client.SendAsync(request).Result;
                    var workflowid = workflowUrl.Replace(_settings.AADCDSUrl, string.Empty).Replace(@"/api/data/v9.1/workflows(", string.Empty).TrimEnd(')');
                    if (response.IsSuccessStatusCode)
                    {
                        _telemetryTracker.TrackTrace(string.Format("Power Automate Flow - {0} is turned on));
                    }
                    else
                    {
                        throw new Exception(string.Format(
                          "The PATCH to turn on Power Automate Flow - {0} failed with a status of '{1}'",
                          workflowid,
                          response.ReasonPhrase));
                    }
                }
            }
Note: The access token is generated using MSAL and instead of a service account, we are utilizing this API by connecting to the  CDS url ( https://orgxxxxx.crm.dynamics.com) as an application. ( This app is registered in Azure)
` Any help is greatly appreciated. Thank you in advance.

**Comment by bvrit-sravya** [comment]
Hi,

I was able to figure out the reason for 400 Bad Request. This is seen when I am trying to turn on the flow by setting statecode = 1. I am accessing the CDS through an API as opposed to a service account. Is there a way I can provide power automate license to an API ?

**Comment by v-aangie** [comment]
@bvrit-sravya — Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product licensing issue here. To contact Support, see here: https://flow.microsoft.com/support/. Closing this issue.
