### ISSUE TITLE
Sort By screenshot shows an incorrect example parameter

### ISSUE THREAD

**Issue by Quartermaster-007** [MicrosoftDocs/power-automate-docs#499]
In most of the screenshots on this Docs page there is an error in the 'Sort by' parameter.
For the 'Sort by' parameters, column and sort order definitions should not be seperated by a column, only multiple sort orders should be.

On the Docs page, this practice is shown and mixed up multiple times. It should be "revenue acs, name desc".
Hope that you can clarify on this and perhaps also include the format in a code snippet box, e.g.:

Sort by:
`{column} {asc/desc}[, {column} {asc/desc}]...`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fae8260-c3b8-4582-884d-72119ab256b7
* Version Independent ID: a12c64c0-9293-d86c-91c3-bce01efd1e1b
* Content: [Use lists of rows in flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/list-rows)
* Content Source: [articles/dataverse/list-rows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/list-rows.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@Quartermaster-007 Thanks for your feedback. This doc was updated so these items have been fixed. Thanks!
