### ISSUE TITLE
Prerequisites of sharing a flow is not correct

### ISSUE THREAD

**Issue by nenon0530** [MicrosoftDocs/power-automate-docs#500]
[Enter feedback here]
"You must have a paid Power Automate license to share a cloud flow."
I think the above prerequisite is not correct since Office 365 user could share a cloud flow.
And the page of "paid Power Automate license" is not including Office 365 licenses.
Please fix the statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to share a cloud flow with other users - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-team-flows)
* Content Source: [articles/create-team-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-team-flows.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@nenon0530 Thanks for reporting this issue. yes, seeded plans also give the rights to share flows. We've updated the docs. You'll see the updated docs in the next 12 hours.
