### ISSUE TITLE
The information is incorrect

### ISSUE THREAD

**Issue by new-kirte** [MicrosoftDocs/power-automate-docs#501]
The guidance is incorrect and the flow template does not work. The email is sent, but Approval Status of a list item is not updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 950382b4-3830-0c0d-98f5-988d0a81f08a
* Version Independent ID: b96c9aa9-445c-2826-490d-a5dd584b9396
* Content: [Trigger approvals from SharePoint lists - Power Automate](https://docs.microsoft.com/en-us/power-automate/trigger-sharepoint-list)
* Content Source: [articles/trigger-sharepoint-list.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/trigger-sharepoint-list.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by new-kirte** [comment]
@MSFTMan,  I am going to create a new issue. There is no issue with the flow. There is wrong guidance and Microsoft support has accepted it. Thanks for ignoring customer feedback

**Comment by zacharyhester2** [comment]
It seems the flow only works when I author a new item for the SP List. From what I'm reading online the automated trigger only works on the Owner's Plan/ wouldn't run for other employees in the company.

Is there a way to make this part of a User's Plan so any employee could submit an Expense for Approval?
