### ISSUE TITLE
IP address allow list

### ISSUE THREAD

**Issue by AndrewYueLiu** [MicrosoftDocs/power-automate-docs#503]
In my project, we need to call a API from Power Automate. We set allow list based this document. But we still received  403 errors sometime. We checked AzureDiagnostics logs, the caller IP was 13.77.3.139, which was from the IP list of Logic apps, , https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-limits-and-config#multi-tenant-azure---outbound-ip-addresses. After we added these IPs, so far there is no issues. 
This document might need to be updated

**Comment by MSFTMan** [comment]
@AndrewYueLiu Thanks for reporting this issue. The complete list of ip addresses is here: https://docs.microsoft.com/en-us/connectors/common/outbound-ip-addresses. Thanks for using Power Automate.
