### ISSUE TITLE
Dataverse is needed for Approvals even in the default environment

### ISSUE THREAD

**Issue by anmateusMSFT** [MicrosoftDocs/power-automate-docs#506]
"If you're using the default environment, you don't need to provision the Dataverse database."

This is not true. Approvals always need a Dataverse database regardless of if they are in the default environment on in a non default one.
https://support.microsoft.com/en-us/topic/power-automate-approvals-provisioning-overview-and-troubleshooting-2306313a-49fa-efde-c716-a34c573ec942
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 013c76ec-927e-4fff-77f3-aed163b9ccf1
* Version Independent ID: b463656a-9ea6-1cc8-8efa-fdd6d83f51bc
* Content: [Get started with Power Automate approvals. - Power Automate](https://docs.microsoft.com/en-us/power-automate/get-started-approvals#permissions-to-create-a-dataverse-database)
* Content Source: [articles/get-started-approvals.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/get-started-approvals.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@anmateusMSFT Thanks for your contribution. If you create an approval flow, then the Dataverse database is created automatically in the default environment. I've update the docs with this info.
