### ISSUE TITLE
Outdated screenshots

### ISSUE THREAD

**Issue by anmateusMSFT** [MicrosoftDocs/power-automate-docs#507]
Screenshots are still showing the old icon of CDS connector.

Should contain the new dataverse legacy (grey) icon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c3bde-6083-7a7c-3469-48137843198f
* Version Independent ID: d1466842-8d49-67ad-1ca1-326511b2560e
* Content: [Create an automated flow with Microsoft Dataverse - Power Automate](https://docs.microsoft.com/en-us/power-automate/connection-cds)
* Content Source: [articles/connection-cds.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/connection-cds.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@anmateusMSFT Thanks for reporting this issue. It's now fixed. You'll see the updated content tomorrow.
