### ISSUE TITLE
approvalCenterSettings-approvalsFilter

### ISSUE THREAD

**Issue by abhishekgawde** [MicrosoftDocs/power-automate-docs#508]
Hello, is there any more documentation available for approvalsFilter. which other properties can be filtered and how?

**Comment by v-aangie** [comment]
@abhishekgawde - Thanks for your input. Can you please provide a link to the page you are looking at?

**Comment by v-aangie** [comment]
@abhishekgawde - Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
