### ISSUE TITLE
Are there powershell commandlets available to register a machine for running desktop flows?

### ISSUE THREAD

**Issue by robwafle** [MicrosoftDocs/power-automate-docs#512]
It seems the gateway is no longer required for running desktop flows, and there is no reason for me to install the power automate gateway if the only thing I need to do is run desktop flows.

I'd like to silently register each of my machines to my power automate environment after the silent install of power automate desktop and avoid using the gateway completely.   Are there any powershell commands that will register the machine?

Thanks!

**Comment by mariosleon** [comment]
Hello @robwafle. Thank you for using Power Automate Desktop. Please note, that the machines feature is still in preview. Despite that, there is an option to silently register your machines which is described [here](https://docs.microsoft.com/en-us/power-automate/desktop-flows/machines-silent-registration#silently-register-a-new-machine).
