### ISSUE TITLE
High Profile documented as having lower action limits than Medium

### ISSUE THREAD

**Issue by Khaveles** [MicrosoftDocs/power-automate-docs#515]
The Action limits section reflects the High profile as having 15,000 yet the Medium indicated 25,000. Please review these limits for accuracy as High should have higher limits than Medium, unless the calculation is different (ie: consolidated across all flows vs. per flow) in which case this should be called out. 

Actions per 24 hours | 2,000 for Low, 5,000 for MediumLow1, 20,000 for MediumLow2, 25,000 for Medium, and 15,000 for High

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config?source=docs)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/limits-and-config.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@Khaveles - Thanks for your feedback. We will soon look into this issue.

**Comment by MSFTMan** [comment]
@Khaveles Thanks for reporting this issue. We've updated the limits in this document late last year. Kindly let us know if you have further questions.
