### ISSUE TITLE
Links do not work

### ISSUE THREAD

**Issue by MMT0905** [MicrosoftDocs/power-automate-docs#516]
The links in this screen shot do not work

![image](https://user-images.githubusercontent.com/52712239/123783092-fd8bd280-d8a3-11eb-8580-5d973ce01b96.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fae8260-c3b8-4582-884d-72119ab256b7
* Version Independent ID: a12c64c0-9293-d86c-91c3-bce01efd1e1b
* Content: [Use lists of rows in flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/list-rows)
* Content Source: [articles/dataverse/list-rows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/list-rows.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by v-aangie** [comment]
@MMT0905 
Thanks for your feedback. We have updated the docs to fix the tip in https://docs.microsoft.com/en-us/power-automate/dataverse/list-rows#advanced-options, and the updated content will be live later today. Closing this issue.
