### ISSUE TITLE
[Incorrect statement] - Medium performance profile is ambiguous and leads to confusion

### ISSUE THREAD

**Issue by manuelpsnunesmsft** [MicrosoftDocs/power-automate-docs#517]
In the section [performance-profiles] for the **Medium Performance profile**, it is **stated that "All instant flows, such as flows with Button or Power Apps triggers, or child flows"**

Statement is incorrect and leads to ambiguity since instant flows triggered from Power Apps that use, for example seeded Office license, do not have the Medium performance profile but Low performance profile.

Please, add a disclaimer.

Ping me if additional details are needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/limits-and-config.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@PriyaKodukula Kindly take a look at this issue.

**Comment by MSFTMan** [comment]
@manuelpsnunesmsft Thans for reporting this issue. We updated the document sometime back.
