### ISSUE TITLE
Performance Profile section is unclear

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/power-automate-docs#518]
The Performance Profile section indicates that "There are five possible values, depending on the flow owner's plan."

However, the description of the Medium performance profile, doesn't seem to have anything to do with the owner's plan. Instead, it seems to be based on the type of the flow. "All instant flows, such as flows with Button or Power Apps triggers, or child flows".

These two statements seem to be in conflict. Please correct the wording of whichever one is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/limits-and-config.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@devlinl Thanks for your contribution. We'll investigate this and update the doc as appropriate.
