### ISSUE TITLE
The situation flow has no creator is recommended? 

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/power-automate-docs#519]
>  If the shared flow still has an active owner, the flow will continue to run.

Yes, that's right.But I was told that the flow will be assigned power automate free instead of an original license ( e.g. flow for office 365) .

The situation flow has no creator is recommended? If no, please describe that changing creator is necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to share a cloud flow with other users - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-team-flows#what-happens-if-the-user-who-created-a-shared-flow-leaves-the-organization)
* Content Source: [articles/create-team-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-team-flows.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@MiyukiAmino Thanks for reporting this issue. To change the owner of a flow, you can make a copy of the flow and let the intended owner create the flow from the copy. Thanks.

**Comment by MiyukiAmino** [comment]
Thank you for your instruction. But my essential question is not about the way to change flow-creator, but what happens when there is no creator for a long time and if something happens docs describe that.

**Comment by MiyukiAmino** [comment]
Thank you so much! I wonder "The situation flow has no creator is recommended?", that's what it looks like when I read docs.
Tons of users are facing the problem of retiring or transferring flow creators.

**Comment by MiyukiAmino** [comment]
Hi, @v-aangie .
Cx asks css team about the issue sometimes, it would be nice to share your investigation result to me. Thanks.

**Comment by MSFTMan** [comment]
> Thanks, @MSFTMan ! No, I'd like to know the recommended operation when the flow creator leaves the organization.
> 
> 1. Need to change the creator?
> 2. Only add co-owners to the flow and modify connections?
> 
> I think cx need to do #1 if cx uses a license other than Power Automate Free because the license will switch to Power Automate Free.
> 
> ## Below description, it reads as if cx only need to do #2.
> What happens if the user who created a shared flow leaves the organization? If the shared flow still has an active owner, the flow will continue to run.

Thanks @MiyukiAmino I understand the question now. There's no way to change the creator of the flow. Even if the creator leaves the organization, I think it would be misleading to change the creator. 

Are you facing a functional problem, or are you just curious what is the recommedation from Microsoft?

**Comment by MSFTMan** [comment]
> Hi, @MSFTMan. I see. My question is "what is the recommedation from Microsoft?" not out of curious, but to answer customer's question. It's one of the most frequently asked questions!

Thanks for clarifying. I'll look into this. Thanks.

**Comment by MSFTMan** [comment]
@MiyukiAmino We've updated the documentation with the following note to let customers know that they should change the owner if there are no active owners in the organization:

If there's no active owner for a flow, you should change the owner. To change the owner of a flow, make a copy of the flow, and then let the intended owner create the flow from the copy.

You will see this update in the next 24 hours. 

Thank you for your patience.

**Comment by MiyukiAmino** [comment]
Hello, @MSFTMan .
Thanks for your kindly help! It's very helpful to CSS and customers.
