### ISSUE TITLE
[PAD] No reference to new argument "Image matching algorithm" in image-based actions

### ISSUE THREAD

**Issue by hyagomartins** [MicrosoftDocs/power-automate-docs#520]
In the latest PAD version, actions based on image matching now include the argument **Image matching algorithm**, with the options _Basic_ and _Advanced_.

The **Wait for Image** action, for example, includes this. But when testing, I couldn't figure out the difference between the options, how each works, and the advantages and disadvantages of using one or the other.

Including these details in the documentation would help us decide the best usage scenario, on debugging desktop flows, and would save time in setting the action using the "trial and error" method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6c3d2f8-31d3-98e7-8083-9199008dff6f
* Version Independent ID: 707817a6-56af-9227-9b36-4180d6a8ec6a
* Content: [Wait | Microsoft Docs - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/wait#waitforimageaction)
* Content Source: [articles/desktop-flows/actions-reference/wait.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/wait.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by MSFTMan** [comment]
@mariosleon Please take a look at this.

**Comment by georgiostrantzas** [comment]
Hello @hyagomartins,

Thank you for pointing out this issue. We are working on adding information regarding image matching algorithms, and you will be able to see the content soon.

**Comment by georgiostrantzas** [comment]
Hello @hyagomartins 

The content regarding image matching algorithms is now available in [Automate using images](https://docs.microsoft.com/en-us/power-automate/desktop-flows/images).
