### ISSUE TITLE
PBI Flows in other Environments

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/power-automate-docs#521]
From the limitations: 
"The PowerBI visual only functions with flows in a tenant's default environment. Any flow created with the visual is created in the users default environment."

Will these flows / triggers be able to be in other environments (not the default) in the future? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a213639f-cfb7-c503-8d6b-b9efc2943ab2
* Version Independent ID: 56ebfc97-1c70-1e34-e56e-104f87a6f064
* Content: [Trigger a cloud flow from any Power BI report - Power Automate](https://docs.microsoft.com/en-us/power-automate/trigger-flow-powerbi-report#known-limitations)
* Content Source: [articles/trigger-flow-powerbi-report.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/trigger-flow-powerbi-report.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **hamenon**

**Comment by MSFTMan** [comment]
@samadane Thanks for your contribution. All roadmap plans are provided in the release [plans](https://cloudblogs.microsoft.com/dynamics365/bdm/2021/07/15/2021-release-wave-2-plans-for-dynamics-365-and-power-platform-now-available/).
