### ISSUE TITLE
Continuation of the issue : The situation flow has no creator is recommended? 

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/power-automate-docs#522]
Thank you for your instruction. But my essential question is not about the way to change flow-creator, but what happens when there is no creator for a long time and if something happens docs describe that.

_Originally posted by @MiyukiAmino in https://github.com/MicrosoftDocs/power-automate-docs/issues/519#issuecomment-879487632_

**Comment by v-aangie** [comment]
@MiyukiAmino - Thanks for your feedback. I've re-opened issue 519, where the history is and am working on a solution for you. Closing this issue. Updates will appear in https://github.com/MicrosoftDocs/power-automate-docs/issues/519.
