### ISSUE TITLE
Details of flow runs after turning off flow

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/power-automate-docs#523]
Need to provide details of flow runs after turning off flow.

Flow Runs with status is running will continue even if flow status is disabled. Only when deleting flow, Flow Runs with status is running will be terminated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b19c08b2-1f6e-0430-6074-18d64d6c8b17
* Version Independent ID: fc9595bd-0d84-ecad-17de-dd3818a6cb3b
* Content: [Turn flows on or off - Power Automate](https://docs.microsoft.com/en-us/power-automate/disable-flow)
* Content Source: [articles/disable-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/disable-flow.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @Puyush6889
* Microsoft Alias: **kapolepa**

**Comment by MSFTMan** [comment]
@DavidPaf Thanks for your contribution. We'll validate this and update the docs as appropriate.

**Comment by MSFTMan** [comment]
@DavidPaf Thanks for your feedback. We've updated the docs. You'll see the update tomorrow.
