### ISSUE TITLE
Lacking Information

### ISSUE THREAD

**Issue by bejeweledone** [MicrosoftDocs/power-automate-docs#524]
In the O365 Cloud there are 4 different types of groups that can be used for various things.   Unfortunately they can't all be used for everything.   This is an excellent article but it does NOT specify which of the 4 O365 group types are needed.     

Microsoft 365
Distribution
Mail-enabled Security
Security

Please make sure you specify the group type in your articles.    

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to share a cloud flow with other users - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-team-flows)
* Content Source: [articles/create-team-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-team-flows.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@bejeweledone Thanks for reporting this issue. We'll investigate and update the docs as needed.

**Comment by bejeweledone** [comment]
Thank you.   It would be great if the creator of these sorts of Doc keep in
mind that they are heavily used and recommended to people who are new to
the platform and that little things like indicating what type of group can
go a long long way towards helping that new person understand what they
need to do.

J

**Comment by Moi0** [comment]
> 
> 
> In the O365 Cloud there are 4 different types of groups that can be used for various things.   Unfortunately they can't all be used for everything.   This is an excellent article but it does NOT specify which of the 4 O365 group types are needed.     
> 
> 
> 
> Microsoft 365
> 
> Distribution
> 
> Mail-enabled Security
> 
> Security
> 
> 
> 
> Please make sure you specify the group type in your articles.    
> 
> 
> 
> Thanks
> 
> 
> 
> 
> 
> ---
> 
> #### Document Details
> 
> 
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> 
> 
> * ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
> 
> * Version Independent ID: ea8ac9ee-e014-ad33-59f![image](https://user-images.githubusercontent.com/84483712/192655901-01a38170-ea0b-4d3f-ba7e-e350e3eaf152.jpeg)5-5d15f8a38ad8
> 
> * Content: [Learn how to share a cloud flow with other users - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-team-flows)
> 
> * Content Source: [articles/create-team-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-team-flows.md)
> 
> * Service: **power-automate**
> 
> * Sub-service: **cloud-flow**
> 
> * GitHub Login: @MSFTMan
> 
> * Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@bejeweledone - Thanks for your feedback. We are closing this issue, as https://docs.microsoft.com/en-us/power-automate/create-team-flows was updated March 9, 2023. If this doesn't address your comment, please open another issue.
