### ISSUE TITLE
When will My Flows be supported via API?

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/power-automate-docs#525]
Is there anything on the roadmap for admins to pull the client data of a flow for flows outside of a solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eecc2503-eee7-8779-2445-d6cd6968a0bd
* Version Independent ID: 532be787-8be9-c9b5-37a2-88841c5b8118
* Content: [Flows are now stored in Dataverse and use the rich Web API - Power Automate](https://docs.microsoft.com/en-us/power-automate/web-api)
* Content Source: [articles/web-api.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/web-api.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* Product: ****
* Technology: ****
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@samadane All roadmap plans are [here](https://cloudblogs.microsoft.com/dynamics365/bdm/2021/01/27/2021-release-wave-1-plans-for-dynamics-365-and-power-platform-now-available/#:~:text=Power%20Automate%20Desktop%20was%20released%20to%20general%20availability,flows%20customers%2C%20secure%20credential%20management%2C%20and%20much%20more.) or [here](https://cloudblogs.microsoft.com/dynamics365/bdm/2021/07/15/2021-release-wave-2-plans-for-dynamics-365-and-power-platform-now-available/).
