### ISSUE TITLE
Action request limits - "Plan limit" seems wrong

### ISSUE THREAD

**Issue by ddevine-msft** [MicrosoftDocs/power-automate-docs#529]
https://docs.microsoft.com/en-us/power-automate/limits-and-config#action-request-limits

The Action request limits seem wrong. Under the "Plan Limit" it says "2,000 for Low, 5,000 for MediumLow1, 20,000 for MediumLow2, 25,000 for Medium, and 15,000 for High"

Why is High 15,000 and Medium 25,000? Seems it should be the other way. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/limits-and-config.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@ddevine-msft I've checked with the product team. The info in the doc is correct. Thanks.

**Comment by aliyoussefi** [comment]
Hi Deon, This looks to be the same as the issue Sam opened up: https://github.com/MicrosoftDocs/power-automate-docs/issues/537#issue-962048535
