### ISSUE TITLE
Wrong syntax for Expand Query

### ISSUE THREAD

**Issue by simongorelate** [MicrosoftDocs/power-automate-docs#530]
From my trial and error the sample for Expand Query should be:
primarycontactid($select=contactid,fullname)

Otherwise I am running into an error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d2fb7a-7614-bba8-c2da-52bc048812f3
* Version Independent ID: b4ade253-98f4-96f3-548b-7bc5e4b38af8
* Content: [Get a row by ID from Dataverse - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/get-row-id)
* Content Source: [articles/dataverse/get-row-id.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/get-row-id.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by v-aangie** [comment]
@simongorelate — Thanks for your feedback. We have updated the docs to fix information about the  expand query example, and the updated content will be live tonight. Closing this issue.
