### ISSUE TITLE
Unclear that you have to clear out environment variables on the export of a solution

### ISSUE THREAD

**Issue by rforster-dev** [MicrosoftDocs/power-automate-docs#531]
Having encountered this ourselves, after following the guidance on this page on exporting a solution we realised that we needed to remove any values in the environment variables _before_ exporting. 

The current guidance is not clear that this needs to happen if you need to change them on import of the target environment.

I would also suggest that when you are exporting a solution, that there should be a prompt to the user on the pane/blade that if there are environment variables, remember to delete the values before exporting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0535b1a-e189-75c9-d5f0-c200a65150ec
* Version Independent ID: 7120c4d7-3223-6c65-f70f-03ca718775f1
* Content: [Learn how to export solution-aware flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/export-flow-solution)
* Content Source: [articles/export-flow-solution.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/export-flow-solution.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@ChrisGarty Can you confirm if this behavior is by design?

**Comment by ChrisGarty** [comment]
On solution export, confirming with the admin about environment variable values is something that we have discussed. It is on our radar and likely something that will be addressed long term as part of the Power Platform ALM tooling improvements.

**Comment by MSFTMan** [comment]
@rforster-dev We've updated the docs with: Before you export a solution, you must delete any environment variables in the solution. You'll see the update in the next day. Thanks for using Power Automate.
