### ISSUE TITLE
Incorrect Link in Article

### ISSUE THREAD

**Issue by SharonFryLV** [MicrosoftDocs/power-automate-docs#532]
In this text "Here's a community article of how to use trigger conditions." this link is incorrect:
https://www.timlinenterprises.com/microsoft-power-automate-flow-trigger-conditions/

Here's what I discovered:
A) timlinenterprises.com now redirects to https://thrivenextgen.com/
B) When I tried the original link with http instead of https, it redirected to https://thrivenextgen.com/microsoft-power-automate-flow-trigger-conditions/
C) It is a very complex article for a beginner!

However, in the meantime, I found this one and it was super simple and worked perfectly. Please consider using it to replace the current one, especially since this is an introductory article:
https://tomriha.com/a-simple-way-to-create-a-trigger-condition-in-power-automate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd64ea9a-d352-f719-fa8c-7c8c7ca20273
* Version Independent ID: d583bc49-1518-0a8a-5364-073225cde2e9
* Content: [Triggers in Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/triggers-introduction)
* Content Source: [articles/triggers-introduction.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/triggers-introduction.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by v-aangie** [comment]
@SharonFryLV - Thanks for your feedback. We've removed the community link and are currently updating our content. Closing this issue.
