### ISSUE TITLE
Sample app Approval Center does not work

### ISSUE THREAD

**Issue by Akuma-U1** [MicrosoftDocs/power-automate-docs#533]
The sample application listed in the bottom of this page is not a working example of all the different types of widgets. When changing widget type to "approvalCenter", which is listed as a valid type of widget, the SDK throws an error.

The setup of the app is correct, as the "templates widget" widget type works as intended.

When checking the iframe implementation, the version of the SDK imported is not the same as the version of the SDK imported in the sample. Neither versions of the SDK work in the sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac3ad92-eb8f-554a-5de3-14c430e594aa
* Version Independent ID: fab1ceb3-5110-4452-0a0d-99346cc31230
* Content: [Integrate Power Automate with websites and apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/embed-flow-dev#resources)
* Content Source: [articles/developer/embed-flow-dev.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/developer/embed-flow-dev.md)
* Service: **power-automate**
* Sub-service: **developer**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@hamenon-ms  Do you have any thoughts about this item?

**Comment by MSFTMan** [comment]
@Akuma-U1 Thanks for reporting this issue. You are correct that the "approvalCenter" widget isn't fully supported in the sample. We'll be making updates to this document in the next few months that will include steps on how to make this work.
