### ISSUE TITLE
Is Power Automate still unavailble to .gov and .mil email addresses

### ISSUE THREAD

**Issue by greenchevy65** [MicrosoftDocs/power-automate-docs#534]
Is this still true?
.gov or .mil email addresses
You receive a message like the following during signup:

Power Automate unavailable: Power Automate is not available for users with .gov or .mil email addresses at this time. Use another work email address or check back later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe370b3-b679-d4ce-eaab-e697ce29f7a7
* Version Independent ID: 382c4a35-4847-0a21-2cf6-f70a308612ab
* Content: [Sign up and sign in - Power Automate](https://docs.microsoft.com/en-us/power-automate/sign-up-sign-in)
* Content Source: [articles/sign-up-sign-in.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/sign-up-sign-in.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @anjlic
* Microsoft Alias: **anjlic**

**Comment by v-aangie** [comment]
@greenchevy65 — Thanks for your feedback. We will soon look into this issue.

**Comment by v-aangie** [comment]
@greenchevy65 - Thanks for your feedback. We are working on updating the UI. For now, please use the appropriate URL listed here - Power Automate US Government service URLs (https://docs.microsoft.com/en-us/power-automate/us-govt#power-automate-us-government-service-urls), instead. Closing the issue.

cc: @MSFTMan
