### ISSUE TITLE
Shortcut in PAD-editor

### ISSUE THREAD

**Issue by lema7913** [MicrosoftDocs/power-automate-docs#535]
What's the shortcut for "Run" and "Run next action" ?
I see a shortcut for "Run from here", but not the others

/Leif

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4262ad3-a842-79f1-8ccc-d7bccc8a3d11
* Version Independent ID: 25f9956b-4e90-bef7-95b1-4d7feb33bec2
* Content: [Debugging a desktop flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/debugging-flow)
* Content Source: [articles/desktop-flows/debugging-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/debugging-flow.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @lema7913,

Thank you very much for the feedback! We have updated the content and you'll be able to see the changes soon in [Debug a desktop flow](https://docs.microsoft.com/power-automate/desktop-flows/debugging-flow).
