### ISSUE TITLE
Typo on High limit actions?

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/power-automate-docs#537]
Is this a typo?
https://docs.microsoft.com/en-us/power-automate/limits-and-config#:~:text=2%2C000%20for%20Low%2C%205%2C000%20for%20MediumLow1%2C%2020%2C000%20for%20MediumLow2%2C%2025%2C000%20for%20Medium%2C%20and%2015%2C000%20for%20High

<html>
<body>

Actions per 24 hours | 2,000 for Low, 5,000 for MediumLow1, 20,000 for MediumLow2, 25,000 for Medium, **and 15,000 for High**
-- | --

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/limits-and-config.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@samadane - Thanks for your feedback. We are tracking this issue in https://github.com/MicrosoftDocs/power-automate-docs/issues/515. Closing this issue.
