### ISSUE TITLE
How to follow up after Submit a template to the Power Automate gallery

### ISSUE THREAD

**Issue by thopt** [MicrosoftDocs/power-automate-docs#538]
Hi team,

How can I follow up if my submission has been approved or pending after Submit a template to the Power Automate gallery?
Do we have any point of contact for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8d0d2-3a6f-c3f1-494d-b0ea73c22f9b
* Version Independent ID: 41bc35b2-5a4d-7406-1ae7-27b292033fcd
* Content: [Submit a cloud flow template - Power Automate](https://docs.microsoft.com/en-us/power-automate/publish-a-template)
* Content Source: [articles/publish-a-template.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/publish-a-template.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @sunaysv
* Microsoft Alias: **sunayv**

**Comment by v-aangie** [comment]
@thopt - 
Thanks for your feedback. We will soon look into this issue on articles/publish-a-template.md.

**Comment by MSFTMan** [comment]
@thopt There's no way for you to contact the team. The team will communicate with you as needed about your template. Thanks for using Power Automate.
