### ISSUE TITLE
Update on "Connection References"

### ISSUE THREAD

**Issue by melody-universe** [MicrosoftDocs/power-automate-docs#539]
Right now, there is no documentation in Power Automate on the concept of Connection References, but when creating a cloud flow, you can *only* link connection references to a flow, and not the connection itself.

Currently, the [only documentation I can find on connection references](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/create-connection-reference) is listed as pre-release documentation, and when working with connection references in solutions, the component explicitly states they are in preview (it's just called "Connection References (preview)").

That said, it seems that from a consumer standpoint that it is impossible to deploy anything to a production Power Automate environment without using preview features, which has some customers understandably nervous.

Can this document (or any documentation on the Power Automate side) be updated to describe how customers can use connection references and be assured that the feature won't change underneath them? Or, if not, can they turn off connection references in their production environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97bf9b6c-5628-f18c-7027-45b21eb3b6bc
* Version Independent ID: a4394ad5-9d46-2a6d-16d9-48b0c88fb401
* Content: [Learn to connect to your data using connections and on-premises data gateways - Power Automate](https://docs.microsoft.com/en-us/power-automate/add-manage-connections)
* Content Source: [articles/add-manage-connections.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/add-manage-connections.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by v-aangie** [comment]
@melody-universe - Thanks for your feedback. We will soon look into this issue on https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/add-manage-connections.md.

**Comment by MSFTMan** [comment]
@melody-universe Thanks for using Power Automate. As you've found, connection references are in preview. Preview features are not intended to be used in production environments. We aren't able to provide details that you requested because preview features can change, or even not be released to General Availability.

**Comment by melody-universe** [comment]
@MSFTMan It is impossible to create and enable a Power Automate flow without using Connection References. This hasn't always been the case, but it currently is that way today. If a customer wants their production environment to remain supported, should I be advising them not to use Power Automate at all, since the entire platform relies on a preview feature?
