### ISSUE TITLE
Delay until Postpone until

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/power-automate-docs#540]
the graphic and text don't depict the Postpone until. It shows a picture of using Delay until. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c84a31-4f63-6ee1-ad15-096cae44cb41
* Version Independent ID: de8cf5bc-b78b-a88e-696f-7755e3ce22f0
* Content: [Trigger flows when a row is added, modified, or deleted - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/create-update-delete-trigger#filter-conditions)
* Content Source: [articles/dataverse/create-update-delete-trigger.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/create-update-delete-trigger.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by v-aangie** [comment]
@devman2k - Thanks for your feedback. We will soon look into this issue on https://docs.microsoft.com/en-us/power-automate/dataverse/create-update-delete-trigger#filter-conditions.

**Comment by MSFTMan** [comment]
@devman2k There's no postpone until property here. We've updated the docs and you'll see the updated content tomorrow.
