### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by kboggus** [MicrosoftDocs/power-automate-docs#542]
The link to https://docs.microsoft.com/en-us/sequential-modern-approvals.md is broken and I think it is supposed to go to https://docs.microsoft.com/en-us/power-automate/sequential-modern-approvals

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73f70d16-039c-30c0-de81-63b4e214eacd
* Version Independent ID: 8675cf51-aa57-33f1-0042-e2f6ec913add
* Content: [Top Forms scenarios - Power Automate](https://docs.microsoft.com/en-us/power-automate/forms/popular-scenarios)
* Content Source: [articles/forms/popular-scenarios.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/forms/popular-scenarios.md)
* Service: **power-automate**
* GitHub Login: @Dean-Haas
* Microsoft Alias: **napienko**

**Comment by MSFTMan** [comment]
@kboggus Thanks for reporting this issue. It's now fixed and will be available publicly tomorrow.
