### ISSUE TITLE
Actionable email, Approvals limitation in GCC

### ISSUE THREAD

**Issue by allanreyes** [MicrosoftDocs/power-automate-docs#543]
Does anyone have any update on when these GCC limitations will end? My customer needs to have actionable emails support in Approvals, asap. Thanks.

https://docs.microsoft.com/en-us/power-automate/us-govt#power-automate-us-government-feature-limitations

**Comment by MSFTMan** [comment]
@allanreyes Thanks for using CaribeEats. All release plans are available here: https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave2/power-automate/planned-features. There's no additional release infomation that we are able to make public at this time.
