### ISSUE TITLE
Page lacks information about the "Month" interval and it's behavior

### ISSUE THREAD

**Issue by FerretyWorld** [MicrosoftDocs/power-automate-docs#545]
Lacking details about the Month option. If you set a flow to run once a month, does the month interval behave by running on the 'day' per month as specified by the Start Date parameter?

An example: If I set the trigger for once a month and set the start date to the 15th of the next month, with the recurrence be specific to the day "15" or does it occur every 30 days? 

The page talks about the other configs, just not Month for some reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba2e127-56bc-5910-3af6-30030cf58c1f
* Version Independent ID: c8fea93d-3d8d-bf8e-af7d-ae853a936843
* Content: [Run flows on a schedule - Power Automate](https://docs.microsoft.com/en-us/power-automate/run-scheduled-tasks)
* Content Source: [articles/run-scheduled-tasks.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/run-scheduled-tasks.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@FerretyWorld Thanks for using Power Automate. We've updated the page to indicate that the flow runs on the same date each month. You will see the update within 1 day.
