### ISSUE TITLE
Cut-off sentence

### ISSUE THREAD

**Issue by Libbyrome** [MicrosoftDocs/power-automate-docs#548]
There is a sentence toward the bottom that says this:
"To see the"

I wonder what the rest of the sentence could say. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7759368-a61e-08ce-e24f-b43a200521dd
* Version Independent ID: 80c1d8d8-a995-1023-91f9-0a1fd687c5b6
* Content: [Create a business process flow in Power Apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-business-process-flow#add-on-demand-workflows-or-actions-using-an-action-step)
* Content Source: [articles/create-business-process-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-business-process-flow.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @vashr
* Microsoft Alias: **vashr**

**Comment by MSFTMan** [comment]
@Libbyrome Thanks for reporting this issue. We've removed the partial sentence. You'll see this update later today or tomorrow.
