### ISSUE TITLE
Not complete

### ISSUE THREAD

**Issue by pascalhollmann** [MicrosoftDocs/power-automate-docs#549]
If you want to upload a file it is not enough to pass the base64 content. you have to compose an object and pass an this.
the content should be 

{
"$content-type": "image/png",

"$content":base64string

}

check this article
https://powerusers.microsoft.com/t5/Power-Automate-Community-Blog/Working-with-Image-and-File-Types-in-Dataverse-CDS/ba-p/809945

if you only pass the base64 string the file is not readeble
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25aa6ad7-bd9a-bae0-1e82-7e9c33378c2d
* Version Independent ID: b3b9583b-b5f4-a243-4220-48b9cf4f4a7c
* Content: [Upload or download image and file content - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/upload-download-file)
* Content Source: [articles/dataverse/upload-download-file.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/upload-download-file.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@radioblazer Please look into this behavior, per our conversation.

**Comment by KendalBond007** [comment]
Thanks for contacting us. Note that the latest update to the doc was made 15 December 2022. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://flow.microsoft.com/support/. Closing this issue.
