### ISSUE TITLE
Double 'full stop'

### ISSUE THREAD

**Issue by Stepnwolf78** [MicrosoftDocs/power-automate-docs#550]
['Set Process Flow Order
PLease delete one 'full stop' here: 'When you have more than one business process flow for a table (row type), you’ll need to set which process is automatically assigned to new rows.. ']

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7759368-a61e-08ce-e24f-b43a200521dd
* Version Independent ID: 80c1d8d8-a995-1023-91f9-0a1fd687c5b6
* Content: [Create a business process flow in Power Apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-business-process-flow)
* Content Source: [articles/create-business-process-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-business-process-flow.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @vashr
* Microsoft Alias: **vashr**

**Comment by MSFTMan** [comment]
@Stepnwolf78 Thanks for reporting this issue. It's fixed and you will see the updated document tomorrow.
