### ISSUE TITLE
There is no "ProcessID" attribute in Get details of a UI element in window

### ISSUE THREAD

**Issue by mtrudel-e3k** [MicrosoftDocs/power-automate-docs#551]
[Enter feedback here]
Hello
I am following instructions on this page but I dont see any attribute named "ProcessId" under Get details of a UI element in window.

What I see under Advanced  is Attribute with this list

- Own Text
- Exists
- Location and Size
- Enabled

I created a flow that download a file from a web site.
TO get the file we need to click a button on the page.
Then it immediately downloads the file in the Download folder but also opens Excel.
I need to close this instance of Excel. This instance was open by the web site not by the flow so this instance in not in a variable in the flow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 063c7e37-9ec7-c2eb-d25a-309dd6d8eddb
* Version Independent ID: c7da3e10-0048-69dd-8e8c-d71887d81fa4
* Content: [Close any window through its process ID - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/how-to/close-window-process-id)
* Content Source: [articles/desktop-flows/how-to/close-window-process-id.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/close-window-process-id.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **getrantz**

**Comment by georgiostrantzas** [comment]
Hello @mtrudel-e3k

Thank you for contacting us! 

I would like to inform you that the "Get details of a UI element in window" action allows you to populate some additional attributes besides these displayed in the drop-down list. Please, visit [this article](https://docs.microsoft.com/en-us/power-automate/desktop-flows/how-to/extract-attributes-window-elements) to find more information about all the properties you can extract from a window.

In your case, you can manually populate the attribute "processed" in the "Attribute name" field of the action.
