### ISSUE TITLE
同時発生したトリガーはどう処理されるのか？

### ISSUE THREAD

**Issue by Iijimasa** [MicrosoftDocs/power-automate-docs#553]
****
Formsへの応答が発生した時をトリガーとしてユーザーに情報を入力kしてもらているが、メールで送付された該当Formsへのリンクをユーザーが同時にクリックした場合どちらかのトリガーがかからない状況が発生しているようです。このようなケースを防ぐ方法はありますか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fd64ea9a-d352-f719-fa8c-7c8c7ca20273
* Version Independent ID: d583bc49-1518-0a8a-5364-073225cde2e9
* Content: [Power Automate でのトリガー - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/triggers-introduction)
* Content Source: [articles/triggers-introduction.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/triggers-introduction.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@Iijimasa Thanks for reporting this issue. This forum is for issues with the Power Automate documentation only. This issue with the trigger and Forms sounds like a request that you must handle thrrough one of the support channels listed here: https://powerautomate.microsoft.com/en-us/support/ .
