### ISSUE TITLE
Mail Connector restricted for new tenants

### ISSUE THREAD

**Issue by expiscornovus** [MicrosoftDocs/power-automate-docs#554]
Hi All,

Hope you are doing well?

In the create your first flow a template is used with uses the Mail connector.

However, the Mail connector is currently restricted for new tenants. 

This might be confusing for people who are just starting with the product because they are not allowed to use that connector and get an error message:
_The Mail connector is currently restricted for new tenants. Please consider using alternatives like Office 365 Outlook, Gmail, SendGrid connector instead. If you still need to use this connector, please contact Microsoft support._

Is it possible to provide a different example template for the create your first flow? Or at least highlight this as a note in the current example?

With kind regards,
Dennis :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf98fbf-59fc-825d-e8bc-b4b5b42719a2
* Version Independent ID: 22977ae9-2f4b-c98e-d19d-1d8ebf43fbd2
* Content: [Get started with Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/getting-started#create-your-first-flow)
* Content Source: [articles/getting-started.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/getting-started.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@expiscornovus Thanks for reporting this issue. We've updated the docs and you'll see the updated document live tomorrow.

**Comment by expiscornovus** [comment]
@MSFTMan, thanks for your quick response and change. That sounds good :)
