### ISSUE TITLE
Typo - increment instead of initialize

### ISSUE THREAD

**Issue by plbowers** [MicrosoftDocs/power-automate-docs#555]
When introducing the action "Initialize variable" you describe the first parameter as "The name for the variable to increment" - the wo rding should be "The name for the variable to INITIALIZE". (Later when talking about the "Increment Variable" action you use the identical wording and it is correct in that case.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79901a7-7164-ab0f-3b0e-27a1714653af
* Version Independent ID: ccbe5229-3334-ccb3-26df-4530dfaa3786
* Content: [Store and manage values in variables - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-variable-store-values)
* Content Source: [articles/create-variable-store-values.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-variable-store-values.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@plbowers Thanks for reporting this issue. It's fixed and will be live in the docs tomorrow.
