### ISSUE TITLE
sequential loops are not by default

### ISSUE THREAD

**Issue by plbowers** [MicrosoftDocs/power-automate-docs#556]
In the special note you say:

===(snip)===
Unless you're incrementing or decrementing variables, changing variables inside loops might create unexpected results if you run loops in parallel. For these cases, try setting your loop to run sequentially, which is the default setting.
===(snip)===

In fact, at least for "apply to each" loops you are PROMPTED to set loops to run sequentially without parallelism but it is NOT the default. The note, as written, makes it appear that leaving things as the default is OK but it should say that you need to change it to make it work right.

(This is just as per the documentation - personally I think as soon as someone changes a variable in a loop the default SHOULD BE to make it sequential rather than me having to go in and change it. But that's a battle for another day.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79901a7-7164-ab0f-3b0e-27a1714653af
* Version Independent ID: ccbe5229-3334-ccb3-26df-4530dfaa3786
* Content: [Store and manage values in variables - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-variable-store-values)
* Content Source: [articles/create-variable-store-values.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-variable-store-values.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by kisubedi** [comment]
@plbowers please confirm the default control is 'parallel' and you were prompted to set it to 'sequential'. If you choose the ellipsis(three button) on an apply to each, you can see the default concurrency control value.
![image](https://user-images.githubusercontent.com/91279975/137042726-c86ba42a-b299-4606-93e5-726db48dc360.png)
