### ISSUE TITLE
Install of PAD as a prereq?

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/power-automate-docs#557]
Further in the document it lists the desktop flows "isntalled".  Should we list PAD as a prereq to be installed on all machines where unattended or attended flows will run?

https://docs.microsoft.com/en-us/power-automate/desktop-flows/run-desktop-flow#prerequisites

**Comment by mariosleon** [comment]
Hello @samadane , thank you for using Power Automate. Please note that the pre-requisite for unattended or attended flows is just the Power Automate machine runtime app. 
The installer resides along with the Power automate Desktop installer, however Power Automate Desktop is not a pre-requisite.
