### ISSUE TITLE
Question: US Gov Tenants (last two bullets)

### ISSUE THREAD

**Issue by JoeAlanis** [MicrosoftDocs/power-automate-docs#560]
Hello,

The bullets at the bottom of the page are unclear.  The first bullet: 

- Power BI – Power Automate US Government doesn’t support Power BI.

Does this mean that there isn't a PowerBI connector for Power Automate? 

For the second bullet:

- Power Platform admin center – You can use the admin center to open support tickets, but other functionality is currently not available in US Government tenants.

This doesn't sound right as the Power Platform Admin center is avail in US Gov tenants. 

Can someone please clarify?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d0a9ce-bdc6-9f60-fecb-eb5cabfe21ee
* Version Independent ID: d2267099-da75-d3d7-77cf-af41fcc1cf1e
* Content: [Power Automate US Government - Power Automate](https://docs.microsoft.com/en-us/power-automate/us-govt#power-automate-us-government-feature-limitations)
* Content Source: [articles/us-govt.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/us-govt.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@JoeAlanis The doc has been updated to reflect the limations of the admin center in US Government tenants.
