### ISSUE TITLE
Silent registration for machines - Power Automate

### ISSUE THREAD

**Issue by andersdissing** [MicrosoftDocs/power-automate-docs#561]
Hello
I’m reading the documentation on Silent registration for machines - Power Automate | Microsoft Docs (https://docs.microsoft.com/en-us/power-automate/desktop-flows/machines-silent-registration#join-silently-a-machine-group). And the part of registering the machine with an Azure AD application is working as described in the documentation. But when I’m trying to join a machine group as the documentation describes the command fails.
The error message stats that the command with a ”Failed to get user name.”-error.
 
My use case:
I’m build an Azure VM Scale Set and on providing a new VM, I execute a PowerShell script that install Pre-requisites and then calls the .\PAD.MachineRegistration.Silent.exe -register and then .\PAD.MachineRegistration.Silent.exe -joinmachinegroup.

My finding so far:
The only case where I can get the .\PAD.MachineRegistration.Silent.exe -joinmachinegroup to work is where I login to my VM, start Power Automate Desktop and login with my Microsoft 365 account. And then run the .\PAD.MachineRegistration.Silent.exe -joinmachinegroup
It doesn’t change anything if an added the authenticationfallback option

Conclusion:
Is there a way where I can join the machine group and without logging in the Power Automate Desktop first?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7023527b-aafd-ac7a-4319-30eb324b3950
* Version Independent ID: 0be01081-3761-63e6-40e8-133b474220b2
* Content: [Silent registration for machines - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/machines-silent-registration)
* Content Source: [articles/desktop-flows/machines-silent-registration.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/machines-silent-registration.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @andersdissing, thank you for using Power Automate. Please note that as machines are linked to the user, you will need to be logged on prior to joining a group similar to what the machine registration requires.
Note, that you may ask technical questions in the [Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to questions and suggest solutions.
