### ISSUE TITLE
項目名が違います

### ISSUE THREAD

**Issue by shima-soft** [MicrosoftDocs/power-automate-docs#564]
誤)xcel ワークシートのアクティブなセル
正)Excel ワークシート内のセルをアクティブ化

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 08dbb236-dbdd-af9e-118a-db2ba29f6733
* Version Independent ID: c9922ccc-6d8b-7f3c-65db-6f3fdc23743e
* Content: [Excel - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/desktop-flows/actions-reference/excel#feedback)
* Content Source: [articles/desktop-flows/actions-reference/excel.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/excel.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
@jowilco Can you please review this?

**Comment by jowilco** [comment]
@shima-soft 
フィードバックをありがとうございます。この問題は調査中です。

**Comment by jowilco** [comment]
@shima-soft 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。

**Comment by shima-soft** [comment]
適切な翻訳への修正、ありがとうございました。
