### ISSUE TITLE
Unable to find New Microsoft Dataverse Connector (Only see Legacy)

### ISSUE THREAD

**Issue by lbagleybhs** [MicrosoftDocs/power-automate-docs#572]
Hi, 

The documentation states that there should be a new Microsoft Dataverse connector for use. When I select an operation in Azure Logic App searching "Microsoft Dataverse" only returns the legacy connector. 

What needs to be done to be able to use the new connector? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c84a31-4f63-6ee1-ad15-096cae44cb41
* Version Independent ID: de8cf5bc-b78b-a88e-696f-7755e3ce22f0
* Content: [Trigger flows when a row is added, modified, or deleted - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/create-update-delete-trigger)
* Content Source: [articles/dataverse/create-update-delete-trigger.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/create-update-delete-trigger.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@lbagleybhs Thanks for contacting us. This document is mean specifically for customers who are using Power Automate. Logic Apps is a different service. I checked Power Automate, and confirmed that Microsoft Dataverse is available as a trigger for cloud flows.

**Comment by MSFTMan** [comment]
@lbagleybhs Per the Logic Apps documentation here: https://docs.microsoft.com/en-us/connectors/connector-reference/connector-reference-logicapps-connectors only the legacy Dataverse connector is available when you create logic apps.
