### ISSUE TITLE
Inconsistent content

### ISSUE THREAD

**Issue by tealsoftwarenz** [MicrosoftDocs/power-automate-docs#576]
This page doesn't seem to fit within the context of the section it is included in.  Every other page in this section is about using the Approvals app - but this section basically tells you how to create your own independent approval app, which seems really weird.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba7205e-3196-ce6a-24fb-f0b5956364b2
* Version Independent ID: 9ce85398-0713-ad34-d19b-3bce887880c5
* Content: [Build an approval loop with Microsoft Dataverse - Power Automate](https://docs.microsoft.com/en-us/power-automate/common-data-model-approve)
* Content Source: [articles/common-data-model-approve.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/common-data-model-approve.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@tealsoftwarenz Thanks for your feedback. The page is intended  to be there. Makers who want to create their own approvals app can use it as needed.
