### ISSUE TITLE
No information provided regarding Run Only Users

### ISSUE THREAD

**Issue by DTronD** [MicrosoftDocs/power-automate-docs#582]
[Enter feedback here]
The page (IMO) makes a broad statement that all M365-authenticated (aka AzureAD) actions in Flow run as the user who invoked the flow and not as the person who built the flow.  I think that is not entirely true.  I have flows that perform actions that show up in ShPt with the createdBy/ModifiedBy of the user-account that the ShPt connection was created with.  That means an flow created by UserMaker who uses an action with a connection that was created using the authentication/login for UserConnectionCreds and invoked by UserFlowInvoker is "seen" by ShPt as UserConnectionCreds, not UserFlowInvoker.

That being said, the flows I have that show this behavior are over a year old.  I just created a new flow and it seems to be behaving as you describe (i.e. ShPt mods appear as UserFlowInvoker instead).  Sadly, attempts to use the Run Only user configuration to force this new flow to behave like our older flows, aren't working.

Soooooooo, some comment in this page  pointing to the docs for how to properly configure the Run Only User config to force the connections to use their embedded authentication instead of the flow-invoking user's would be great.

And, if my observations about old flow behavior versus newer are correct, some sort of comment about when that change took place and how differences can be observed in the same enviro depending on the age of the flows would maybe prevent frustration (and support tickets being turned in to MSFT).

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1337e97f-27bd-cb9b-e877-a31bc2e54e45
* Version Independent ID: 3031af8f-dc78-bfb5-98db-d4e250d4b4cb
* Content: [Authentication and security for planning a Power Automate project - Power Automate](https://docs.microsoft.com/en-us/power-automate/guidance/planning/authentication-security)
* Content Source: [articles/guidance/planning/authentication-security.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/guidance/planning/authentication-security.md)
* Service: **power-automate**
* Sub-service: **guidance**
* GitHub Login: @taiki-yoshida
* Microsoft Alias: **tayoshi**

**Comment by KendalBond007** [comment]
Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://flow.microsoft.com/support/. Closing this issue.

NOTE: doc last updated 15 Feb 2022
