### ISSUE TITLE
Apply to each default limit is wrongly mentioned 

### ISSUE THREAD

**Issue by rishi1212** [MicrosoftDocs/power-automate-docs#586]
https://docs.microsoft.com/en-us/power-automate/limits-and-config#concurrency-looping-and-debatching-limits

it says "Apply to each concurrency	1 is the default limit. You can change the default to a value between 1 and 50 inclusively.	This limit is highest number of "apply to each" loop iterations that can run at the same time, or in parallel."

but in realty if i leave this confiq off , the apply to each runs on some degree of parallelism 

there are various product ICM for same.

**Comment by MSFTMan** [comment]
@rishi1212 Thanks for using Power Automate. The default is 1. The parallesim you experience isn't guaranteed for every run. This is why the default is 1 because that’s what we can commit to.
