### ISSUE TITLE
Excel Macro in Power Automate

### ISSUE THREAD

**Issue by TDog77** [MicrosoftDocs/power-automate-docs#597]
[Enter feedback here]

I wish this page had instructions for running an excel macro on a new file using macros from the PERSONAL.xlsb file
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dc55a7-126d-ffea-52e2-fae25bd36780
* Version Independent ID: 39c7d75e-ede0-d333-fae6-e673fee1ed60
* Content: [Run macros on an Excel workbook - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/how-to/run-macros-excel)
* Content Source: [articles/desktop-flows/how-to/run-macros-excel.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/run-macros-excel.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @TDog77 

Thank you for pointing out this issue. We are working on adding information regarding running macros stored in the PERSONAL.xlsb file and you'll be able to see the updated content soon.

Note, that you may ask technical questions in the [Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to questions and suggest solutions.
