### ISSUE TITLE
Should be updated to reflect new licensing

### ISSUE THREAD

**Issue by Nicokirr** [MicrosoftDocs/power-automate-docs#599]
Mention of the transition period should be removed
Threasholds should be checked and eventually updated to reflect the new API calls limits described [here ](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#licensed-user-request-limits )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/limits-and-config.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@Nicokirr Thanks for using Power Automate. There's no longer any mention of the transition period in this document since the most recent updates.
