### ISSUE TITLE
デスクトップ用 Power Automate ではなく、Power Automate for desktop が製品名として記載される必要があります

### ISSUE THREAD

**Issue by nakamae1983** [MicrosoftDocs/power-automate-docs#601]
[フィードバックをこちらに入力してください]
"Power Automate Desktop" が、"Power Automate for desktop" に製品名が変更になりましたが、ja-jp の公開情報の表記がすべて "デスクトップ用 Power Automate" になっています。
これらは、製品名としての "Power Automate for desktop" に統一されて記載される必要があると考えます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 67bfcee8-33a4-a706-5ef1-4d08174b3b32
* Version Independent ID: b1b9a4dd-db58-9f9d-ee65-9a590366d803
* Content: [デスクトップ用 Power Automate の前提条件と制限 - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/desktop-flows/setup?WT.mc_id=twitter)
* Content Source: [articles/desktop-flows/setup.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/setup.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by jowilco** [comment]
@nakamae1983 
フィードバックをありがとうございます。翻訳を更新しました。更新された翻訳はライブです。この問題をクローズします。

Power Automate for desktop -> デスクトップ用 Power Automate
