### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by glittery11** [MicrosoftDocs/power-automate-docs#605]
'Subtract dates' is translated as '날짜 차감'.
Koreans will misunderstand this as 'decrease the date'.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 6187c3e6-5b3e-4b5c-05eb-6f4c7612570f
* Version Independent ID: 7776f0e2-a633-b29d-0f67-4607aedc5472
* Content: [Datetime - Power Automate](https://docs.microsoft.com/ko-kr/power-automate/desktop-flows/actions-reference/datetime#subtract)
* Content Source: [articles/desktop-flows/actions-reference/datetime.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/datetime.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by jowilco** [comment]
@glittery11
Thanks for your feedback. We are looking into this issue.

**Comment by jowilco** [comment]
@glittery11 
Thanks for your feedback. We have updated the translations to 날짜 차이, and the updated translations are live. Closing this issue.
