### ISSUE TITLE
Admin rights to start/stop a service

### ISSUE THREAD

**Issue by trajekolus** [MicrosoftDocs/power-automate-docs#607]
This documentation should explain how to get elevated rights for starting or stopping a service.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb78751c-57d3-5cec-b91d-a68a95b3a8e1
* Version Independent ID: d323dec1-69c9-890f-45e4-d86bf9e789b0
* Content: [Windows services - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/services#start)
* Content Source: [articles/desktop-flows/actions-reference/services.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/services.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @trajekolus. Thank you for reporting this. We are working towards adding this information and will be available soon.

**Comment by georgiostrantzas** [comment]
Hello @trajekolus! We have updated our documentation and you can find a section regarding running Power Automate with elevated rights [here](https://docs.microsoft.com/en-us/power-automate/desktop-flows/setup#run-power-automate-with-elevated-rights).
