### ISSUE TITLE
Error in HTTP(download from web)

### ISSUE THREAD

**Issue by temitopefunmi** [MicrosoftDocs/power-automate-docs#608]
My PAD flow was working perfectly until i did an update and now i get the error: Failed to download from web: Invalid URI: The format of the URI could not be determined.. 
I then used the same URI in Browser automation after launching a new browser instance and there was no issue with the URI.
Could there be a glitch in the latest update?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a843a8-7e9e-53ef-6955-bd22e62f8e8a
* Version Independent ID: fd74890d-8fd9-3354-5584-3cba236902c8
* Content: [HTTP | Microsoft Docs - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/web)
* Content Source: [articles/desktop-flows/actions-reference/web.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/web.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @temitopefunmi, thank you for using Power Automate. Please note that I have forwarded this case to the product and development team. Note, that you may ask technical questions and report technical issues you face in the[ Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to questions and suggest solutions.

**Comment by temitopefunmi** [comment]
Never mind. I figured out that i now add to add the https://....complete uri unlike i did before the update.
Thank you.
