### ISSUE TITLE
Japanese translation error

### ISSUE THREAD

**Issue by daichan** [MicrosoftDocs/power-automate-docs#609]
日本語訳が違っています。

次のイメージは、Office 365 Outlook アクションの部分的なリストを示しています。 フローを開始するために使用できるフローの完全リストは、Office 365 Outlook ~~トリガー~~ です。

次のイメージは、Office 365 Outlook アクションの部分的なリストを示しています。 フローを開始するために使用できるフローの完全リストは、Office 365 Outlook **アクション** です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0514f0fe-5fd7-7502-384d-9efca247a5c6
* Version Independent ID: 65704690-e5d5-fae7-321e-efa60a9422be
* Content: [Microsoft 365 メールおよび Power Automate の概要 - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/email-overview#feedback)
* Content Source: [articles/email-overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/email-overview.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Dealgan12** [comment]
This is now been updated in the the 13th December publish and string has been updated.
