### ISSUE TITLE
MSTeams with PVA in PowerAutomate to post messages into Channel and Groupchat

### ISSUE THREAD

**Issue by Santhosh0505** [MicrosoftDocs/power-automate-docs#612]
Hi Team,

I am trying to use Power Automate to post proactive notification using PVA in MSTeams.
image.
![image](https://user-images.githubusercontent.com/48650250/143467594-bac8b882-d624-4e87-85cb-d03eaeec75ce.png)

Seems this feature is only available with one-on-one chat with bot, but I need channel and Group chat also. Can you please help if there is some way or any release of this feature already in roadmap.

Any suggested alternative way to achieve this is most appreciated.
Thanks in Advance.

**Comment by MSFTMan** [comment]
@Santhosh0505 Thanks for using Power Automate. The items you see in the list are the only ones supported at this time. The roadmap (https://powerautomate.microsoft.com/en-us/roadmap/) is updated continuously. Feel free to check it out for updates. Thanks!
