### ISSUE TITLE
sql querying excel files, column names or column numbers or header row? Which row?

### ISSUE THREAD

**Issue by rmpasswd** [MicrosoftDocs/power-automate-docs#613]
[Enter feedback here]
Hello, 
Thank you for specifying the specifics! I had a questions about column names.
Do you mean the header row that is usually in Row 1 of a standard excel sheet?
Or by column name you mean C1, C2, C3 etc?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d722e3-fee6-9cca-f4a8-18f7a2f5fa44
* Version Independent ID: 2cc91535-bbd7-6161-eccf-459ba004d67d
* Content: [Run SQL queries on Excel files - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/how-to/sql-queries-excel)
* Content Source: [articles/desktop-flows/how-to/sql-queries-excel.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/sql-queries-excel.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @rmpasswd 

Thank you for using Power Automate! We are working on clarifying this information and you'll be able to see the updated content soon. 

Note, that you may ask technical questions in the [Power Automate community](https://preview.flow.microsoft.com/support/) where technical experts can respond to questions and suggest solutions.
