### ISSUE TITLE
Error in Datatable example

### ISSUE THREAD

**Issue by GomesLuciano** [MicrosoftDocs/power-automate-docs#614]
In the section where Datatable was defined and you guys show an example on how to add a new row, the example is wrong.
I tried to use **%Product + ['Product3','30 USD']_%_** as mentioned but the system showed this error.

![image](https://user-images.githubusercontent.com/90220395/143665027-56911534-e1f9-4368-a679-7e94370c10f4.png)

When I changed it to **%Product_%_ + ['Product3','30 USD']**  I was able to save the component without an error.

I hope this helps

Luciano Gomes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c072a86-f779-49d4-4992-897c288ee663
* Version Independent ID: 3e2e7687-e85c-8ade-9786-cb2cb7476412
* Content: [Variable data types - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/variable-data-types)
* Content Source: [articles/desktop-flows/variable-data-types.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/variable-data-types.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @GomesLuciano, thank you for your feedback! As we present in the article, the first part of the expression is the name of the existed datatable variable. In this specific example, the variable name should be **Products**, not **Product**. 

If you have additional technical questions, please feel free to ask them in the [Power Automate community](https://preview.flow.microsoft.com/support/) where technical experts can assist you further.

**Comment by GomesLuciano** [comment]
Hello Georgio, thanks for your comment.
The problem was not the name, because as I said, when I changed the syntax (with the same name) it worked.
The problem with the example seems to be where the % was placed.
Thanks

**Comment by georgiostrantzas** [comment]
Unfortunately, we couldn't reproduce this functionality to verify that there is an issue. Could you upload a screenshot of your flow?

**Comment by GomesLuciano** [comment]
Hi Georgio,

Actually I am still learning and I was trying to find a way to handle arrays in PAD, so I found datatable datatype, but I did not used it at all.
During my tests, I tried to add rows to a datatable inside a loop so I used the set variable as shown in the example

![image](https://user-images.githubusercontent.com/90220395/144048372-8f3e9878-db88-4eea-987a-f095498dff84.png)

But, as I said, the syntax in the example seems to be wrong, 

%Product + ['Product3','30 USD']% **gave an error: "Parameter 'To': Syntax error."**

%Product% + ['Product3','30 USD'] **worked correctly (with no errors)**

That's how to investigate.

I hope this helps.

**Comment by georgiostrantzas** [comment]
Please, upload a screenshot of your desktop flow, so we can replicate the exact steps you have followed. I created a loop that populates a datatable and works as expected with the presented notation. Normally, the notation you mention above creates a text variable and doesn't add an item to a datatable, 

![set-variable-example](https://user-images.githubusercontent.com/68054762/144230657-58936350-bdfa-493c-92bb-8444775d3697.png)

![table-loop-example](https://user-images.githubusercontent.com/68054762/144230659-20d19188-d493-49a3-ba04-4cb235c031c6.png)
