### ISSUE TITLE
The Markdown for headers doesn't work with Outlook at least as indicated in your table.

### ISSUE THREAD

**Issue by mattdreher** [MicrosoftDocs/power-automate-docs#616]
The Markdown for headers doesn't work with Outlook at least as indicated in your table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/approvals-markdown-support.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @hamenon-ms
* Microsoft Alias: **hamenon**

**Comment by MSFTMan** [comment]
@mattdreher Thanks for using Power Automate. Can you say specifically what doesn't work with the sample Markdown?

**Comment by mattdreher** [comment]
Last I checked, none of the header Markdown worked for outlook.  

```
# This is a H1 header
## This is a H2 header
### This is a H3 header
#### This is a H4 header
##### This is a H5 header
```

**Comment by MSFTMan** [comment]
@mattdreher Thanks for using Power Automate. I just tested this and all the headers appear in the email that I received in the latest version of Outlook, and in Teams. Here's what I placed in the Details field of the flow.

# This is H1
## This is H2

### This is H3

#### This is H4

It worked. Kindly try again or you can get help from one of the [support options](https://powerautomate.microsoft.com/en-us/support/).
