### ISSUE TITLE
Importing information missing from this page

### ISSUE THREAD

**Issue by VFXpro** [MicrosoftDocs/power-automate-docs#617]
1.  Limit of how many files can be merged is missing?
2. Can files stored in Sharepoint or in the Cloud can be used?  (https// path)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 266b63a0-dbb2-8126-b5d1-8e96899ef1e5
* Version Independent ID: f328c0ff-5021-e91a-8e0c-3f48dd5d4949
* Content: [PDF | Microsoft Docs - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/pdf#mergefiles)
* Content Source: [articles/desktop-flows/actions-reference/pdf.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/pdf.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @VFXpro, thank you for using Power Automate and for sharing your feedback with us. Up to now there have been no reports indicating there is a limit on the number of files one can merge. On the second question, note that for the time being you can use only local files in the said actions.

Note, that you may ask technical questions in the [Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to questions and suggest solutions.

**Comment by VFXpro** [comment]
Sadly, local files defeats the purpose of a cloud based flow...  all the files I want to merge are in Azure Storage or SharePoint. 🙁
________________________________
