### ISSUE TITLE
Add Required Location for WinAutomation Processes.dat File

### ISSUE THREAD

**Issue by jstraete** [MicrosoftDocs/power-automate-docs#618]
When running the Process Migrator program for WinAutomation, I get the following error after selecting WinAutomation as the program I am wanting to process from:

"Error while retrieving data from the database. Please make sure the Processes.dat file is in the correct location."

My file is in "C:\Users...your username goes here...\Documents\WinAutomation\Processes.dat" which is the default location as stated here: https://docs.microsoft.com/en-us/previous-versions/troubleshoot/winautomation/product-documentation/winautomation-help-files/winautomation-database-and-backup

If documentation could be added to know where the program is looking for this file so I can complete the migration process that would be very helpful. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3c6f199-c750-341f-8cad-473e759f7aa9
* Version Independent ID: c2bce283-0381-bb79-7c68-642449a8683f
* Content: [Process migrator for Softomotive products (preview) - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/softomotive-migrator)
* Content Source: [articles/desktop-flows/softomotive-migrator.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/softomotive-migrator.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @jstraete. Thank you for using Power Automate. Please check that the file you mention is also specified the same way in the WinAutomation > Settings > Processes File field as this database is the one used during the flows migration.

**Comment by jstraete** [comment]
Hey @mariosleon, thank you for looking into this issue I am having. Here is a minute-long video showing my setup and the issue I am running into that I think will help show my setup: https://www.youtube.com/watch?v=QTlHFzny4Ik I still do not see what I am doing wrong, but hopefully you can point me in the right direction after looking at that. Thanks!
