### ISSUE TITLE
Power Automate Button text

### ISSUE THREAD

**Issue by ClusteredIndex** [MicrosoftDocs/power-automate-docs#619]
[Enter feedback here]

I don't have any option to change the text on a Power Automate button
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to share a cloud flow with other users - Power Automate](https://docs.microsoft.com/en-gb/power-automate/create-team-flows)
* Content Source: [articles/create-team-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-team-flows.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@ClusteredIndex Thanks for using Power Automate. Kindly indicate which section of this article you're referring to so that we can help to clarify. Thanks!
