### ISSUE TITLE
Poll Generator doesn't seem to work. Cannot see responses.

### ISSUE THREAD

**Issue by aconstantin2** [MicrosoftDocs/power-automate-docs#621]
I'm looking to create an anonymous poll in a Teams Channel via Power Automate & let everyone see the responses.

If I follow the advice on @MSFTMan's page here: https://docs.microsoft.com/en-us/power-automate/poll-generator-sample I get this error: https://github.com/microsoft/AdaptiveCards/issues/2924 ("Unable to reach app. Please try again.")

The answer to Issue #2924 just states to use "Post adaptive card and wait for a response" instead of "Post adaptive card in a chat for channel", but although this makes the error go away, I still cannot see the results of the poll in the Channel I posted it.

Upon entering my choices, I just get a Thank You message instead of the current poll results. I understand the response is sent back & might be interpreted in PowerApps, but that's not what I'm looking for - I just want the poll to be posted & people to vote on it & see results.

So, is the poll-generator-sample JSON created by @MSFTMan meant to function like a normal Poll post (created manually, in Teams via Forms), or not? 

I'm currently looking for any further options that allow me to specify the properties of my created poll & simply set the options I have if I create it manually:
`[√] Share results automatically after voting`
and
`[√] Keep responses anonymous`

Thanks

<img width="539" alt="Screenshot 2021-12-08 at 13 17 05" src="https://user-images.githubusercontent.com/22143583/145207207-d93f122f-be49-4857-8508-70a1b14f9dde.png">
!

**Comment by aconstantin2** [comment]
Any thoughts on this please?

**Comment by MSFTMan** [comment]
@aconstantin2 Thanks for using Power Automate. This sample isn't designed to post the results of the poll. Consider using the [support options available](https://powerautomate.microsoft.com/en-us/support/) to help address your specific scenario.
