### ISSUE TITLE
HTML Code for Power Automate Confusing Step

### ISSUE THREAD

**Issue by ducktapeonmydesk** [MicrosoftDocs/power-automate-docs#622]
I've followed the instructions for how to send a ["beautifully formatted email" in power automate](https://docs.microsoft.com/en-us/power-automate/email-customization).  However, I kept running into the issue after step 7 where I couldn't click the </> button again.  It took me a **long** time to realize that you don't click it again - you have to click save.

Can you please add a step 8 that clarifies that?

**Comment by MSFTMan** [comment]
@ducktapeonmydesk Thanks for using Power Automate. We've added another step to let makers know that they must click **Save** and then test the flow. You'll see the update publicly in the next day or two.
