### ISSUE TITLE
Provide examples or Syntax information for boxes in these actions. 

### ISSUE THREAD

**Issue by lordneeko** [MicrosoftDocs/power-automate-docs#623]
I came to this page looking for syntax examples because, on Power Automate Desktop it will error with "Syntax Error" but not provide any details on what the syntax is supposed to look like

Your site doesn't give any help on the syntax either. I'm trying to figure out the correct syntax for the "Custom Headers" and the "URL" boxes of the "Invoke Web Service" action.  I've got a webservice that uses the APIkey in the URI parameters and the URL box says that is a syntax error. So I was going to try to pass it in the header instead, and that says syntax error also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8e2976-904f-3f49-3763-258921756883
* Version Independent ID: ed1857b9-0cb8-af4c-73e1-2c0e1144b75f
* Content: [Automation in the web - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/automation-web)
* Content Source: [articles/desktop-flows/automation-web.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/automation-web.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @lordneeko, thank you for helping us improve our documentation page! We are working on adding more examples regarding the configuration of the "Invoke web service" action, and you will be able to see the changes soon. 

Please, keep in mind that each web service requires a different configuration and structure, so there isn't a universal solution for every possible scenario. Refer to the documentation of the API you want to use to find more information regarding the required URL syntax, headers, and body.
