### ISSUE TITLE
Extensão POwer Automate no Power BI Desktop

### ISSUE THREAD

**Issue by vitorconti97** [MicrosoftDocs/power-automate-docs#624]
Olá, tudo bem?

Estou com um problema e queria saber se podem me ajudar.

Estou tentando criar um fluxo no Power Automate através do Power BI usando a extensão. Eu incluo os dados que desejo que o fluxo envie mas na hora de configurar as ações a tela fica em branco e não consigo seguir. Sabem oque pode ser?
![Capturar](https://user-images.githubusercontent.com/95830242/145307740-04d837f2-5db7-4c6e-8ff9-e6f48e63d508.PNG)

**Comment by MSFTMan** [comment]
Translation:
Hello how are you?

I have a problem and I was wondering if you could help me.

I'm trying to create a flow in Power Automate through Power BI using the extension. I include the data I want the flow to send but when I configure the actions the screen is blank and I can't follow. Do you know what it could be?

**Comment by MSFTMan** [comment]
@vitorconti97 Thanks for using Power Automate. This sounds like a support request. You can get support from any of the following options: https://powerautomate.microsoft.com/en-us/support/ 
Thanks!
