### ISSUE TITLE
Phone app can't add var steps

### ISSUE THREAD

**Issue by iaanw** [MicrosoftDocs/power-automate-docs#625]
Turns out you can't add any variable-related steps on the phone app (Android 12). They just don't appear as options when searching for actions to add. 

Might be worth calling this out on the prereqs section or if there's a phone : web portal comparison topic or something? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79901a7-7164-ab0f-3b0e-27a1714653af
* Version Independent ID: ccbe5229-3334-ccb3-26df-4530dfaa3786
* Content: [Store and manage values in variables - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-variable-store-values)
* Content Source: [articles/create-variable-store-values.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-variable-store-values.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@iaanw Thanks for using Power Automate. I've confirmed that variables aren't available on my Android device. We've added a note to let makers know that they cannot create this flow on a mobile device since variables aren't available.
