### ISSUE TITLE
IP address missing

### ISSUE THREAD

**Issue by xuehzhu** [MicrosoftDocs/power-automate-docs#626]
[Enter feedback here]
SomeIP address seems not listed in this document. For example, IP 13.70.78.224 is not listed in Australia region
 https://docs.microsoft.com/en-us/power-automate/ip-address-configuration

The other document has more IP address and contains IP 13.70.78.224
https://docs.microsoft.com/en-us/connectors/common/outbound-ip-addresses#power-platform

This would be misleading to cx. Pleaese help clarify the difference.
Also in the document : https://docs.microsoft.com/en-us/connectors/common/outbound-ip-addresses#:~:text=Use%20the%20following%20IP%20addresses%20in%20your%20allow%20list%20to%20facilitate%20Power%20Platform%20requests.
It says: " Use the following IP addresses in your allow list to facilitate Power Platform requests." It's not called facilitate. From customer testing they confirm flow is actually using the IP address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6e3dd3-5411-0304-205e-d5cb1af3b387
* Version Independent ID: 0bbab5a5-458b-7d88-028c-51e20039b2b6
* Content: [IP address configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/ip-address-configuration)
* Content Source: [articles/ip-address-configuration.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/ip-address-configuration.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @masisley
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@xuehzhu Thanks for reporting this issue about the missing IP addresses. We've updated this document to point to the common list of IP addresses for Power Platform. You will see this update within 24 hours.

"Facilitate" is used to me "use". So the wording is correct. Thank you.
