### ISSUE TITLE
Before eMail is actually sent, how to preview output from Flow ?

### ISSUE THREAD

**Issue by sunnyintoronto** [MicrosoftDocs/power-automate-docs#627]
I need to make changes to eMail before Flow send it out. How to Build such Flow?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ff9b6a8-6184-29e5-61ea-ae610a6082d7
* Version Independent ID: 45fce21f-9715-ac39-ddc9-55d97d835535
* Content: [Customize Email with Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/email-customization)
* Content Source: [articles/email-customization.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/email-customization.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@sunnyintoronto Thanks for using Power Automate. In this forum, we aren't able to give advice on how to build specific flows for specific scenarios. You might want to check out the dynamic content, which gives you access to most of the data that's available in a flow at design time and run time. You can access the dynamic content in which you are interested and then modify it using string expressions before you include it in the body of an email in Power Automate. Good luck.
