### ISSUE TITLE
Power Automate Flows as Templates

### ISSUE THREAD

**Issue by iddycol** [MicrosoftDocs/power-automate-docs#628]
I was looking for an answer to the question s it possible to create and share templates privately (either within and organisation or across organisations) - this page may benefit from an answer to that question (I presume it is currently not supported)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf8d0d2-3a6f-c3f1-494d-b0ea73c22f9b
* Version Independent ID: 41bc35b2-5a4d-7406-1ae7-27b292033fcd
* Content: [Submit a cloud flow template - Power Automate](https://docs.microsoft.com/en-us/power-automate/publish-a-template)
* Content Source: [articles/publish-a-template.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/publish-a-template.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@iddycol Thanks for reporting this issue. Templates are for the public gallery only. We've updated the article and you'll see this update within 24 hours.
