### ISSUE TITLE
Differences between numerous Power Automates

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/power-automate-docs#629]
Hi,
It would be grate if you could explain the differences between numerous Power Automates. I can see that there are at least 3 different mentions of Power Automate: Power Automate, Power Automate Desktop and Power Automate for desktop. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6870e9fe-dca9-66a8-1cd0-0000b83f385c
* Version Independent ID: ca5edb5e-80c3-05ef-b5aa-7c607f5cc706
* Content: [Overview of the types of flows in Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/flow-types)
* Content Source: [articles/flow-types.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/flow-types.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by mariosleon** [comment]
Hello @gvggvg, thank you for using Power Automate. Power Automate is the web application with which you may automate tasks on the web creating cloud flows. Similarly, it's desktop version is Power Automate for desktop with which you form desktop flows. Power Automate Desktop is a previous official name of Power Automate for desktop.
