### ISSUE TITLE
Exchange version accepted

### ISSUE THREAD

**Issue by Mesquita07** [MicrosoftDocs/power-automate-docs#631]
To connect from microsoft exchange, there is only until 2013 sp1 version. 
The version that i used to connect in my exchange is Exchange/15.20.4778.018. 2016. 

There are any other way to have sucssess in connect with exchange?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ee22751a-ede8-9d9e-f173-afb7b51385a5
* Version Independent ID: 0bec19de-95a0-79b4-37f0-e771fa1415f0
* Content: [Exchange - Power Automate](https://docs.microsoft.com/pt-br/power-automate/desktop-flows/actions-reference/exchange#connecttoexchangeserver)
* Content Source: [articles/desktop-flows/actions-reference/exchange.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/exchange.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @Mesquita07, thank you for using Power Automate. Please note that you may use the 2013 option for MS Exchange 15 as well.

Also please keep in mind that you may ask technical questions in the [Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to questions and suggest solutions.
