### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by gtacchini** [MicrosoftDocs/power-automate-docs#633]
[Enter feedback here]

The workflow processes link is broken and showing 404 error.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7759368-a61e-08ce-e24f-b43a200521dd
* Version Independent ID: 80c1d8d8-a995-1023-91f9-0a1fd687c5b6
* Content: [Create a business process flow in Power Apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-business-process-flow)
* Content Source: [articles/create-business-process-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-business-process-flow.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @vashr
* Microsoft Alias: **vashr**

**Comment by mariosleon** [comment]
Hello @gtacchini, thank you for reporting this issue. It's being fixed and will be updated soon.
