### ISSUE TITLE
Environment URL Change affects flows 

### ISSUE THREAD

**Issue by elifesy** [MicrosoftDocs/power-automate-docs#635]
[Enter feedback here]
#Environment URL Change:
After changing the environment URL, the flows will stop working till you open and save the flow ... then it starts to trigger 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41be07d3-6596-29e2-f9c6-449db00254dd
* Version Independent ID: 7a282d6d-0b39-ed50-6dbe-2b726662ea39
* Content: [Troubleshoot common issues with triggers - Power Automate](https://docs.microsoft.com/en-us/power-automate/triggers-troubleshoot)
* Content Source: [articles/triggers-troubleshoot.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/triggers-troubleshoot.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@elifesy Thanks for using Power Automate. We've update the document with this troubleshooting step.
