### ISSUE TITLE
Document meanings of parentheses, curly braces, and any options

### ISSUE THREAD

**Issue by DaveKriewall** [MicrosoftDocs/power-automate-docs#636]
[Enter feedback here]
I cannot find any documentation explaining the use of parentheses following another key.  The following example is given in this article:
`{Control}({B})`
without any explanation what purpose the parentheses serve.  I am guessing they exist to delimit the scope of the {Control} key, but it would be nice to confirm that.

There is also no explanation why the `B` above is enclosed in curly braces `{B}`.  Is there some subtle distinction between generating a Unicode letter B and pressing the key with a letter B label?  What if anything would be wrong or different if I specified `{Control}(B)` ?

I have seen examples given of an optional "colon: number" syntax which purports to generate multiple keystrokes, e.g.
`{Up:4}`
would generate four presses and releases of the `Up` key.  This option does not seem to be documented anywhere.  There may be other such options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da493128-4cee-6e87-d610-5725718616b4
* Version Independent ID: 53a253b5-d157-24ee-9cff-08deb60d7f5c
* Content: [Automate applications using keyboard shortcuts - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/how-to/automate-applications-keyboard-shortcuts)
* Content Source: [articles/desktop-flows/how-to/automate-applications-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/automate-applications-keyboard-shortcuts.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @DaveKriewall, thank you for sharing your feedback and helping us improve the Power Automate documentation page. We are working on adding information regarding the mentioned topics, and you'll be able to see the updated content soon.

The curly brackets notation makes the action simulate the key's physical press. If you enter a character without brackets, the action will populate it as a hardcoded text in the focused field.

The parentheses indicate that the keys inside them will be pressed simultaneously with the modifier key. If you don't enclose the second key inside parentheses, the two keys will be sent separately.
