### ISSUE TITLE
"Run a flow built with Power Automate for desktop action" is totally changed?

### ISSUE THREAD

**Issue by afantima** [MicrosoftDocs/power-automate-docs#637]
![image](https://user-images.githubusercontent.com/46115099/147516713-ec113c2c-d244-4f65-95c5-25a33bbdd38b.png)
I need setup "connect" when I select "Run a flow built with Power Automate for desktop action".
Nothing about this in the article, maybe this plugin is totally changed?
I'm gated here.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482ae90c-6a0a-f8c6-05cb-660ad43ba0e0
* Version Independent ID: 770951a1-ea51-bb85-f6a3-f7d9148510a5
* Content: [Create a Power Automate desktop flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/create-flow)
* Content Source: [articles/desktop-flows/create-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/create-flow.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @afantima, thank you for using Power Automate and helping us improve our documentation page! We are currently working on adding more information regarding machines and you will be able to see the updated article soon.

The configuration of the action remains the same as presented in the respective article. The settings displayed on your screenshot appear only if you haven't already created a connection to your machine. 

You have to register a machine through Power Automate for desktop settings, and then populate the respective fields in the action. You can find more information regarding the machines and how to configure them [here](https://docs.microsoft.com/en-us/power-automate/desktop-flows/manage-machines).
