### ISSUE TITLE
Rushed page... not real good info on the type of details output

### ISSUE THREAD

**Issue by VFXpro** [MicrosoftDocs/power-automate-docs#642]
**Get details of web page** section doesn't even list the type of data output nor provide examples.  Web URL? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a720f49a-5556-3766-7093-1034adbaa169
* Version Independent ID: ec081829-d7e8-f673-207e-43c247146216
* Content: [Browser automation - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/webautomation#getdetailsofwebpage)
* Content Source: [articles/desktop-flows/actions-reference/webautomation.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/webautomation.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @VFXpro, thank you for pointing out this issue! We are currently working on adding a new how-to article regarding the "Get details of web page" action, and you will be able to see the new content soon. Presently, we provide a quick reference of the action in the [Automate web flows](https://docs.microsoft.com/power-automate/desktop-flows/automation-web#web-data-extraction) article.
