### ISSUE TITLE
Custom Controls In Business Process flows outdated

### ISSUE THREAD

**Issue by PandaBoy00** [MicrosoftDocs/power-automate-docs#643]
Hi there,

Following the instructions provided by this page link me to a 2019 Power Automate Community Blog, in which I follow the step by step as listed on the blog.  The listed instructions doesn't work at all and custom controls wasn't added to the Business Process Flows.

Are there updated instructions? Are the instructions out of date or this feature isn't supported anymore?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 792c0e95-24ac-c787-6549-d778dfd86b12
* Version Independent ID: 8e67638d-5793-2554-2372-168c2e2eb866
* Content: [Use custom controls in business process flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/custom-controls-business-process-flows)
* Content Source: [articles/custom-controls-business-process-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/custom-controls-business-process-flows.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by KendalBond007** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.flow.microsoft.com. Closing this issue.
