### ISSUE TITLE
The API appears to not allow update flows or turn on flows

### ISSUE THREAD

**Issue by xuyen1** [MicrosoftDocs/power-automate-docs#644]
Hello team, 

I am able to use the API to list flows, turn off flows. However when trying to update the flows or turn on the flows, I got this error:
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"BapListServicePlansFailed","message":"{\"error\":{\"code\":\"MissingUserDetails\",\"message\":\"The user details for tenant id 'c3e4d7bf-e647-42c6-983c-94d5d6329072' and principal id '12f7a44c-e9f3-4f36-8558-d0ad4e88b8b3' doesn't exist.\"}}"}}".
![image](https://user-images.githubusercontent.com/54014335/149046689-5dd1ad14-0263-45a6-b97d-9754c0276474.png)

The user does exist. It is an application user with System admin role. Using that account the flow is able to list flows and turn off flows successfully. However when trying to update flows or turn on the flows, the error occurred. 

Could you please look into this?
Please feel free to let me know if you require further information. 

Regards
Susan Nguyen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eecc2503-eee7-8779-2445-d6cd6968a0bd
* Version Independent ID: 532be787-8be9-c9b5-37a2-88841c5b8118
* Content: [Flows are now stored in Dataverse and use the rich Web API - Power Automate](https://docs.microsoft.com/en-us/power-automate/web-api#list-flows)
* Content Source: [articles/web-api.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/web-api.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* Product: ****
* Technology: ****
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by fowl2** [comment]
these links might help

https://docs.microsoft.com/en-us/power-platform/admin/troubleshooting-user-needs-read-write-access-organization#user-is-missing-from-environment-despite-meeting-all-requirements

https://docs.microsoft.com/en-us/connectors/powerplatformforadmins/#force-sync-user

**Comment by KendalBond007** [comment]
Thanks for your feedback. If you continue to encounter this issue, or have other product-related feedback, visit https://ideas.flow.microsoft.com. Closing this issue.
