### ISSUE TITLE
Known issue is not applicable anymore, please remove

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/power-automate-docs#645]
[Enter feedback here]
The following known issue is not true anymore. As of Jan 2022, approvals sent in any environment in the tenant will show in the approvers' Teams feed (if notification settings are set to ON in the flow and in the approvers's Teams)

> Known issues
> Currently, only approvals sent in your organization's default environment are listed within the approvals app in Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca92526-b28b-a548-8e40-6f76e7f4e37d
* Version Independent ID: 01bf30de-2382-b6b1-d643-ccc4fef999ff
* Content: [Respond to an approval in Microsoft Teams - Power Automate](https://docs.microsoft.com/en-us/power-automate/teams/respond-to-approvals-in-teams)
* Content Source: [articles/teams/respond-to-approvals-in-teams.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/teams/respond-to-approvals-in-teams.md)
* Service: **power-automate**
* Sub-service: **teams**
* GitHub Login: @MSFTMan
* Microsoft Alias: **hamenon**

**Comment by MSFTMan** [comment]
@hamenon-ms Hi Harysh, is this correct? Thanks!

**Comment by fowl2** [comment]
The Teams notification feed shows from all environments, but the Teams Approvals app only shows one environment at a time.

**Comment by MSFTMan** [comment]
@user0604 Thanks for reporting this issue. We've removed this known issue because it no longer applies. You'll see the update live in the next day or two.
