### ISSUE TITLE
アクションとトリガーへのコメント追加に関するドキュメント更新のお願い

### ISSUE THREAD

**Issue by AnoTarai3** [MicrosoftDocs/power-automate-docs#646]
このドキュメントでは、ユーザーがコメントを追加できるようになるには、少なくとも一度はフローを保存する必要があると書かれています。

現在はその通りだと思いますが、2021年11月以前に作成したフローを開くと、自動的に保存されているようです。
フローを作成した時期によって動作が異なるのは、多くのユーザーにとって想定外のことだと思います。

このように自動的にフローを保存するのは一度だけだが、説明と異なるため、ユーザーを混乱させる原因となる。

以下のようにアップデートして、それに関する記述を追加することをお勧めします。
多くのユーザーにとって有益な情報になると思います。

-----------------------------------------------
既知の問題

・2021 年 11 月以前に作成したフローを開いた場合は自動で保存される動作をする場合がございます。この事象はフローごとに 1 回のみ発生する事象で、ユーザーに影響は与えません。
-----------------------------------------------

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 020e0c95-525b-eebd-d7f6-eb2214e5d6e9
* Version Independent ID: 8ce00223-24fb-809c-b97f-9cd7996aa25c
* Content: [詳細オプションと複数のアクションの追加 - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/multi-step-logic-flow#limitations)
* Content Source: [articles/multi-step-logic-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/multi-step-logic-flow.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
Translation to English:
This document states that the flow must be saved at least once before users can add comments.

I think that's true now, but when you open a flow you created before November 2021, it seems to be automatically saved.
I think it's unexpected for many users that the behavior varies depending on when the flow was created.

This way, you only save the flow automatically once, but it's different from the description, which confuses the user.

We recommend that you update to include a description of it as follows:
I think it will be useful information for many users.

**Comment by KendalBond007** [comment]
Translation of suggested text:

・ If you open a flow created before November 2021, it may be saved automatically. This is a one-time occurrence per flow and does not affect the user.

This wouldn't be specifically about the date, but the product version that created the flow. This could be mentioned in a [!NOTE] addressing earlier versions.

**Comment by KendalBond007** [comment]
Thanks for your feedback. For product-related feedback, visit https://ideas.flow.microsoft.com. Closing this issue
