### ISSUE TITLE
Help doc update: desktop trigger from cloud flow

### ISSUE THREAD

**Issue by chilismaug** [MicrosoftDocs/power-automate-docs#648]
I believe the sentence "You will need the on-premises data gateway to trigger your desktop flows from a cloud flow." is no longer true in 2022.
 
 I have been triggering desktop machine connections from cloud flows since autumn 2021.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6cfbc11-176d-228c-a8cb-ef229a9a5d62
* Version Independent ID: 5c96eafd-b9cc-507b-4b8c-8de7c4210c6f
* Content: [Install Power Automate on your device - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/install)
* Content Source: [articles/desktop-flows/install.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/install.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @chilismaug, thank you for pointing out this issue and helping us improve our documentation page! We are currently working on making it more clear that users can use either on-premises data gateways or direct connectivity, and you will be able to see the changes soon.
