### ISSUE TITLE
2 instances of "folder" misspelled as "fodler"

### ISSUE THREAD

**Issue by spamspambaconspam** [MicrosoftDocs/power-automate-docs#653]
misspelling:
https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/outlook#processemailmessages

Under OPERATION Argument:

2 instances of "folder" misspelled as "fodler"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc53dfd-8c62-11ff-78a8-a6cae06bc4ac
* Version Independent ID: 2f5b95d6-fb4a-61a6-0fdf-52b18975c901
* Content: [Outlook - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/outlook#processemailmessages)
* Content Source: [articles/desktop-flows/actions-reference/outlook.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/outlook.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @spamspambaconspam thank you for reporting this issue. It's being corrected and will be available very soon.
