### ISSUE TITLE
Skip Field with Expression

### ISSUE THREAD

**Issue by fogalvin** [MicrosoftDocs/power-automate-docs#655]
I am trying to use expression to update a field only if a value was included. However, running an if(empty()) results in a null for true. There is no way to skip a field using expressions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8802ae53-70d7-7bb2-4c85-7b0cf5cb644c
* Version Independent ID: 14a2af80-479a-b7d6-0a5d-9aa675a3fe92
* Content: [Use a flow to update a row in Dataverse - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/update)
* Content Source: [articles/dataverse/update.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/update.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@fogalvin Thanks for reporting this issue. Have a look at https://docs.microsoft.com/en-us/power-automate/use-expressions-in-conditions#use-the-empty-expression for a tutorial on how to use expressions. I hope that helps.
