### ISSUE TITLE
Fanstastic docs page!

### ISSUE THREAD

**Issue by anttipajunen** [MicrosoftDocs/power-automate-docs#656]
Just want to say this is a fantastic docs page and very well written! I whish this level of quality would go to all docs pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963ac648-0f69-902f-c752-2223cfd895ba
* Version Independent ID: 963ac648-0f69-902f-c752-2223cfd895ba
* Content: [Get started with task mining in process advisor - Power Automate](https://docs.microsoft.com/en-us/power-automate/task-mining-tutorial#feedback)
* Content Source: [articles/task-mining-tutorial.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/task-mining-tutorial.md)
* Service: **power-automate**
* Sub-service: **process-advisor**
* GitHub Login: @nijemcevic
* Microsoft Alias: **tatn**

**Comment by MSFTMan** [comment]
@anttipajunen Thank you for the feedback. I'll pass it on to the team.
