### ISSUE TITLE
Where can I find the Row ID

### ISSUE THREAD

**Issue by Jcodaar** [MicrosoftDocs/power-automate-docs#657]
Nice document, but I wonder where can I get the Row ID from? 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 32d2fb7a-7614-bba8-c2da-52bc048812f3
* Version Independent ID: b4ade253-98f4-96f3-548b-7bc5e4b38af8
* Content: [Een rij ophalen uit Dataverse op id - Power Automate](https://docs.microsoft.com/nl-nl/power-automate/dataverse/get-row-id)
* Content Source: [articles/dataverse/get-row-id.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/get-row-id.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@Jcodaar You would need to create an action in the flow that gets the row id that you need. For example, create a query to get rows that meet your criteria and then get the specific row id that you need from the dynamic content for previous steps. I've updated the document to reflect this suggestion. Thank you.
