### ISSUE TITLE
Clarify documentation for Scope - User

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/power-automate-docs#658]
Please clarify in the text on this page when settings "Scope to user", state whether that scoped user means the modified by field of the record must match user that is set as the Flow Connection for the Dataverse. Does this mean the flow will not trigger if the user used in the connection to dataverse is not the user currently making the modification. Or will the flow on this dataverse record trigger for every edit regardless of the dataverse connection user

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c84a31-4f63-6ee1-ad15-096cae44cb41
* Version Independent ID: de8cf5bc-b78b-a88e-696f-7755e3ce22f0
* Content: [Trigger flows when a row is added, modified, or deleted - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/create-update-delete-trigger)
* Content Source: [articles/dataverse/create-update-delete-trigger.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/create-update-delete-trigger.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by KendalBond007** [comment]
Thanks for contacting us. The Scope heading describes the ownership scope for Users. For additional information, contact Support at: https://flow.microsoft.com/support/ Closing this issue.
