### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by Modris-lat** [MicrosoftDocs/power-automate-docs#659]
[Enter feedback here]
Very limited information on how to convert from text to date time, no default input output examples. Should I use /,-,. symbols between days month and years.

---
#### Docum
![Screenshot 2022-01-31 125202](https://user-images.githubusercontent.com/63401754/151781642-7b0ab44a-6d51-4720-8a95-5ac7800a4ff3.png)
ent Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263c52c4-e89d-2fa5-c8d5-d791e3a37350
* Version Independent ID: 9afb1a06-c257-07c7-f50a-6697a28a811b
* Content: [Text | Microsoft Docs - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/text#feedback)
* Content Source: [articles/desktop-flows/actions-reference/text.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/text.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @Modris-lat, thank you for your feedback and for helping us improve our documentation page! We are currently working on adding a how-to section regarding the text-datetime conversion, and you will be able to see the new content soon.

The default format for the dates to convert depends on the region settings of your machine. The custom format supports the notations presented in [this article](https://docs.microsoft.com/en-us/power-automate/desktop-flows/variable-data-types#dates-and-time). You can separate the day, month, and year parts with dots, forward slashes, or dashes.
