### ISSUE TITLE
URL returns a 404

### ISSUE THREAD

**Issue by garybushey** [MicrosoftDocs/power-automate-docs#661]
The URL in step 3 returns a 404 error message

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5ba2f6-b1cd-bb14-744b-1eadc98608d4
* Version Independent ID: 4689a032-aa04-36b4-b448-37357f32b522
* Content: [Use RPA with Dynamics 365 Finance - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/dynamics365-fin-rpa)
* Content Source: [articles/desktop-flows/dynamics365-fin-rpa.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/dynamics365-fin-rpa.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by mariosleon** [comment]
Hello @garybushey, thank you for reporting this issue. We resolved it and will be updated in a few hours.
