### ISSUE TITLE
Inconsistent request limits between two pages

### ISSUE THREAD

**Issue by Craig-Humphrey** [MicrosoftDocs/power-automate-docs#662]
Hi,
I'm just trying to optimize the licensing for a client and was stoked to see that [Power Apps per user (in medium)](https://docs.microsoft.com/en-us/power-automate/limits-and-config#action-request-limits) now has a 100,000 request limit per day.

However, the [API Request Limits](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#licensed-user-request-limits) page still has it sitting at 40,000 requests per day.

Can you please confirm that 100,000 is correct? And if so, give the owner of the incorrect page a nudge :)

Thanks
Craig

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/limits-and-config.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by Craig-Humphrey** [comment]
This is in no way related to [#707](https://github.com/MicrosoftDocs/power-automate-docs/issues/707)

**Comment by MSFTMan** [comment]
@Craig-Humphrey Thanks for reporting this issue. Kindly note that the 100,000 requests per day is only available during the transition period. After the transition period, the number of requests per day reverts to the 40,000 request per day. We will clarify the document. More info on the transition period is available here: https://docs.microsoft.com/en-us/power-platform/admin/power-automate-licensing/types#transition-period
