### ISSUE TITLE
检索 Outlook 中的电子邮件 问题

### ISSUE THREAD

**Issue by zanghao268** [MicrosoftDocs/power-automate-docs#673]
[在此处输入反馈]
From contains 里填写完整邮件地址，无法搜索到结果。
Subject contains里填写内容，是可以搜索到结果。

请问是否有需要注意的地方

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6fc53dfd-8c62-11ff-78a8-a6cae06bc4ac
* Version Independent ID: 2f5b95d6-fb4a-61a6-0fdf-52b18975c901
* Content: [Outlook - Power Automate](https://docs.microsoft.com/zh-cn/power-automate/desktop-flows/actions-reference/outlook#retrieveemailmessages)
* Content Source: [articles/desktop-flows/actions-reference/outlook.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/outlook.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
English translation:

Fill in the full email address in From contains, and the search result cannot be found.
Fill in the content in Subject contains, and you can search for results.

Is there anything to pay attention to?

**Comment by georgiostrantzas** [comment]
Hello @zanghao268, thank you for using Power Automate for desktop. As this question concerns a technical issue, not a documentation issue, we would kindly ask you to post your question to the [Power Automate community](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity), where technical experts can assist you.
