### ISSUE TITLE
Unclear Custom Connector limits

### ISSUE THREAD

**Issue by eBentl** [MicrosoftDocs/power-automate-docs#674]
The 'Limits and configuration - Power Automate' page suggests M365 licenses allow a user to run a single Flow using Custom Connectors, while also saying that any use of Custom Connectors requires a premium license.

I also can't find any reference elsewhere to M365 licenses granting any entitlement for Custom Connectors - is this information correct? And if so can this be clarified and referenced in the Power Platform Licensing Guide.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/43974241/155285130-1d53fbf3-48a3-4bc6-a9a7-1bc9a601cce4.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7b1f84-92bd-7188-a7d0-359a930525dd
* Version Independent ID: dd7d2d01-bdee-b656-ca63-e19305963d28
* Content: [Limits and configuration - Power Automate](https://docs.microsoft.com/en-us/power-automate/limits-and-config#custom-connector-limits)
* Content Source: [articles/limits-and-config.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/limits-and-config.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@eBentl Thanks for using Power Automate. The note about Microsoft 365 license is an error. We will remove it. Thank you for reporting this issue.
