### ISSUE TITLE
Typo - Extra Word

### ISSUE THREAD

**Issue by Digim1** [MicrosoftDocs/power-automate-docs#675]
Looks like an additional word in this particular line.
![image](https://user-images.githubusercontent.com/100302825/155361263-c725a6fe-861d-4939-a75f-dce0ea5500f5.png)

Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b01c8ef-c2d3-f6e0-f137-94352bbe8ef6
* Version Independent ID: fdc71451-fa34-f6ca-5652-ffc261282957
* Content: [Troubleshoot known issues with Forms in flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/forms/troubleshoot-issues#feedback)
* Content Source: [articles/forms/troubleshoot-issues.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/forms/troubleshoot-issues.md)
* Service: **power-automate**
* GitHub Login: @Dean-Haas
* Microsoft Alias: **napienko**

**Comment by MSFTMan** [comment]
@Digim1 Thanks for reporting this issue. It's fixed. You'll see the updated document within 6 hours.
