### ISSUE TITLE
Broken link in documetnation

### ISSUE THREAD

**Issue by jesslyn-omm** [MicrosoftDocs/power-automate-docs#676]
In this (https://docs.microsoft.com/en-us/power-automate/dataverse/search#search-type) paragraph, there is a link to "[Search across table data using Dataverse search](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/relevance-search#searchmode-any--all-optional)" that leads to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d183b2-d2a2-d22e-2927-d013763207ca
* Version Independent ID: 3775a526-3765-a067-c48d-a663f08aa4dc
* Content: [Use Dataverse search to retrieve rows - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/search)
* Content Source: [articles/dataverse/search.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/search.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by KumarVivek** [comment]
This is fixed, and should be live shortly.
