### ISSUE TITLE
Cannot use code to add photos to body of email

### ISSUE THREAD

**Issue by WCarp** [MicrosoftDocs/power-automate-docs#677]
Cannot use code to add photos to body of Outlook email, Either the instructions are not clear or it doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d343d0b9-fdc2-5eb0-ba51-0b2ddabc90de
* Version Independent ID: 888e8708-1b7c-4da9-cd0e-6384801d9f4c
* Content: [Add images to email messages - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/how-to/add-images-email-messages?WT.mc_id=365AdminCSH_OfficeHome)
* Content Source: [articles/desktop-flows/how-to/add-images-email-messages.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/add-images-email-messages.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @WCarp, thank you for reporting this issue. Could you please upload a screenshot of your flow so we can replicate this specific scenario? We ran some testing flows, and the presented HTML code has worked as expected.

**Comment by georgiostrantzas** [comment]
The issue has been closed because we didn't receive a response.
