### ISSUE TITLE
Power Automate supports Power BI Actions in government cloud

### ISSUE THREAD

**Issue by Hikmer** [MicrosoftDocs/power-automate-docs#679]
this is incorrect [Power BI](https://docs.microsoft.com/en-us/connectors/powerbi/) – Power Automate US Government doesn’t support Power BI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d0a9ce-bdc6-9f60-fecb-eb5cabfe21ee
* Version Independent ID: d2267099-da75-d3d7-77cf-af41fcc1cf1e
* Content: [Power Automate US Government - Power Automate](https://docs.microsoft.com/en-us/power-automate/us-govt)
* Content Source: [articles/us-govt.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/us-govt.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by RedsGT** [comment]
#1596 @MSFTMan This has been resolved and can be closed.

**Comment by MSFTMan** [comment]
@Hikmer We've updated the documentation. Thank you.
