### ISSUE TITLE
PA desktop Can't sign in with your current license

### ISSUE THREAD

**Issue by MlleBaeten** [MicrosoftDocs/power-automate-docs#681]
Looking at my Microsoft work account > Subscriptions, I see that I have a Power Automate for Office 365 license, and I can create flows in Power Automate web app.
I was able to download and sign into the Power Automate desktop app, however, I can't see any of my cloud flows, and when I try to troubleshoot with the Power Automate machine runtime, it gives me the following error message:
**Can't sign in with your current license**
You need an organization premium account to register your machine. You can start a free trial or purchase a Power Automate licence to unlock the full spectrum of RPA features.
Error details
Correlation Id: 62b62234-dd58-4242-b07f-7c57897c5b9f

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9b37b6-0532-03f9-e18d-41cd43f8dfdf
* Version Independent ID: 16444576-b3ce-78e0-37f7-e0cab9c9c13e
* Content: [Troubleshooting Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/troubleshoot)
* Content Source: [articles/desktop-flows/troubleshoot.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/troubleshoot.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by cochamos** [comment]
> Looking at my Microsoft work account > Subscriptions, I see that I have a Power Automate for Office 365 license, and I can create flows in Power Automate web app. I was able to download and sign into the Power Automate desktop app, however, I can't see any of my cloud flows, and when I try to troubleshoot with the Power Automate machine runtime, it gives me the following error message: **Can't sign in with your current license** You need an organization premium account to register your machine. You can start a free trial or purchase a Power Automate licence to unlock the full spectrum of RPA features. Error details Correlation Id: 62b62234-dd58-4242-b07f-7c57897c5b9f
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 0d9b37b6-0532-03f9-e18d-41cd43f8dfdf
> * Version Independent ID: 16444576-b3ce-78e0-37f7-e0cab9c9c13e
> * Content: [Troubleshooting Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/troubleshoot)
> * Content Source: [articles/desktop-flows/troubleshoot.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/troubleshoot.md)
> * Service: **power-automate**
> * Sub-service: **desktop-flow**
> * GitHub Login: @mariosleon
> * Microsoft Alias: **marleon**

Hey,

This is an expected behavior. With your O365 license you can sign-in to PAD as a free user, or use the free (non-premium) connectors in cloud flows. However, running a flow from the portal to your machine (via the machine runtime app) requires a premium connector and thus a RPA with attended licence (paid).
