### ISSUE TITLE
Japanese version of IE11 support description not yet corrected

### ISSUE THREAD

**Issue by Hiroyuki-Hayashi** [MicrosoftDocs/power-automate-docs#683]
[フィードバックをこちらに入力してください]
The Japanese version of the IE11 support description has not been corrected.
We think it should be removed.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cee8a6fc-8a07-bcf7-412f-21344c46f4c6
* Version Independent ID: 3289c7dd-3a4a-0d96-0e4c-e08689ab2c2d
* Content: [よくあるご質問 - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/frequently-asked-questions)
* Content Source: [articles/frequently-asked-questions.yml](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/frequently-asked-questions.yml)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
Thanks for the feedback. This has been fixed. Thanks!
