### ISSUE TITLE
Power Automate Desktop - EXE name changed

### ISSUE THREAD

**Issue by shanu77122** [MicrosoftDocs/power-automate-docs#684]
Note that the EXE name has changed from "Setup.Microsoft.PowerAutomateDesktop.exe" but the download now has a name change to "Setup.Microsoft.PowerAutomate.exe"
Just caught me out when delivering an update via Endpoint Manager.  The Guide still states the old name. https://docs.microsoft.com/en-us/power-automate/desktop-flows/install

**Comment by mariosleon** [comment]
Hello @shanu77122, thank you for raising this issue. We updated the docs and will soon reflect the change.
