### ISSUE TITLE
Incorrect and missing command line arguments

### ISSUE THREAD

**Issue by codyjm** [MicrosoftDocs/power-automate-docs#686]
In the _Command line argument details_ section, the command '-DISABLETURNONRD' is different from what is documented when passing -HELP to the installer - '-DISABLETURNONRDP'.

Some of the commands documented when passing -HELP to the installer are also missing from the documentation:
-ALLOWOPTIONALDATACOLLECTION
-RESTOREDEFAULTCONFIG
-DONOTINSTALLPAD
-DONOTINSTALLMACHINERUNTIME

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6cfbc11-176d-228c-a8cb-ef229a9a5d62
* Version Independent ID: 5c96eafd-b9cc-507b-4b8c-8de7c4210c6f
* Content: [Install Power Automate on your device - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/install#feedback)
* Content Source: [articles/desktop-flows/install.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/install.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @codyjm, thank you for pointing this out. We have updated the docs and will very soon show the available commands.
