### ISSUE TITLE
How to get all OneDrive sites using power automate?

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/power-automate-docs#687]
Is there a way to get all user OneDrive sites using power automate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee8a6fc-8a07-bcf7-412f-21344c46f4c6
* Version Independent ID: 3289c7dd-3a4a-0d96-0e4c-e08689ab2c2d
* Content: [Frequently asked questions - Power Automate](https://docs.microsoft.com/en-us/power-automate/frequently-asked-questions)
* Content Source: [articles/frequently-asked-questions.yml](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/frequently-asked-questions.yml)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by jaganpt** [comment]
Any update on this?

**Comment by MSFTMan** [comment]
@jaganpt Thanks for using Power Automate. Can you clarify what you mean exactly? All the functionality for OneDrive connector is available here: https://docs.microsoft.com/en-us/connectors/onedrive/.

**Comment by jaganpt** [comment]
Hi @MSFTMan,
I would like to fetch all one drive sites using power automate. But I don't find any way using power automate. Is there a way to get all user OneDrive sites using power automate?

**Comment by MSFTMan** [comment]
> Hi @MSFTMan, I would like to fetch all one drive sites using power automate. But I don't find any way using power automate. Is there a way to get all user OneDrive sites using power automate?

You can only use the actions that are available publicly. There isn't an action to get all sites. You can check the [community ](https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity)to see if others have come up with a workaround for this problem.
