### ISSUE TITLE
Use a Trigger Mid Flow?

### ISSUE THREAD

**Issue by EmEnglish** [MicrosoftDocs/power-automate-docs#690]
Article states triggers can be used mid-flow to delay actions. I've been unable to utilize this functionality and can't find it mentioned anywhere else. Is this a new/limited feature or is it an error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2533fa7-a9c2-5203-9d33-a04288246d0c
* Version Independent ID: 9465133e-bafd-b35d-c228-6587970da6ee
* Content: [Use wait conditions to delay flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/wait-conditions#feedback)
* Content Source: [articles/dataverse/wait-conditions.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/wait-conditions.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@EmEnglish Thanks for report this. A trigger can only be used at the start of a flow. I've fixed the typo in the sentence. You'll see the update in a few hours. Thanks!

**Comment by EmEnglish** [comment]
Thank you!
