### ISSUE TITLE
need to put message content into an input.text  (adaptive card)

### ISSUE THREAD

**Issue by Steve-Lutz** [MicrosoftDocs/power-automate-docs#692]
You show an image of selecting dynamic content and you can select Message Content.   I cannot see what you did to get to that selection screen.  I need the message content to show in my input.text on  the adaptive card.  I neither know how to hardcode in the Card Payload editor or put in the Element properties Default value. 

Please help!

Thank you.

Steve Lutz 
steve_lutz@byu.edu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47dafbdb-ccd0-0bf2-a83e-f465821a753c
* Version Independent ID: 049c241f-c017-5939-082a-ebbadaf5e4d1
* Content: [Trigger a cloud flow from any message in Microsoft Teams - Power Automate](https://docs.microsoft.com/en-us/power-automate/trigger-flow-teams-message#best-practices)
* Content Source: [articles/trigger-flow-teams-message.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/trigger-flow-teams-message.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **hamenon**

**Comment by MSFTMan** [comment]
@Steve-Lutz The dynamic content screen pops up when you tap/click into a field (such as a text box) where the dynamic content can go. Note that you must add the action that generates the dynamic content before you can then select that content from the list of dynamic content. Good luck!
