### ISSUE TITLE
Example of file extraction would be useful

### ISSUE THREAD

**Issue by IanPodmore** [MicrosoftDocs/power-automate-docs#694]
Having issue with downloading a file from Dataverse.  File will not open from download but will open if downloaded directly from D365CE

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25aa6ad7-bd9a-bae0-1e82-7e9c33378c2d
* Version Independent ID: b3b9583b-b5f4-a243-4220-48b9cf4f4a7c
* Content: [Upload or download image and file content - Power Automate](https://docs.microsoft.com/en-gb/power-automate/dataverse/upload-download-file)
* Content Source: [articles/dataverse/upload-download-file.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/upload-download-file.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@IanPodmore  Thanks for using Power Automate. We're investigating this issue.

**Comment by radioblazer** [comment]
@IanPodmore If still applicable, can you please share the type of file you are downloading, and what page or view the download is not working from?

**Comment by tapanm-MSFT** [comment]
Closing due to no response in long time. If issue persists, please feel free to reach out.
