### ISSUE TITLE
No documentation for "widgetStyleSettings" property

### ISSUE THREAD

**Issue by hoovercj** [MicrosoftDocs/power-automate-docs#695]
The page includes a code snippet for `sdk.renderWidget` where it passes an object with the property `widgetStyleSettings` but there is no documentation for what that that value is or how to use it.

```
var widget = sdk.renderWidget('<widgettype>', {
        container: 'flowDiv',
        flowsSettings: {},
        templatesSettings: {},
        approvalCenterSettings: {},
        widgetStyleSettings: {}
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac3ad92-eb8f-554a-5de3-14c430e594aa
* Version Independent ID: fab1ceb3-5110-4452-0a0d-99346cc31230
* Content: [Integrate Power Automate with websites and apps - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/embed-flow-dev)
* Content Source: [articles/developer/embed-flow-dev.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/developer/embed-flow-dev.md)
* Service: **power-automate**
* Sub-service: **developer**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@hoovercj Thanks for using Power Automate. This is an internal class, which we do not document. Thank you.

**Comment by hoovercj** [comment]
Perhaps the code snippet should be updated then to remove the internal
property, then? This is public documentation so it is confusing if there is
a property there with no documentation, especially because the line above
says

> "Be sure to provide the widget type and corresponding settings".

```diff
var widget = sdk.renderWidget('<widgettype>', {
        container: 'flowDiv',
        flowsSettings: {},
        templatesSettings: {},
        approvalCenterSettings: {},
-        widgetStyleSettings: {}
});
```
