### ISSUE TITLE
Compose

### ISSUE THREAD

**Issue by rogerprz** [MicrosoftDocs/power-automate-docs#698]
Do you guys not read your own examples? It is not clear what the compose input should be. You're saying use an array with integers but then somehow somewhere we have an array of emails? Can you provide clear examples of the inputs allowed and how they are referenced later? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79bddf7e-aad7-5b99-0b73-a893d25615f5
* Version Independent ID: f2f0c4d6-b613-d269-4756-bcd7548f76ec
* Content: [Understand data operations (contains video) - Power Automate](https://docs.microsoft.com/en-us/power-automate/data-operations)
* Content Source: [articles/data-operations.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/data-operations.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@rogerprz Thank you for your feedback. The different sections of this document use different examples to show how to use different data operations. In the compose action section (https://docs.microsoft.com/en-us/power-automate/data-operations#use-the-compose-action), it shows you how to use an array of integers. On the other hand, in the join action section (https://docs.microsoft.com/en-us/power-automate/data-operations#use-the-join-action) it shows you how to use an array of emails. I've updated the document to clarify this these sections are separate and not intended to be a full single example. Thanks for your feedback and have a great day.
