### ISSUE TITLE
Power Automate - Flow to delete apps not used after a period of time

### ISSUE THREAD

**Issue by ClaudiuVio** [MicrosoftDocs/power-automate-docs#699]
Hello,

As I said in the title I need to delete Power Apps that are not used for example after a period of time.

How I should approach this? Using a flow? Powershell(there is no way to check for example last access time for an app)?

**Comment by MSFTMan** [comment]
@claudiuVio Thanks for using Power Automate. This channel is specifically for issues found in the documentaion for Power Automate. Kindly check the support options available to you here: https://powerautomate.microsoft.com/en-us/support/ for questions about Power Automate. Thank you.
