### ISSUE TITLE
Clarification regarding licensing

### ISSUE THREAD

**Issue by mblennegard** [MicrosoftDocs/power-automate-docs#700]
This page mentions that if the owner of a flow is set to a service account, a per Flow plan license is needed.

![image](https://user-images.githubusercontent.com/27766499/159233923-78345e47-f86e-4a86-881a-df65567cf21f.png)

This definitely needs clarification.
Does this refer to only flows containing Premium connectors or even Standard connectors?
Does it really mean that a per Flow licence is needed instead of a per User plan for the service account?

Either way, this sort of licensing details needs to be available in the documentation regarding licensing and not hidden in a page like this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31cec7a2-60a1-ac2c-c4c4-a35594395b57
* Version Independent ID: 31cec7a2-60a1-ac2c-c4c4-a35594395b57
* Content: [Change the owner of cloud flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/change-cloud-flow-owner?utm_campaign=Power%20Platform%20Weekly&utm_medium=email&utm_source=Revue%20newsletter)
* Content Source: [articles/change-cloud-flow-owner.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/change-cloud-flow-owner.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@mblennegard Thanks for using Power Automate and for your feedback. We've updated the docs to claarify and link to the licensing documentation.
