### ISSUE TITLE
Lack of connectors available for on-premise data gateways

### ISSUE THREAD

**Issue by htakedah** [MicrosoftDocs/power-automate-docs#703]
Lack of connectors available for on-premise data gateway. 
Please add "SAP ERP" and "Desktop flow". Please add any others that are missing if it exists.
![image](https://user-images.githubusercontent.com/101810541/159392110-aadce451-b820-49fa-9fc5-ed2a8f009ab5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 213d2c56-a05d-0ba5-6165-f52e0eb1be7b
* Version Independent ID: b089a13e-14f0-116c-fcef-474760ee6068
* Content: [Learn to manage on-premises data gateways - Power Automate](https://docs.microsoft.com/en-us/power-automate/gateway-manage)
* Content Source: [articles/gateway-manage.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/gateway-manage.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by schabungbam** [comment]
Missing:
BizTalk Server
Desktop Flows
SAP ERP

**Comment by MSFTMan** [comment]
@htakedah Thanks for reporting this issue. We've updated the docs. You'll see the update in the next few hours.
