### ISSUE TITLE
文本错误

### ISSUE THREAD

**Issue by DaimuX** [MicrosoftDocs/power-automate-docs#704]
若要使流迭代访问页面上的所有链接，请使用 循环 操作。 循环应该从 0 开始，并以 %DataFromWebPage.Count-1% 结束。
应该改成
若要使流迭代访问页面上的所有链接，请使用 循环 操作。 循环应该从 0 开始，并以 %DataFromWebPage.RowsCount-1% 结束。
![屏幕截图 2022-03-23 123146](https://user-images.githubusercontent.com/87256073/159624470-67e1e2e7-83a4-494b-8880-9be3b78d1eae.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0fcb6665-095d-7494-87a4-6a56470e13af
* Version Independent ID: 87a6cfd0-846a-bbf5-4279-721fc5a01a72
* Content: [单击链接列表中的所有元素 - Power Automate](https://docs.microsoft.com/zh-cn/power-automate/desktop-flows/how-to/click-elements-list-links)
* Content Source: [articles/desktop-flows/how-to/click-elements-list-links.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/click-elements-list-links.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
English translation

‎To make the flow iteration access all the links on the page, use the Loop action. The loop should start at 0 and end with %DataFromWebPage.Count-1%. ‎

‎ Should be changed to‎

‎To make the flow iterate access to all links on the page, use the Loop action. The loop should start at 0 and end with %DataFromWebPage.RowsCount-1%.‎

**Comment by DaimuX** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我现在在休假，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。或者你可以打我电话和通过QQ联系我

**Comment by georgiostrantzas** [comment]
Hello @DaimuX, thank you for helping us improve the Power Automate documentation page. We have resolved the mentioned issue, and you will be able to see the changes soon.
