### ISSUE TITLE
Run a Child Flow Cannot be found following the steps mentioned in the document

### ISSUE THREAD

**Issue by KalapJo1** [MicrosoftDocs/power-automate-docs#705]
I've tried following the document mentioning the flow actions in which there is no action called Run a child Flow. Did the document miss any prerequisites or something is wrong said here? Can you please help me here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f42c36-4ce0-fff2-4cfb-e191c636edf4
* Version Independent ID: 510353c0-7e45-0302-d7d4-80c68bff7eb4
* Content: [Call Child Flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-child-flows)
* Content Source: [articles/create-child-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-child-flows.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by cmbUIT** [comment]
I am experiencing this issue as well. What are the recommended steps? Is this action no longer available? 
![2022-12-07_12h42_38](https://user-images.githubusercontent.com/94487679/206268595-b360f7a3-c32f-4863-836a-c49d61f155d7.png)

**Comment by xpac1985** [comment]
Almost exactly a year later, I'm hitting the same issue.
Workaround for me: Tell Copilot to "Add an action to call another flow" and it will add this action, although it cannot be found in the UI.
