### ISSUE TITLE
Incorrect implementation of "Outcome is equals to Approve"

### ISSUE THREAD

**Issue by Hiroyuki-Hayashi** [MicrosoftDocs/power-automate-docs#707]
I'm a member of CSS in Japan.
I am posting this because our customer pointed a video of this Page out to me.

The Condition shown at 4:10 of the video is as follows.
「Outcome is equals to Approve」

It was pointed out that this implementation might be wrong because the output of Outcome is "Approve, Approve" in the case of "everyone must approve".

We believe that the correct answer is as follows, as stated in the Community article.
「Outcome does not contain Reject」

https://powerusers.microsoft.com/t5/Building-Flows/New-approvals-don-t-have-response-option/m-p/292443

We would appreciate it if you could confirm this.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 78d8ec21-2a2d-e06d-9379-b30b3595cfe7
* Version Independent ID: 978afb49-2fa2-9e95-76e4-446e689f19a0
* Content: [全員が承認する必要のある承認フローを作成する (ビデオを含む) - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/all-assigned-must-approve)
* Content Source: [articles/all-assigned-must-approve.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/all-assigned-must-approve.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@Hiroyuki-Hayashi Thanks for reporting this issue. This issue is being tracked here: https://github.com/MicrosoftDocs/power-automate-docs/issues/662.

**Comment by Craig-Humphrey** [comment]
This is in no way related to [#662](https://github.com/MicrosoftDocs/power-automate-docs/issues/662).
It should be re-opened and properly investigated.
