### ISSUE TITLE
Filtering Attributes not working

### ISSUE THREAD

**Issue by DavidMendes94** [MicrosoftDocs/power-automate-docs#709]
Anyone else having the issue with the "when a row is modified" select attributes

Even though I have it populated with the field I want to trigger it on, it still runs for other instances

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c84a31-4f63-6ee1-ad15-096cae44cb41
* Version Independent ID: de8cf5bc-b78b-a88e-696f-7755e3ce22f0
* Content: [Trigger flows when a row is added, modified, or deleted - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/create-update-delete-trigger)
* Content Source: [articles/dataverse/create-update-delete-trigger.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/create-update-delete-trigger.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by radioblazer** [comment]
Is the column specified in select filter being updated when the row is being created or modified? To check this, you can enable auditing for the record and confirm if the specific column is in the request. Currently the trigger will run anytime the selected column is included in a create/modify request, even if the value has not changed.

**Comment by MSFTMan** [comment]
@DavidMendes94 per the response from @radioblazer, this is a know issue. The product team is aware of it and is evaluating how to address it. Thank you.

**Comment by Keeno1974** [comment]
Has this issue been resolved as yet. I am trying the same thing myself. Trying to generate an email when a custom field is set to a value. Tried several things but the error is still displaying
