### ISSUE TITLE
Update "Project Oakdale" references

### ISSUE THREAD

**Issue by jwillisrose** [MicrosoftDocs/power-automate-docs#712]
FYI - this page still says "Project Oakdale"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c21f8e65-0f40-3ebb-8354-58897b55151d
* Version Independent ID: 99313c27-45bb-6ab4-d78a-6f0499614c4e
* Content: [Use Power Automate flows in Microsoft Teams (contains video) - Power Automate](https://docs.microsoft.com/en-us/power-automate/teams/overview#feedback.)
* Content Source: [articles/teams/overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/teams/overview.md)
* Service: **power-automate**
* Sub-service: **teams**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by KumarVivek** [comment]
@jwillisrose This is fixed now; thanks for reporting it.
