### ISSUE TITLE
Join machine group failure

### ISSUE THREAD

**Issue by csteelatgburg** [MicrosoftDocs/power-automate-docs#713]
The description for the joinmachinegroup command lists three arguments:
Environmentid
Groupid
Grouppassword

However, the example command given only includes the groupid and grouppassword. Is the Environment ID required?

When attempting to run the command I receive an authentication failed error message. Can you please provide the proper syntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7023527b-aafd-ac7a-4319-30eb324b3950
* Version Independent ID: 0be01081-3761-63e6-40e8-133b474220b2
* Content: [Silent registration for machines - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/machines-silent-registration)
* Content Source: [articles/desktop-flows/machines-silent-registration.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/machines-silent-registration.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by mariosleon** [comment]
Hello @csteelatgburg thank you for using Power Automate. The Environment ID is not required when joining the machine group. For the issue you are confronting, note that you might be providing an erroneous password, or your user doesn't have permissions to join the machine group.
