### ISSUE TITLE
What happen with flows created by user that is out of company.

### ISSUE THREAD

**Issue by VaneCohr** [MicrosoftDocs/power-automate-docs#714]
Hi!!! all!!!

I need to know, what happen with flows I created in the cloud with the company mail and then I stop working at the company??. That flows I created will be deleted??

**Comment by MSFTMan** [comment]
@VaneCohr Thanks for using Power Automate. https://docs.microsoft.com/en-us/power-automate/change-cloud-flow-owner to change the owner of a flow.
