### ISSUE TITLE
How to set focus of a custom form?

### ISSUE THREAD

**Issue by jpmchia** [MicrosoftDocs/power-automate-docs#715]
When running a desktop flow, how do you set the focus to the custom form?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc9a6e07-8ef8-f460-644d-59aeb4716189
* Version Independent ID: dc9a6e07-8ef8-f460-644d-59aeb4716189
* Content: [Handle custom forms - Power Automate](https://docs.microsoft.com/en-gb/power-automate/desktop-flows/how-to/handle-custom-forms)
* Content Source: [articles/desktop-flows/how-to/handle-custom-forms.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/handle-custom-forms.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @jpmchia, thank you for using Power Automate! Custom forms always stay on top of other windows. You can minimize a custom form to hide it and work with other windows.

Please, note that you may ask technical questions in the [Power Automate community](https://preview.flow.microsoft.com/en-us/support/) where technical experts can respond to questions and suggest solutions.
