### ISSUE TITLE
Power Automate Switching Environments Docs

### ISSUE THREAD

**Issue by AJ-Acevedo** [MicrosoftDocs/power-automate-docs#723]
The [Switching environments](https://docs.microsoft.com/en-us/power-automate/environments-overview-maker#switching-environments) section of the Power Automate [Choosing an environment](https://docs.microsoft.com/en-us/power-automate/environments-overview-maker) page appears to be outdated. 

You no longer choose your environment under your profile. The Environments menu now has it's own place in the menu bar at the top right. See screenshot below.

![PowerAutomateEnv](https://user-images.githubusercontent.com/953092/165194744-0672d077-a967-4e8f-8121-e8109e582796.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ddd5e3-db39-4f50-4be4-71ae16dd19d2
* Version Independent ID: 61cafb41-19d2-24cc-a17f-85a36b22b4fa
* Content: [Learn about Power Automate environments - Power Automate](https://docs.microsoft.com/en-us/power-automate/environments-overview-maker)
* Content Source: [articles/environments-overview-maker.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/environments-overview-maker.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@AJ-Acevedo Thansk for using Power Automate and for reporting this issue. It's now fixed and you'll see the update live within 24 hours.
