### ISSUE TITLE
Distinct in Fetch XML Query seems to be working after all

### ISSUE THREAD

**Issue by KoenJanssensPD** [MicrosoftDocs/power-automate-docs#725]
Dear,
It seems that the List Rows actions does support the distinct operator in the Fetch XML Query.
This in contrast to what is stated in part https://docs.microsoft.com/en-us/power-automate/dataverse/list-rows#fetch-xml-query
The notes (and workaround) can be removed (or kept for reference/alternative)
Best regards,
Koen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fae8260-c3b8-4582-884d-72119ab256b7
* Version Independent ID: a12c64c0-9293-d86c-91c3-bce01efd1e1b
* Content: [Use lists of rows in flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/dataverse/list-rows#feedback)
* Content Source: [articles/dataverse/list-rows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/dataverse/list-rows.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **Deonhe**

**Comment by MSFTMan** [comment]
@radioblazer Do you know if this feature is now fully supported?

**Comment by v-aangie** [comment]
Started conversation with Matt T.
