### ISSUE TITLE
Unable to paste flow

### ISSUE THREAD

**Issue by ahuang23** [MicrosoftDocs/power-automate-docs#727]
I'm unable to paste a flow that my coworker extracted from his machine and saved to share drive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f370eb5f-d0fb-2779-3055-d55dc2ca804e
* Version Independent ID: 7ccac574-8fea-055e-cb37-8d39a26113ca
* Content: [Share/export a desktop flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/how-to/share-export-desktop-flows)
* Content Source: [articles/desktop-flows/how-to/share-export-desktop-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/share-export-desktop-flows.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @ahuang23, thank you for using Power Automate. The schema of some actions might change from one version of Power Automate for desktop to another. These actions might not be recognized when pasting between different versions of the designer. You can find more information regarding this issue in [Managing the workspace toolbar](https://docs.microsoft.com/power-automate/desktop-flows/designer-workspace#managing-the-workspace-toolbar).
