### ISSUE TITLE
Suggestion for major improvement: lists of available values!

### ISSUE THREAD

**Issue by ShadowInID** [MicrosoftDocs/power-automate-docs#736]
A major and useful improvement to the Power Automate documentation would be lists of available values for the parameters.  For example, the section on getting web element attributes should include (or link to) a list of which attributes can be selected.  Yes, we can see from the program itself that "Own Text" and "Exists" are available, but from various other pages and websites we can find out that "waelementcentercoords" is also a valid attribute!  What else can we do with this Action?  Can we get the Style attribute?  That would be very useful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a720f49a-5556-3766-7093-1034adbaa169
* Version Independent ID: ec081829-d7e8-f673-207e-43c247146216
* Content: [Browser automation - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/webautomation)
* Content Source: [articles/desktop-flows/actions-reference/webautomation.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/webautomation.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @ShadowInID, thank you for helping us improve the Power Automate documentation page. The "Get details of element on web page" action can extract any possible HTML attribute that a web element may have + the "waelementrectangle" attribute. We updated the document [here ](https://docs.microsoft.com/en-us/power-automate/desktop-flows/automation-web#web-data-extraction)to make this functionality clear to the users.

On the other hand, the "Get details of a UI element in window" action supports a limited number of attributes, so we created a table with all of them [here](https://docs.microsoft.com/en-us/power-automate/desktop-flows/how-to/extract-attributes-window-elements).
