### ISSUE TITLE
Non-working link due to missing locale

### ISSUE THREAD

**Issue by ashemedai** [MicrosoftDocs/power-automate-docs#739]
In the document there's a link `Find examples from your industry` pointing to `https://customers.microsoft.com/search?sq=%22Power%20Automate%22&ff=story_product_categories%26%3EPower%20Automate&p=0&so=story_publish_date%20desc`. The URL should be `https://customers.microsoft.com/en-us/search?sq=%22Power%20Automate%22&ff=story_product_categories%26%3EPower%20Automate&p=2&so=story_publish_date%20desc`. Do note the addition of the locale specifier, the current setup doesn't allow for a missing locale specifier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf98fbf-59fc-825d-e8bc-b4b5b42719a2
* Version Independent ID: 22977ae9-2f4b-c98e-d19d-1d8ebf43fbd2
* Content: [Get started with Power Automate (contains video) - Power Automate](https://docs.microsoft.com/en-us/power-automate/getting-started)
* Content Source: [articles/getting-started.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/getting-started.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@ashemedai Thanks for reporting this issue. We've fixed it. You'll see the update in the next few hours.
