### ISSUE TITLE
Are the cloud flows under 'Solutions' paginated?

### ISSUE THREAD

**Issue by bvrit-sravya** [MicrosoftDocs/power-automate-docs#740]
Hi,

We have a number of cloud flows( 700) in the 'Default Solution' container. I wanted to know if these flows are paginated? I see that  workflows are loaded as I scroll down but wanted to know if there is pagination implemented internally? 

Any help is greatly appreciated. 

Thanks
SLS

**Comment by MSFTMan** [comment]
@bvrit-sravya Thanks for reporting this issue. Will find out.

**Comment by MSFTMan** [comment]
@ChrisGarty Please take a look at this.

**Comment by ChrisGarty** [comment]
The resources in the solution explorer UI are paginated so that makers can progressively see all of them as they scroll down. This allows the initial page load to be faster.

**Comment by bvrit-sravya** [comment]
Thank you @ChrisGarty for the clarification.
