### ISSUE TITLE
Letter Case

### ISSUE THREAD

**Issue by Matt-03** [MicrosoftDocs/power-automate-docs#744]
Is this comparison case sensitive?
How do I preform a case insensitive comparison?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27504e8c-568f-ee52-542c-5ca87c2906db
* Version Independent ID: dc8f9282-90ce-60e0-402c-ea8829b6334e
* Content: [Use expressions in conditions in Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/use-expressions-in-conditions?WT.mc_id=365AdminCSH_PPACA1)
* Content Source: [articles/use-expressions-in-conditions.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/use-expressions-in-conditions.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@Matt-03 To do case insensitive comparison, just use the ToLower() method on each string that you want to compare. This forces them all to lower case.
