### ISSUE TITLE
How to save automated task as a app ?

### ISSUE THREAD

**Issue by Ford68** [MicrosoftDocs/power-automate-docs#745]
I want like to know if there is any way that I can save a task as a app ? Basically I am trying to simplify a task for a old lady but is to complicated for her to open Power Automator and start the task manually every single time. How can I save it as a app or icon or something that when doble clicked to performed the task?

**Comment by MSFTMan** [comment]
[Instant flows](https://docs.microsoft.com/power-automate/introduction-to-button-flows) can be used enable your scenario. All the person would need to do is to tap a button and the flow runs. Also, you may consider creating [a scheduled flow](https://docs.microsoft.com/power-automate/run-scheduled-tasks) as well. This way, the flow runs without any interaction from a human.
