### ISSUE TITLE
What table permission is needed to see the outcome of the instant flow run within a business process flow?

### ISSUE THREAD

**Issue by m3ngi3** [MicrosoftDocs/power-automate-docs#746]
My questions:

1. Why does the status change to Processing when I click the Run Flow button in the BPF but do NOT actually run the flow from the popup??
![image](https://user-images.githubusercontent.com/47530580/169351172-3e91d207-13f6-47b9-a68d-50b98fc3b312.png)
It stays Processing... forever...
This causes undesired / unexpected user experience. Especially when you make the run required in the BPF it needs to be succeeded for User.

1. What permissions are needed for non-system admins to see this status??
![image](https://user-images.githubusercontent.com/47530580/169351359-0fd1e923-216f-4162-b035-86b43a76353a.png)
The Security Role configuration screen does not mention Process Logs / Workflow Logs / workflowlogs anywhere...
so how will my left User (not Environment Admin) be able to see the actual Flow run outcome like my right user (Environment Admin) and above all be able to proceed to Next Stage if the Flow actually has run successfully??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a740ae25-17bc-ef31-13bd-5ca96ced14b5
* Version Independent ID: aec899f5-9e72-2b39-e96b-6dfaa8389409
* Content: [Create instant flows in business process flows - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-instant-flows)
* Content Source: [articles/create-instant-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-instant-flows.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @vashr
* Microsoft Alias: **vashr**

**Comment by MSFTMan** [comment]
@HemantGaur Kindly take a look at this issue. Thanks!

**Comment by MSFTMan** [comment]
@m3ngi3 Thanks for reporting this issue. We've updated the docs with the following note: **The user requires read access to the **System Jobs** table in Dataverse for the status to change from *Processing* to *Completed* **. You'll see the update within the next few hours.

**Comment by Decsus** [comment]
> @m3ngi3 Thanks for reporting this issue. We've updated the docs with the following note: **The user requires read access to the **System Jobs** table in Dataverse for the status to change from _Processing_ to _Completed_ **. You'll see the update within the next few hours.

You are my hero!!!
