### ISSUE TITLE
Restore delete flows ::: The parameter "IncludeDeleted" cannot be found

### ISSUE THREAD

**Issue by albertocaa1317** [MicrosoftDocs/power-automate-docs#747]
If I execute:
Get-AdminFlow -EnvironmentName Default-XXX -IncludeDeleted $true

I have this expection:
Get-AdminFlow : A parameter cannot be found that matches parameter name 'IncludeDeleted'.
At line:1 char:77
+ ... me Default-XXX -IncludeDeleted $true
+                                                     ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AdminFlow], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-AdminFlow

**Comment by kisubedi** [comment]
Hi @albertocaa1317! Thanks for reaching out. Please confirm you are using the latest version of the Administration module i.e 2.0.147?  https://www.powershellgallery.com/packages/Microsoft.PowerApps.Administration.PowerShell/2.0.147? You can use the command: Get-InstalledModule to know what version is installed on your machine. If its older than 2.0.147, please install the latest module by using force parameter: Hope this works!
