### ISSUE TITLE
The "Get group info" paragraph needs the following detail:

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/power-automate-docs#748]
The "Get group info" section just says: "Gets information about a group from the Active Directory server" which is not informative. It should mention that it returns 4 properties of a group:

Description
DisplayName
Members
Name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99d94f3-671c-56b9-43aa-ace95c78e85c
* Version Independent ID: 23036a14-c90e-3f34-d6b3-3e3565de6a93
* Content: [Active Directory - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/activedirectory#getgroupinfo)
* Content Source: [articles/desktop-flows/actions-reference/activedirectory.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/activedirectory.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @Mike-Crowley, thank you for using Power Automate and helping us improve our documentation page. You can find information regarding all Active Directory-related data types [here](https://docs.microsoft.com/en-us/power-automate/desktop-flows/variable-data-types#active-directory). We are currently working on connecting the actions reference with this page, so users can find information for each produced data type without effort. You'll be able to see the changes soon.
