### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by Jer0meM0rr0w** [MicrosoftDocs/power-automate-docs#749]
[Enter feedback here]
There is no need to make this documentation even more confusing!

**Choose the right trigger**
Triggers can be started instantly or manually, on a schedule, or automatically when some other even occurs.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd64ea9a-d352-f719-fa8c-7c8c7ca20273
* Version Independent ID: d583bc49-1518-0a8a-5364-073225cde2e9
* Content: [Triggers in Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/triggers-introduction)
* Content Source: [articles/triggers-introduction.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/triggers-introduction.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by MSFTMan** [comment]
@Jer0meM0rr0w Thanks for reporting this issue. It's fixed.
