### ISSUE TITLE
Update with client support for markdown links

### ISSUE THREAD

**Issue by iddycol** [MicrosoftDocs/power-automate-docs#756]
[Enter feedback here]

Please update with support (or not) for markdown links in Outlook client - these don't currently appear to work even in the latest O365 builds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support?source=docs)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/approvals-markdown-support.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @hamenon-ms
* Microsoft Alias: **hamenon**

**Comment by MSFTMan** [comment]
@iddycol Thanks for your feedback. Can you let us know specifically what doesn't work? We have tested these and they are working for you. If you have screenshots, those would help as well. Thanks!
