### ISSUE TITLE
Create connection to Cloud Automate from Desktop Flow

### ISSUE THREAD

**Issue by masonj-tech** [MicrosoftDocs/power-automate-docs#758]
If our computer does not join any domain, please advise how to create a connection to Cloud Power Automate from Desktop Flow？
No guide on this topic in this page. 
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 50a1a74f-75df-ccf6-207d-c82ec5d204e8
* Version Independent ID: 2214022c-fa62-210c-0f81-30ec75c8ffe9
* Content: [从云端流触发桌面流 - Power Automate](https://docs.microsoft.com/zh-cn/power-automate/desktop-flows/link-pad-flow-portal?WT.mc_id=365AdminCSH_PPACA1)
* Content Source: [articles/desktop-flows/link-pad-flow-portal.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/link-pad-flow-portal.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @masonj-tech, thank you for using Power Automate and helping us improve the documentation page. If your machine hasn't joined a domain, just populate the name of the device and your account name. For example, if the device name is 'MS006' and the account name 'ADMINISTRATOR', enter 'MS006\ADMINISTRATOR'.

We are currently working on adding the appropriate information to the documentation page and you will be able to see the changes soon.
