### ISSUE TITLE
Issue with "When email arrives in a folder" Trigger

### ISSUE THREAD

**Issue by Aussieegg** [MicrosoftDocs/power-automate-docs#761]
Hi,
I am trying to use the :when an email arrives in a folder" to trigger the flow but it only works if the email arrives on that day. If it is placed in the folder manually the next day the flow does not trigger.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38b2975-5eb6-1aa4-c1fd-d0f033ace5ca
* Version Independent ID: 85899731-9939-a779-29c4-4da652667b74
* Content: [Trigger a cloud flow based on email properties in Power Automate - Power Automate](https://docs.microsoft.com/en-us/power-automate/email-triggers)
* Content Source: [articles/email-triggers.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/email-triggers.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@Aussieegg Thanks for reporting this issue. The trigger works through the email server. If you manually place an email in the folder, it will not trigger the flow. Thank you.

**Comment by Aussieegg** [comment]
Hi MSFTMan, the manual proceeds works if the email is placed in the mailbox folder on the same day as it arrives in the mailbox but not when it is the day after.
