### ISSUE TITLE
Need examples on these pages

### ISSUE THREAD

**Issue by gotoreports** [MicrosoftDocs/power-automate-docs#763]
Doc pages very helpful.  What is missing are some basic, very basic, examples though, as seen on many other doc pages for other products.  Keep up the great work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52e0d3b7-5d54-b28b-ed97-8bc0970d0c96
* Version Independent ID: c25847a1-f575-cfd9-73e5-10cdf75bbfa6
* Content: [Variables - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/variables#retrievedatatablecolumnintolist)
* Content Source: [articles/desktop-flows/actions-reference/variables.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/variables.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @gotoreports, thank you for using Power Automate and helping us improve the documentation page. Can you give us some examples of content you think is missing from the actions reference articles?

**Comment by georgiostrantzas** [comment]
This issue got closed because we didn't receive further information. Users can reopen it when more details are available.
