### ISSUE TITLE
Define "organization premium account"

### ISSUE THREAD

**Issue by mauledbyjesus** [MicrosoftDocs/power-automate-docs#767]
Is an "organization premium account" a work/shool account with the ("premium") Per User with Unattended RPA license assigned? I've gotten that question a few times and it is unclear how these accounts relate to each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9705e0ca-aac2-4da2-34ac-670a86ad77b9
* Version Independent ID: 3efe3ae8-cff1-36ce-899e-c98e89a4e747
* Content: [Getting started with an organization premium account - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/getting-started-org)
* Content Source: [articles/desktop-flows/getting-started-org.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/getting-started-org.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @mauledbyjesus, thank you for using Power Automate. An organization premium account is the account type that belongs to organizations that own paid licenses for RPA.

If you sign in with a work or school email address and the organization doesn't own paid RPA licenses, you get all Power Automate capabilities included in Office 365.

If you have a non-business user account (such as an account that ends with @outlook.com or @gmail.com), you can still use Power Automate with the free plan.

You can find more information regarding the differences between the account types [here](https://docs.microsoft.com/en-us/power-automate/desktop-flows/setup#sign-in-account-comparison). Also, you can find information about licensing [here](https://docs.microsoft.com/en-us/power-platform/admin/power-automate-licensing/types).
