### ISSUE TITLE
What is the point of creating multiple selectors? 

### ISSUE THREAD

**Issue by rbtzn-orange** [MicrosoftDocs/power-automate-docs#772]
Hello, I discovered that you can create several selectors for the same UI element.
I tried to do it to manage a window that can be displayed in English or in French (only the name of the window in the selector path changes), I expected the system to be able to manage the interface in both languages in this way:
-> attempt to retrieve the UI element via the first selector -> KO -> attempt to retrieve the UI element via the second selector -> OK, but that doesn't seem to be the case.

So why leave the possibility of creating multiple selectors? 

Thanks in advance and thanks for your work :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c63ac396-e73b-ed94-678a-e98d456ed95f
* Version Independent ID: c76bc275-a21b-5ffc-fe0d-ef02597c8f99
* Content: [Build a custom selector - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/build-custom-selectors)
* Content Source: [articles/desktop-flows/build-custom-selectors.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/build-custom-selectors.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @rbtzn-orange, thank you for using Power Automate. The use of multiple selectors is precisely the one you describe. When a selector fails, desktop flows use the next one in order. For help regarding technical issues, please reach out to our support teams through [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to investigate further.

**Comment by georgiostrantzas** [comment]
A description of how multiple selectors work already exists in [this section](https://docs.microsoft.com/en-us/power-automate/desktop-flows/ui-elements#ui-elements-properties) of the documentation. However, we will also add it in the 'Build a custom selector' article to avoid any future confusion. Thank you for the feedback!

**Comment by georgiostrantzas** [comment]
The new content has been published and you can find it [here](https://docs.microsoft.com/en-us/power-automate/desktop-flows/build-custom-selectors). Don't hesitate to contact us for further feedback. Thank you for your contribution!
