### ISSUE TITLE
Variable slicing

### ISSUE THREAD

**Issue by ZeroSysLog** [MicrosoftDocs/power-automate-docs#774]
I am a user from Winautomation, Robin language.
Text, list and datatable type variables can be sliced using index.
However, this is currently not mentioned in the Docs, so it is difficult to explain to new users as an official feature.
I would like to see this mentioned in Docs if it will continue to be supported in the future.

`%Variable[start:stop]%`

May be omitted if the first or last position is specified.

Text type
`SET Text TO $'''abcde'''`

`Text[:3]`   abc
`Text[2:4]` cd
`Text[3:]`   de
Functions similar to Get subtext action

List type 

`SET List TO [1, 2, 3, 4, 5]`

`List[:3]`       %[1,2,3]%
`List[2:4]`  %[3,4]%
`List[3:]`  %[4,5]%

Datatable types

`Variables.CreateNewDatatable InputTable: { ^['Column1', 'Column2'], [$'''a''', 0], [$'''b''', 1], [$'''c''', 2], [$'''d''', 3] } DataTable=> DataTable`

`Datatable[2:4]`      %{ ^['Column1', 'Column2'], ['c', 2], ['d', 3] }%

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c072a86-f779-49d4-4992-897c288ee663
* Version Independent ID: 3e2e7687-e85c-8ade-9786-cb2cb7476412
* Content: [Variable data types - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/variable-data-types)
* Content Source: [articles/desktop-flows/variable-data-types.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/variable-data-types.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @ZeroSysLog, thank for sharing your feedback and helping us improve the documentation page. We are currently working on adding this information to the documentation and you'll be able to see the new content soon.

**Comment by georgiostrantzas** [comment]
Hello again @ZeroSysLog! The new content has been published and you can find it [here](https://docs.microsoft.com/en-us/power-automate/desktop-flows/variable-data-types). Thank you for your feedback!

**Comment by ZeroSysLog** [comment]
Hello.
@georgiostrantzas 
Thank you for the feedback reflected.
We are pleased that the materials have been enhanced.
