### ISSUE TITLE
Windows Server 2022 Support

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/power-automate-docs#775]
Regarding

> When Power Automate runs in unattended mode, it automatically signs into the target devices that run Windows 10, Windows Server 2016, or Windows Server 2019.

Is Windows Server 2022 now also fully supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea541994-b3d3-7f6a-e3bf-2465dcfb7df2
* Version Independent ID: cd0ebb34-b041-b7f5-633d-afc1995d2f4e
* Content: [Run a Power Automate desktop flow - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/run-pad-flow)
* Content Source: [articles/desktop-flows/run-pad-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/run-pad-flow.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @VitalyMCT, thank you for using Power Automate! I would like to inform you that Windows Server 2022 is fully supported. We are working on updating the appropriate articles and you'll be able to see the changes soon.
