### ISSUE TITLE
"Click download link" does not work

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/power-automate-docs#776]
"Click download link" does not work as described here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a720f49a-5556-3766-7093-1034adbaa169
* Version Independent ID: ec081829-d7e8-f673-207e-43c247146216
* Content: [Browser automation - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/webautomation#clickdownloadlink)
* Content Source: [articles/desktop-flows/actions-reference/webautomation.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/webautomation.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @gvggvg, thank you for using Power Automate and helping us improve our documentation page. Could you give us more information regarding the mentioned issue? Which part of the article is not valid?

**Comment by gvggvg** [comment]
The whole flow "Click download link" does not work. Yes, it works with Automation Browser. But Automation Browser is Internet Explorer, that is no longer supported, isn't it ?

**Comment by georgiostrantzas** [comment]
Thank you for sharing your feedback! For help with the technical issues, please reach out to our support teams through [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to investigate further.
