### ISSUE TITLE
webautomation.md is missing documentation for Extract Type

### ISSUE THREAD

**Issue by JJKW1984** [MicrosoftDocs/power-automate-docs#782]
We could use some additional details for the power automate desktop browser web automation extract data from web page feature. The Extract type: undefined,  list, single value, hand picked, list, table, and entire html table are undocumented. The use of the base CSS selector and other CSS selectors don't work as expected. Or at least as I would expect them too!

Is it possible to provide more details and possible examples for these options?

**Comment by georgiostrantzas** [comment]
Hello @JJKW1984, thank you for using Power Automate and helping us improve our content! We are currently working on adding more information regarding extracting web data and you will be able to see the changes soon.

**Comment by georgiostrantzas** [comment]
The new content has been published and you can find it [here](https://docs.microsoft.com/en-us/power-automate/desktop-flows/automation-web#web-extraction-of-structured-data). Thank you for your feedback and don't hesitate to contact us for further suggestions.
