### ISSUE TITLE
Embed images to email body

### ISSUE THREAD

**Issue by sandramcg** [MicrosoftDocs/power-automate-docs#789]
The section "Embed images to email body" doesn't clarify which Power Automate actions it can be used with. I have tried the "Send an email from a shared mailbox" action but it doesn't have the "HTML" toggle as shown on your screenshot. Googling the issue, it seems I have to put a whole bunch of extra steps in, something involving base64? Very complex for an end user who just needs to send a nicely formatted email from a shared mailbox!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d343d0b9-fdc2-5eb0-ba51-0b2ddabc90de
* Version Independent ID: 888e8708-1b7c-4da9-cd0e-6384801d9f4c
* Content: [Add images to email messages - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/how-to/add-images-email-messages)
* Content Source: [articles/desktop-flows/how-to/add-images-email-messages.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/add-images-email-messages.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @sandramcg, thank you for using Power Automate and helping us improve the documentation page. The presented method can be used with all the send email actions (Send email, Send Exchange email message, Send email message through Outlook), as all of them offer the "Body is HTML" toggle. Can you upload a screenshot of the configured email action of your flow so we can replicate this specific scenario?

**Comment by georgiostrantzas** [comment]
The ticket has been closed because the requested information hasn't been provided.

**Comment by sandramcg** [comment]
I need to use the "Send an email from a Shared Mailbox" action which
doesn't offer this toggle.

**Comment by georgiostrantzas** [comment]
@sandramcg thank you for providing additional information. The **Send an email from a shared mailbox** action is only available in cloud flows. The mentioned documentation page refers only to desktop flows. The available actions to send emails in desktop flows are:

- Send email
- Send Exchange email message
- Send email message through Outlook
