### ISSUE TITLE
Please elaborate on the specifications of the "Windows OCR Engine."

### ISSUE THREAD

**Issue by cidrugHug8** [MicrosoftDocs/power-automate-docs#790]
Please elaborate on the specifications of the "Windows OCR Engine."

Can it work only on the local PC? If so, is this engine the same as the OCR engine provided in Windows.Media.Ocr namespace?
https://docs.microsoft.com/en-us/uwp/api/windows.media.ocr.ocrengine?view=winrt-22621

Or does it require a network connection? If so, does this engine call Azure Read? Will it be secured?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 81d0345a-3fab-2adc-c7cc-c4d2b03fe0d2
* Version Independent ID: c50b23b6-616c-2962-b87f-7593e7c97f4b
* Content: [OCR | Microsoft Docs - Power Automate](https://docs.microsoft.com/ja-jp/power-automate/desktop-flows/actions-reference/ocr)
* Content Source: [articles/desktop-flows/actions-reference/ocr.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/ocr.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @cidrugHug8, thank you for using Power Automate and helping us improve the documentation page. You can use the OCR actions to automate both physical machines and [virtual desktops](https://docs.microsoft.com/en-us/power-automate/desktop-flows/virtual-desktops). 

The Windows OCR Engine is the same as the engine provided in Windows.Media.Ocr namespace and comes pre-installed with Power Automate for desktop. The engine itself works locally and doesn't require any internet or cloud connection, but Power Automate for desktop requires an internet connection to work.

We are currently working on adding this information to the appropriate article and you will be able to see the changes soon.
