### ISSUE TITLE
This document doesn't tell me how to get this information from the *desktop*.  I want to get the list of flows from a PAD implementation on my local machine without any cloud access.  How do I do that?

### ISSUE THREAD

**Issue by jamiemaclennan** [MicrosoftDocs/power-automate-docs#797]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35ac6c6-f132-4d0f-f023-52e0d225a55c
* Version Independent ID: e35ac6c6-f132-4d0f-f023-52e0d225a55c
* Content: [Work with desktop flows using code - Power Automate](https://docs.microsoft.com/en-us/power-automate/developer/desktop-flow-public-apis)
* Content Source: [articles/developer/desktop-flow-public-apis.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/developer/desktop-flow-public-apis.md)
* Service: **power-automate**
* Sub-service: **developer**
* GitHub Login: @benabbon
* Microsoft Alias: **nabena**

**Comment by georgiostrantzas** [comment]
Hello @jamiemaclennan and thank you for using Power Automate. All desktop flows are saved in Dataverse; only some information is cached locally. As a result, the requested functionality isn't available. For help with the technical issues, please reach out to our support teams through [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to investigate further.
