### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/power-automate-docs#800]
> The Tolerance field defines the acceptable **ammount** of differences between the provided image and the image is compared with.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 665766de-41cc-133c-3912-3225b1809abe
* Version Independent ID: 90389108-945d-05b3-0658-432b65b5a021
* Content: [Images - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/images)
* Content Source: [articles/desktop-flows/images.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/images.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @VitalyMCT, thank you for using Power Automate and helping us improve our documentation page.  We are currently working on resolving the issue, and you will be able to see the changes soon.
