### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by julians1966** [MicrosoftDocs/power-automate-docs#805]
The text "The kit includes a Power App and multiple flows to automate the scaling **up and down** of machines" implies that the virtual machines are scaled vertically i.e., the size of the virtual machine is changed. 

This is incorrect, the scaling is horizontal i.e. identical virtual machines are started and stopped.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd336291-a93b-bb9a-0172-e88329c04bc0
* Version Independent ID: cd336291-a93b-bb9a-0172-e88329c04bc0
* Content: [Introduction to the Power Automate Azure Virtual Desktop integration starter kit - Power Automate](https://docs.microsoft.com/en-us/power-automate/desktop-flows/avd-overview)
* Content Source: [articles/desktop-flows/avd-overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/avd-overview.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @julians1966, thank you for using Power Automate and helping us improve our documentation. We are currently working on fixing the inaccurate terminology in the mentioned article, and you'll be able to see the changes soon.

**Comment by georgiostrantzas** [comment]
The updated content is now live. Thank you for the feedback and don't hesitate to contact us for more comments regarding the documentation.
