### ISSUE TITLE
What happens when ownership of a solution-aware cloud flow is shared with a user who isn't Dataverse?

### ISSUE THREAD

**Issue by apomphre** [MicrosoftDocs/power-automate-docs#810]
This section heading is missing the word "in"
What happens when ownership of a solution-aware cloud flow is shared with a user who isn't Dataverse?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to share a cloud flow with other users - Power Automate](https://docs.microsoft.com/en-us/power-automate/create-team-flows)
* Content Source: [articles/create-team-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-team-flows.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@apomphre Thanks for reporting this issue. We've fixed it.
