### ISSUE TITLE
Link to URL with a non microsoft certificate.

### ISSUE THREAD

**Issue by null-zero** [MicrosoftDocs/power-automate-docs#813]
The link labeled "[Power Automate](https://powerautomate.com/)"
Seems to no longer be under the control of Microsoft, and is instead owned by someone who makes phishing websites.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae761774-78a1-83be-4f75-18ff7ad9074d
* Version Independent ID: f6f4a32d-f5af-3e07-9178-a65547039c3b
* Content: [Share and manage desktop flows - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/manage#share-desktop-flows)
* Content Source: [articles/desktop-flows/manage.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/manage.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by georgiostrantzas** [comment]
Hello @null-zero, thank you for helping us improve our documentation page. The links have been updated. Don't hesitate to contact us if you have any additional feedback.
