### ISSUE TITLE
Screenshots on /dataverse/create-update-delete-trigger.md are out of date

### ISSUE THREAD

**Issue by bthompson-365** [MicrosoftDocs/power-automate-docs#814]
Column filter is now called Select Columns and the screenshots should look like...

![image](https://user-images.githubusercontent.com/59604916/191440130-01da97aa-5ebd-4dc3-ad8e-80094461a8ea.png)

**Comment by v-aangie** [comment]
Talked with Matt Townsend about this in December and January in chat. Sent email today 2/2 with PR https://github.com/MicrosoftDocs/power-automate-docs-pr/pull/1875. Issue can be closed once the PR is merged.

**Comment by v-aangie** [comment]
@bthompson-365 - Thanks for your feedback. We have updated the docs to fix information about the Select Columns field and the updated content is live. Closing this issue.
