### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by IndianRichard** [MicrosoftDocs/power-automate-docs#815]
I get nothing but a placeholder image where the image I want is supposed to be. I have tried everything so far with no luck. 
I created a get file... I used that file information to create an expression to input into the img. I removed the quotes as suggested I changed the data:jpeg to data:png I tried everything under the sun including your suggestion to attach the image. IT DOES NOT WORK! This is v3ry frustrating and cannot be this difficult. As a developer I can't imaging the simple user trying to perform this operation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d343d0b9-fdc2-5eb0-ba51-0b2ddabc90de
* Version Independent ID: 888e8708-1b7c-4da9-cd0e-6384801d9f4c
* Content: [Add images to email messages - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/how-to/add-images-email-messages)
* Content Source: [articles/desktop-flows/how-to/add-images-email-messages.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/add-images-email-messages.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **v-gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @IndianRichard, thank you for using Power Automate! Can you please upload a screenshot from your desktop flow so we can investigate further?

**Comment by georgiostrantzas** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
