### ISSUE TITLE
Windows Store

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/power-automate-docs#820]
I think the article would benefit from being extended to cover this deployment mechanism.

For example, one of the questions users have is whether side-by-side deployments of MSI and Microsoft Store installations are supported.

**Comment by georgiostrantzas** [comment]
Hello @VitalyMCT, thank you for using Power Automate and helping us improve our documentation. Can you please send us the article you are referring to?

**Comment by VitalyMCT** [comment]
@georgiostrantzas My apologies, I accidentally erased the link to the original article in the ticket template.

It's https://learn.microsoft.com/en-us/power-automate/desktop-flows/install

**Comment by georgiostrantzas** [comment]
Having side-by-side deployments of MSI and Microsoft Store installations of Power Automate for desktop isn't supported. If you have already a Microsoft Store installation, you won't be able to install an MSI version. The opposite is possible, but it could cause issues and we don't recommend it. We are currently working on adding this information to our docs and you'll be able to see the changes soon.

**Comment by VitalyMCT** [comment]
@georgiostrantzas Thanks for your response. 

Regarding

>If you have already a Microsoft Store installation, you won't be able to install an MSI version.

It seems that attempting to do so with the current versions generates a warning about a duplicate installation (upon running the MSI installer). The user is then given a choice to proceed or cancel. Please try it out.

**Comment by georgiostrantzas** [comment]
We have added a note [here ](https://learn.microsoft.com/en-us/power-automate/desktop-flows/install)to warn users that duplicate installations aren't recommended for any case. Thank you very much for your feedback!

**Comment by VitalyMCT** [comment]
@georgiostrantzas Thanks for the update. I've reviewed the updates and see some challenges with the newly added section:

1. "Open a browser and go directly to the [Power Automate page](https://aka.ms/pbidesktopstore) of the Microsoft Store." This goes to Power BI instead
2. "Go to the [Power Automate product page](https://flow.microsoft.com/desktop/), and then select Download Free.". There is no such button on this page
3. Some Markdown issues with missing spaces, etc.

Also, I think it's very important to cover any differences between the two deployment options on this page. Are certain features supported by one version vs. the other? If so, what are they?

**Comment by georgiostrantzas** [comment]
Thank you for the additional feedback. We have updated the links and you'll be able to see the changes soon. Additionally, we are working on developing new articles regarding the installation that will include new information. 

The only difference between the two deployment options is that you don't need admin rights to install Power Automate through the Microsoft Store. The available features are the same.
