### ISSUE TITLE
How do I use these File Actions in Power Automate

### ISSUE THREAD

**Issue by GuyBoswell** [MicrosoftDocs/power-automate-docs#823]
How do I use these File Actions in Power Automate.  Lots of useful things to do but no relationship to how Power Automate actually works

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 307cfcfa-687c-d1d6-e255-43d3e4c9ce0c
* Version Independent ID: c63e178e-04d8-3dcf-36f5-06cee150afe4
* Content: [File | Microsoft Docs - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/file)
* Content Source: [articles/desktop-flows/actions-reference/file.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/file.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @mariosleon
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @GuyBoswell, thank you for using Power Automate and helping us improve our documentation. 

The actions reference contains a small getting started guide regarding deploying file actions. We will update it to include some additional information that introduces the basic functionality of the group. 

If you have any specific scenarios you would like to see covered in the documentation, feel free to mention them so we can add them to the how-to section.

**Comment by georgiostrantzas** [comment]
You can find our updated getting started guide [here](https://learn.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/file#getting-started-with-file-actions). Thank you very much for your feedback!

**Comment by GuyBoswell** [comment]
Still doesn't explain at all how these are used in Power Automate????

**Comment by georgiostrantzas** [comment]
Thank you for the quick answer! The getting started guide shows how to deploy and configure these actions in your desktop flows. If you want to trigger your desktop flows for your cloud flows, you can refer to our respective article [here](https://learn.microsoft.com/en-us/power-automate/desktop-flows/link-pad-flow-portal).
