### ISSUE TITLE
Download link to CRM app isn't working

### ISSUE THREAD

**Issue by MrHosz** [MicrosoftDocs/power-automate-docs#825]
Link to the legacy CRM app isnt working properly:
section: https://learn.microsoft.com/en-us/power-automate/desktop-flows/dynamics365-cs-rpa#install-and-configure-contoso-crm-app

Download url is: https://aka.ms/ContosoCRMApp ---> https://d365rpa.blob.core.windows.net/blob1/contoso_legancy_crm_setup.zip

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 385ab7e2-6554-02dc-9163-fa566cbc774e
* Version Independent ID: 298ec053-059e-8e74-692b-8075a53c2fe8
* Content: [Use RPA with Dynamics 365 Customer Service - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/dynamics365-cs-rpa)
* Content Source: [articles/desktop-flows/dynamics365-cs-rpa.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/dynamics365-cs-rpa.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @MrHosz, thank you for using Power Automate and helping us improve the documentation! The link has been updated and you'll be able to see the change soon.
