### ISSUE TITLE
Contoso CRM app not public

### ISSUE THREAD

**Issue by julians1966** [MicrosoftDocs/power-automate-docs#827]
The link https://aka.ms/ContosoCRMApp to the CRM app is not public

<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:dfa0deba-301e-0017-3145-e8732f000000 Time:2022-10-25T07:40:38.1488950Z</Message>
</Error>

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 385ab7e2-6554-02dc-9163-fa566cbc774e
* Version Independent ID: 298ec053-059e-8e74-692b-8075a53c2fe8
* Content: [Use RPA with Dynamics 365 Customer Service - Power Automate](https://learn.microsoft.com/en-gb/power-automate/desktop-flows/dynamics365-cs-rpa)
* Content Source: [articles/desktop-flows/dynamics365-cs-rpa.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/dynamics365-cs-rpa.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @julians1966, thank you for using Power Automate and helping us improve the documentation! The link has been updated and you'll be able to see the change soon.
