### ISSUE TITLE
Typo in section On block error

### ISSUE THREAD

**Issue by svenhitrain** [MicrosoftDocs/power-automate-docs#835]
Instead of " diving a number by zero" it should read "dividing a number by zero"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2967a61-2d02-ba17-7074-213852fc90e4
* Version Independent ID: 461c1c33-40c7-6d20-a4e5-c5c76c97f914
* Content: [Flow control - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/flowcontrol?source=recommendations)
* Content Source: [articles/desktop-flows/actions-reference/flowcontrol.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/flowcontrol.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @svenhitrain, thank you for using Power Automate and helping us improve the documentation. We are currently working on resolving the spelling mistake and you'll be able to see the change soon.
