### ISSUE TITLE
Creat Desktop shortcut not available

### ISSUE THREAD

**Issue by BillC58** [MicrosoftDocs/power-automate-docs#839]
The article states: "To create a shortcut for a desktop flow, right-click on its name in the console and select Create desktop shortcut."

However, that option is not available:

![image](https://user-images.githubusercontent.com/60044767/200027767-03010ad9-58ac-49d8-abce-6e7bef66a683.png)

Is there a step that I am missing?

Bill

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea541994-b3d3-7f6a-e3bf-2465dcfb7df2
* Version Independent ID: cd0ebb34-b041-b7f5-633d-afc1995d2f4e
* Content: [Run a Power Automate desktop flow - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/run-pad-flow)
* Content Source: [articles/desktop-flows/run-pad-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/run-pad-flow.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @BillC58, thank you for using Power Automate. What type of account are you using? This feature is available only for premium users. You can find a list with all the premium features of desktop flows [here](https://learn.microsoft.com/en-us/power-automate/desktop-flows/premium-features).

**Comment by BillC58** [comment]
Thanks. That explains it. I am using the free version.

Bill
________________________________
