### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by iangorman2020** [MicrosoftDocs/power-automate-docs#846]
b. To automate the end-of-cycle reporting process on Dynamics 365 Finance, download the solution here https://aka.ms/D365FinanceEndCycleReportingRPASolution

This link leads to an error: https://aka.ms/D365FinanceEndCycleReportingRPASolution

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc5ba2f6-b1cd-bb14-744b-1eadc98608d4
* Version Independent ID: 4689a032-aa04-36b4-b448-37357f32b522
* Content: [Use RPA with Dynamics 365 Finance - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/dynamics365-fin-rpa)
* Content Source: [articles/desktop-flows/dynamics365-fin-rpa.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/dynamics365-fin-rpa.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @iangorman2020, thank you for using Power Automate! The download link has been updated.
