### ISSUE TITLE
Mozilla Firefox extension is missing

### ISSUE THREAD

**Issue by chromial** [MicrosoftDocs/power-automate-docs#848]
Navigate to [Install Power Automate browser extensions]( https://learn.microsoft.com/en-us/power-automate/desktop-flows/install-browser-extensions)
Scroll down the page until you get to: If you skip the installation of the browser extensions, you can do it manually later using the following links or through the Tools > Browser extensions options in the flow designer.
    Microsoft Edge
    Google Chrome
    Mozilla Firefox
Click [Mozilla Firefox](https://addons.mozilla.org/en-US/firefox/addon/power-automate-desktop/versions/)

Expected: a page containing a browser extension

Actual: Oops! We can’t find that page
If you’ve followed a link from another site for an extension or theme, that item is no longer available. ... etc.

**Comment by georgiostrantzas** [comment]
Hello @chromial, thank you for using Power Automate! The Mozilla Firefox extension is currently unavailable, but it will be available again after the December release.
