### ISSUE TITLE
UI Element Picker- Not Picking

### ISSUE THREAD

**Issue by Pikahood** [MicrosoftDocs/power-automate-docs#849]
Hi, when using Get Details of Element on Webpage, the UI Element Picker is not able to pick anything in the frame. Just the header of the web app is being grabbed by it . Should we manually use a custom  selector to grab the iframe url ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9aa96721-3a3c-094a-3abe-6242c1febb0e
* Version Independent ID: 1ee81b1c-dc76-6a95-3420-17f5ff82b695
* Content: [Handle iframes on a web page - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/how-to/handle-iframes)
* Content Source: [articles/desktop-flows/how-to/handle-iframes.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/how-to/handle-iframes.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @Pikahood, thank you for using Power Automate! If the iframe is a cross-domain iframe, it isn't supported yet. If it isn't a cross-domain iframe, ensure web automation actions work as expected in general on your browser.  For further technical help, please reach out to our support teams through [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support).
