### ISSUE TITLE
Edit columns in 28-day history of flow run

### ISSUE THREAD

**Issue by CFH4030** [MicrosoftDocs/power-automate-docs#850]
The documentation shows 16 options for columns in the run history. These additional columns are supposed to help you troubleshoot a failed flow. I have 3 options only. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d04539c-cf39-3ab2-7ee2-5141e6a5bf89
* Version Independent ID: 81a19210-725f-17a7-238e-1ff3ffe14d23
* Content: [Troubleshooting a cloud flow - Power Automate](https://learn.microsoft.com/en-us/power-automate/fix-flow-failures)
* Content Source: [articles/fix-flow-failures.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/fix-flow-failures.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by georgiostrantzas** [comment]
Hello @CFH4030, thank you for using Power Automate. The number of columns isn't standard.  The column options are based on your flow trigger outputs.
