### ISSUE TITLE
"Fix my error" emails

### ISSUE THREAD

**Issue by CFH4030** [MicrosoftDocs/power-automate-docs#851]
According to the documentation, I should be receiving emails when my flow fails that will help me fix the error. I don't receive these emails. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d04539c-cf39-3ab2-7ee2-5141e6a5bf89
* Version Independent ID: 81a19210-725f-17a7-238e-1ff3ffe14d23
* Content: [Troubleshooting a cloud flow - Power Automate](https://learn.microsoft.com/en-us/power-automate/fix-flow-failures)
* Content Source: [articles/fix-flow-failures.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/fix-flow-failures.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by natalie-pienkowska** [comment]
Thank you for raising this issue, @CFH4030. In order for us to help you, we need more information on the flows for which you have not been receiving a failure for. Can you please open a customer support ticket with Power Automate so that we can better help you resolve the issue?

**Comment by georgiostrantzas** [comment]
Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
