### ISSUE TITLE
End-of-cycle reporting process on Dynamics 365 Finance link is not working

### ISSUE THREAD

**Issue by magnomgp** [MicrosoftDocs/power-automate-docs#854]
The End-of-cycle reporting process on Dynamics 365 Finance link is not working.

b. To automate the end-of-cycle reporting process on Dynamics 365 Finance, download the solution here https://aka.ms/D365FinanceEndCycleReportingRPASolution

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:9c5ab4a9-501e-0073-6b6f-ff82b7000000 Time:2022-11-23T19:09:11.0873370Z</Message>
</Error>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc5ba2f6-b1cd-bb14-744b-1eadc98608d4
* Version Independent ID: 4689a032-aa04-36b4-b448-37357f32b522
* Content: [Use RPA with Dynamics 365 Finance - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/dynamics365-fin-rpa#installing-the-dynamics-365-rpa-solution)
* Content Source: [articles/desktop-flows/dynamics365-fin-rpa.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/dynamics365-fin-rpa.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @magnomgp, thank you for using Power Automate! The download link has been updated.
