### ISSUE TITLE
The link to Dynamics 365 Finance solution download does not work

### ISSUE THREAD

**Issue by maciunex** [MicrosoftDocs/power-automate-docs#855]
Hi,
The link to Dynamics 365 Finance solution download does not work (https://aka.ms/D365FinanceEndCycleReportingRPASolution)
Other two work just fine, however this points to following URL: https://d365rpa.blob.core.windows.net/d365rpasolutions/Dyn365FinanceRPA_2_0_0_4.zip
The page shows following error:
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:9c1d0ba3-001e-0023-3fe0-ff40e7000000 Time:2022-11-24T08:44:37.2886706Z</Message>
</Error>
![image](https://user-images.githubusercontent.com/118968088/203734842-6753d1a0-032f-4f40-bdc1-eeac75615dbb.png)

Can you please re-upload/check the link/verify that anonymous public access is possible?

Thanks,
Maciej

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc5ba2f6-b1cd-bb14-744b-1eadc98608d4
* Version Independent ID: 4689a032-aa04-36b4-b448-37357f32b522
* Content: [Use RPA with Dynamics 365 Finance - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/dynamics365-fin-rpa#known-issues)
* Content Source: [articles/desktop-flows/dynamics365-fin-rpa.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/dynamics365-fin-rpa.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @maciunex, thank you for using Power Automate! The download link has been updated.
