### ISSUE TITLE
Fix verbiage

### ISSUE THREAD

**Issue by Oodit** [MicrosoftDocs/power-automate-docs#858]
There is a verbiage change required. Please search on this page "as an table", it should be as a table.  Hope you got it. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7632694a-e3b9-7f71-5e19-765d4d203155
* Version Independent ID: c961c989-bc01-5088-6993-b5ee9485d4f4
* Content: [Business process flows overview - Power Automate](https://learn.microsoft.com/en-us/power-automate/business-process-flows-overview)
* Content Source: [articles/business-process-flows-overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/business-process-flows-overview.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DEONHE**

**Comment by v-aangie** [comment]
Correction made in https://github.com/MicrosoftDocs/power-automate-docs-pr/pull/1892.

**Comment by v-aangie** [comment]
@Oodit -
