### ISSUE TITLE
first recurrence runs immediately

### ISSUE THREAD

**Issue by raikat** [MicrosoftDocs/power-automate-docs#861]
[Enter feedback here]
Hello,

According documentation flow shouldn't run immediately if there is given a specific start date and time in advance. But looks like this is not true. Have tried to put starting date 2 days ahead and run flow daily (and many other different options) but first run starts immediately. Below is my simple flow image.

![image](https://user-images.githubusercontent.com/119249458/204154384-14a9a075-bee2-45b6-8b49-5091537fdce0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba2e127-56bc-5910-3af6-30030cf58c1f
* Version Independent ID: c8fea93d-3d8d-bf8e-af7d-ae853a936843
* Content: [Run flows on a schedule in Power Automate - Power Automate](https://learn.microsoft.com/en-us/power-automate/run-scheduled-tasks)
* Content Source: [articles/run-scheduled-tasks.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/run-scheduled-tasks.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by georgiostrantzas** [comment]
Hello @raikat, thank you for using Power Automate!  We tried to reproduce the issue, but we didn't achieve to get the behavior you are describing. As the issue doesn't seem to be related to the documentation, please reach out to our support teams through [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support) to investigate further.
