### ISSUE TITLE
documented ProxyServer registry does not seem to work

### ISSUE THREAD

**Issue by pyrocam** [MicrosoftDocs/power-automate-docs#862]
According to the documentation if I add this key the application will bypass the system proxy and instead use the specified proxy.
I have two proxies, Proxy A does not permit power automate to authenticate, Proxy B does. 

to replicate
create registry key 
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Power Automate Desktop]
"ProxyServer"="ProxyB:3980"
fully close the application
set system proxy to proxy B: The application logs in
fully close the application
set system proxy to proxy A: the application does not log in. 

I note I had to create the Power Automate Desktop key in HKLM but there is one in HKCU, I tried adding there and it does not work there either. is there a typo in the documentation? does it require a certain version of the application? I am using 2.26.139.22312

**Comment by georgiostrantzas** [comment]
Hello @pyrocam, thank you for using Power Automate! Please, try to enter "https://ProxyB:3980" instead of "ProxyB:3980". Also, the "Power Automate Desktop" part of the registry key path may doesn't exist. If it doesn't, you need to create it.

**Comment by pyrocam** [comment]
> Hello @pyrocam, thank you for using Power Automate! Please, try to enter "https://ProxyB:3980" instead of "ProxyB:3980". Also, the "Power Automate Desktop" part of the registry key path may doesn't exist. If it doesn't, you need to create it.

Thanks, although it was http://ProxyB:3980  that worked. I had to create it. Cheers!
