### ISSUE TITLE
Installation Process

### ISSUE THREAD

**Issue by armely** [MicrosoftDocs/power-automate-docs#868]
When going through the installation process, you don't get the option to validate features checked in the install process like machine-runtime part below. 
Make sure you've checked the Install the machine-runtime app to connect to the Power Automate cloud portal option in the installer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bea0fc-f35a-b960-c042-d2a5ce0ecaec
* Version Independent ID: 1390f494-d3c5-db24-77a9-7e8585de9fe9
* Content: [Manage machines - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/manage-machines)
* Content Source: [articles/desktop-flows/manage-machines.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/manage-machines.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **gtrantzas**

**Comment by georgiostrantzas** [comment]
Hello @armely, thank you for using Power Automate! The installer doesn't include a screen to validate your selection in a previous step. If you think this feature would be useful, you can reach out to the [Power Automate Ideas community forum](https://ideas.powerautomate.com/d365community/forum/086dd68e-597f-ec11-8d21-0022482e8f9f) to suggest it.
