### ISSUE TITLE
Important step makes this page useless as it can not be done from what I am seeing

### ISSUE THREAD

**Issue by csjasnoch** [MicrosoftDocs/power-automate-docs#871]
This page is dedicated to having a flow run from "A new trigger".

The process steps tell you to "Add a new step" which adds a new step to the end of the flow. After that it states (In a blue box with a warning) the trigger must be first.

From what I see there is no way to move flow steps, meaning the idea to "Add a new trigger" is not actually possible through how this page describes, yet implies it tells you how to do it and you can.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd64ea9a-d352-f719-fa8c-7c8c7ca20273
* Version Independent ID: d583bc49-1518-0a8a-5364-073225cde2e9
* Content: [Triggers in Power Automate - Power Automate](https://learn.microsoft.com/en-us/power-automate/triggers-introduction)
* Content Source: [articles/triggers-introduction.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/triggers-introduction.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by georgiostrantzas** [comment]
Hello @csjasnoch, thank you for using Power Automate! You can move actions by dragging and dropping them. The initial trigger can't be moved, because the flow must start with it. However, you can delete it, and then Power Automate will prompt you to select a new trigger. We are currently working on updating the article to make this process clear.

**Comment by georgiostrantzas** [comment]
Hello @csjasnoch! The page has been updated.
