### ISSUE TITLE
"Verfassen" statt "zusammenstellen" 

### ISSUE THREAD

**Issue by ZwilleSmutje** [MicrosoftDocs/power-automate-docs#872]
[Hier Feedback eingeben]
The translation to german is incorrect.
It should say "Verfassen" statt "zusammenstellen" 

This is very important in order for germans to even FIND the function in power automate because seachning for "compose" results in an empty search result.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: 79bddf7e-aad7-5b99-0b73-a893d25615f5
* Version Independent ID: f2f0c4d6-b613-d269-4756-bcd7548f76ec
* Content: [Verwenden Sie Datenvorgänge in Power Automate (enthält Videos) - Power Automate](https://learn.microsoft.com/de-de/power-automate/data-operations)
* Content Source: [articles/data-operations.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/data-operations.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@ZwilleSmutje @Bernadette2022 - Thanks for your feedback. We have informed the Localization team about this issue in our localized content. Closing the issue.

**Comment by Bernadette2022** [comment]
@ZwilleSmutje our localization supplier triage this feedback and the current translaton looks to be appropriate:

There are two translations for term “compose” - "Verfassen" and "zusammenstellen".
Confirmed by our de-de translator, both are correct, and their usage depends on different situations.

By comparing, it seems our current translation for compose is acceptable and consistent in the whole article. (Please see below the German screenshot on the right of current English screenshot).
