### ISSUE TITLE
Missing documentation on CDS instance templates

### ISSUE THREAD

**Issue by imi-diener** [MicrosoftDocs/power-automate-docs#875]
I'm trying to find out whether it's possible to provision a CDS instance for an environment while also setting the domain at the same time. My best guess is that if it's possible, it might be through provisioning templates, but I was unable to find any documentation on what they are or how to use them.

**Comment by ChrisGarty** [comment]
Hi Imi,
Have a look at https://learn.microsoft.com/en-us/power-platform/admin/create-environment and https://learn.microsoft.com/en-us/power-platform/admin/create-database.
If that documentation is insufficient, then open another issue there.
- Chris
