### ISSUE TITLE
Incorrect translation of the word 'button' into Korean

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftDocs/power-automate-docs#876]
In this document, and also in other documents as well where they mention 'buttons' and 'button flows', the word 'button' is currently translated as '단추'. However, '단추' refers to the buttons on dress shirts, so it is an incorrect translation. It should be translated as '버튼', which is the Korean word referring to the buttons on software which we can click on to trigger flows. 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. learn.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: ced33bf5-ecdb-4aa9-fc67-0fac06659369
* Version Independent ID: dcd3c2f4-6a2e-f9ce-d573-0a9d6e530de5
* Content: [즉각적인 흐름으로 반복적인 작업 실행 - Power Automate](https://learn.microsoft.com/ko-kr/power-automate/introduction-to-button-flows)
* Content Source: [articles/introduction-to-button-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/introduction-to-button-flows.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@SDSTony @Bernadette2022 - Thanks for your feedback. We have informed the Localization team about this issue in our localized content. Closing the issue.
