### ISSUE TITLE
Document not reflecting the current state of using Advanced mode in condition. 

### ISSUE THREAD

**Issue by judeper** [MicrosoftDocs/power-automate-docs#877]
We can no longer use the advanced editor for Condition. 

PM Post on Feb 6, 2019
https://flow.microsoft.com/en-us/blog/build-more-powerful-conditions-in-flows-and-more/

Previously, you could select Edit in advanced mode and then enter the expressions in a text box. However, this old mode was difficult to work with as it did not give you access to IntelliSense for expressions or Dynamic content. **There is no longer an Edit in advanced mode**

This document still shows the steps under the "Use the 'and' expression" on editing the condition using Advanced mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27504e8c-568f-ee52-542c-5ca87c2906db
* Version Independent ID: dc8f9282-90ce-60e0-402c-ea8829b6334e
* Content: [Use expressions in conditions in Power Automate - Power Automate](https://learn.microsoft.com/en-us/power-automate/use-expressions-in-conditions)
* Content Source: [articles/use-expressions-in-conditions.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/use-expressions-in-conditions.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by v-aangie** [comment]
@kisubedi - Can you please validate this PR? If it needs to be updated, please let me know the changes. Thanks!

**Comment by kisubedi** [comment]
@judeper Please share the screenshot of what you are seeing vs what you are expecting. The condition action should support the simplified point and click condition builder. 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/91279975/211884224-7a20aa67-b4d0-45c8-a701-4d927f48fc25.png">

**Comment by v-aangie** [comment]
@judeper - Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
