### ISSUE TITLE
UI Elements not detected on the browser when using Power Automate

### ISSUE THREAD

**Issue by Mustafabdi** [MicrosoftDocs/power-automate-docs#881]
UI Elements not detected on the browser when using Power Automate

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8caf6c81-d08b-26b3-8d6f-caabb64a7f43
* Version Independent ID: 8479732d-e1a9-f882-436b-872125307747
* Content: [Introduction to other types of desktop flows (contains video) - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/overview)
* Content Source: [articles/desktop-flows/overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/overview.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DeonHe**

**Comment by v-aangie** [comment]
@Mustafabdi - Thanks for contacting us. As this is a legacy topic, please refer to https://learn.microsoft.com/en-us/power-platform/admin/get-help-support to request further investigation. Closing this issue.
