### ISSUE TITLE
Typing mistake in the business process flows overview page

### ISSUE THREAD

**Issue by saleembdr** [MicrosoftDocs/power-automate-docs#882]
I think that the word 'displyed' in the end of the business process flows overview page has a typing mistake.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7632694a-e3b9-7f71-5e19-765d4d203155
* Version Independent ID: c961c989-bc01-5088-6993-b5ee9485d4f4
* Content: [Business process flows overview - Power Automate](https://learn.microsoft.com/en-us/power-automate/business-process-flows-overview)
* Content Source: [articles/business-process-flows-overview.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/business-process-flows-overview.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **DEONHE**

**Comment by v-aangie** [comment]
Corrected in https://github.com/MicrosoftDocs/power-automate-docs-pr/pull/1891.

**Comment by v-aangie** [comment]
@saleembdr - Thanks for your feedback. We have updated the docs to fix information about https://learn.microsoft.com/power-automate/business-process-flows-overview, and the updated content will be live in a few hours. Closing this issue.
