### ISSUE TITLE
Inability to use find or replace in DataTables extracted from PDFs

### ISSUE THREAD

**Issue by tito-x** [MicrosoftDocs/power-automate-docs#884]
![image](https://user-images.githubusercontent.com/121934374/210521173-dbeccca2-9465-42c4-8d9f-0463734ca72a.png)
 
When I tried to use the 'find or replace in data table' action in a data table that was extracted from a PDF, I got the error: "Parameter 'Data table': Input 'ExtractedPDFTables[0].Datatable' can't have trailers."

Even if there is another method to search through data tables from an extracted PDF, I believe one should still be able to use the  'find or replace in data table' action directly on it.

Regards,
tito-x

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52e0d3b7-5d54-b28b-ed97-8bc0970d0c96
* Version Independent ID: c25847a1-f575-cfd9-73e5-10cdf75bbfa6
* Content: [Variables actions reference - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/variables#findorreplaceindatatable)
* Content Source: [articles/desktop-flows/actions-reference/variables.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/variables.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @tito-x, thank you for using Power Automate! You can try using the "Set variable" action to set the value "%ExtractedPDFTables[0].DataTable%" to a new variable. Then, populate this variable in the "Data table" field of the "Find or replace in data table" action. For further help with technical issues, please reach out to our support teams through [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support).

**Comment by georgiostrantzas** [comment]
We are currently working on resolving the bug in the data table actions, but my suggested solution will make your desktop flow work till the fix is public.
