### ISSUE TITLE
'Continue flow run' of 'On error' Not working 

### ISSUE THREAD

**Issue by tito-x** [MicrosoftDocs/power-automate-docs#886]
It appears as if the option 'Continue flow run' in 'On error' isn't working.

Here's the error:
![image](https://user-images.githubusercontent.com/121934374/210827896-5d3a5c9b-e444-48aa-9e49-e65efaedaf38.png)

Here's my 'On error' setting:
![image](https://user-images.githubusercontent.com/121934374/210828076-bc221b58-bbf6-4a6f-bf78-5ff5d1627af9.png)

What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ff3d374-1569-6f71-3228-17de1257fab7
* Version Independent ID: a1fe549f-80aa-3893-5f1f-df611cc3e33e
* Content: [Handle errors in desktop flows - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/errors)
* Content Source: [articles/desktop-flows/errors.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/errors.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **iomavrid**

**Comment by georgiostrantzas** [comment]
Hello @tito-x, thank you for using Power Automate! The error in the screenshot is a logic error. As a result, you can't handle it using the error-handling options of the actions. To handle logic errors, you should use the "On block error" action. For further help with technical issues, please reach out to our support teams through [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support).

**Comment by tito-x** [comment]
Is there a way to skip that particular iteration? As the loop works fine for other iterations in the loop.

**Comment by georgiostrantzas** [comment]
Because this is a technical question and not related to the documentation, please reach out to our support teams through [support ticket](https://docs.microsoft.com/power-platform/admin/get-help-support).
