### ISSUE TITLE
There is no MSI installer

### ISSUE THREAD

**Issue by Karl-Qlogic** [MicrosoftDocs/power-automate-docs#893]
The download for MSI installer is an .exe file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6cfbc11-176d-228c-a8cb-ef229a9a5d62
* Version Independent ID: 5c96eafd-b9cc-507b-4b8c-8de7c4210c6f
* Content: [Install Power Automate - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/install)
* Content Source: [articles/desktop-flows/install.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/install.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **pefelesk**

**Comment by georgiostrantzas** [comment]
Hello @Karl-Qlogic, thank you for using Power Automate! The current link downloads an exe file which is an MSI installer wrapped in an executable boostrapper.
