### ISSUE TITLE
No limitations section -- what about guest users?

### ISSUE THREAD

**Issue by bernatagulloesbrina** [MicrosoftDocs/power-automate-docs#897]
I read the page trying to understand if there's a way to share a flow with a guest user of my tenant as I'm getting an error, but there's no mention about them. Could you please clarity? Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to share a cloud flow with other users - Power Automate](https://learn.microsoft.com/en-us/power-automate/create-team-flows)
* Content Source: [articles/create-team-flows.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/create-team-flows.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by georgiostrantzas** [comment]
Hello @bernatagulloesbrina, thank you for using Power Automate. We added a note to the article to make it clear that sharing cloud flows with guest users in your tenant isn't possible.

**Comment by justdevcode** [comment]
Previously we were able to add guest as co-owners to a Flow. This then stopped working and the workaround was to change the user type in AAD from guest to member, add the guest user to the Flow and then change the user type back to guest. Now it seems that the workaround does not work either and we are no longer able to add guests? Is MS no longer going to support adding guest as Flow owners?
