### ISSUE TITLE
SEO Isn't enough - Missing download page/links

### ISSUE THREAD

**Issue by WiseManSings** [MicrosoftDocs/power-automate-docs#901]
People search for articles to do things, but it is always broken up, requiring them to go to several docs pages to find all the answers. This is a page on how to use Desktop Automate. Could you provide a link to download the darn thing so people can try it along with the article? Even the "Intro to desktop flows..." doesn't have a link to download/install. https://learn.microsoft.com/en-us/power-automate/desktop-flows/introduction

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa317dc5-cfeb-eaa5-9cb7-019c836d5f01
* Version Independent ID: 6db0a130-c53b-ca8e-5a9a-16ff7de3bf1f
* Content: [Record desktop flows - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/recording-flow)
* Content Source: [articles/desktop-flows/recording-flow.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/recording-flow.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @WiseManSings, thank you for using Power Automate. [This documentation page](https://learn.microsoft.com/en-us/power-automate/desktop-flows/install) provides all the information needed for the installation.
