### ISSUE TITLE
Wrong information on help page

### ISSUE THREAD

**Issue by masteroleg** [MicrosoftDocs/power-automate-docs#909]
[Enter feedback here]
Details(Right-click mouse) - no shortcut
Settings: Wrong screenshot on support page

Action requid: Totally review whole supportt page, because it no relevant to real product.
Version: 2.28.135.23016

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eaec2d03-a3ce-b4e1-e803-16a8f756cda4
* Version Independent ID: eaec2d03-a3ce-b4e1-e803-16a8f756cda4
* Content: [Run desktop flows via URL or desktop shortcuts - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/run-desktop-flows-url-shortcuts)
* Content Source: [articles/desktop-flows/run-desktop-flows-url-shortcuts.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/run-desktop-flows-url-shortcuts.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **pefelesk**

**Comment by georgiostrantzas** [comment]
Hello @masteroleg, thank you for using Power Automate. What type of account do you use to sign in? This feature is available only for premium accounts. You can find a list with all the premium features [here](https://learn.microsoft.com/en-us/power-automate/desktop-flows/premium-features).
