### ISSUE TITLE
Automating download with Invoke-WebRequest URI for https://go.microsoft.com/fwlink/?linkid=2102613

### ISSUE THREAD

**Issue by ivebeenchosen** [MicrosoftDocs/power-automate-docs#915]
Hi,

I need to automate a reocurring download of the latest version of Setup.Microsoft.PowerAutomate.exe through Powershell, with the Invoke-WebRequest method, and wondering if the link to download the latest version of Power Automate Desktop is being changed in the future, or if it always will be "https://go.microsoft.com/fwlink/?linkid=2102613"?
The link is mentioned at 1. [Download the Power Automate installer] at https://learn.microsoft.com/en-us/power-automate/desktop-flows/install

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6cfbc11-176d-228c-a8cb-ef229a9a5d62
* Version Independent ID: 5c96eafd-b9cc-507b-4b8c-8de7c4210c6f
* Content: [Install Power Automate - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/install)
* Content Source: [articles/desktop-flows/install.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/install.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **pefelesk**

**Comment by georgiostrantzas** [comment]
Hello @ivebeenchosen, thank you for using Power Automate! We aren't planning any changes to the link soon, but we can't guarantee that it won't change in the distant future.
