### ISSUE TITLE
No create shortcut option

### ISSUE THREAD

**Issue by GitHubJohn2** [MicrosoftDocs/power-automate-docs#926]
[Enter feedback here]There is no create shortcut option that is presented after a right click.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eaec2d03-a3ce-b4e1-e803-16a8f756cda4
* Version Independent ID: eaec2d03-a3ce-b4e1-e803-16a8f756cda4
* Content: [Run desktop flows via URL or desktop shortcuts - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/run-desktop-flows-url-shortcuts)
* Content Source: [articles/desktop-flows/run-desktop-flows-url-shortcuts.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/run-desktop-flows-url-shortcuts.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **pefelesk**

**Comment by georgiostrantzas** [comment]
Hello @GitHubJohn2, thank you for using Power Automate. Desktop shortcuts are available only for premium accounts. What kind of account did you use to sign in to Power Automate for desktop? You can find a list with all the premium features for desktop flows [here](https://learn.microsoft.com/en-us/power-automate/desktop-flows/premium-features).
