### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by m-neill** [MicrosoftDocs/power-automate-docs#95]
The flow interface no longer looks like what is described here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a50a5424-6bb4-c34c-bb82-991a5dd3e0df
* Version Independent ID: ea8ac9ee-e014-ad33-59f5-5d15f8a38ad8
* Content: [Learn how to add other owners to a flow and create team flows - Microsoft Flow](https://docs.microsoft.com/en-us/flow/create-team-flows)
* Content Source: [flow-docs/create-team-flows.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/create-team-flows.md)
* Service: **flow**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by MSFTMan** [comment]
@m-neill Thanks for using Power Automate. We've updated this document and it should be visible to you in a couple days.
