### ISSUE TITLE
Activate cell

### ISSUE THREAD

**Issue by robertlovasz** [MicrosoftDocs/power-automate-docs#954]
[Enter feedback here]

Really? They couldn't figure out a better name for this action? Activate cell? Sounds like some middle east terrorist group being told to start something...

Select cell, Chose sell, Select active cell, Set active cell, Focus Cell, ... I can come up with 10 different new names in a minute, that would describe this action better, and wouldn't sound weird like this. 
I'm not the person who usually complains, "it hurts my feelings", but come on, "activate cell" really sounds weird, for selecting the focused (or in your words "active") cell. I mean what is wrong with "Select active cell" why it had to be 'activate' cell.
Maybe this is the wrong spot to give feedback on this:) If that is the case, then sorry :D
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08dbb236-dbdd-af9e-118a-db2ba29f6733
* Version Independent ID: c9922ccc-6d8b-7f3c-65db-6f3fdc23743e
* Content: [Excel actions reference - Power Automate](https://learn.microsoft.com/en-us/power-automate/desktop-flows/actions-reference/excel#activatecellinexcel)
* Content Source: [articles/desktop-flows/actions-reference/excel.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/desktop-flows/actions-reference/excel.md)
* Service: **power-automate**
* Sub-service: **desktop-flow**
* GitHub Login: @georgiostrantzas
* Microsoft Alias: **marleon**

**Comment by georgiostrantzas** [comment]
Hello @robertlovasz, thank you for using Power Automate! The VBA method that selects and activates cells in Excel is called "Activate", so we gave the same name to the action.
