### ISSUE TITLE
Desktop misspelled as Dekstop

### ISSUE THREAD

**Issue by dparanka** [MicrosoftDocs/power-automate-docs#982]
Desktop misspelled as Dekstop

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e52022c-99d7-aba1-9c1d-0e97cec7ffbf
* Version Independent ID: 0ca15f3d-2e81-d9af-0b95-3111ee150ea0
* Content: [Learning catalog for Power Automate - Power Automate](https://learn.microsoft.com/en-us/power-automate/learning-catalog/learning-catalog)
* Content Source: [articles/learning-catalog/learning-catalog.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/learning-catalog/learning-catalog.md)
* Service: **power-automate**
* GitHub Login: @MSFTMan
* Microsoft Alias: **deonhe**

**Comment by ProfessorKendrick** [comment]
Thanks for bringing this typo to our attention.  The content has been corrected. Closing the issue.
