### ISSUE TITLE
Flow Approvals Email notification formating disgraceful

### ISSUE THREAD

**Issue by morayf** [MicrosoftDocs/power-automate-docs#99]
From a renowned software company, it seems absolutely outrageous that there are dozens of different formatting styles for the same thing.  Flow is supposed to make life easy and automated, but there is no stable and simple way to format the email notice.  It seems no one can be bothered to sort this problem out without a clunky coding work around.  Flow is simple, but it does not provide for a user experience unless you are a serious coder.  Microsoft Sort this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Microsoft Flow approvals - Microsoft Flow](https://docs.microsoft.com/en-us/flow/approvals-markdown-support#feedback)
* Content Source: [flow-docs/approvals-markdown-support.md](https://github.com/MicrosoftDocs/flow-docs/blob/live/flow-docs/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by z7x** [comment]
I agree. The formatting is totally broken in Outlook 365/2019 'preview' view. It looks different on Flow app (iOS) and again different on the actual Approval page online....

**Comment by perk8** [comment]
I would like for the link in the Approval Email to work. I can deal with everything else, but this is urgent.

**Comment by wy62** [comment]
Agreed. Markdown in actionable messages does not work fully in the Outlook 365 desktop client. Some Markdown works, other does not. The formatting looks terrible. But it looks fine in the Outlook web client. I understand this has been an issue for a long time, according to this thread: https://powerusers.microsoft.com/t5/General-Flow-Discussion/Markdown-rendering-not-working-in-some-approval-mails/td-p/165072.

Microsoft really needs to get on top of this and prioritise it.

**Comment by MSFTMan** [comment]
@wy62 Thanks for using Power Automate. We are aware of this issue and it's being worked on. We do not have a planned release date currently. In the meantime, kindly use OWA or the approvals center to process approvals.

**Comment by HairyDrumroll** [comment]
@MSFTMan says:
> We are aware of this issue and it's being worked on. We do not have a planned release date currently. 

So, leave the ticket open then.

> In the meantime, kindly use OWA or the approvals center to process approvals.

Not really a suitable fix. Please reopen the ticket Deon.

**Comment by 686578** [comment]
Agree.

Please reopen ticket.

Ticket should remain open until fix is implemented and or referenced in this article. As with basically any issue reporting process...

**Comment by l85m** [comment]
Why is this issue closed? This is still broken.

**Comment by HarryDriscollTWE** [comment]
@MSFTMan / @gcorvera  / @bishalgoswami 
Please reopen. Issue remains unresolved.

**Comment by bubbleswap** [comment]
@MSFTMan / @gcorvera / @bishalgoswami 

As of today, markdown does not format correctly in Outlook version 1908, and formats correctly in Outlook version 2002.

Please reopen. Issue remains unresolved.

**Comment by nvgni** [comment]
when would MS would come up with a fix? we use to format using info-path email out template in the past versions and with the new Powerautomate we went 10 steps down instead of going up a step, whats the solution here MS support? please do not say this is tough to implement?? reuse the code please..
