### ISSUE TITLE
Benefits, not Benifits

### ISSUE THREAD

**Issue by jmbcreates** [MicrosoftDocs/power-automate-docs#990]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf98fbf-59fc-825d-e8bc-b4b5b42719a2
* Version Independent ID: 22977ae9-2f4b-c98e-d19d-1d8ebf43fbd2
* Content: [Get started with Power Automate - Power Automate](https://learn.microsoft.com/en-us/power-automate/getting-started)
* Content Source: [articles/getting-started.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/main/articles/getting-started.md)
* Service: **power-automate**
* Sub-service: **cloud-flow**
* GitHub Login: @natalie-pienkowska
* Microsoft Alias: **napienko**

**Comment by v-aangie** [comment]
@jmbcreates - Thanks for your feedback. The article has been updated since this request, and this is no longer an issue. Closing this issue.
