### ISSUE TITLE
Create a message to Teams with image attached

### ISSUE THREAD

**Issue by R-Dan** [MicrosoftDocs/power-automate-docs#999]
Hello everybody,

            I'm trying to create an event that sends a chat message to an array of emails. But, on this message, I also need to attach an image with the chosen text (like in Outlook with an image at the message's end), and, if possible, insert an hyperlink at this same image. Do you know how to do that?

**Comment by v-aangie** [comment]
@R-Dan - Thanks for contacting us. Unfortunately, we're unable to handle Support requests for the product here. To contact Support, see here: https://flow.microsoft.com/support/. Closing this issue.
